### ISSUE TITLE
SystemError: (libev) epoll_wait: Bad file descriptor

### ISSUE THREAD

**Issue by aigr** [gevent/gevent#1008]
* gevent version: 1.2.2
* Python version: 2.7.9
* Operating System: Debian 8

### Description:

I'm trying to use a combination of gevent, [DeamonContext](https://pagure.io/python-daemon/) and [python-ldap](https://www.python-ldap.org/) to run a set of worker greenlets that cooperatively use a pool of connections to an LDAP server to run queries against it.

The idea is to:
* Create and maintain a pool of connections to an LDAP server.
* Have a set of greenlet workers:
  * Take a connection from the pool.
  * Use the connection to query the LDAP server.
  * Put the connection back into the pool.

This worked very well in Debian 7, but does not work as expected under Debian 8.

### What I've run:

The script `test.py` is a "minimal" use case. It ends with a:
```python
Traceback (most recent call last):
  File "./test.py", line 292, in <module>
    main()
  File "./test.py", line 93, in main
    gevent.joinall([bawler])
  File "virt/local/lib/python2.7/site-packages/gevent/greenlet.py", line 649, in joinall
    return wait(greenlets, timeout=timeout, count=count)
  File "virt/local/lib/python2.7/site-packages/gevent/hub.py", line 1037, in wait
    return list(iwait(objects, timeout, count))
  File "virt/local/lib/python2.7/site-packages/gevent/hub.py", line 984, in iwait
    item = waiter.get()
  File "virt/local/lib/python2.7/site-packages/gevent/hub.py", line 938, in get
    Waiter.get(self)
  File "virt/local/lib/python2.7/site-packages/gevent/hub.py", line 898, in get
    return self.hub.switch()
  File "virt/local/lib/python2.7/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
SystemError: (libev) epoll_wait: Bad file descriptor
```

### Workaround:

If I modify the script `test.py` to start with:
```python
import gevent.hub
gevent.hub.Hub.backend = "poll"
```

Then it all seems to work out as expected. Also `"select"` seems to work.

### Sample log output:

The `test.log` is an example output.

During the first 186 lines all looks more or less as expected.

One thing that bothers me a bit is that `gevent.get_hub().loop.fileno()` returns 7 on line 12:
```
----- 2017-07-31T11:54:17.735661 INFO libev.loop = epoll default pending=0 ref=0 fileno=7
```

The number 7 is later also used as the file descriptor for an ldap connection on line 48:
```
----- 2017-07-31T11:54:17.812319 INFO PB 2 connected via FD 7.
```

Have I got my file descriptors mixed up? When `gevent.hub.Hub.backend` is set to `"poll"`, this doesn't seem to generate any problems.

On lines 187 and 188 the first direct signs of trouble can be noticed:
```
----- 2017-07-31T11:54:20.913909 WARN PB 4 open FD: 7 (0) <<<<<
----- 2017-07-31T11:54:20.913962 WARN PB 4 open FD: 8 (0) <<<<<
```

It seems that the file descriptors 7 and 8 have unexpectedly "broken".

Any operations on those connection will fail. The `test.py` script closes the file descriptors with `os.close(fd)`. Is there a need and way to tell gevent about that?

**Comment by aigr** [comment]
[test.py.txt](https://github.com/gevent/gevent/files/1187261/test.py.txt)
[test.log.txt](https://github.com/gevent/gevent/files/1187262/test.log.txt)

**Comment by xbonio** [comment]
I also struggle with the issue running [Locust](https://locust.io/) on macOS High Sierra.

gevent version: 1.2.2

`[2017-12-04 17:40:39,200] iMac.local/ERROR/stderr: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/locust/core.py", line 271, in run
    self.execute_next_task()
  File "/Library/Python/2.7/site-packages/locust/core.py", line 297, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/Library/Python/2.7/site-packages/locust/core.py", line 309, in execute_task
    task(self, *args, **kwargs)
  File "/Users/mikolaj/Desktop/locust/locustfile.py", line 25, in exam_select
    .format(examId, respondentId))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/locust/clients.py", line 114, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/locust/clients.py", line 158, in _send_request_safe_mode
    return requests.Session.request(self, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 242, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/Library/Python/2.7/site-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/Library/Python/2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/Library/Python/2.7/site-packages/urllib3/util/wait.py", line 26, in _wait_for_io_events
    selector.select(timeout) if key[1] & events]
  File "/Library/Python/2.7/site-packages/urllib3/util/selectors.py", line 320, in select
    self._writers, timeout)
  File "/Library/Python/2.7/site-packages/urllib3/util/selectors.py", line 94, in _syscall_wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/urllib3/util/selectors.py", line 310, in _select
    return select.select(r, w, [], timeout)
  File "/Library/Python/2.7/site-packages/gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()`

**Comment by jamadden** [comment]
It looks like we have an answer, thanks!
