### ISSUE TITLE
libuv: test__threadpool.TestMaxsize.test_inc sometimes fails

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1057]
This test sometimes fails on libuv. Due to the decreased timer resolution?
```
  /home/travis/build/gevent/gevent/src/gevent/hub.py:169: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
    hub.wait(loop.timer(seconds, ref=ref))
  ..../home/travis/build/gevent/gevent/src/gevent/hub.py:169: UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
    hub.wait(loop.timer(seconds, ref=ref))
  .
  ======================================================================
  FAIL: test_inc (__main__.TestMaxsize)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/travis/build/gevent/gevent/src/greentest/greentest.py", line 326, in wrapper
      return method(self, *args, **kwargs)
    File "/home/travis/build/gevent/gevent/src/greentest/greentest.py", line 315, in wrapper
      return method(self, *args, **kwargs)
    File "/home/travis/build/gevent/gevent/src/greentest/greentest.py", line 196, in wrapper
      return method(self, *args, **kwargs)
    File "test__threadpool.py", line 345, in test_inc
      self.assertEqual(done, [1, 2])
  AssertionError: Lists differ: [2, 1] != [1, 2]
  
  First differing element 0:
  2
  1
  
  - [2, 1]
  + [1, 2]
```

**Comment by jamadden** [comment]
There is a timer resolution issue in threadpool, but the real issue is just like #1058 : callbacks and timers race on the first entry into the loop. libev always ran timers first, but libuv can notice and run expired timers *before* it runs callbacks (on first entry into the loop). Both tests had an implicit assumption that callbacks always happened first.

**Comment by jamadden** [comment]
It also turns out that starting a timer *while you are in a timer callback* can run that new timer in the same iteration of the loop, if it happens to expire. I don't think libev did that.

In gevent that happens all the time. Consider this:
```python
gevent.sleep(0.001)
gevent.spawn_later(0.001, something)
gevent.sleep(0.001)
```

After each `gevent.sleep`, the following code is running in a timer callback. By default, each time we begin a timer we update the loop's notion of the current time (hence letting timers expire). So it's entirely possible that as we enter the second `gevent.sleep`, the `spawn_later` will immediately happen, instead of on the next loop iteration as it would in libev. 

Perhaps we shouldn't be updating the loop's notion of the current time when we create new timers by default.
