### ISSUE TITLE
1.3.0.dev0 import error

### ISSUE THREAD

**Issue by cielpy** [gevent/gevent#1065]
* gevent version: 1.3.0.dev0
* Python version: 3.6.3
* Operating System: macOS 10.13.2 (17C88)

### Description:

Just `pip install https://github.com/gevent/gevent/archive/master.zip` (latest commit ad0f8c7)

then import gevent and run, error occur.

```
$ python a.py
Traceback (most recent call last):
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/core.py", line 10, in <module>
    raise ImportError("Not attempting corecext")
ImportError: Not attempting corecext

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 18, in <module>
    import gevent
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/__init__.py", line 51, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/hub.py", line 449, in <module>
    class Hub(RawGreenlet):
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/hub.py", line 483, in Hub
    loop_class = [_import(loop_class)]
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/hub.py", line 399, in _import
    return _import(path[-1])
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/hub.py", line 415, in _import
    x = __import__(module)
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/core.py", line 20, in <module>
    from gevent.libuv import loop as _core
  File "/Users/xxx/flask_helloworld/flask_helloworld/lib/python3.6/site-packages/gevent/libuv/loop.py", line 16, in <module>
    from gevent.libuv import _corecffi # pylint:disable=no-name-in-module,import-error
ImportError: cannot import name '_corecffi'
```

### What I've run:

```
a.py


import gevent

```

**Comment by jamadden** [comment]
Thanks for your report, but installing from a github archive is not a supported installation method. If you'd like to run a development version, please follow the instructions [under "Development"](https://pypi.python.org/pypi/gevent#development).

**Comment by cielpy** [comment]
Thanks for your reply, I have build it use pip, it works well!
