### ISSUE TITLE
Install fails on Alpine 3.7, CPython=3.6.3-r9

### ISSUE THREAD

**Issue by spacether** [gevent/gevent#1083]
* gevent version: 1.3a1
* Python version: CPython=3.6.3-r9 from https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/python3-dev
* Operating System: Alpine 3.7, x86_64 in a docker image

### Description:

I am trying to install gevent as a required library from my setup.py file of a python library that I am installing on system-wide python in my OS. This installation is occurring when I build my docker image. In my setup.py I have
```
    install_requires=['flask', 'requests', 'gunicorn', 'pytest', 'pytz', 'gevent'],
```
When I am building my docker image, the below line is run to install my library, which requires gevent in setup.py
```
RUN python3 setup.py install
```

Installation of gevent fails with the following log
```
Processing dependencies for iftttbot==1.0.1
Searching for gevent
Reading https://pypi.python.org/simple/gevent/
Downloading https://pypi.python.org/packages/69/82/3b99d84531bc8f38fbcf1e584edc44e153f375dfd419eae5e56e0b1493ea/gevent-1.3a1.tar.gz#md5=48942df95375e22aed7970652c440c4c
Best match: gevent 1.3a1
Processing gevent-1.3a1.tar.gz
Writing /tmp/easy_install-xrxw16sy/gevent-1.3a1/setup.cfg
Running gevent-1.3a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xrxw16sy/gevent-1.3a1/egg-dist-tmp-1odrgn59
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-xrxw16sy/gevent-1.3a1/setup.py", line 44, in <module>
  File "/tmp/easy_install-xrxw16sy/gevent-1.3a1/_setuplibev.py", line 94, in <module>
  File "/tmp/easy_install-xrxw16sy/gevent-1.3a1/_setuputils.py", line 168, in cythonize1
TypeError: cythonize() got an unexpected keyword argument 'include_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    entry_points={'console_scripts':['iftttbot=iftttbot.cmd:cli']}
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-xrxw16sy/gevent-1.3a1/setup.py", line 44, in <module>
  File "/tmp/easy_install-xrxw16sy/gevent-1.3a1/_setuplibev.py", line 94, in <module>
  File "/tmp/easy_install-xrxw16sy/gevent-1.3a1/_setuputils.py", line 168, in cythonize1
TypeError: cythonize() got an unexpected keyword argument 'include_path'
```
How do I install gevent without getting this error?

**Comment by jamadden** [comment]
I suggest installing with pip: `pip install .`. That way you'll be able to use the (binary) wheels  provided on PyPI.

If you don't want to do that, you'll need to have Cython installed first.
```
pip install cython
python setup.py install
```

**Comment by spacether** [comment]
Per your instructions, changing my install line in my Dockerfile to:
```
RUN pip3 install .
```
solved the problem. Thanks for the help!
