### ISSUE TITLE
os.waitpid(pid) seems racy under libuv on linux

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1104]
Seen [on travis](https://travis-ci.org/gevent/gevent/jobs/342124732#L2029):
```
  Traceback (most recent call last):
    File "/home/travis/build/gevent/gevent/src/greentest/2.7/test_socketserver.py", line 201, in test_ForkingTCPServer
      self.stream_examine)
    File "/home/travis/.runtimes/versions/python2.7.14/lib/python2.7/contextlib.py", line 24, in __exit__
      self.gen.next()
    File "/home/travis/build/gevent/gevent/src/greentest/2.7/test_socketserver.py", line 68, in simple_subprocess
      testcase.assertEqual(pid2, pid)
  AssertionError: 26421 != 26430
```

where `simple_subprocess` is a context manager:
```python
@contextlib.contextmanager
def simple_subprocess(testcase):
    pid = os.fork()
    if pid == 0:
        # Don't raise an exception; it would be caught by the test harness.
        os._exit(72)
    yield None
    pid2, status = os.waitpid(pid, 0)
    testcase.assertEqual(pid2, pid)
    testcase.assertEqual(72 << 8, status)
```

The pid we spawned doesn't match the pid we waited for, even though we explicitly passed exactly that pid to `waitpid`. It's not clear how this happens. I haven't seen this on macOS (and maybe not on Python 3?) but macOS delivers child signals differently than linux does.

**Comment by jamadden** [comment]
I have been unable to reproduce this on Ubuntu 16.04 (?) with kernel 4.4.0-112 in a virtual machine with 2 cpus and 4GB of memory on CPython 2.7.12. test_socketserver.py runs in about .7s (half what it takes on the failed example). If I reduce the memory by half, cut it back to one processer and throttle it so that test_socketserver takes 1.4s, I have been able to reproduce it one out of ten times, so that's a start.

**Comment by jamadden** [comment]
I've also been able to reproduce a hang waiting on a process.

The AssertionError above is just an implementation bug, but the hang is actually a race condition: starting a new child watcher for the pid at the same time the old child watcher runs. The new child watcher will never be called. This can be fixed by more carefully controlling when child watchers run (in libev they're batched, here they were called when the signal handler ran---we can defer that to a batch).
