### ISSUE TITLE
ValueError: fd must be non-negative: -1 

### ISSUE THREAD

**Issue by cw1427** [gevent/gevent#1139]
* gevent version: 1.2.2
* Python version: python2.7.14
* Operating System: ubuntu 16.0.4

### Description:
When I run the gevent in uwsgi in docker, I got error as below:

uwsgi config:
```conf
[uwsgi]
module = wsgi_handler:app
socket = 0.0.0.0:8080
socket = /uwsgi-socket
pidfile = /%n.pid
master = 1
processes = 1
enable-threads = true
threads = 1
gevent = 10
gevent-monkey-patch=true
logdate= %%s
memory-report = true
max-requests=1000000
socket-timeout = 3600
```

```
1520761024 - worker respawning too fast !!! i have to sleep a bit (2 seconds)...                 
1520761026 - Respawned uWSGI worker 1 (new pid: 151)                                             
1520761026 - *** running gevent loop engine [addr:0x55ca1d3d44d0] ***                            
Traceback (most recent call last):                                                              
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/li
```

Can anyone help to check what does the error mean:  fd must be non-negative: -1 ?

**Comment by jamadden** [comment]
That error means a file descriptor of -1 was passed to gevent and libev. File descriptors cannot be negative so that's an incorrect value.

I cannot tell you how that value got passed to gevent because that's not in the traceback. (Perhaps if you include more traceback it might be helpful.) I also cannot help you with docker or uwsgi.

**Comment by arcivanov** [comment]
Most likely it's a case of closed socket. Socket object sets returned fileno() to -1 when you close it and it becomes unuseable in the read/write/extra sets. It's most likely a total order problem in your code.

**Comment by cw1427** [comment]
Hi, thanks for response. There is the traceback. Meanwhile I have no aware of "It's most likely a total order problem in your code" and how the socket have been closed?

1520830426 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x5627135788a0 pid: 1 (default app)
1520830426 - uWSGI running as root, you can use --uid/--gid/--chroot options
1520830426 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
1520830426 - *** uWSGI is running in multiple interpreter mode ***
1520830426 - spawned uWSGI master process (pid: 1)
1520830426 - spawned uWSGI worker 1 (pid: 16, cores: 10)
1520830426 - spawned uWSGI worker 2 (pid: 17, cores: 10)
1520830426 - spawned uWSGI worker 3 (pid: 18, cores: 10)
1520830426 - *** running gevent loop engine [addr:0x562712f724d0] ***
1520830426 - spawned uWSGI worker 4 (pid: 19, cores: 10)
1520830426 - spawned uWSGI worker 5 (pid: 20, cores: 10)
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
1520830427 - DAMN ! worker 1 (pid: 16) died :( trying respawn ...
1520830427 - Respawned uWSGI worker 1 (new pid: 21)
1520830427 - DAMN ! worker 2 (pid: 17) died :( trying respawn ...
1520830427 - Respawned uWSGI worker 2 (new pid: 22)
1520830427 - DAMN ! worker 3 (pid: 18) died :( trying respawn ...
1520830427 - Respawned uWSGI worker 3 (new pid: 23)
1520830427 - DAMN ! worker 4 (pid: 19) died :( trying respawn ...
1520830427 - Respawned uWSGI worker 4 (new pid: 24)
1520830427 - DAMN ! worker 5 (pid: 20) died :( trying respawn ...
1520830427 - *** running gevent loop engine [addr:0x562712f724d0] ***
1520830427 - Respawned uWSGI worker 5 (new pid: 25)
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
Traceback (most recent call last):
ValueError  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
: fd must be non-negative: -1
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
Traceback (most recent call last):
  File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
  File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
ValueError: fd must be non-negative: -1
1520830428 - DAMN ! worker 1 (pid: 21) died :( trying respawn ...

**Comment by arcivanov** [comment]
"Total order", in this context, refers to parallel (threaded) code, that when collapsed via monkey-patching into a single ordered thread of execution, exposes a concurrency bug.

**Comment by cw1427** [comment]
Sorry, I don't understand your comment. Could you help to explain more clearly? Since you mentioned monkey-patch, I also commented it as below and re-build the docker image to run it, but it seems the same errors.

[uwsgi]
module = wsgi_handler:app
socket = :8080
master = 1
processes = 2
enable-threads=true
gevent = 10
#gevent-monkey-patch=true
logdate= %%s
logto=/bsm/logs/uwsgi-log
memory-report = true
max-requests=1000000
socket-timeout = 3600

**Comment by arcivanov** [comment]
It's a bug in uWSGI.

**Comment by jamadden** [comment]
This has been moved upstream at https://github.com/unbit/uwsgi/issues/1761
