### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object [py36]

### ISSUE THREAD

**Issue by VictorHVS** [gevent/gevent#1141]
* gevent version: gevent==1.2.2
* Python version: Python 3.6.4  downloaded from python.org
* Operating System: macOS 10.13.3 (17D102)

### Description:

I'm tryng to send a POST inside of a websocket. So, I got this error:

```
Traceback (most recent call last):
  File "apps/core/order_book.py", line 84, in <module>
    thing()
  File "apps/core/order_book.py", line 69, in thing
    dp.bot.send_message(chat_id="-287763810", text="We are the champions!")
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/utils/request.py", line 273, in post
    **urlopen_kwargs)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/utils/request.py", line 190, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/Users/victorhvs/Workspace/victorhvs/calltraderbot/env/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 264, in create_urllib3_context
    context.options |= options
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 321 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### What I've run:

```python
import logging

from telegram.ext import (Updater)
from time import sleep
from bittrex_websocket.websocket_client import BittrexSocket

updater = Updater("XXX", request_kwargs={'read_timeout': 6, 'connect_timeout': 7})
dp = updater.dispatcher

def thing():
    class MySocket(BittrexSocket):
        pass

    # Create the socket instance
    ws = MySocket()
    # Enable logging
    ws.enable_log()
    # Define tickers
    tickers = ['BTC-ETH', 'BTC-LTC', 'BTC-ZEC', 'ETH-NEO', 'ETH-ZEC']
    # Subscribe to live order book
    ws.subscribe_to_orderbook(tickers)

    while True:
        i = 0
        sleep(1)
        sync_states = ws.get_order_book_sync_state()
        for state in sync_states.values():
            if state == 3:
                i += 1
        if i == len(tickers):
            print('We are fully synced. Hooray!')
            for ticker in tickers:
                dp.bot.send_message(chat_id="237810", text="We are the champions!")
        
        else:
            sleep(1)

thing()
```

I got error with this peace:

```python
dp.bot.send_message(chat_id="-287763810", text="We are the champions!")
```

But using outside of the websocket I dont get erros.

**Comment by jamadden** [comment]
This looks like the same as #1016 and #903. The solution to both of those was to monkey-patch earlier, before anything else is imported.

I don't see *any* use of gevent in the code sample or the stack trace though, so if it's the same problem it's not visible here.

**Comment by jamadden** [comment]
BTW, I suggest using gevent 1.3a2. It's essentially stable, just missing a few planned features. It can produce a warning that can help narrow this down.

**Comment by VictorHVS** [comment]
I upgrate to 1.3a2, and I'm importing "import gevent.monkey" first, but it persist.

**Comment by VictorHVS** [comment]
I solve my problem with this -> https://github.com/slazarov/python-bittrex-websocket/issues/31

Ty, and sorry for this.
