### ISSUE TITLE
test__event.py often fails under PyPy

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1148]
* gevent version: master
* Python version: PyPy2 5.10.0
* Operating System: Travis CI

Always with this same exception:

```
 GEVENT_DEBUG=debug GEVENT_LOOP=libuv GEVENT_RESOLVER=thread GEVENT_RESOLVER_NAMESERVERS=8.8.8.8 /home/travis/.runtimes/snakepit/pypy5100 -u -X track-resources test__event.py
  ..F.........................
  ======================================================================
  FAIL: test_set (__main__.TestAsyncResult)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/travis/build/gevent/gevent/src/greentest/greentest/errorhandler.py", line 48, in wrapper
      return method(self, *args, **kwargs)
    File "/home/travis/build/gevent/gevent/src/greentest/greentest/errorhandler.py", line 35, in wrapper
      return method(self, *args, **kwargs)
    File "/home/travis/build/gevent/gevent/src/greentest/greentest/testcase.py", line 63, in wrapper
      return method(self, *args, **kwargs)
    File "test__event.py", line 118, in test_set
      event1.get()
  AssertionError: MyException not raised
  
  ----------------------------------------------------------------------
  Ran 28 tests in 2.898s
```

**Comment by jamadden** [comment]
Snarf. I just saw it in CPython 2.7 as well.
