### ISSUE TITLE
Unable to -m gevent.monkey non py files (pyo, pyc)

### ISSUE THREAD

**Issue by 3ddi** [gevent/gevent#1157]
* gevent version: 1.2.2
* Python version: cPython 2.7.9 that comes with ubuntu 14.04
* Operating System: ubuntu 14.04

### Description:
All of my project is pre compiled into pyo files, and I would like to execute it using the -m gevent.monkey option but when I do it, I get:
```Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 702, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 678, in main
    exec(f.read(), globals())
TypeError: expected string without null bytes
````
The command I used is:
python -OO -m gevent.monkey <script_path>.pyo

The main reason it happens is that gevent uses `exec` to run the provided script, and it doesn't support non plain text scripts.

What I think that can replace it, is to use `imp` instead. Here is a snippet of what I added to monkey.py
```moduel_path = sys.argv[0].rsplit('.', 1)[0]
        fp, pathname, description = imp.find_module(moduel_path)
        try:
            imp.load_module("__main__", fp, pathname, description)
        finally:
            fp.close()
```

**Comment by arcivanov** [comment]
`pyo` is not a script, it's optimized bytecode. gevent.monkey opens a script.

**Comment by 3ddi** [comment]
I see, but python allows executing it using -OO, why not supporting the same options as python?

**Comment by jamadden** [comment]
There are a number of other things 'python <path>' can do that `python -m gevent.monkey <path>` can't. Notably, it can run packages:
```console
$ mkdir foo
$ echo "print('hi from', __file__, __name__)" > foo/__main.py
$ python foo
hi from foo/__main__.py __main__
$ $ python -m gevent.monkey foo
Traceback (most recent call last):
  File "//3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "//3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "//src/gevent/monkey.py", line 804, in <module>
    main()
  File "//src/gevent/monkey.py", line 773, in main
    with open(sys.argv[0]) as f:
IsADirectoryError: [Errno 21] Is a directory: 'foo'
```

Using `imp` doesn't help that situation:
```console
$ <update gevent.monkey to use imp>
$ python -m gevent.monkey foo
Traceback (most recent call last):
  File "//3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "//3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "//src/gevent/monkey.py", line 811, in <module>
    main()
  File "//src/gevent/monkey.py", line 777, in main
    fp, pathname, descr = imp.find_module(sys.argv[0])
  File "//lib/python3.7/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'foo'
```

However, [`runpy.run_path`](https://docs.python.org/2.7/library/runpy.html#runpy.run_path) does handle that case as well as a simple script:
```console
$ <update gevent.monkey to use runpy>
$ python -m gevent.monkey foo
hi from foo/__main__.py __main__
$ echo "print('hi from a script', __file__, __name__)" > script.py
$ python script.py
hi from a script script.py __main__
$ python -m gevent.monkey script.py
hi from a script script.py __main__
$ python -O -c 'import script' # Make a .pyc file
hi from a script /private/tmp/script.py script
$ python __pycache__/script.cpython-37.opt-1.pyc
hi from a script __pycache__/script.cpython-37.opt-1.pyc __main__
$ python -m gevent.monkey __pycache__/script.cpython-37.opt-1.pyc
hi from a script __pycache__/script.cpython-37.opt-1.pyc __main__
```

I think we didn't use `runpy.run_path` because it's 2.7+, but that's OK now. I'll look into making that change.
