### ISSUE TITLE
ssl not working with gevent and socketio

### ISSUE THREAD

**Issue by habi3000** [gevent/gevent#1170]
* gevent version:1.2.2
* Python version: Python 3.6.3
* Operating System: Ubuntu 17.10 kernel version:4.13.0-38-generic 

### Description:
 i am trying to use https with socketio and gevent my code works great without ssl argument to the socketio.run, but when i use `socketio.run(app, port=5000, keyfile=mycert2,certfile=mycert2)`
i get the following error, the message keeps repeating for ever

```
/home/habi/PycharmProjects/untitled3/venv/bin/python /home/habi/PycharmProjects/untitled3/__init__.py
Server initialized for gevent.
lowlevelsocket
Waiting for incoming connections...
Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Fri Apr  6 20:32:34 2018 <Greenlet at 0x7fabfe50a5a0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError

Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Fri Apr  6 20:32:34 2018 <Greenlet at 0x7fabfd5775a0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError

Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Fri Apr  6 20:32:34 2018 <Greenlet at 0x7fabfd577638: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError

Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Fri Apr  6 20:32:34 2018 <Greenlet at 0x7fabfe50a5a0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError
```

### What I've run:

1-tried the code without keyfile and certfiel, it worked.
2-made sure that i am using https in the url 
3-tried different browsers

```python
`from gevent import monkey
monkey.patch_all()
import redis, os, time
import gevent.socket as socket
import gevent.ssl as ssl
from time import gmtime, strftime
from multiprocessing import Process
from threading import Thread
from flask import *
from flask_socketio import SocketIO


mycert = "/home/habi/PycharmProjects/untitled3/cert.pem"
mycert2 = "/home/habi/PycharmProjects/untitled3/cert2.pem"

app = Flask(__name__)
app.secret_key = 'secret'
socketio = SocketIO(app, logger=True, engineio_logger=True, async_mode='gevent')
rdb = redis.StrictRedis(host='111111', port=16112, db=0,
                        password='11111')
os.environ['TZ'] = 'Riyadh'
time.tzset()


class PrintExceptThread(Thread):
    def run(self):
        try:
            self._run()
        except Exception as e:
            print('{} got exception {}'.format(self.__class__.__name__, e))


class lowlevelsocket(Process):
    def run(self):
        print("lowlevelsocket")
        while True:
            print("Waiting for incoming connections...")
            tcpsock.listen(20)
            (conn, (ip, port)) = tcpsock.accept()
            newthread = ClientThread(ip, port, conn)
            newthread.start()


class ClientThread(Thread):
    def __init__(self, ip, port, conn):
        super().__init__()
        self.ip = ip
        self.port = port
        # self.conn = context.wrap_socket(conn, server_side=True)
        self.conn = conn
        print("[+] New thread started for {}: {}".format(ip, port))

    def run(self):
        while True:
            data = self.conn.recv(2048)
            if not data:
                break
            rdb.publish('carmessage', data)


def carmessageHandler(message):
    lis = str(message['data'].decode('ascii')).strip().split(',')
    if len(lis)>2:
        link = 'https://www.google.com/maps/search/?api=1&query={},{}'.format(lis[1], lis[2])
    ltime = strftime("%a, %d %b %Y %H:%M:%S", gmtime())
    print(lis)
    if lis[0] == 'drunk':
        socketio.send("[+] " + ltime + " WARNING Drunk driver detected at <a href=" + link + " >this location</a> ")
    elif lis[0] == 'rollover':
        socketio.send("[+] " + ltime + " WARNING Roll Over detected at <a href=" + link + " >this location</a> ")
    elif lis[0] == 'airbag':
        socketio.send("[+] " + ltime + " WARNING Accident detected at <a href=" + link + " >this location</a> ")
    elif lis[0] == 'speed':
        socketio.send("[+] " + ltime + " WARNING Speed Violation detected at <a href=" + link + " >this location</a> with vechile ID="+str(lis[3]))
    else:
        socketio.send(ltime + " " + str(lis))


@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if request.form['password'] == 'admin' and request.form['username'] == 'admin':
            session['user'] = request.form['username']
            return redirect(url_for('carmsg'))
    return render_template('index.html')


@app.route('/carmsg/')
def carmsg():
    if g.user:
        return render_template('carmsg.html')
    return render_template('index.html')


@app.before_request
def beforeRequest():
    g.user = None
    if 'user' in session:
        g.user = session['user']


@socketio.on('message')
def handle_message(message):
    print('received message: ' + message)


context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(certfile=mycert, keyfile=mycert)
TCP_IP = '0.0.0.0'
TCP_PORT = 5100
BUFFER_SIZE = 1024
tcpsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
tcpsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
tcpsock.bind((TCP_IP, TCP_PORT))
lowlevelsocketPro = lowlevelsocket()
lowlevelsocketPro.start()
p = rdb.pubsub(ignore_subscribe_messages=True)
p.subscribe(**{'carmessage': carmessageHandler})
p.run_in_thread(0.001)
socketio.run(app, port=5000, keyfile=mycert2,certfile=mycert2)
#socketio.run(app, port=5000)
````
hope i provided all the required information, please ask if something is missing

**Comment by jamadden** [comment]
Thank you for the report. Unfortunately, that's a lot of third-party dependencies to wade through (flask, socketio, redis) and I don't have the time or energy to do that. Can you boil it down to the essentials (using only gevent and the standard library)? There's a good chance in doing so you'll discover the issue...

**Comment by AndCycle** [comment]
some info that might help someone,

I do have a simple flask app which involve 
`flask-socketio`, `ssl`, `gevent-pywsgi`, `gevent-websocket` 
without any problem, 

so I think the problem probably comes from `multiprocessing` and `threading` 
which is a nightmare mix with `gevent`

**Comment by habi3000** [comment]
hi, i think the problem is with the certificate it self

**Comment by bsolomon1124** [comment]
Possibly related/additional examples:

- https://bugs.python.org/issue31122
- https://github.com/gevent/gevent/issues/1247
- https://stackoverflow.com/questions/49042162/ssleoferror-using-gevent
