### ISSUE TITLE
gevent 1.3.2 fail to install on centos:7 docker image

### ISSUE THREAD

**Issue by dantonpimentel** [gevent/gevent#1221]
* gevent version: 1.3.2
* Python version: python 2.7.5 from centos:7 docker image
* Operating System: docker image

### Description:

pip install is failing on the dockerized version of centos 7. More information with steps to reproduce the problem below.

```
[root@94b6a831e82b tmp]# pip install gevent==1.3.2
Collecting gevent==1.3.2
  Using cached https://files.pythonhosted.org/packages/62/85/3a75fa15a5375506a6617c1ce706ea800f016ca2be1a87165f1ab5aff3a2/gevent-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n5GstP/gevent/setup.py", line 417, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/tmp/pip-build-n5GstP/gevent/setup.py", line 401, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 601, in resolve
        requirements = list(requirements)[::-1]  # set up the stack
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
        line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2817, in scan_list
        "Expected ',' or end-of-list in",line,"at",line[p:]
    ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")
```

### What I've run:

```
From the host:
docker pull centos:7
docker run -ti --rm centos:7

From the container:
yum install -y epel-release && yum install -y python-pip
pip install gevent==1.3.2
```

**Comment by jamadden** [comment]
Thanks for the report. Your version of setuptools is very outdated and needs to be updated. Cf #1209

**Comment by jamadden** [comment]
1.3.2.post0 manylinux1 wheels have been posted.
