### ISSUE TITLE
CFFI install issue

### ISSUE THREAD

**Issue by SanderBeekhuis** [gevent/gevent#1223]
* gevent version: 1.3.2
* Python version: Please be as specific as possible: "Python 3.4.2 (virtualenv)"
* Operating System: Please be as specific as possible: "Debian GNU/Linux 8 (jessie) (Linux tc1 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux)"

### Description:

When I'm trying to install gevent it errors out in the following way:
```
Requirement already satisfied: cffi in ./lib/python3.4/site-packages (from -r requirements.txt (line 8)) (1.11.5)
Collecting gevent (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/62/85/3a75fa15a5375506a6617c1ce706ea800f016ca2be1a87165f1ab5aff3a2/gevent-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vf8h8gpg/gevent/setup.py", line 417, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/tmp/pip-install-vf8h8gpg/gevent/setup.py", line 401, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/srv/python/google/lib/python3.4/site-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/srv/python/google/lib/python3.4/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/srv/python/google/lib/python3.4/site-packages/pkg_resources.py", line 603, in resolve
        requirements = list(requirements)[::-1]
      File "/srv/python/google/lib/python3.4/site-packages/pkg_resources.py", line 2721, in parse_requirements
        "version spec")
      File "/srv/python/google/lib/python3.4/site-packages/pkg_resources.py", line 2697, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")
```

I've reverted back to gevent 1.2.2. This works as expected.

It may be related to this change but I don't know (https://github.com/gevent/gevent/commit/14544dae9bdbc85be20ceee98c07ef7e539d0e01)

I have only limited acces to this machine for testing.

### What I've run:

`pip install -r requirements.txt`

**Comment by blaise-io** [comment]
I have the same issue

 - Ubuntu 14.04.5 LTS (Trusty)
 - Python 2.7.6
 - Gevent 1.3.2

```
Collecting gevent==1.3.2
  Downloading https://files.pythonhosted.org/packages/62/85/3a75fa15a5375506a6617c1ce706ea800f016ca2be1a87165f1ab5aff3a2/gevent-1.3.2.tar.gz (4.6MB)
    100% |################################| 4.6MB 153kB/s 
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    error in gevent setup command: 'extras_require' requirements cannot include environment markers, in 'test': 'psutil; platform_python_implementation == "CPython" or sys_platform != "win32"'
```

Gevent 1.3.1 installs without issues.

**Comment by jamadden** [comment]
Thanks for the reports. That error means that the version of `setuptools` installed is too old. You'll need to update it. (1.3.1 installed because there was  a binary wheel available for it, but a packaging error means that 1.3.2 has to be installed from source.)

**Comment by jamadden** [comment]
1.3.2.post0 manylinux1 wheels have been posted.
