### ISSUE TITLE
From source build for 1.3.2 fails with pip environment marker exception

### ISSUE THREAD

**Issue by pkittenis** [gevent/gevent#1224]
* gevent version: ``1.3.2``
* Python version: All CPython versions, 2.7.x - 3.6.3
* Operating System: Ubuntu 14.04.5 LTS

### Description:

`pip install -U gevent` downloads source distribution due to missing manylinux wheels but from source builds fail with:

```
Successfully built gevent
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 91, in check_install_conflicts
    return state, check_package_set(state)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 62, in check_package_set
    missed = req.marker.evaluate()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_vendor/packaging/markers.py", line 301, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_vendor/packaging/markers.py", line 226, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/_vendor/packaging/markers.py", line 208, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

### What I've run:

```
pip install -U pip setuptools
pip install -U gevent
```

See also [build log with these steps from travis](https://travis-ci.org/ParallelSSH/parallel-ssh/jobs/385633224).

**Comment by jamadden** [comment]
I've never seen that before, I have no idea what it is. Perhaps your version of `wheel` is out of date in comparison with setuptools and pip? Otherwise this looks like a bug in `pip` or its vendored `packaging`.

**Comment by jamadden** [comment]
1.3.2.post0 manylinux1 wheels have been posted.

**Comment by pkittenis** [comment]
Indeed, it does not seem to come from gevent - closing. Weird one, cannot even replicate anymore. There are mentions of this happening on/off elsewhere too.
