### ISSUE TITLE
gevent fails to install 1.3.x, but works 1.2.0

### ISSUE THREAD

**Issue by hdost** [gevent/gevent#1234]
* gevent version: 1.3.x
* Python version: Python 3.4.3
* pip version: pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
* Operating System: Linux version 3.13.0-139-generic (buildd@lgw01-amd64-031) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #188-Ubuntu SMP Tue Jan 9 14:43:09 UTC 2018

### Description:
Expected this to install, but fails with the following error

```
---- Begin output of /usr/bin/pip3 install gevent ----
STDOUT: Downloading/unpacking gevent
  Running setup.py (path:/tmp/pip_build_root/gevent/setup.py) egg_info for package gevent
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/gevent/setup.py", line 417, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/tmp/pip_build_root/gevent/setup.py", line 401, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 595, in resolve
        requirements = list(requirements)[::-1]  # set up the stack
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
        line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
        "Expected ',' or end-of-list in",line,"at",line[p:]
    ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/gevent/setup.py", line 417, in <module>
    run_setup(EXT_MODULES, run_make=_BUILDING)

  File "/tmp/pip_build_root/gevent/setup.py", line 401, in run_setup
    "signal_os_incompat = gevent.monkey:_subscribe_signal_os",

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 595, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/gevent
Storing debug log for failure in /home/ubuntu/.pip/pip.log
STDERR:
---- End output of /usr/bin/pip3 install gevent ----
Ran /usr/bin/pip3 install gevent returned 1
```

### What I've run:

```python
pip3 install gevent
```

**Comment by jamadden** [comment]
Thanks for the report. Your version of setuptools is too old, you need to update it (potentially in a virtual environment). Your version of pip is also too old to install binary wheels; updating pip will let many installs, including gevent's, use binary wheels and be much faster.

cf #1223
