### ISSUE TITLE
 No module named 'gevent.__hub_local

### ISSUE THREAD

**Issue by feimeng115** [gevent/gevent#1250]
* gevent version: 1.3.4
* Python version: 3.6.5
* Operating System: linux-4.15.2.0 on imx6q

### Description:

when import gevent , then thers is a Traceback below.

Howerver, this code works well on unbuntu18.04

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python/lib/python3.6/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/python/lib/python3.6/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/python/lib/python3.6/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ModuleNotFoundError: No module named 'gevent.__hub_local'**
```

```
Remember to put tracebacks in literal blocks
```

### What I've run:

```python
# -*- coding: utf-8 -*-

import gevent

def fa():
    while 1:
        print('-------fa-------')
        gevent.sleep(1)


def fb():
    while 1:
        print('-------fb-------')
        gevent.sleep(0.5)


if __name__ == '__main__':

    g1 = gevent.spawn(fa)
    g2 = gevent.spawn(fb)

    g1.join()
    g2.join()

```

**Comment by jamadden** [comment]
If I understand correctly, "imx6q" is some sort of custom arm board. That means that this would not be a manylinux1 x86/amd64 binary installed wheel, and instead was built and installed from source.

In that case, I don't know what to tell you beyond the usual information about debugging failing extension module imports: check that the expected dynamic library is in the correct place on disk, examine the output of 'python -vv', try a fresh build from source (and examine the output carefully---you may need to use pip's -v option depending on how you're installing).

**Comment by manatlan** [comment]
Same traceback, with gevent 1.3.5, on python3.6.5, on **Windows10**(sp0), with a freezed app (with pyinstaller).

**Comment by jamadden** [comment]
"frozen" installs are in a constant state of brokenness. They're not tested by the project. There's a function in `__init__.py` that's supposed to make it better, but again, it's not tested. I'll accept PRs against it if it works for you, but it's not something I have any spare time for.
