### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by Mradr** [gevent/gevent#1265]
I am using the following package from https://github.com/mitmproxy/mitmproxy

When I from gevent import monkey; monkey.patch_all() it seems that everything just freeze. Looking into it more - it looks like the threads are being blocking - so I disable (thread=False) and then I still get the same blocking so I then disable (thread=False, select=False) and then I get cannot switch to a different thread. (thread=False, select=False, socket=False) seems to fix it - but I'm not understanding the problem in this case that is causing the threads to block and/or socket to be useable here. 

I'm sure the following files are needed to be look at to make this work, but it's a bit over my head and would like some feedback on this if I can:
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/master.py 
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/tcp.py (603)
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/coretypes/basethread.py (5)

My greater understand here is that greenlets are not the same as a thread as they are lighter weight than a raw thread would be, but is there any reason that a greenlet would not function the same as a normal thread would in this case?

Socket error:
```
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\site-packages\mitmproxy\net\tcp.py", line 601, in connection_thread
    close_socket(connection)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\site-packages\mitmproxy\net\tcp.py", line 261, in close_socket
    if not sock.recv(4096):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\_socket3.py", line 382, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 261, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 262, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
greenlet.error: cannot switch to a different thread
```

**Comment by jamadden** [comment]
> My greater understand here is that greenlets are not the same as a thread as they are lighter weight than a raw thread would be, but is there any reason that a greenlet would not function the same as a normal thread would in this case?

Yes, there's very much a reason. greenlets are *not* threads and are *not* preemptively scheduled. If this library is doing operations that require preemitive scheduling in a way that gevent cannot monkey-patch around, then it won't work. `patch_all` is gevent's best attempt at making libraries work non-preemptively and turning off individual options usually doesn't make things any better. Having "everything just freeze" is a great sign that some part of the library isn't cooperating with gevent despite the patches---usually a library implemented in C doing its own IO; the traceback at this point would help confirm that, as would gevent's own monitoring features. See [these posts](https://dev.nextthought.com/blog/2018/06/gevent-blocking-greenlets.html) for more info.

I see this library uses pyOpenSSL. I don't know very much about pyOpenSSL, but I do know pyOpenSSL is a C library built on OpenSSL (technically it uses CFFI to interface with the C OpenSSL). It implements its own `Connection` class, and it delegates most of its IO to the OpenSSL library. I'm going to guess that's where the problem is---the C ssl library is talking directly to the C (operating system) socket file descriptor, bypassing gevent entirely. So in short, I'm guessing pyOpenSSL is not gevent compatible.

A quick [web search](
https://www.google.com/search?client=safari&rls=en&q=pyopenssl+gevent&ie=UTF-8&oe=UTF-8) seems to confirm that, and the number one hit is a project that purports to make them compatible.

**Comment by Mradr** [comment]
So I follow the code they used there and converted the current SSL to use it - but I seem to be still having some blocking going on here. Mind taking a look again and see what I might be missing? Also thanks so much so far on helping out so far.

https://pastebin.com/ZWdHc1KM
https://www.diffchecker.com/lOqYqoPU (see the different)

**Comment by jamadden** [comment]
Sorry, I'm not a pyOpenSSL expert, I've helped all I can.
