### ISSUE TITLE
BlockingIOError multiprocessing error

### ISSUE THREAD

**Issue by 2335270107** [gevent/gevent#1268]
Traceback (most recent call last):
  File "/Users/maopinglin/Desktop/my/xiangmu/bwl/bwl.gouyungou.com/pachong/index.py", line 136, in <module>
    xsTimeOut = m.dict()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/managers.py", line 662, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/managers.py", line 554, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
BlockingIOError: [Errno 35] Resource temporarily unavailable

===================================
以上是错误提示,使用了多进程+多线程+gevent

**Comment by arcivanov** [comment]
MP is not monkeypatched and doesn't work with gevent.

**Comment by jamadden** [comment]
Only very simple uses of `multiprocessing.Process` are supported in a monkey-patched environment; the higher level abstractions are not. This is poorly documented (there's just a note on `gevent.monkey.patch_thread`), so that could be improved. I'll keep this open as a documentation bug.

**Comment by ml31415** [comment]
As it's not yet referenced here, for anyone feeling adventurous, this might help:

https://github.com/karellen/geventmp

**Comment by jgehrcke** [comment]
And for those who feel a little less adventurous; https://github.com/jgehrcke/gipc is actually rather well-proven; and satisfies a number of basic use cases.

**Comment by arcivanov** [comment]
As a note: geventmp does not require writing any additional code, it simply requires installation and standard gevent monkey-patch activation. That is the purpose of the library - transparent greening.
