### ISSUE TITLE
gevent installation issue

### ISSUE THREAD

**Issue by jeffiy** [gevent/gevent#1271]
* gevent version: 1.3.5
* Python version: Please be as specific as possible: "Python 3.6"
* Operating System: Please be as specific as possible: "PYNQ (ubuntu Linux 16.04 Linux armvhf"

### Description:

i am installing gevent on y PYNQ board but getting the error. following is the overall output of installation.

### What I've run:
```
xilinx@pynq:~/gevent-1.3.5$ sudo python3.6 setup.py install
[sudo] password for xilinx:
/opt/python3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing src/gevent.egg-info/PKG-INFO
writing dependency_links to src/gevent.egg-info/dependency_links.txt
writing entry points to src/gevent.egg-info/entry_points.txt
writing requirements to src/gevent.egg-info/requires.txt
writing top-level names to src/gevent.egg-info/top_level.txt
reading manifest file 'src/gevent.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'changelog.rst'
warning: no files found matching 'Makefile.ext'
warning: no files found matching 'known_failures.py'
warning: no files found matching '.pep8'
no previously-included directories found matching '*/__pycache__'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.lo' found anywhere in distribution
warning: no previously-included files matching '*.la' found anywhere in distribution
warning: no previously-included files matching 'config.log' found anywhere in distribution
warning: no previously-included files matching 'config.status' found anywhere in distribution
no previously-included directories found matching 'doc/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.coverage' found under directory 'src/greentest'
no previously-included directories found matching 'src/greentest/htmlcov'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/c-ares'
warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps/c-ares'
no previously-included directories found matching 'deps/libev/.deps'
no previously-included directories found matching 'deps/libuv/.deps'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libev'
warning: no previously-included files matching 'libtool' found under directory 'deps/libev'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/libev'
warning: no previously-included files matching 'config.h' found under directory 'deps/libev'
warning: no previously-included files matching '_corecffi.c' found under directory 'src/gevent'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching 'configure-output'
warning: no files found matching 'Makefile.ext'
warning: no previously-included files matching '.deps' found under directory 'deps/c-ares'
warning: no previously-included files matching '.libs' found under directory 'deps/c-ares'
warning: no previously-included files matching '.deps' found under directory 'deps/libuv'
warning: no previously-included files matching '.libs' found under directory 'deps/libuv'
warning: no previously-included files matching '.deps' found under directory 'deps/libev'
warning: no previously-included files matching '.libs' found under directory 'deps/libev'
writing manifest file 'src/gevent.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-armv7l-3.6/gevent.libuv._corecffi.c'
already up-to-date
generating cffi module 'build/temp.linux-armv7l-3.6/gevent.libev._corecffi.c'
already up-to-date
Running '(cd  "/home/xilinx/gevent-1.3.5/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /home/xilinx/gevent-1.3.5/build/temp.linux-armv7l-3.6/libev
: not found: 14: ./configure:
./configure: 30: ./configure: Syntax error: newline unexpected (expecting ")")
Traceback (most recent call last):
  File "setup.py", line 417, in <module>
    run_setup(EXT_MODULES, run_make=_BUILDING)
  File "setup.py", line 401, in run_setup
    "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
  File "/opt/python3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/python3.6/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/python3.6/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 141, in run
    base_class.run(self)
  File "/opt/python3.6/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 141, in run
    base_class.run(self)
  File "/opt/python3.6/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/opt/python3.6/lib/python3.6/site-packages/Cython-0.28.5-py3.6-linux-armv7l.egg/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/python3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/python3.6/lib/python3.6/site-packages/Cython-0.28.5-py3.6-linux-armv7l.egg/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/xilinx/gevent-1.3.5/_setuputils.py", line 200, in build_extension
    self.gevent_prepare(ext)
  File "/home/xilinx/gevent-1.3.5/_setuputils.py", line 197, in gevent_prepare
    configure(self, ext)
  File "/home/xilinx/gevent-1.3.5/_setuplibev.py", line 56, in configure_libev
    system(libev_configure_command)
  File "/home/xilinx/gevent-1.3.5/_setuputils.py", line 151, in system
    if _system(cmd, cwd=cwd, env=env, **kwargs):
  File "/home/xilinx/gevent-1.3.5/_setuputils.py", line 147, in _system
    return check_call(cmd, cwd=cwd, env=env, **kwargs)
  File "/opt/python3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/home/xilinx/gevent-1.3.5/deps/libev"  && sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' returned non-zero exit status 2.

```

**Comment by jamadden** [comment]
Based on that output, libev doesn’t support that platform. You can try installing a newer version of bash/sh (I’m guessing that platform uses some variant of busybox so that might nit be easy).

**Comment by jamadden** [comment]
(I edited the report to fix the formatting errors that were a result of ignoring the instructions.)
