### ISSUE TITLE
Build manylinux2010 wheels

### ISSUE THREAD

**Issue by jamadden** [gevent/gevent#1346]
pip 19 can install them and auditwheel 2.0 can create them. We just need to find an appropriate docker image

This should allow us to distribute libuv support in binary form on linux, a prerequisite towards making libuv the default on all platforms.

**Comment by bluetech** [comment]
Hi @jamadden, I tried to install gevent 1.5a1 and use the libuv backend, bit it fails -- thought you might like to know. Here are the steps I used:

```
$ uname -a
Linux ran 5.1.7-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 4 15:47:45 UTC 2019 x86_64 GNU/Linux
$ python --version
Python 3.7.3

$ python3.7 -m venv venv
$ . venv/bin/activate
$ pip install --upgrade pip
Successfully installed pip-19.1.1

$ pip install gevent==1.5a1
Collecting gevent==1.5a1
  Using cached https://files.pythonhosted.org/packages/3f/b4/c2acb758ae147c4320f3e0903afbc1031179e53740e2cf815f73ec51c898/gevent-1.5a1-cp37-cp37m-manylinux2010_x86_64.whl
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython" (from gevent==1.5a1)
  Using cached https://files.pythonhosted.org/packages/9d/ef/ac10aa1293f64939e4511909c570d969566126214af5dd7ba0afd353d88b/greenlet-0.4.15-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: greenlet, gevent
Successfully installed gevent-1.5a1 greenlet-0.4.15

$ ls venv/lib/python3.7/site-packages/gevent/libuv/
__pycache__/  _corecffi.abi3.so*  _corecffi_build.py  _corecffi_cdef.c  _corecffi_source.c  __init__.py  loop.py  watcher.py

$ python -c 'import gevent; gevent.config.loop = "libuv"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/_config.py", line 197, in __setattr__
    self.set(name, value)
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/_config.py", line 204, in set
    self.settings[name].set(value)
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/_config.py", line 150, in set
    self.value = self.validate(self._convert(val))
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/_config.py", line 223, in _import_one_of
    return self._import_one(candidates[-1])
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ran/tmp/py-spy/venv/lib/python3.7/site-packages/gevent/libuv/loop.py", line 15, in <module>
    from gevent.libuv import _corecffi # pylint:disable=no-name-in-module,import-error
ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by bluetech** [comment]
Hmm, I see I was just missing the `cffi` package - after installing it it works fine.
