### ISSUE TITLE
Intermittent LoopExit using ThreadPoolExecutor and waitable Futures

### ISSUE THREAD

**Issue by drpoggi** [gevent/gevent#1350]
* gevent version: 1.4.0
* Python version: cPython 2.7.15 (Ubuntu system python) 
* Operating System: Ubuntu 18.04

### Description:

I have a blocking function that I would like to run in a new thread, however when using ThreadPoolExecutor as I am in the below code it intermittently raises a LoopExit Exception. This may be due to me misusing ThreadPoolExecutor, but that clarification would be much appreciated.

Without the `gevent.sleep` it usually raises the LoopExit exception, however occasionally it does succeed. With the sleep included it seems to always succeed. Here is the traceback:

```
Traceback (most recent call last):
  File "/opt/virtualenv/default/lib/python2.7/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
  File "/opt/sample.py", line 18, in run_func
    answer = gevent.wait([result])
  File "src/gevent/_hub_primitives.py", line 217, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 254, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 152, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_hub_primitives.py", line 143, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_waiter.py", line 192, in gevent.__waiter.MultipleWaiter.get
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
LoopExit: This operation would block forever
	Hub: <Hub 'ThreadPool Worker Hub' at 0x7fe765086d60 epoll pending=0 ref=1 fileno=6 thread_ident=0x7fe764d1d700>
	Handles:
[]
2019-02-11T21:53:11Z (<ThreadPool at 0x7fe764f66a50 1/2/5 hub=<Hub at 0x7fe765086cb0 thread_ident=0x140631881508672>>, <function run_func at 0x7fe764f788c0>) failed with LoopExit

Traceback (most recent call last):
  File "/opt/sample.py", line 23, in <module>
    r.result()
  File "/opt/virtualenv/default/lib/python2.7/site-packages/gevent/threadpool.py", line 508, in result
    return self.asyncresult.result(timeout=timeout)
  File "src/gevent/event.py", line 344, in gevent._event.AsyncResult.result
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "/opt/virtualenvs/integrations_api/default/lib/python2.7/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
  File "/opt/integrations_api/default/bug.py", line 18, in run_func
    answer = gevent.wait([result])
  File "src/gevent/_hub_primitives.py", line 217, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 254, in gevent.__hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 152, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_hub_primitives.py", line 143, in gevent.__hub_primitives._WaitIterator.__next__
  File "src/gevent/_waiter.py", line 192, in gevent.__waiter.MultipleWaiter.get
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub 'ThreadPool Worker Hub' at 0x7fe765086d60 epoll pending=0 ref=1 fileno=6 thread_ident=0x7fe764d1d700>
	Handles:
[]
```

### What I've run:

```python
import gevent
from gevent import monkey
from gevent.threadpool import ThreadPoolExecutor, ThreadPool
monkey.patch_all()

POOL1 = ThreadPoolExecutor(5)
POOL2 = ThreadPoolExecutor(5)


def func():
    return


def run_func():
    result = POOL1.submit(func)
    # gevent.sleep(1)
    answer = gevent.wait([result])
    print(answer)


r = POOL1.submit(run_func)
r.result()
```

I also see this behavior with just one instance of ThreadPoolExecutor used for everything, but since this is (albeit much simplified) how my application is running I left it to use two in case that's not supported. Thanks for any input and/or clarifications!

**Comment by drpoggi** [comment]
Hi @jamadden just wanted to ping you to see if you've had a chance to look into this. Is this a bug, or perhaps just my improper usage of `ThreadPoolExecutor`?

**Comment by pkittenis** [comment]
Looking at the code, why is there a `result = POOL1.submit(func)` line in the `run_func`? That is already the target of the threadpool so would expect the target function to just run what it needs to run. Spawning greenlets in a new threadpool executor like that will require gevent imports inside the thread target so separate hubs are created per thread. Otherwise the two threads will share a hub which can lead to deadlocks as above.

The below works as expected for me:
```
import gevent
from gevent import monkey
from gevent.threadpool import ThreadPoolExecutor, ThreadPool
monkey.patch_all()

POOL1 = ThreadPoolExecutor(5)
POOL2 = ThreadPoolExecutor(5)


def func():
    return


def run_func():
    result = func()
    print(result)


r = POOL1.submit(run_func)
r.result()
```

**Comment by jamadden** [comment]
gevent's threadpool is primarily intended for running individual non-cooperative functions (either because they block on non-patched IO, or because they're CPU intensive; using the system's native DNS functions is an example of the former).

Threads in the threadpool do not necessarily have a running `hub` (event loop) or if they do, they may not have any other greenlets to switch to: hence the `LoopExit`. It largely depends on what else has been done in that thread in the past, something that can be very non-deterministic. Running blocking gevent functions, like `gevent.wait`, in a threadpool is thus pretty chancy. (It used to be much worse, you couldn't even use the threadpool itself *at all* from inside a threadpool thread!)

Running blocking gevent functions inside a threadpool isn't something we particularly want to encourage: there's substantial overhead to running additional hubs, and objects such as sockets (and `socket.makefile`) can have very surprising behaviour when passed between threads/hubs. (We are definitely open to improving documentation and error messages.)

In this particular case, using the native gevent `ThreadPool` interface, instead of `ThreadPoolExecutor`, may be a better option. It offers some specific functions such as `apply` that are specifically intended to be "recursion safe" without the caller needing to know the context of how they were run.

**Comment by drpoggi** [comment]
Thank you for the explanation and the advice, and especially for the work you do on this great library 👍
