### ISSUE TITLE
cannot import name import_c_accel

### ISSUE THREAD

**Issue by zeroheure** [gevent/gevent#1359]
* gevent version: error hapened with 2 versions :
     * gevent-1.2.1 + greenlet-0.4.12 from Centos 
     * gevent-1.4.0 +greenlet-0.4.15 from pip
* Python version: Python 2.7 from Centos repository
* Operating System: Centos 7.6.1810 Linux 3.10.0-957.5.1.el7.x86_64

### Description:
Web server running Odoo 10 installed from RPM package. 
I'm not a dev, I saw the problem in the logs 
```
Traceback (most recent call last):
File "/usr/bin/odoo", line 5, in <module>
__import__('pkg_resources').declare_namespace('odoo.addons')
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2146, in declare_namespace
declare_namespace(parent)
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2162, in declare_namespace
_handle_ns(packageName, path_item)
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2097, in _handle_ns
loader.load_module(packageName)
File "/usr/lib64/python2.7/pkgutil.py", line 246, in load_module
mod = imp.load_module(fullname, self.file, self.filename, self.etc)
File "/usr/lib/python2.7/site-packages/odoo/__init__.py", line 14, in <module>
import gevent.monkey
File "/usr/lib64/python2.7/site-packages/gevent/__init__.py", line 87, in <module>
from gevent._hub_local import get_hub
File "/usr/lib64/python2.7/site-packages/gevent/_hub_local.py", line 100, in <module>
from gevent._util import import_c_accel
ImportError: cannot import name import_c_accel
```
I'm not  a developer, but if I understand well, `import_c_accel` should be in `gevent/util.py` file, but it is not there. Any help welcome. Thanks.

**Comment by jamadden** [comment]
It should be in the [`gevent/_util.py`](https://github.com/gevent/gevent/blob/master/src/gevent/_util.py#L76) file.

But that was only added for gevent 1.*3*. A correct install of gevent 1.2.1 wouldn't be trying to import it.

It seems like your installation is incorrect. You might try uninstalling everything and reinstalling from scratch. Make sure you don't have a `gevent` directory after you uninstall.

If the problem persists, it would seem to be an error in either the packaging or the installation method. I'm sure the packages on pypi.org are correct, but I can't speak to downstream RPMs or downstream system-provided `pip` (which tend not to behave like the standard `pip`).

**Comment by zeroheure** [comment]
Yes it is in `gevent/_util.py` file.
I will reinstall, many thanks.
