### ISSUE TITLE
Debugging in PyCharm: docker + django + gevent + python3.6 error

### ISSUE THREAD

**Issue by jaddison** [gevent/gevent#1361]
* gevent version: 1.4.0
* Python version: `python:3.6-stretch` docker image
* Operating System: host macos; using docker-compose; docker image is debian stretch (see above)
>PyCharm 2018.3.5 (Professional Edition)
>Build #PY-183.5912.18, built on February 25, 2019
>JRE: 1.8.0_152-release-1343-b28 x86_64
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
>macOS 10.14.3

### Description:

Using django, gevent, docker, trying to debug in PyCharm (yes, I have the gevent checkbox ticked):
```
Connected to pydev debugger (build 183.5912.18)
django_1         | Traceback (most recent call last):
django_1         |   File "/opt/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 382, in _on_run
django_1         |     r = self.sock.recv(1024)
django_1         |   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 382, in recv
django_1         |     self._wait(self._read_event)
django_1         |   File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
django_1         |   File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
django_1         |   File "src/gevent/_hub_primitives.py", line 252, in gevent.__hub_primitives._primitive_wait
django_1         |   File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
django_1         |   File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
django_1         |   File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
django_1         |   File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
django_1         |   File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
django_1         |   File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
django_1         |   File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
django_1         |   File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
django_1         | greenlet.error: cannot switch to a different thread
```

I monkeypatch in Django's *manage.py*:
```
#!/usr/bin/env python
try:
    from gevent import monkey
    monkey.patch_all()
except ImportError:
    pass

try:
    import psycogreen.gevent
    psycogreen.gevent.patch_psycopg()
except ImportError:
    pass

import os  # noqa: E402
import sys  # noqa: E402

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "chatterblock.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)
```

It runs fine when using PyCharm's 'Run' method, but not its 'Debug' method - it errors as above.

It was works fine in Python3.5 in Vagrant/Virtualbox (Ubuntu image) - but not in docker (`python:3.6-stretch` docker image). I can't say for sure that it's Python3.5 vs 3.6 - it's more likely to be my switch to using docker?

**Comment by jamadden** [comment]
This would seem to indicate a problem with PyCharm, potentially trying to use a socket from multiple native threads. There's not much I can do about that, especially since I don't use or really know anything about PyCharm.

Since there's been no additional activity since March, I'm closing this. Feel free to reopen with additional details if there seems to be a gevent bug in a recent version.
