### ISSUE TITLE
cannot import name greenlet

### ISSUE THREAD

**Issue by TheDomco** [gevent/gevent#1396]
* gevent version: 1.4.0
* Python version: 2.7.15
* Operating System: W10 32bit

### Description:

I am trying to import gevent in my python embedded application. Setting python home path to C:\Python27 before Py_Initialize. I installed gevent through pip. If I try to import from python.exe (command line) it works well. However, in my application I am getting the error below. I've searched around the net and I only found some articles about name shadowing. I guess line 12 in file greenlet.py in gevent folder 
```
from greenlet import greenlet
```
is trying to import greenlet from the gevent folder instead of importing greenlet.pyd from site-packages folder. I have however no idea why would this happen or how to fix this. __hybrid_import is just builtin __import__. Any help would be appreciated.
```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "system.py", line 184, in __hybrid_import

  File "C:\Python27\lib\site-packages\gevent\__init__.py", line 63, in <module>

    
import socket  # pylint:disable=unused-import,useless-suppression

  File "system.py", line 184, in __hybrid_import

  File "C:\Python27\lib\site-packages\gevent\socket.py", line 16, in <module>

    
from gevent._compat import PY3

  File "system.py", line 184, in __hybrid_import

  File "C:\Python27\lib\site-packages\gevent\_compat.py", line 9, in <module>

    
import os

  File "system.py", line 184, in __hybrid_import

  File "C:\Python27\lib\site-packages\gevent\os.py", line 48, in <module>

    
from gevent.hub import _get_hub_noargs as get_hub

  File "system.py", line 184, in __hybrid_import

  File "C:\Python27\lib\site-packages\gevent\hub.py", line 14, in <module>

    
from greenlet import greenlet as RawGreenlet

  File "system.py", line 184, in __hybrid_import

  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 12, in <module>

    
from greenlet import greenlet

ImportError
: 
cannot import name greenlet

```

**Comment by jamadden** [comment]
`gevent/hub.py` begins with `from __future__ import absolute_import`, (as does `gevent/greenlet.py`) so even on Python 2` `from greenlet import greenlet` *should* look for the global `greenlet` module. 

I would guess there is something wrong with the way the embedded application is configuring python and its path (`sys.path`). Alternately, I guess its possible the replacement `__hybrid_import` isn't respecting the nuances of the `__import__` API...

**Comment by TheDomco** [comment]
Thank you, that was the problem.
``` I guess its possible the replacement `__hybrid_import` isn't respecting the nuances of the `__import__` API...
```
