### ISSUE TITLE
ImportError: cannot import name _corecffi

### ISSUE THREAD

**Issue by maingoh** [gevent/gevent#1419]
I installed gevent using `pip install gevent` and have the latest version 1.4.0. I would like to compare the speed between all event loops but don't manage to use libuv. Is there a specific installation to do ?
```
>>> import gevent
>>> gevent.config.loop = 'libuv'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gevent/_config.py", line 197, in __setattr__
    self.set(name, value)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_config.py", line 204, in set
    self.settings[name].set(value)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_config.py", line 150, in set
    self.value = self.validate(self._convert(val))
  File "/usr/local/lib/python2.7/dist-packages/gevent/_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "/usr/local/lib/python2.7/dist-packages/gevent/_config.py", line 223, in _import_one_of
    return self._import_one(candidates[-1])
  File "/usr/local/lib/python2.7/dist-packages/gevent/_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/gevent/libuv/loop.py", line 15, in <module>
    from gevent.libuv import _corecffi # pylint:disable=no-name-in-module,import-error
ImportError: cannot import name _corecffi
```

**Comment by jamadden** [comment]
If you want to use libuv with gevent 1.4 on Linux, you need to build from source. The binary wheels that pip installs by default cannot contain libuv support because of limitations in the manylinux1 specification. See http://www.gevent.org/installing_from_source.html for more info on doing that.

If you install gevent 1.5a1 on Linux, libuv support is available using the binary wheel. (However, note that it is compiled with lowest-common-denominator settings, so it may not be as capable as a gevent built from source on your specific platform, and it may not be as fast as one built with your specific compiler optimizations.)

**Comment by maingoh** [comment]
Thank you, this is perfectly working ! 
I couldn't find the documentation about it, maybe highlight it a bit more here http://www.gevent.org/loop_impls.html ?
