### ISSUE TITLE
run WSGIServer in normal python threads

### ISSUE THREAD

**Issue by kevinkwl** [gevent/gevent#1427]
* gevent version: 1.4.0
* Python version: Python 3.5.2
* Operating System: Linux 4.15.0-50-generic #54~16.04.1-Ubuntu SMP x86_64 GNU/Linux

### Description:

Trying to run two separate WSGIServer in two separate python normal threads, and I'm getting the following output

```
Traceback (most recent call last):
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/threadpool.py", line 389, in _on_async
    self.receiver(self)
  File "src/gevent/event.py", line 339, in gevent._event.AsyncResult.__call__
  File "src/gevent/event.py", line 259, in gevent._event.AsyncResult.set_exception
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/_tblib.py", line 426, in dump_traceback
    return dumps(tb)
TypeError: 'NoneType' object is not callable
2019-06-06T21:02:48Z <async_ at 0x7f08eb03cc78> failed with TypeError

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "gs.py", line 16, in run_wsgi
    server.serve_forever()
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/baseserver.py", line 367, in serve_forever
    self.start()
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/baseserver.py", line 305, in start
    self.init_socket()
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/pywsgi.py", line 1491, in init_socket
    self.update_environ()
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/pywsgi.py", line 1503, in update_environ
    name = socket.getfqdn(address[0])
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/_socketcommon.py", line 269, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/_socketcommon.py", line 241, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/resolver/thread.py", line 68, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "/home/kangwei.ling/.local/lib/python3.5/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 293, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
        Hub: <Hub '' at 0x7f08ea451390 epoll pending=0 ref=0 fileno=5 resolver=<gevent.resolver_thread.Resolver at 0x7f08e9f83dd8 pool=<ThreadPool at 0x7f08e9f83e10 0/1/10 hub=<Hub at 0x7f08ea451390 thread_ident=0x139676253406976>>> threadpool=<ThreadPool at 0x7f08e9f83e10 0/1/10 hub=<Hub at 0x7f08ea451390 thread_ident=0x139676253406976>> thread_ident=0x7f08e977c700>
        Handles:
[]

```

### What I've run:
A simple program to demo:

```python
from gevent.pywsgi import WSGIServer
from threading import Thread

def app(env, start_response):
    if env['PATH_INFO'] == '/':
        start_response('200 OK', [('Content-Type', 'text/html')])
        return [b"<b>hello world</b>"]
    start_response('404 Not Found', [('Content-Type',
        'text/html')])
    return [b'<h1>Not Found</h1>']


def run_server(port):
    def run_wsgi():
        server = WSGIServer(('0.0.0.0', port), app)
        server.serve_forever()
    t = Thread(target=run_wsgi)
    print('starting')
    t.start()

if __name__ == '__main__':
    run_server(5000)
    run_server(5999)
```

when I give the server '127.0.0.1' or 'localhost', everything runs fine. 

 if I just run one server  (still in another thread), it also works without errors.

The problem only occurs when I run multiple servers and provided a non-canonical ip. Is there any way to work around this?

Thanks.

P.S. Currently, monkey patching can't be used because I m trying to develop a framework.

**Comment by jamadden** [comment]
Have you tried using [a non-threaded resolver](http://www.gevent.org/dns.html)? The 'blocking' one would be the simplest.

**Comment by kevinkwl** [comment]
Hi @jamadden , using the block resolver actually worked! I am quite intrigued by this problem. As I am quite new to gevent, can you give some details why the thread-resolver cause such problem in a 'multi thread' environment?

Thank you so much!

**Comment by jamadden** [comment]
I can't give very much detail without spending time digging into this particular setup. In general, running multiple event loops in multiple threads has been something that has to be approached with great care. It's not really a tested scenario (especially *without* monkey-patching), and the benefits are often very small (unless the workload is very specific, such as a CPU heavy load that releases the GIL --- but oftentimes the threadpool works just as well for that). I try to squash bugs there as they pop up but as I said, it's not really tested with any consistency.

**Comment by kevinkwl** [comment]
I see. Thanks for the help anyway!
