### ISSUE TITLE
patch_all() on python3.7 does not work right now.

### ISSUE THREAD

**Issue by allwell997** [gevent/gevent#1450]
I cannot run a gevent program. the error is as bellow , please check. 
1. python enviorment  Pycharm / Python3.7 / win10
2. my imported list 
     from gevent import monkey; monkey.patch_all()
     import gevent
     import requests
3. the error shows here.
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['_shaded_thriftpy.transport._ssl (C:\\Program Files\\JetBrains\\PyCharm 2019.1\\helpers\\third_party\\thriftpy\\_shaded_thriftpy\\transport\\_ssl.py)']. 
  from gevent import monkey; monkey.patch_all()

how to do in next step ?

**Comment by arcivanov** [comment]
Yes it does work. This issue comes up several times a year.

Make sure to check "Gevent compatible" here:
![image](https://user-images.githubusercontent.com/5355666/63236440-a75f9a00-c20b-11e9-9194-c954349ae33a.png)

In the alternative you can verify by running from command line without PyCharm.

**Comment by allwell997** [comment]
I have been changed the settting as your comments. But there still is the same error notification. 

MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['_shaded_thriftpy.transport._ssl (C:\\Program Files\\JetBrains\\PyCharm 2019.1\\helpers\\third_party\\thriftpy\\_shaded_thriftpy\\transport\\_ssl.py)']. 
  monkey.patch_all()

**Comment by arcivanov** [comment]
@allwell997 could you please post code that performs multipatching in full?

**Comment by allwell997** [comment]
from gevent import monkey
monkey.patch_all()
import gevent

import requests
import time

def get_home(url):
    rsp = requests.get(url)
    if rsp.status_code == 200:
        print('{} bytes received from {}'.format(len(rsp.text), url))

start = time.time()

url_lst = ['http://www.baidu.com',
           'http://www.taobao.com',
           'http://www.jd.com',
           'http://www.sina.com.cn',
           'http://www.weibo.com']
g_lst = []
for url in url_lst:
    g = gevent.spawn(get_home, url)
    g_lst.append(g)

gevent.joinall(g_lst)

took = time.time() - start
print(took)

**Comment by arcivanov** [comment]
There is no `__main__` stanza. Are you sure this is what you're invoking?

**Comment by arcivanov** [comment]
Are you getting the same result from the command line?

**Comment by allwell997** [comment]
I added the __main__ in the program. but the same error notification occured. but it is work well with command line. 
==================================================
from gevent import monkey
monkey.patch_all()
import gevent

import requests
import time

def get_home(url):
    rsp = requests.get(url)
    if rsp.status_code == 200:
        print('{} bytes received from {}'.format(len(rsp.text), url))

if __name__ == '__main__':

    start = time.time()

    url_lst = ['http://www.baidu.com',
               'http://www.taobao.com',
               'http://www.jd.com',
               'http://www.sina.com.cn',
               'http://www.weibo.com']
    g_lst = []
    for url in url_lst:
        g = gevent.spawn(get_home, url)
        g_lst.append(g)

    gevent.joinall(g_lst)

    took = time.time() - start
    print(took)

**Comment by arcivanov** [comment]
If it works well with command line it's not an issue with gevent, but with your PyCharm setup.

**Comment by allwell997** [comment]
here you are the full information. could you help me to set up my pycharm or others? 
=======================================================
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['_shaded_thriftpy.transport._ssl (C:\\Program Files\\JetBrains\\PyCharm 2019.1\\helpers\\third_party\\thriftpy\\_shaded_thriftpy\\transport\\_ssl.py)']. 
  monkey.patch_all()
2381 bytes received from http://www.baidu.com
99675 bytes received from http://www.jd.com
141860 bytes received from http://www.taobao.com
564079 bytes received from http://www.sina.com.cn
6117 bytes received from http://www.weibo.com
1.3283326625823975
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_bundle\pydev_code_executor.py", line 112, in add_exec
    self.finish_exec(more)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_bundle\pydev_console_utils.py", line 211, in finish_exec
    return server.notifyFinished(more)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\transport.py", line 226, in _req
    return super(TSyncClient, self)._req(_api, *args, **kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\thrift.py", line 160, in _req
    return self._recv(_api)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\thrift.py", line 172, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\protocol\binary.py", line 372, in read_message_begin
    self.trans, strict=self.strict_read)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\protocol\binary.py", line 164, in read_message_begin
    sz = unpack_i32(inbuf.read(4))
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\transport\__init__.py", line 32, in read
    return readall(self._read, sz)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\transport\__init__.py", line 14, in readall
    chunk = read_fn(sz - have)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\transport.py", line 160, in _read
    return self._reader.read_response(sz)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\transport.py", line 33, in read_response
    return self._response_pipe.read(sz)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\io.py", line 40, in read
    self.bytes_produced.wait()
  File "C:\Program Files\Python37\lib\threading.py", line 296, in wait
    waiter.acquire()
  File "C:\Program Files\Python37\lib\site-packages\gevent\thread.py", line 84, in acquire
    return BoundedSemaphore.acquire(self, blocking, timeout)
Traceback (most recent call last):
  File "src\gevent\_semaphore.py", line 100, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_semaphore.py", line 128, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src\gevent\_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\server.py", line 34, in handle
    self.processor.process(iprot, oprot)
  File "src\gevent\_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\thrift.py", line 257, in process
    api, seqid, result, call = self.process_in(iprot)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\thrift.py", line 212, in process_in
    api, type, seqid = iprot.read_message_begin()
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\protocol\binary.py", line 372, in read_message_begin
    self.trans, strict=self.strict_read)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\protocol\binary.py", line 164, in read_message_begin
    sz = unpack_i32(inbuf.read(4))
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\transport\__init__.py", line 32, in read
    return readall(self._read, sz)
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x2a3bb210d38 default default pending=0 ref=0 resolver=<gevent.resolver_thread.Resolver at 0x2a3bb579390 pool=<ThreadPool at 0x2a3bb579400 0/5/10 hub=<Hub at 0x2a3bb210d38 thread_ident=0x18536>>> threadpool=<ThreadPool at 0x2a3bb579400 0/5/10 hub=<Hub at 0x2a3bb210d38 thread_ident=0x18536>> thread_ident=0x4868>
	Handles:
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B9DAB378>, type=b'check', watcher=<loop at 0x2a3bb258898 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B7306B88>, type=b'timer', watcher=<loop at 0x2a3bb258898 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B9DAB2C8>, type=b'prepare', watcher=<loop at 0x2a3bb258898 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B9DAB168>, type=b'check', watcher=<loop at 0x2a3bb258898 default default pending=0 ref=0>, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B9DBC5E8>, type=b'async', watcher=<async_ at 0x2a3bb579470 callback=<bound method ThreadPool._on_fork of <ThreadPool at 0x2a3bb579400 0/5/10 hub=<Hub at 0x2a3bb210d38 thread_ident=0x18536>>> args=() watcher=<cdata 'struct uv_async_s *' owning 224 bytes> handle=<cdata 'void *' 0x000002A3BB5A59A8> ref=False>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B7375368>, type=b'poll', watcher=None, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B97C5DD8>, type=b'poll', watcher=None, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B732A498>, type=b'poll', watcher=None, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3B9757AF8>, type=b'poll', watcher=None, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3BAA3C898>, type=b'poll', watcher=None, ref=1, active=0, closing=0)]
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\transport\__init__.py", line 14, in readall
    chunk = read_fn(sz - have)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\third_party\thriftpy\_shaded_thriftpy\transport\buffered\__init__.py", line 39, in _read
    self._rbuf = BytesIO(self._trans.read(max(sz, self._buf_size)))
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\transport.py", line 215, in read
    return self._read_fn(sz)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\transport.py", line 27, in read_request
    return self._request_pipe.read(sz)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_comm\io.py", line 40, in read
    self.bytes_produced.wait()
  File "C:\Program Files\Python37\lib\threading.py", line 296, in wait
    waiter.acquire()
  File "C:\Program Files\Python37\lib\site-packages\gevent\thread.py", line 84, in acquire
    return BoundedSemaphore.acquire(self, blocking, timeout)
  File "src\gevent\_semaphore.py", line 100, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_semaphore.py", line 128, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src\gevent\_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x2a3ba778328 default pending=0 ref=0 thread_ident=0x3484>
	Handles:
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3BAE1FB88>, type=b'check', watcher=<loop at 0x2a3bb5a8b70 default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3BAE0EF68>, type=b'timer', watcher=<loop at 0x2a3bb5a8b70 default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3BAE1D508>, type=b'prepare', watcher=<loop at 0x2a3bb5a8b70 default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000002A3BAE1F3F8>, type=b'check', watcher=<loop at 0x2a3bb5a8b70 default pending=0 ref=0>, ref=1, active=0, closing=0)]

**Comment by allwell997** [comment]
I have soloved it. I set the debug configuration and then remove the run with python console. it is work well.  Thanks.
