### ISSUE TITLE
Cannot compile Script that uses Gevent

### ISSUE THREAD

**Issue by DivineSentry** [gevent/gevent#1458]
Using Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Using Gevent ( Have tried both 1.4.0 & 1.5a1 with the same result)

using this command `nuitka --remove-output --plugin-enable=tk-inter --plugin-enable=gevent --follow-imports --plugin-enable=pylint-warnings --show-progress --show-scons --mingw64 script.py`

```python traceback
Problem with statement at C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\__init__.py:1:
-> # Copyright (c) 2009-2012 Denis Bilenko. See LICENSE for details.

Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'C:\\Users\\win1\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\gevent\\__init__.py', 'package': None, 'name': 'gevent'}>'.
Traceback (most recent call last):
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 759, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 561, in optimize
    finished = makeOptimizationPass(initial_pass=False)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 456, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 167, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 514, in computeModule
    trace_collection=self.trace_collection
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 549, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\nodes\AssignNodes.py", line 261, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 525, in onExpression
    parent = expression.parent
AttributeError: parent
```

**Comment by jamadden** [comment]
Sorry, I can't help you with that. It looks like some internal problem in nuitka (though the location the compiler's pointing to doesn't make any sense) and I know nothing about its internals. I only have a basic awareness of it as a project. 

gevent already has its most important parts compiled (on CPython) and uses a number of dynamic features of the Python language. I don't know how well to expect static compilers to deal with those.

**Comment by DivineSentry** [comment]
Thanks for the reply!, Didn't realize this wouldn't fall under your purview, will now open an issue with nuitka, thank you!
