### ISSUE TITLE
Gevent fails to install with Python debug build

### ISSUE THREAD

**Issue by navytux** [gevent/gevent#1461]
* gevent version: 1.4.0-178-g9d27d269 (today's master)
* Python version: CPython-dbg 2.7.16 as shipped by Debian 10.1
* Operating System: Debian GNU/Linux 10.1 on amd64 (kernel: `4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux`)

### Description:

Hello up there. I was trying to install gevent under debug Python build (which performs reference counting error checks and other runtime verifications) and though installation succeeds, further attempt to `import gevent` fails with

```
ImportError: /home/kirr/src/tools/py/py2dbg.venv/local/lib/python2.7/site-packages/gevent/__hub_local_d.so: undefined symbol: Py_InitModule4_64
```

I've got the impression that the failure is that gevent somehow uses non-debug Python headers and CFLAGS and then it fails with python-dbg who intentionally renames some symbols to catch such issues.

Please see full details below:

```
kirr@deco:~/src/tools/py/gevent$ git describe 
1.4.0-178-g9d27d269

kirr@deco:~/src/tools/py/gevent$ git clean -fdx

kirr@deco:~/src/tools/py/gevent$ virtualenv -p python2-dbg ../py2dbg.venv
Running virtualenv with interpreter /usr/bin/python2-dbg
New python executable in /home/kirr/src/tools/py/py2dbg.venv/bin/python2-dbg
Also creating executable in /home/kirr/src/tools/py/py2dbg.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

kirr@deco:~/src/tools/py/gevent$ . ../py2dbg.venv/bin/activate

(py2dbg.venv) kirr@deco:~/src/tools/py/gevent$ which python
/home/kirr/src/tools/py/py2dbg.venv/bin/python

(py2dbg.venv) kirr@deco:~/src/tools/py/gevent$ python --version
Python 2.7.16

(py2dbg.venv) kirr@deco:~/src/tools/py/gevent$ git clean -fdx

(py2dbg.venv) kirr@deco:~/src/tools/py/gevent$ pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /home/kirr/src/tools/py/gevent
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython" (from gevent==1.5a2.dev0)
Building wheels for collected packages: gevent
  Building wheel for gevent (PEP 517) ... done
  Created wheel for gevent: filename=gevent-1.5a2.dev0-cp27-cp27dmu-linux_x86_64.whl size=4293456 sha256=edf4b4bd64937852bdb9412e08d205262633367d9298d0f4d956cb1524177892
  Stored in directory: /tmp/pip-ephem-wheel-cache-Duh9c8/wheels/12/e6/3e/e6eb533a12ee703ab95c78b8435960b12a24bb50316139ea04
Successfully built gevent
Installing collected packages: greenlet, gevent
Successfully installed gevent-1.5a2.dev0 greenlet-0.4.15

(py2dbg.venv) kirr@deco:~/src/tools/py/gevent$ python -c 'import gevent'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kirr/src/tools/py/py2dbg.venv/local/lib/python2.7/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/home/kirr/src/tools/py/py2dbg.venv/local/lib/python2.7/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/kirr/src/tools/py/py2dbg.venv/local/lib/python2.7/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /home/kirr/src/tools/py/py2dbg.venv/local/lib/python2.7/site-packages/gevent/__hub_local_d.so: undefined symbol: Py_InitModule4_64
```

See also https://lab.nexedi.com/kirr/gevent/commit/83ebd4d8 which might help a bit as well.

Thanks beforehand,
Kirill

**Comment by jamadden** [comment]
I'm happy to review PRs but probably won't find time to work on this myself soon.

**Comment by navytux** [comment]
@jamadden, thanks for feedback. Let me see if I can get to this eventually.

**Comment by navytux** [comment]
@jamadden thanks for fixing this.
