### ISSUE TITLE
ModuleNotFoundError: No module named '_socket'

### ISSUE THREAD

**Issue by JoshiPriyanka92** [gevent/gevent#1463]
* gevent version: gevent-1.5a1
* Python version: 3.7.4
* Operating System: Ubuntu 16.04
* pip version:19.2.3

### Description:

**Trying to run gevent inside py37 virtual env**: 
I am trying to start a uwsgi service which uses gevent 1.4.0 inside py3.7 virtual env. But I keep . getting ModuleNotFoundError: No module named '_socket'. Tried setting PYTHONPATH to lib folder as suggested in different places online, but no luck. 

```
(devenv) admin@rb01:~$ /opt/ns/devenv/bin/uwsgi  --buffer-size 65535 --http-socket sample01:6010 --need-app --wsgi-file /opt/ns/devenv/lib/python3.7/site-packages/sampleproxy/apps/start.py --callable app --enable-threads --gevent 2000
*** Starting uWSGI 2.0.18 (64bit) on [Thu Sep 19 11:18:52 2019] ***
compiled with version: 5.4.0 20160609 on 13 September 2019 12:39:35
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: rb01
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/admin
detected binary path: /opt/ns/devenv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15651
your memory page size is 4096 bytes
detected max file descriptor number: 200000
- async cores set to 2000 - fd table size: 200000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address sample01:6010 fd 3
Python version: 3.7.2 (default, Sep  2 2019, 14:27:02)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x16b89d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 143852464 bytes (140480 KB) for 2000 cores
*** Operational MODE: async ***
Traceback (most recent call last):
  File "/opt/ns/devenv/lib/python3.7/site-packages/nssamlproxy/apps/server.py", line 13, in <module>
    monkey.patch_all()
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/monkey.py", line 982, in patch_all
    patch_socket(dns=dns, aggressive=aggressive)
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/monkey.py", line 178, in ignores
    return func(*args, **kwargs)
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/monkey.py", line 679, in patch_socket
    from gevent import socket
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/socket.py", line 22, in <module>
    from gevent import _socket3 as _source # python 2: pylint:disable=no-name-in-module
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_socket3.py", line 14, in <module>
    from gevent import _socketcommon
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_socketcommon.py", line 115, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***

```

### Tried importing signal, _socket and _sockecommon from different locations:

**When importing by activating the virtual env, but outside the site-packages path**: 

```(devenv) admin@rb01:~$ python3.7
Python 3.7.4 (default, Sep  2 2019, 20:44:09)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _socket
>>> import signal
>>> from gevent import _socketcommon
>>>
```
**When importing by activating the virtual env, but inside the site-packages path**: 
```(devenv) admin@rb01:/opt/ns/devenv/lib/python3.7/site-packages/gevent$ python3.7
Python 3.7.4 (default, Sep  2 2019, 20:44:09)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gevent import _socketcommon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._config import config
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_config.py", line 699, in <module>
    Loop().get()
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_config.py", line 146, in get
    self.value = self.validate(self._default())
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_config.py", line 219, in _import_one_of
    return self._import_one(item)
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "/opt/ns/devenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/libev/corecext.pyx", line 42, in init gevent.libev.corecext
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/signal.py", line 30, in <module>
    _signal_signal = _signal.signal
AttributeError: module 'signal' has no attribute 'signal'
>>>
>>>
>>>
>>> import signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/signal.py", line 30, in <module>
    _signal_signal = _signal.signal
AttributeError: module 'signal' has no attribute 'signal'
```
**After setting the PYTHONPATH**:
```(devenv) admin@rb01:/opt/ns/devenv/lib/python3.7/site-packages/gevent$ export PYTHONPATH=/opt/ns/devenv/lib
(devenv) admin@rb01:/opt/ns/devenv/lib/python3.7/site-packages/gevent$ python3.7
Python 3.7.4 (default, Sep  2 2019, 20:44:09)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/signal.py", line 19, in <module>
    from gevent._util import _NONE as _INITIAL
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/opt/ns/devenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
    ctypedef class greenlet.greenlet [object PyGreenlet]:
  File "/opt/ns/devenv/lib/python3.7/site-packages/gevent/greenlet.py", line 12, in <module>
    from greenlet import greenlet
ImportError: cannot import name 'greenlet' from 'greenlet' (/opt/ns/devenv/lib/python3.7/site-packages/gevent/greenlet.py)
>>> import _socket
>>>
```

Any suggestion/solution to get through this ?

**Comment by jamadden** [comment]
Based on the examples for "but inside the site-packages path" and "After setting the PYTHONPATH", it looks like `sys.path` is incorrect. It looks like the `gevent/` directory itself is on the path, instead of the directory *containing* `gevent/`. That is, the path contains `/opt/ns/devenv/lib/python3.7/site-packages/gevent` when all it actually should contain is `/opt/ns/devenv/lib/python3.7/site-packages/`. That explains the shadowing of the standard modules and modules from other packages.

I don't know why uWSGI can't import the stdlib `_socket` module. Something like the output of `python -v` would tell you where it looked, and that that often explains why it can't be found, but I have no idea how to do any of that with uWSGI.

**Comment by thepjoshi** [comment]
Thanks @jamadden, my paths were indeed screwed up.
