### ISSUE TITLE
gevent 1.3b1 broke coverage.py measurement after joinall()

### ISSUE THREAD

**Issue by nedbat** [gevent/gevent#1471]
* gevent version: 1.3b1 (or later, also broken with 1.4.0)
* Python version: CPython 3.6.7
* Operating System: Mac OS 10.13.6

### Description:

Using coverage.py to measure coverage.  Lines after `gevent.joinall` are marked as unexecuted, even though they have been executed.  https://github.com/nedbat/coveragepy/issues/841 is the original report for coverage.py

Versions 1.3a2 and before aren't broken.  Versions 1.3b1 and later are.  If you want to try changing the gevent version, you can change it in the tox.ini file: https://github.com/nedbat/coveragepy/blob/nedbat/bug841/tox.ini#L19-L25

I'll be digging more into this. I don't expect you to figure out everything about how coverage.py does what it does.  Central to it is `gevent.getcurrent`, which is used to determine if the execution context has changed.  Did 1.3b1 introduce a change there?

How to reproduce:
```
$ git clone https://github.com/nedbat/coveragepy
Cloning into 'coveragepy'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 25027 (delta 2), reused 8 (delta 2), pack-reused 25015
Receiving objects: 100% (25027/25027), 13.06 MiB | 16.80 MiB/s, done.
Resolving deltas: 100% (15058/15058), done.

$ cd coveragepy

$ git checkout nedbat/bug841
Branch 'nedbat/bug841' set up to track remote branch 'nedbat/bug841' from 'origin' by rebasing.
Switched to a new branch 'nedbat/bug841'
@/tmp/bug841/coveragepy [tmp-5b6181b55fa71418] nedbat/bug841 ± pip install -r requirements/dev.pip
Requirement already satisfied: pip==19.3.1 in /usr/local/virtualenvs/tmp-5b6181b55fa71418/lib/python3.6/site-packages (from -r requirements/dev.pip (line 7)) (19.3.1)
Collecting virtualenv==16.7.6
  Using cached https://files.pythonhosted.org/packages/89/66/786e0d6f61bd0612f431e19b016d1ae46f1cb8d21a80352cc6774ec876e3/virtualenv-16.7.6-py2.py3-none-any.whl
Collecting pluggy==0.13.0
  Using cached https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl
Collecting tox==3.14.0
  Using cached https://files.pythonhosted.org/packages/a7/0c/ed234b83d2c4fcef1cfccf97371183d51dafae62e64334de34d0a6333114/tox-3.14.0-py2.py3-none-any.whl
Collecting tox-battery==0.5.1
  Using cached https://files.pythonhosted.org/packages/ce/2f/f2b73f1c51bf49cc580770edc929104e7f655f56e4811f89494e4ec61835/tox_battery-0.5.1-py2.py3-none-any.whl
Collecting pytest==4.6.6
  Using cached https://files.pythonhosted.org/packages/64/f1/187a98b8f913a8f3a53d213cca2fae19718565f36165804d7f4f91fe5b76/pytest-4.6.6-py2.py3-none-any.whl
Collecting pytest-xdist==1.30.0
  Using cached https://files.pythonhosted.org/packages/f7/80/2af1fc039f779f61c7207dc9f79a1479874e7795f869fddaf135efde1cd4/pytest_xdist-1.30.0-py2.py3-none-any.whl
Collecting flaky==3.6.1
  Using cached https://files.pythonhosted.org/packages/fe/12/0f169abf1aa07c7edef4855cca53703d2e6b7ecbded7829588ac7e7e3424/flaky-3.6.1-py2.py3-none-any.whl
Collecting mock==3.0.5
  Using cached https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/87/42/54/0a9c2dcc4b90546d40215817d7c723f99a4ab16da637be9539/PyContracts-1.8.12-cp36-none-any.whl
Collecting hypothesis==4.41.2
  Using cached https://files.pythonhosted.org/packages/bc/af/392c2f90d69c6d3c5214a9c25fc7d336e1e600adf7ff80638139f12f7ae5/hypothesis-4.41.2-py3-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/8f/7c/f0/d32d4d197e195edc4c8c122a8249fd8111f8faf0bdc8430777/unittest_mixins-1.6-cp36-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/13/c3/cf/5920a8fd6333073b25f24d63ae8d3577d6f9000f14ff4d6114/pudb-2019.1-cp36-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/cc/28/5a/2687513046a61b17dd78be058a43a069c271f5d7b7623f3dfd/greenlet-0.4.15-cp36-cp36m-macosx_10_13_x86_64.whl
Collecting pylint==2.4.3
  Using cached https://files.pythonhosted.org/packages/ea/f1/758de486e46ea2b8717992704b0fdd968b7cbc2bc790b976fae4a35a212c/pylint-2.4.3-py3-none-any.whl
Collecting check-manifest==0.40
  Using cached https://files.pythonhosted.org/packages/4c/76/247904bbfbfc7077389d97062c97db557da4f3184fc5a22eb0834607ffbf/check_manifest-0.40-py2.py3-none-any.whl
Collecting readme_renderer==24.0
  Using cached https://files.pythonhosted.org/packages/c3/7e/d1aae793900f36b097cbfcc5e70eef82b5b56423a6c52a36dce51fedd8f0/readme_renderer-24.0-py2.py3-none-any.whl
Collecting requests==2.22.0
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting twine==2.0.0
  Using cached https://files.pythonhosted.org/packages/c4/43/b9c56d378f5d0b9bee7be564b5c5fb65c65e5da6e82a97b6f50c2769249a/twine-2.0.0-py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting toml>=0.9.4
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting six<2,>=1.0.0
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting py<2,>=1.4.17
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting packaging>=14
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting more-itertools>=4.0.0; python_version > "2.7"
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Collecting atomicwrites>=1.0
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting wcwidth
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting pytest-forked
  Using cached https://files.pythonhosted.org/packages/03/1e/81235e1fcfed57a4e679d34794d60c01a1e9a29ef5b9844d797716111d80/pytest_forked-1.1.3-py2.py3-none-any.whl
Collecting execnet>=1.1
  Using cached https://files.pythonhosted.org/packages/d3/2e/c63af07fa471e0a02d05793c7a56a9f7d274a8489442a5dc4fb3b2b3c705/execnet-1.7.1-py2.py3-none-any.whl
Collecting pyparsing
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting decorator
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/74/bc/50/ae030267a192919b289f84661cfeb5573cf383841c543e8696/future-0.18.1-cp36-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/34/06/50/24011714e101b5ad8518c69175d117a257413e3c15a92983f0/urwid-2.0.1-cp36-cp36m-macosx_10_13_x86_64.whl
Collecting pygments>=1.0
  Using cached https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl
Collecting astroid<2.4,>=2.3.0
  Using cached https://files.pythonhosted.org/packages/64/d3/4ba68bd56297556c9c2e5072d71d1664feaa86d9726c237a9fe496d440f4/astroid-2.3.2-py3-none-any.whl
Collecting isort<5,>=4.2.5
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting mccabe<0.7,>=0.6
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting docutils>=0.13.1
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting bleach>=2.1.0
  Using cached https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting tqdm>=4.14
  Using cached https://files.pythonhosted.org/packages/e1/c1/bc1dba38b48f4ae3c4428aea669c5e27bd5a7642a74c8348451e0bd8ff86/tqdm-4.36.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/virtualenvs/tmp-5b6181b55fa71418/lib/python3.6/site-packages (from twine==2.0.0->-r requirements/dev.pip (line 24)) (41.4.0)
Collecting pkginfo>=1.4.2
  Using cached https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
Collecting requests-toolbelt!=0.9.0,>=0.8.0
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting zipp>=0.5
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting apipkg>=1.4
  Using cached https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
Processing /Users/ned/Library/Caches/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd/wrapt-1.11.2-cp36-cp36m-macosx_10_13_x86_64.whl
Processing /Users/ned/Library/Caches/pip/wheels/18/4a/35/83cbf6c0c77e61e36fadcee6f055fdd9abad8e21d487e31b48/lazy_object_proxy-1.4.2-cp36-cp36m-macosx_10_13_x86_64.whl
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8"
  Using cached https://files.pythonhosted.org/packages/4c/16/9a45b107957d9e50ff9c99352516e59966433d5cf9148e6b4ba60bd4ce96/typed_ast-1.4.0-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting webencodings
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: virtualenv, more-itertools, zipp, importlib-metadata, pluggy, toml, six, py, pyparsing, packaging, filelock, tox, tox-battery, atomicwrites, attrs, wcwidth, pytest, pytest-forked, apipkg, execnet, pytest-xdist, flaky, mock, decorator, future, PyContracts, hypothesis, unittest-mixins, urwid, pygments, pudb, greenlet, wrapt, lazy-object-proxy, typed-ast, astroid, isort, mccabe, pylint, check-manifest, docutils, webencodings, bleach, readme-renderer, urllib3, certifi, idna, chardet, requests, tqdm, pkginfo, requests-toolbelt, twine
Successfully installed PyContracts-1.8.12 apipkg-1.5 astroid-2.3.2 atomicwrites-1.3.0 attrs-19.3.0 bleach-3.1.0 certifi-2019.9.11 chardet-3.0.4 check-manifest-0.40 decorator-4.4.0 docutils-0.15.2 execnet-1.7.1 filelock-3.0.12 flaky-3.6.1 future-0.18.1 greenlet-0.4.15 hypothesis-4.41.2 idna-2.8 importlib-metadata-0.23 isort-4.3.21 lazy-object-proxy-1.4.2 mccabe-0.6.1 mock-3.0.5 more-itertools-7.2.0 packaging-19.2 pkginfo-1.5.0.1 pluggy-0.13.0 pudb-2019.1 py-1.8.0 pygments-2.4.2 pylint-2.4.3 pyparsing-2.4.2 pytest-4.6.6 pytest-forked-1.1.3 pytest-xdist-1.30.0 readme-renderer-24.0 requests-2.22.0 requests-toolbelt-0.9.1 six-1.12.0 toml-0.10.0 tox-3.14.0 tox-battery-0.5.1 tqdm-4.36.1 twine-2.0.0 typed-ast-1.4.0 unittest-mixins-1.6 urllib3-1.25.6 urwid-2.0.1 virtualenv-16.7.6 wcwidth-0.1.7 webencodings-0.5.1 wrapt-1.11.2 zipp-0.6.0

$ COVERAGE_NO_PYTRACER=1 tox -e py36 -- -vv -k test_gevent -n 0

py36 create: /private/tmp/bug841/coveragepy/.tox/py36
py36 installdeps: -rrequirements/pytest.pip, pip==19.3.1, setuptools==41.4.0, gevent==1.3b1, eventlet==0.25.1, greenlet==0.4.15
py36 develop-inst: /private/tmp/bug841/coveragepy
py36 installed: apipkg==1.5,atomicwrites==1.3.0,attrs==19.3.0,-e git+https://github.com/nedbat/coveragepy@ac70de1886bef8e46b90d94450275022a64e5c95#egg=coverage,decorator==4.4.0,dnspython==1.16.0,eventlet==0.25.1,execnet==1.7.1,flaky==3.6.1,future==0.18.1,gevent==1.3b1,greenlet==0.4.15,hypothesis==4.41.2,importlib-metadata==0.23,mock==3.0.5,monotonic==1.5,more-itertools==7.2.0,packaging==19.2,pluggy==0.13.0,pudb==2019.1,py==1.8.0,PyContracts==1.8.12,Pygments==2.4.2,pyparsing==2.4.2,pytest==4.6.6,pytest-forked==1.1.3,pytest-xdist==1.30.0,six==1.12.0,unittest-mixins==1.6,urwid==2.0.1,wcwidth==0.1.7,zipp==0.6.0
py36 run-test-pre: PYTHONHASHSEED='3145977284'
py36 run-test: commands[0] | python setup.py --quiet clean develop
warning: no previously-included files found matching 'ci/*.token'
no previously-included directories found matching 'doc/_build'
no previously-included directories found matching 'tests/eggsrc/build'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
py36 run-test: commands[1] | python igor.py zip_mods install_egg remove_extension
py36 run-test: commands[2] | python igor.py test_with_tracer py -vv -k test_gevent -n 0
Skipping tests with Python tracer
py36 run-test: commands[3] | python setup.py --quiet build_ext --inplace
py36 run-test: commands[4] | python igor.py test_with_tracer c -vv -k test_gevent -n 0
=== CPython 3.6.9 with C tracer (.tox/py36/bin/python) ===
============================================================================ test session starts ============================================================================
platform darwin -- Python 3.6.9, pytest-4.6.6, py-1.8.0, pluggy-0.13.0 -- /private/tmp/bug841/coveragepy/.tox/py36/bin/python
cachedir: .tox/py36/.pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/private/tmp/bug841/coveragepy/.hypothesis/examples')
rootdir: /private/tmp/bug841/coveragepy, inifile: setup.cfg
plugins: xdist-1.30.0, flaky-3.6.1, forked-1.1.3, hypothesis-4.41.2
collected 898 items / 894 deselected / 4 selected
run-last-failure: no previously failed tests, not deselecting items.

tests/test_concurrency.py::ConcurrencyTest::test_gevent PASSED                                                                                                        [ 25%]
tests/test_concurrency.py::ConcurrencyTest::test_gevent_join PASSED                                                                                                   [ 50%]
tests/test_concurrency.py::ConcurrencyTest::test_gevent_joinall FAILED                                                                                                [ 75%]
tests/test_concurrency.py::ConcurrencyTest::test_gevent_simple_code PASSED                                                                                            [100%]

================================================================================= FAILURES ==================================================================================
____________________________________________________________________ ConcurrencyTest.test_gevent_joinall ____________________________________________________________________

self = <tests.test_concurrency.ConcurrencyTest testMethod=test_gevent_joinall>

    def test_gevent_joinall(self):
        code = """\
            import gevent

            greenlet = gevent.spawn(lambda: None)
            gevent.joinall([greenlet])
            print("covered after joinall")
            """
>       self.try_some_code(code, "gevent", gevent, "covered after joinall\n")

tests/test_concurrency.py:283:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_concurrency.py:249: in try_some_code
    self.assertEqual(line_counts(data)['try_it.py'], lines)
E   AssertionError: 3 != 4
--------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------
covered after joinall

            import gevent

            greenlet = gevent.spawn(lambda: None)
            gevent.joinall([greenlet])
            print("covered after joinall")

3: [1, 3, 4]
 X             import gevent

 X             greenlet = gevent.spawn(lambda: None)
 X             gevent.joinall([greenlet])
               print("covered after joinall")

========================================================================== short test summary info ==========================================================================
FAILED tests/test_concurrency.py::ConcurrencyTest::test_gevent_joinall - AssertionError: 3 != 4
============================================================ 1 failed, 3 passed, 894 deselected in 4.86 seconds =============================================================
ERROR: InvocationError for command /private/tmp/bug841/coveragepy/.tox/py36/bin/python igor.py test_with_tracer c -vv -k test_gevent -n 0 (exited with code 1)
__________________________________________________________________________________ summary __________________________________________________________________________________
ERROR:   py36: commands failed
```
Explanation of the test output: the lines prefixed with X are ones that coverage.py says were executed.  The last line (`print("covered after joinall")`) is marked as not executed, even though it was, because the test compares the stdout, and sees that message in the output.

**Comment by jamadden** [comment]
> Central to it is `gevent.getcurrent`, which is used to determine if the execution context has changed. Did 1.3b1 introduce a change there?

No,  `gevent.getcurrent` is just an alias for `greenlet.getcurrent`:

```console
$ python -c 'import gevent; print(gevent.getcurrent.__module__)'
greenlet
```

What *did* change in 1.3b1 and later was that more of gevent is compiled into a native code  extension using Cython, including `gevent.joinall` and most of the gevent hub. Similarly to [this earlier issue](https://github.com/gevent/gevent/issues/1232) (and specifically [this](https://github.com/nedbat/coveragepy/issues/663#issuecomment-399708957)) I would guess that has something to do with it; what, exactly, I don't know. Does setting PURE_PYTHON in the environment before importing gevent fix it, as it did the earlier issue? It's also possible that a newer gevent (e.g., 1.5a2), built with a newer Cython, might fix the issue.

**Comment by jamadden** [comment]
Ah, and if I go to https://github.com/nedbat/coveragepy/issues/841 I see that `PURE_PYTHON` indeed fixes it. I confirmed locally that 1.5a2 doesn't make a difference.

**Comment by jamadden** [comment]
Making a small modification to the example program and running it with a plain `python -m trace` does show the lines as executed, though `coverage --concurrency=gevent` still misses them (as does greenlet and no concurrency):

```python
import gevent
import unittest


class TestJoinAll(unittest.TestCase):
    def test_joinall(self):
        def coroutine():
            return 5

        greenlet = gevent.spawn(coroutine)
        gevent.joinall([greenlet])

        result = greenlet.get()  # this line runs, but is not covered
        assert 4 == result       # this line runs, but is not covered


TestJoinAll().test_joinall()
```

coverage
```console
coverage run --include=foo.py --concurrency=gevent -m foo
Traceback (most recent call last):
  File "/private/tmp/foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "/private/tmp/foo.py", line 14, in test_joinall
    assert 4 == result       # this line runs, but is not covered
AssertionError
[jmadden@Curie /tmp (relstorage38)]$ coverage report
Name     Stmts   Miss  Cover
----------------------------
foo.py      11      2    82%
[jmadden@Curie /tmp (relstorage38)]$ coverage report -m
Name     Stmts   Miss  Cover   Missing
--------------------------------------
foo.py      11      2    82%   13-14
```

```console 
$ python -m trace -t foo.py  > exctrace
Traceback (most recent call last):
...
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/trace.py", line 448, in runctx
    exec(cmd, globals, locals)
  File "foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "foo.py", line 14, in test_joinall
    assert 4 == result       # this line runs, but is not covered
AssertionError
$ tail -10 exctrace
_config.py(147):         return self.value
hub.py(612):         return self.periodic_monitoring_thread
hub.py(579):             loop = self.loop
hub.py(580):             loop.error_handler = self
hub.py(581):             try:
hub.py(582):                 loop.run()
 --- modulename: foo, funcname: coroutine
foo.py(8):             return 5
foo.py(13):         result = greenlet.get()  # this line runs, but is not covered
foo.py(14):         assert 4 == result       # this line runs, but is not covered
```

```console
$ coverage run --include foo.py --concurrency=gevent -m foo; coverage report -m
Traceback (most recent call last):
  File "/private/tmp/foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "/private/tmp/foo.py", line 14, in test_joinall
    assert 4 == result       # this line runs, but is not covered
AssertionError
Name     Stmts   Miss  Cover   Missing
--------------------------------------
foo.py      11      2    82%   13-14
$ coverage run --include foo.py --concurrency=greenlet -m foo; coverage report -m
Traceback (most recent call last):
  File "/private/tmp/foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "/private/tmp/foo.py", line 14, in test_joinall
    assert 4 == result       # this line runs, but is not covered
AssertionError
Name     Stmts   Miss  Cover   Missing
--------------------------------------
foo.py      11      2    82%   13-14
$ coverage run --include foo.py -m foo; coverage report -m
Traceback (most recent call last):
  File "/private/tmp/foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "/private/tmp/foo.py", line 14, in test_joinall
    assert 4 == result       # this line runs, but is not covered
AssertionError
Name     Stmts   Miss  Cover   Missing
--------------------------------------
foo.py      11      2    82%   13-14
```

**Comment by jamadden** [comment]
I tweaked `gevent.getcurrent` to report what Python thinks the traceback is when its called, and what greenlet it returns (just added some print statements and a wrapper around `greenlet.getcurrent`) so that I could see when coverage is calling it. Extract near the end of the output from running `coverage run`:

```
...
Got current <Hub '' at 0x104aec2c0 select default pending=0 ref=1 thread_ident=0x10448b5c0>
  File "/gevent/hub.py", line 577, in run
    self.start_periodic_monitoring_thread()
  File "//gevent/hub.py", line 612, in start_periodic_monitoring_thread
    return self.periodic_monitoring_thread
  File "//gevent/__init__.py", line 105, in getcurrent
    import traceback; traceback.print_stack(file=sys.stdout)
Got current <Greenlet at 0x1052adef0: coroutine>
  File "/private/tmp/foo.py", line 7, in coroutine
    def coroutine():
  File "/gevent/__init__.py", line 105, in getcurrent
    import traceback; traceback.print_stack(file=sys.stdout)
Got current <Greenlet at 0x1052adef0: coroutine>
  File "/private/tmp/foo.py", line 8, in coroutine
    return 5
  File "gevent/__init__.py", line 105, in getcurrent
    import traceback; traceback.print_stack(file=sys.stdout)
Got current <greenlet.greenlet object at 0x104a96f50>
  File "/private/tmp/foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "/private/tmp/foo.py", line 14, in test_joinall
    assert 4 == result       # this line runs, but is not covered
  File "//gevent/__init__.py", line 105, in getcurrent
    import traceback; traceback.print_stack(file=sys.stdout)
Got current <greenlet.greenlet object at 0x104a96f50>
...
  File "//site-packages/coverage/execfile.py", line 199, in run
    exec(code, main_mod.__dict__)
  File "/private/tmp/foo.py", line 17, in <module>
    TestJoinAll().test_joinall()
  File "//src/gevent/__init__.py", line 105, in getcurrent
    import traceback; traceback.print_stack(file=sys.stdout)
Got current <greenlet.greenlet object at 0x104a96f50>
...
```

` <greenlet.greenlet object at 0x104a96f50>` is the main greenlet, the one automatically created for a thread. It's typically the only plain `greenlet.greenlet` (as opposed to `gevent.greenlet.Greenlet` or a subclass) around. It ran for a long time before this snippet and was requested and returned a bunch of times.

This snippet is after the call to `gevent.spawn`. The gevent hub runs for awhile (mostly in C so invisibly here) and eventually control gets handed over to the coroutine. It gets asked for twice, and then control is right back in the main greenlet. 

Interestingly, the main greenlet does get asked for on  `assert 4 == result       # this line runs, but is not covered`, but I don't see it asked for on the preceding line, the one immediately following `gevent.joinall` (`result = greenlet.get()`) *or* the line for `gevent.joinall` itself, which somewhat surprises me...(though I haven't really looked at how and when coverage decides to call its `concur_id_func`).

In the PURE_PYTHON version, or 1.3a1 before `joinall` was native, the sequence is different. The hub switches to the coroutine, but then there are events captured in the hub *again* after coroutine finishes, and *then* we're back in the main greenlet, where it's captured (exiting?) `gevent.joinall`. In the C accelerated version, there's no capture of the main greenlet entering or exiting `joinall` at all. Using `greenlet.join()` is similar in that it makes some Python calls and those result in coverage calling `getcurrent` and seeing the entry and exit of `greenlet.join`.

If I make a tiny Python wrapper around the C version of joinall:
```
# gevent/__init__.py
from gevent.greenlet import joinall
# New code
_ja = joinall
def joinall(*args):
    return _ja(*args)
```

Then coverage works. It "sees" the entry and exit of this function and captures the greenlet at that time.

Handwaving: I would guess, then, that if coverage doesn't see an entry and exit event for a function before the greenlet identity switches, it gets confused. Since `gevent.joinall`  is native code that can result in a greenlet switching, but doesn't generate all the right trace events, coverage is somehow losing track of where it is? Something like that?

**Comment by nedbat** [comment]
@jamadden Thanks for digging into it.  I'll have to come back to read this more carefully when I can focus more on it.  Gevent is still quite foreign to me.
