### ISSUE TITLE
Two tests fail on build (test__close_backend_fd and test__select) on openSUSE (support for libev > 4.25)

### ISSUE THREAD

**Issue by mcepl** [gevent/gevent#1501]
* gevent version: 1.5a3
* Python version: Please be as specific as possible: "cPython 2.7.17 from the distribution package"
* Operating System: Please be as specific as possible: "openSUSE/Tumbleweed as of 2020-01-02."

### Description:

When building the distribution package, we run the test suite with some tests excluded (mainly because build processes don’t have network connection in the build systems):

```
# create ignore list of tests that reach out to the net
# test_ssl.py is fragile as it expect specific responses from ssl and
#  does not account to our local changes
# Also, gh#gevent/gevent#1390
cat <<'EOF' >> network_tests.txt
test_urllib2net.py
test__server.py
test__server_pywsgi.py
test__socket_ssl.py
test___example_servers.py
test__socket_dns.py
test__getaddrinfo_import.py
test__examples.py
test_https.py
test_urllib2_localnet.py
test_ssl.py
test__ssl.py
EOF
export GEVENT_RESOLVER=thread
# Setting the TRAVIS environment variable makes some different configuration
# for tests that use the network so they don't fail on travis (or obs)
export TRAVIS=1
# Setting the APPVEYOR environment variable makes the tests use a workaround
# for Appveyor that we also need in obs for "wait_threads() failed to cleanup 1 threads"
export APPVEYOR=1
export LANG=en_US.UTF-8
PYTHONPATH=%{buildroot}%{$python_sitearch} $python -m gevent.tests --ignore network_tests.txt
```
and the tests fail with:

```
[  137s] | /usr/bin/python2 -u -mgevent.tests.test__close_backend_fd
[  137s]   Traceback (most recent call last):
[  137s]     File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
[  137s]       "__main__", fname, loader, pkg_name)
[  137s]     File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
[  137s]       exec code in run_globals
[  137s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.5.0~a3-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__close_backend_fd.py", line 18, in <module>
[  137s]       class Test(unittest.TestCase):
[  137s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.5.0~a3-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__close_backend_fd.py", line 57, in Test
[  137s]       name, func = _make_test(count, backend)
[  137s]     File "/home/abuild/rpmbuild/BUILDROOT/python-gevent-1.5.0~a3-0.x86_64/usr/lib64/python2.7/site-packages/gevent/tests/test__close_backend_fd.py", line 51, in _make_test
[  137s]       test.__name__ = 'test_' + backend + '_' + str(count)
[  137s]   TypeError: cannot concatenate 'str' and 'int' objects
[  137s] 
[  137s] ! /usr/bin/python2 -u -mgevent.tests.test__close_backend_fd [code 1] [took 0.0s]
```
and
```
[  151s] | /usr/bin/python2 -u -mgevent.tests.test__select
[  151s]   .python2: ev_epoll.c:134: epoll_modify: Assertion `("libev: I/O watcher with invalid fd found in epoll_ctl", errno != EBADF && errno != ELOOP && errno != EINVAL)' failed.
[  151s] 
[  151s] ! /usr/bin/python2 -u -mgevent.tests.test__select [code -6] [took 0.4s]
```

The complete build log (with all installed packages and other details of the build process) is [available](https://github.com/gevent/gevent/files/4016342/_log.txt).

**Comment by jamadden** [comment]
Thanks!

The immediate cause would seem to be using a non-embedded copy of libev in a version (4.27) that’s not (yet) supported by gevent.

**Comment by mcepl** [comment]
Any idea how to make it work? We (as all Linux distros) really don’t like embedded versions of libraries.

**Comment by jamadden** [comment]
1.5a3 won't work with a libev newer than 4.25 (what it embeds). I have to make changes to gevent to support newer libev.

**Comment by mcepl** [comment]
> ADDED: Those are high on the priority list and should go with the next gevent release.

Next gevent release being 1.5.0 or the one after that?

**Comment by jamadden** [comment]
1.5 has been released. Closing.
