### ISSUE TITLE
assert_switches raises _FailedToSwitch with gevent.sleep

### ISSUE THREAD

**Issue by karlb** [gevent/gevent#1517]
* gevent version: 1.5a3
* Python version: Python 3.7.1 (default, Nov 12 2018, 13:22:25) from debian buster
* Operating System: Debian buster: Linux version 4.19.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.67-2 (2019-08-28)

### Description:

I would expect the following program to run without errors, since `gevent.sleep` should not block:
```python
import gevent
import gevent.util


def func1():
    with gevent.util.assert_switches(max_blocking_time=1.0):
        gevent.sleep(1.1)
        gevent.sleep(0.1)


jobs = {gevent.spawn(func1)}
gevent.joinall(jobs, raise_error=True)
```

But I get a `_FailedToSwitch` exception.
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "assert_switches.py", line 8, in func1
    gevent.sleep(0.1)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 639, in __exit__
    raise _FailedToSwitch(message)
gevent.util._FailedToSwitch: To any greenlet in 1.2011 seconds (max allowed 1.0000 seconds)
================================================================================

2020-01-21T09:46:16Z : Greenlet <Greenlet at 0x7f90d4acbe18: func1> appears to be blocked
    Reported by <gevent.__tracer.MaxSwitchTracer object at 0x7f90d3417518>
Blocked Stack (for thread id 0x7f90d5570080):
  File "assert_switches.py", line 8, in func1
    gevent.sleep(0.1)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 631, in __exit__
    report_lines = tracer.did_block_hub_report(hub, active_greenlet, {})

Info:
********************************************************************************
* Threads
********************************************************************************
Thread 0x7f90d5570080 (MainThread) (CURRENT)

  File "assert_switches.py", line 8, in func1
    gevent.sleep(0.1)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 631, in __exit__
    report_lines = tracer.did_block_hub_report(hub, active_greenlet, {})
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 152, in format_run_info
    _format_thread_info(lines, thread_stacks, limit, current_thread_ident)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 190, in _format_thread_info
    lines.append(''.join(traceback.format_stack(frame, limit)))

********************************************************************************
* Greenlets
********************************************************************************
---- Thread boundary
<greenlet.greenlet object at 0x7f90d45da438>
 :    Parent: None
 :    Running:
 :      File "assert_switches.py", line 12, in <module>
 :        gevent.joinall(jobs, raise_error=True)
 +--- <Greenlet "Greenlet-0" at 0x7f90d4acbe18: func1>
 :          Parent: <Hub '' at 0x7f90d341c100 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7f90d5570080>
 :          Running:
 :            File "assert_switches.py", line 8, in func1
 :              gevent.sleep(0.1)
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 631, in __exit__
 :              report_lines = tracer.did_block_hub_report(hub, active_greenlet, {})
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 153, in format_run_info
 :              _format_greenlet_info(lines, greenlet_stacks, limit)
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 215, in _format_greenlet_info
 :              'running_stack_limit': limit,
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 362, in format_lines
 :              for l in self._render(tree)]
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 435, in _render
 :              self.__render_children(tree)
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 455, in __render_children
 :              child_tree = child._render(tree.deeper())
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 419, in _render
 :              tree.details['running_stack_limit'])
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 378, in __render_tb
 :              tb = ''.join(traceback.format_stack(frame, limit))
 :          Spawned at:
 :            File "assert_switches.py", line 11, in <module>
 :              jobs = {gevent.spawn(func1)}
 +--- <Hub '' at 0x7f90d341c100 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7f90d5570080>
            Parent: <greenlet.greenlet object at 0x7f90d45da438>
            Running:
              File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/hub.py", line 611, in run
                loop.run()
2020-01-21T09:46:16Z <Greenlet "Greenlet-0" at 0x7f90d4acbe18: func1> failed with _FailedToSwitch

Traceback (most recent call last):
  File "assert_switches.py", line 12, in <module>
    gevent.joinall(jobs, raise_error=True)
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "assert_switches.py", line 8, in func1
    gevent.sleep(0.1)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 639, in __exit__
    raise _FailedToSwitch(message)
gevent.util._FailedToSwitch: To any greenlet in 1.2011 seconds (max allowed 1.0000 seconds)
================================================================================

2020-01-21T09:46:16Z : Greenlet <Greenlet at 0x7f90d4acbe18: func1> appears to be blocked
    Reported by <gevent.__tracer.MaxSwitchTracer object at 0x7f90d3417518>
Blocked Stack (for thread id 0x7f90d5570080):
  File "assert_switches.py", line 8, in func1
    gevent.sleep(0.1)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 631, in __exit__
    report_lines = tracer.did_block_hub_report(hub, active_greenlet, {})

Info:
********************************************************************************
* Threads
********************************************************************************
Thread 0x7f90d5570080 (MainThread) (CURRENT)

  File "assert_switches.py", line 8, in func1
    gevent.sleep(0.1)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 631, in __exit__
    report_lines = tracer.did_block_hub_report(hub, active_greenlet, {})
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 152, in format_run_info
    _format_thread_info(lines, thread_stacks, limit, current_thread_ident)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 190, in _format_thread_info
    lines.append(''.join(traceback.format_stack(frame, limit)))

********************************************************************************
* Greenlets
********************************************************************************
---- Thread boundary
<greenlet.greenlet object at 0x7f90d45da438>
 :    Parent: None
 :    Running:
 :      File "assert_switches.py", line 12, in <module>
 :        gevent.joinall(jobs, raise_error=True)
 +--- <Greenlet "Greenlet-0" at 0x7f90d4acbe18: func1>
 :          Parent: <Hub '' at 0x7f90d341c100 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7f90d5570080>
 :          Running:
 :            File "assert_switches.py", line 8, in func1
 :              gevent.sleep(0.1)
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 631, in __exit__
 :              report_lines = tracer.did_block_hub_report(hub, active_greenlet, {})
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 153, in format_run_info
 :              _format_greenlet_info(lines, greenlet_stacks, limit)
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 215, in _format_greenlet_info
 :              'running_stack_limit': limit,
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 362, in format_lines
 :              for l in self._render(tree)]
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 435, in _render
 :              self.__render_children(tree)
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 455, in __render_children
 :              child_tree = child._render(tree.deeper())
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 419, in _render
 :              tree.details['running_stack_limit'])
 :            File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/util.py", line 378, in __render_tb
 :              tb = ''.join(traceback.format_stack(frame, limit))
 :          Spawned at:
 :            File "assert_switches.py", line 11, in <module>
 :              jobs = {gevent.spawn(func1)}
 +--- <Hub '' at 0x7f90d341c100 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7f90d5570080>
            Parent: <greenlet.greenlet object at 0x7f90d45da438>
            Running:
              File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/hub.py", line 611, in run
                loop.run()
```

**Comment by jamadden** [comment]
That's what the `hub_only` argument is for. Without setting it to true, `assert_switches` is going to require that any other greenlet gets to run before `max_blocking_time` expires. But here you have no other greenlets, you *only* have the hub to switch to. Set it to true and your example passes because you're switching into and out of the hub.

**Comment by karlb** [comment]
`hub_only=True` really seems to behave like I want it to. I didn't understant the difference in behavior correctly when reading the documentation. Thanks for the clarification!

Is there a typical case where one would want the behavior of `hub_only=False`?
