### ISSUE TITLE
gevent.subprocess.Popen crashes on Mac

### ISSUE THREAD

**Issue by wiggin15** [gevent/gevent#1524]
* gevent version: latest "master" (commit 36704768)
* Python version: 3.7.3 installed by "brew"
* Operating System: macOS 10.14.6

### Description:
Using gevent.subprocess on macOS causes a weird traceback.

### What I've run:
```python
~ python
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gevent.subprocess import Popen
>>> Popen("echo hi", shell=True)
hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arnony/.venvs/work3/lib/python3.7/site-packages/gevent-1.5a4.dev0-py3.7-macosx-10.14-x86_64.egg/gevent/subprocess.py", line 751, in __init__
    restore_signals, start_new_session)
  File "/Users/arnony/.venvs/work3/lib/python3.7/site-packages/gevent-1.5a4.dev0-py3.7-macosx-10.14-x86_64.egg/gevent/subprocess.py", line 1614, in _execute_child
    errpipe_read.close()
  File "/Users/arnony/.venvs/work3/lib/python3.7/site-packages/gevent-1.5a4.dev0-py3.7-macosx-10.14-x86_64.egg/gevent/_fileobjectcommon.py", line 363, in close
    self._do_close(fobj, self._close)
  File "/Users/arnony/.venvs/work3/lib/python3.7/site-packages/gevent-1.5a4.dev0-py3.7-macosx-10.14-x86_64.egg/gevent/_fileobjectposix.py", line 318, in _do_close
    fobj.close()
  File "/Users/arnony/.venvs/work3/lib/python3.7/site-packages/gevent-1.5a4.dev0-py3.7-macosx-10.14-x86_64.egg/gevent/_fileobjectposix.py", line 129, in close
    self.__destroy_events()
  File "/Users/arnony/.venvs/work3/lib/python3.7/site-packages/gevent-1.5a4.dev0-py3.7-macosx-10.14-x86_64.egg/gevent/_fileobjectposix.py", line 112, in __destroy_events
    hub.cancel_waits_close_and_then(
AttributeError: 'Hub' object has no attribute 'cancel_waits_close_and_then'
>>>
```

**Comment by jamadden** [comment]
Thanks for the report. I am unable to reproduce. The relevant method was added in https://github.com/gevent/gevent/commit/8fcac63ecc4311989c5c99b3a1421b71d8991b09. 

Perhaps you haven't properly rebuilt all the cython extension modules since then? `python setup.py clean && python setup.py build_ext -i` should work in a virtual environment with gevent installed in editable mode.

**Comment by wiggin15** [comment]
Ah. I did try to rebuild the extension before reporting the issue, but apparently I was missing the "clean" step. This fixed the issue. Thanks, and sorry about that!
