### ISSUE TITLE
SystemError when using gevent.subprocess on AIX

### ISSUE THREAD

**Issue by wiggin15** [gevent/gevent#1538]
* gevent version: 1.5a3
* Python version: 3.8.0
* Operating System: AIX 7.1

### Description:

When using gevent.subprocess.Popen on AIX with gevent 1.5a3, I get this very weird traceback. I have no idea what it means or why it happens only on AIX.

```
bash-5.0# /opt/python/bin/python
Python 3.8.0 (default, Feb  5 2020, 10:24:22)
[GCC 4.9.4] on aix
Type "help", "copyright", "credits" or "license" for more information.
>>> from gevent.subprocess import Popen
>>> Popen("echo hi", shell=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python/lib/python3.8/site-packages/gevent/subprocess.py", line 650, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/python/lib/python3.8/site-packages/gevent/subprocess.py", line 1563, in _execute_child
hi
    data = errpipe_read.read()
  File "/opt/python/lib/python3.8/site-packages/gevent/_fileobjectposix.py", line 157, in readall
    data = self.__read(DEFAULT_BUFFER_SIZE)
  File "/opt/python/lib/python3.8/site-packages/gevent/_fileobjectposix.py", line 151, in __read
    wait_on_watcher(self._read_watcher, None, None, self.hub)
  File "src/gevent/_hub_primitives.py", line 299, in gevent.__hub_primitives.wait_on_watcher
    def wait_on_watcher(watcher, timeout=None, timeout_exc=_NONE, hub=None):
  File "src/gevent/_hub_primitives.py", line 323, in gevent.__hub_primitives.wait_on_watcher
    _primitive_wait(watcher, timeout, timeout_exc, hub)
  File "src/gevent/_hub_primitives.py", line 277, in gevent.__hub_primitives._primitive_wait
    hub.wait(watcher)
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    def wait(self, watcher):
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    def wait(self, watcher):
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    result = waiter.get()
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
    return self.hub.switch()
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    def switch(self):
SystemError: NULL result without error in PyObject_Call
```

Thanks in advance!

**Comment by jamadden** [comment]
Can you try with the environment variable `PURE_PYTHON` set to 1? This looks like it might be an issue with the underlying `greenlet` library, but it could also be a problem in Cython; setting that environment variable will eliminate gevent's Cython-ized code.

**Comment by wiggin15** [comment]
With `PURE_PYTHON=1` I get a similar error but not exactly the same:
```
  File "gevent-1.5a3-py3.8-aix-7.1.egg/gevent/_greenlet_primitives.py", line 65, in switch
    return _greenlet_switch(self) # pylint:disable=undefined-variable
SystemError: <method 'switch' of 'greenlet.greenlet' objects> returned NULL without setting an error
```

I am currently having problems reproducing this reliably. If you can point me to some direction that would be helpful. If not, I'll keep trying to understand what's going on and update if I find anything. Thanks!

**Comment by jamadden** [comment]
That error points pretty clearly to a bug in greenlet, I think. The next step would be to open an issue over there: https://github.com/python-greenlet/greenlet/issues

**Comment by wiggin15** [comment]
Thank you @jamadden . This looks like a bug already reported over there: https://github.com/python-greenlet/greenlet/issues/145

**Comment by jamadden** [comment]
Yes, that looks like it. Thanks.
