### ISSUE TITLE
gevent Native Module Errors On Heroku While Running Embedded

### ISSUE THREAD

**Issue by Daniihh** [gevent/gevent#1543]
* gevent version: 1.4.0
* Python version: Python 3.8.X provided from Heroku's buildpack
* Operating System: Heroku Web Dyno

### Description:
While running `gevent.monkey.patch_all()` in my web application, my Heroku app quit with this error:
```
2020-03-10T20:49:00.873710+00:00 app[web.1]: Traceback (most recent call last):
2020-03-10T20:49:00.873721+00:00 app[web.1]: File "/app/out/server_impl/__init__.py", line 1, in <module>
2020-03-10T20:49:00.873855+00:00 app[web.1]: from gevent import monkey; monkey.patch_all()
2020-03-10T20:49:00.873875+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gevent/__init__.py", line 87, in <module>
2020-03-10T20:49:00.874029+00:00 app[web.1]: from gevent._hub_local import get_hub
2020-03-10T20:49:00.874033+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
2020-03-10T20:49:00.874173+00:00 app[web.1]: import_c_accel(globals(), 'gevent.__hub_local')
2020-03-10T20:49:00.874189+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_util.py", line 105, in import_c_accel
2020-03-10T20:49:00.874339+00:00 app[web.1]: mod = importlib.import_module(cname)
2020-03-10T20:49:00.874343+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-03-10T20:49:00.874518+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-03-10T20:49:00.874548+00:00 app[web.1]: ImportError: /app/.heroku/python/lib/python3.8/site-packages/gevent/__hub_local.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyExc_SystemError
```

I don't know what caused this, the `monkey.patch_all` function runs perfectly everywhere except on Heroku, my assumption is that some asset typically present on a normal operating system is missing on Heroku's web dynos.

**Comment by Daniihh** [comment]
Update: This issue appears not to be related to `monkey.patch_all()`.

**Comment by jamadden** [comment]
That error means that a binary (ABI) symbol that's supposed to be present dynamically at runtime *isn't*. It's possible that the gevent and Python libraries were compiled with different settings.

However, gevent 1.4 doesn't support Python 3.8 anyway. For 3.8 support, you need gevent 1.5. gevent 1.5 distributes compiled binaries from PyPI for Python 3.8 (and gevent 1.4 does not), so if you can install an updated gevent using the binaries from PyPI that might resolve the issue; if not, at least it's a combination that *should* work, which is a place to start.

**Comment by Daniihh** [comment]
Thanks for the quick reply! I updated gevent to 1.5a3, same issue, traceback and all.

**Comment by jamadden** [comment]
Can you still please post the traceback? The filenames are a clue.

**Comment by Daniihh** [comment]
```
2020-03-10T23:36:35.527025+00:00 app[web.1]: Traceback (most recent call last):
2020-03-10T23:36:35.527059+00:00 app[web.1]: File "/app/out/server_impl/__init__.py", line 1, in <module>
2020-03-10T23:36:35.527594+00:00 app[web.1]: from gevent import monkey; monkey.patch_all()
2020-03-10T23:36:35.527601+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gevent/__init__.py", line 87, in <module>
2020-03-10T23:36:35.527967+00:00 app[web.1]: from gevent._hub_local import get_hub
2020-03-10T23:36:35.528000+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
2020-03-10T23:36:35.528288+00:00 app[web.1]: import_c_accel(globals(), 'gevent.__hub_local')
2020-03-10T23:36:35.528319+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_util.py", line 105, in import_c_accel
2020-03-10T23:36:35.528576+00:00 app[web.1]: mod = importlib.import_module(cname)
2020-03-10T23:36:35.528607+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-03-10T23:36:35.528866+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-03-10T23:36:35.528991+00:00 app[web.1]: ImportError: /app/.heroku/python/lib/python3.8/site-packages/gevent/__hub_local.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyExc_SystemError
```
Pretty sure they're the same.

Thought I should show the result from `pip` from the Python buildpack too.
```
-----> Installing requirements with pip
       Collecting pymongo
         Downloading pymongo-3.10.1-cp38-cp38-manylinux2014_x86_64.whl (480 kB)
       Collecting dnspython
         Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
       Collecting gevent==1.5a3
         Downloading gevent-1.5a3-cp38-cp38-manylinux2010_x86_64.whl (7.3 MB)
       Collecting greenlet>=0.4.14; platform_python_implementation == "CPython"
         Downloading greenlet-0.4.15-cp38-cp38-manylinux1_x86_64.whl (45 kB)
       Installing collected packages: pymongo, dnspython, greenlet, gevent
       Successfully installed dnspython-1.16.0 gevent-1.5a3 greenlet-0.4.15 pymongo-3.10.1
```

**Comment by jamadden** [comment]
Thanks!

I'm a bit stumped as to what the problem is given this information. That's a key symbol and it appears to be using the standard binary distribution with known-good compile options, so I don't know why it can't be resolved.

There are a few things you could try to get unstuck.

You can use the environment variable `PURE_PYTHON=1` to disable the C optimizations, but (1) that may or may not work; it could just kick the error farther down the road to the *required* C libraries and (2) it may or may not work for your performance requirements.

You might check what version of pip you're using; [some issues suggest](https://github.com/heroku/heroku-buildpack-python/issues/804) that Heroku had issues with binary wheels that were [only recently solved with a newer version of pip](https://github.com/heroku/heroku-buildpack-python/pull/919).

You might also try installing with `—no-binary gevent` to build gevent from scratch locally. I don't know if that's even possible (I think it probably is because I don't know how else gevent 1.4 could have been installed).

**Comment by Daniihh** [comment]
Update: SOOOO I decided to do more poking around.
I already had reverted back to a previous build that deployed and ran successfully.
I SSHed into the web dyno (the dyno that actually runs the server) and I did `pip install gevent==1.5a3`.
It compiled, just as it did on deployment.
THEN I ran `python` and typed `import gevent`.
**It worked?**

The only things that I think changed between those deployments and SSHing into the preupdate version is:
- The file being ran, which I'm doubtful because _`from gevent import monkey; monkey.patch_all()` is the first python statement in my file_.
- The fact I'm running the python file via an import.
- Some random environment change.
- A huge conspiracy theory???

Going to be doing more research on this.

**Comment by Daniihh** [comment]
Sorry this took 18 days to respond, my life is a mess.
But you're not here to hear about some random guy's life.

Anyways, I think I finally found out the root of the problem. This issue is actually very very specific. The requirements are as follows:
- The environment is a Heroku dyno.
- You run python embedded via Rust's pyo3. (Haven't tested other embedding libraries or methods.)

The whole reason why I was running python embedded was because originally I was planning to start a rewrite of my project at a later date in a compiled language. (Yes Python can be compiled, although it uses a virtual machine.) It would mean I didn't have to complete the rewrite, I could still call the existing Python code from Rust.

At this point it's not necessary for you to fix this anytime soon, working around it is easy enough.

**Comment by jamadden** [comment]
Absolutely no worries! Things are rough for me too and so many people. I am so sorry things are a mess for you, and I sincerely hope they get better. 

Thanks for the update, I’ll go ahead and close.
