### ISSUE TITLE
Fails to install on msys2, unless cffi is installed first

### ISSUE THREAD

**Issue by hgdagon** [gevent/gevent#1551]
* gevent version: 1..4.0
* Python version: 3.8 from msys2 repo
* Operating System: Windows 10 x64

### Description:

Installing  a python module, which requires gevent, or installing gevent on its own

### What I've run:

`pip install gevent`

```python
ERROR: Command errored out with exit status 1:
     command: C:/msys64/mingw64/bin/python.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:/Users/George/AppData/Local/Temp/pip-install-at7msw5e/gevent/setup.py'"'"'; __file__='"'"'C:/Users/George/AppData/Local/Temp/pip-install-at7msw5e/gevent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base C:/Users/George/AppData/Local/Temp/pip-install-at7msw5e/gevent/pip-egg-info
         cwd: C:/Users/George/AppData/Local/Temp/pip-install-at7msw5e/gevent/
    Complete output (56 lines):
    Compiling src/gevent/libev/corecext.pyx because it depends on C:/msys64/mingw64/lib/python3.8/site-packages/Cython/Includes/libc/string.pxd.
    [1/1] Cythonizing src/gevent/libev/corecext.pyx
    Compiling src/gevent/resolver/cares.pyx because it depends on C:/msys64/mingw64/lib/python3.8/site-packages/Cython/Includes/libc/string.pxd.
    [1/1] Cythonizing src/gevent/resolver/cares.pyx
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: C:/msys64/mingw64/bin/python.exe -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:/Users/George/AppData/Local/Temp/pip-wheel-1jhyp1oh/cffi/setup.py'"'"'; __file__='"'"'C:/Users/George/AppData/Local/Temp/pip-wheel-1jhyp1oh/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d C:/Users/George/AppData/Local/Temp/pip-wheel-8ey8vprz
           cwd: C:/Users/George/AppData/Local/Temp/pip-wheel-1jhyp1oh/cffi/
      Complete output (12 lines):
      _configtest.c:2:2: error: #error "not MSVC"
          2 | #error "not MSVC"
            |  ^~~~~
      Note: will not use '__thread' in the C code
      ***** The above error message can be safely ignored.

      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:/msys64/mingw64/bin/python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:/Users/George/AppData/Local/Temp/tmpv8c49tqb', '--quiet', 'cffi>=1.11.5']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/George/AppData/Local/Temp/pip-install-at7msw5e/gevent/setup.py", line 427, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "C:/Users/George/AppData/Local/Temp/pip-install-at7msw5e/gevent/setup.py", line 328, in run_setup
        setup(
      File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['C:/msys64/mingw64/bin/python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:/Users/George/AppData/Local/Temp/tmpv8c49tqb', '--quiet', 'cffi>=1.11.5']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by jamadden** [comment]
This is a problem building CFFI.  It appears CFFI won't build on your platform. If that's the case, gevent won't run on your platform.

If you're able to 'pip install cffi' and have it work, then that suggests an issue with the way pip is handling the build of CFFI in the context of dependencies. I've encountered issues with that before, and the solution was to upgrade pip, so I suggest making sure you have the latest version of pip *and* its dependency wheel.

You may also try gevent 1.5, which includes a `pyproject.toml` and opts-in to a newer way of handling dependencies at build time. Again, though, that requires a new version of pip. 

Since gevent 1.4 *does not support Python 3.8* I would highly recommend using gevent 1.5 in any case.

Good luck!
