### ISSUE TITLE
test_unlink fails on i686

### ISSUE THREAD

**Issue by mbakke** [gevent/gevent#1558]
* gevent version: 1.5.0
* Python version: 3.8.2 and 3.7.4
* Operating System: Please be as specific as possible: "GNU Guix (i686)"

### Description:

Running gevent.tests on i686 causes a test failure in test__core_stat.py:

```
/gnu/store/p8adfrwwb0iv5bvsxsq5k0szwffaxjrj-python-wrapper-3.8.2/bin/python -u -mgevent.tests.test__core_stat
  F..
  ======================================================================
  FAIL: test_unlink (__main__.TestCoreStat)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/guix-build-python-gevent-1.5.0.drv-0/gevent-1.5.0/build/lib.linux-i686-3.8/gevent/testing/errorhandler.py", line 48, in wrapper
      return method(self, *args, **kwargs)
    File "/tmp/guix-build-python-gevent-1.5.0.drv-0/gevent-1.5.0/build/lib.linux-i686-3.8/gevent/testing/errorhandler.py", line 35, in wrapper
      return method(self, *args, **kwargs)
    File "/tmp/guix-build-python-gevent-1.5.0.drv-0/gevent-1.5.0/build/lib.linux-i686-3.8/gevent/testing/testcase.py", line 169, in wrapper
      return method(self, *args, **kwargs)
    File "/tmp/guix-build-python-gevent-1.5.0.drv-0/gevent-1.5.0/build/lib.linux-i686-3.8/gevent/tests/test__core_stat.py", line 114, in test_unlink
      self._check_attr('attr', True)
    File "/tmp/guix-build-python-gevent-1.5.0.drv-0/gevent-1.5.0/build/lib.linux-i686-3.8/gevent/tests/test__core_stat.py", line 66, in _check_attr
      self.assertIsNone(x, name)
  AssertionError: os.stat_result(st_mode=998, st_ino=0, st_dev=24289517527629824, st_nlink=30000, st_uid=0, st_gid=0, st_size=6814484352664076288, st_atime=1586620778, st_mtime=0, st_ctime=-2) is not None : attr
  
  ----------------------------------------------------------------------
  Ran 3 tests in 1.208s
  
  FAILED (failures=1)
```

**Comment by jamadden** [comment]
Ok. You appear to be building from source. Are you using any special build settings? (e.g., not using the embedded libraries). Are you using any special runtime settings? (e.g., using environment variables to select different loop implementations).

What kernel and libc are you using?

You specify i686. Does that mean this test works on the same platform when compiled for 64-bits? If so, I have no idea why that would be. I do not test or distribute 32-bit Linux/macOS builds, but the same 32-bit test passes on Windows.

Note that gevent's test suite is pretty sensitive to timing and low-level OS details. This particular test is sensitive to the kernel's file notification abilities, which may also depend on the particular filesystem in use.

**Comment by mbakke** [comment]
Hi, sorry for the incomplete bug report!  This test works fine on x86_64 on the same hardware, but consistently fails when built for i686.

Using system libev (4.31) and c-ares (1.16.0), kernel 5.4.23 and glibc 2.31.

**Comment by jamadden** [comment]
There are no explicit differences between the 32- and 64-bit code paths, so we're just left with implicit differences such as data model differences (pointer sizes, etc) and ABI issues (number of registers and parameter passing strategies). The latter can result in timing changes, but neither is something that I can do anything about. 

Is this repeatable, especially in isolation? I would guess that this was an example of a flaky test in this environment, for whatever reason.

**Comment by jamadden** [comment]
I've been running this in gevent's CI on the 32-bit manylinux docker image fairly frequently over the last few days and have not had a failure there.

**Comment by jamadden** [comment]
There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.

**Comment by mbakke** [comment]
@jamadden Are the 32-bit manylinux builds done on a file system < 4GiB?

There is something fishy about the `stat` result, as inode number is 0, and `st_size` is in the petabyte range.  But I don't understand what this test does or how to interpret the result.

Do you have any tips for debugging further?

**Comment by Apteryks** [comment]
Hi, I'm another Guix user.

We're now at version 21.12.0 and Python 3.9.9, and this test still fails like so:

```
======================================================================
  FAIL: test_unlink (gevent.tests.test__core_stat.TestCoreStat)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/gnu/store/b62zkpx580gmy8r83aiwzrpp5c4vi3lr-python-gevent-21.12.0/lib/python3.9/site-packages/gevent/testing/errorhandler.py", line 47, in restore_fatal_error_wrapper
      return method(self, *args, **kwargs)
    File "/gnu/store/b62zkpx580gmy8r83aiwzrpp5c4vi3lr-python-gevent-21.12.0/lib/python3.9/site-packages/gevent/testing/errorhandler.py", line 34, in fatal_error_wrapper
      return method(self, *args, **kwargs)
    File "/gnu/store/b62zkpx580gmy8r83aiwzrpp5c4vi3lr-python-gevent-21.12.0/lib/python3.9/site-packages/gevent/testing/testcase.py", line 182, in timeout_wrapper
      return method(self, *args, **kwargs)
    File "/gnu/store/b62zkpx580gmy8r83aiwzrpp5c4vi3lr-python-gevent-21.12.0/lib/python3.9/site-packages/gevent/tests/test__core_stat.py", line 114, in test_unlink
      self._check_attr('attr', True)
    File "/gnu/store/b62zkpx580gmy8r83aiwzrpp5c4vi3lr-python-gevent-21.12.0/lib/python3.9/site-packages/gevent/tests/test__core_stat.py", line 66, in _check_attr
      self.assertIsNone(x, name)
  AssertionError: os.stat_result(st_mode=999, st_ino=0, st_dev=3993275925406941184, st_nlink=30000, st_uid=0, st_gid=0, st_size=7120047666339250176, st_atime=1657765281, st_mtime=0, st_ctime=-2) is not None : attr
  
  ----------------------------------------------------------------------
  Ran 46 tests in 1.169s
  ```
  
  The direct dependencies used are:
```
dependencies: c-ares@1.17.2 libev@4.33 python-dnspython@2.1.0 python-greenlet@1.1.2
+ python-objgraph@3.4.1 python-psutil@5.9.0 python-zope-event@4.4 python-zope-interface@5.1.0
```
