### ISSUE TITLE
For 1.5.0, dependency psutil is not installed by pip, causing monkey-patch errors

### ISSUE THREAD

**Issue by ekimekim** [gevent/gevent#1561]
* gevent version: 1.5.0
* Python version: 2.7.17
* Pip version: 9.0.1
* Operating System: ubuntu 18.04 (docker image. tested on an arch linux base system, kernel 5.5.11-arch1-1)

### Description:

After installing gevent 1.5.0 to an Ubuntu 18.04 docker image using `pip install gevent` or `pip install gevent==1.5.0`, I get this error upon trying to run `gevent.monkey.patch_all()`:

```
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 1122, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 173, in _notify_patch
    notify_and_call_entry_points(event)
  File "/usr/local/lib/python2.7/dist-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=5.6.1; platform_python_implementation == "CPython" or python_version != "2.7" and extra == "recommended"' distribution was not found and is required by the application
```

If I re-run `pip install gevent` a second time, then psutil is downloaded and everything works fine.

### What I've run:

from an `ubuntu:18.04` base image:
```
# apt update && apt install python-pip
# pip install gevent==1.5.0
# python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 1122, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 173, in _notify_patch
    notify_and_call_entry_points(event)
  File "/usr/local/lib/python2.7/dist-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=5.6.1; platform_python_implementation == "CPython" or python_version != "2.7" and extra == "recommended"' distribution was not found and is required by the application
```
Can be fixed by running pip again:
```
# pip install gevent==1.5.0
Requirement already satisfied: gevent==1.5.0 in /usr/local/lib/python2.7/dist-packages
Collecting psutil>=5.6.1; platform_python_implementation == "CPython" or python_version != "2.7" and extra == "test" (from gevent==1.5.0)
  Downloading https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz (449kB)
    100% |################################| 450kB 2.5MB/s 
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /usr/local/lib/python2.7/dist-packages (from gevent==1.5.0)
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /root/.cache/pip/wheels/d7/69/b4/3200b95828d1f0ddb3cb5699083717f4fdbd9b4223d0644c57
Successfully built psutil
Installing collected packages: psutil
Successfully installed psutil-5.7.0
# python  
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
True
```

If I repeat the above steps but with `gevent==1.4.0` then everything works. psutil is not installed.

It's unclear if this is a packaging problem on gevent's end or a pip bug, but I figured posting here would be the best place to start.

**Comment by jamadden** [comment]
Thank you for the report. I don't see how this could be a gevent bug. The metadata that gevent passes to setuptools is entirely declarative and doesn't change from one run to the next. Nor is psutil a required dependency; it's an optional dependency installed with certain extras only.

**Comment by ekimekim** [comment]
> Nor is psutil a required dependency; it's an optional dependency installed with certain extras only.

This seems to be a bug then. Because I'm not installing any extras, and yet without `psutil` installed monkey patching will fail (see the traceback above). What is the expected case where psutil is a dependency? Am I somehow requiring it accidentially?

**Comment by jamadden** [comment]
It looks like a bug in your pip or setuptools. gevent has no control over what `pkg_resources` decides is part of the requirements once it passes the static metadata over to setuptools. 

An updated pip would also be able to install the binary wheels which this outdated version cannot.

**Comment by ekimekim** [comment]
Getting the latest version of pip via `pip install --upgrade pip` did indeed solve this problem, thanks. I expect this problem may be quite widespread since this is the version of pip that anyone on ubuntu LTS will get by default (at least until the end of this month).
