### ISSUE TITLE
pip3 install latest gevent package has compatibility issues

### ISSUE THREAD

**Issue by Vieufoux** [gevent/gevent#1579]
* gevent version:1.5.0
* gunicorn version:20.0.4
* Python version: Python 3.6.9
* Operating System: Ubuntu 18.04.1 LTS

### Description:

I try to start my Django Unicorn,
When I specified to install gevent version 1.4.0, everything works fine.
But when I installed latest version(1.5.0), I met this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in init_process
    self.patch()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 53, in patch
    monkey.patch_all()
  File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 1122, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 173, in _notify_patch
    notify_and_call_entry_points(event)
  File "/usr/local/lib/python3.6/dist-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=5.6.1; platform_python_implementation == "CPython" or python_version != "2.7" and extra == "monitor"' distribution was not found and is required by the application
```

**Comment by Vieufoux** [comment]
Actually I found that "pip3 install psutil==5.7.0" will fix this error, but I don't want to install the specific version of psutil to workaround this issue. Can you fix this issue?

**Comment by jamadden** [comment]
Please search the issue archive. I think you will find that you used a very outdated version of pip to perform the installation.
