### ISSUE TITLE
1.5+ no longer install on amazonlinux

### ISSUE THREAD

**Issue by corby** [gevent/gevent#1605]
* gevent version: 1.5, 20+
* Python version: 3.7.6
* Operating System: amazonlinux:2 docker image

### Description:
gevent 1.4.0 installs from the binary wheel on amazonlinux no problem.
1.5 and 20+ don't install from the binary wheel anymore and the source will not complile because it has a dependency on the deprecated binary /usr/bin/file

```
   Running '(cd  "/tmp/pip-build-jxm9onav/gevent/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/pip-build-jxm9onav/gevent                                                                                [4/1987]
    ./configure: line 6527: /usr/bin/file: No such file or directory
    config.status: error: in `/tmp/pip-build-jxm9onav/gevent/deps/libev':
    config.status: error: Something went wrong bootstrapping makefile fragments
        for automatic dependency tracking.  Try re-running configure with the
        '--disable-dependency-tracking' option to at least be able to build
        the package (albeit without support for automatic dependency tracking).
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jxm9onav/gevent/setup.py", line 436, in <module>
        run_setup(EXT_MODULES)
      File "/tmp/pip-build-jxm9onav/gevent/setup.py", line 420, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.7/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/lib64/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-jxm9onav/gevent/_setuputils.py", line 365, in build_extension
        self.gevent_prepare(ext)
      File "/tmp/pip-build-jxm9onav/gevent/_setuputils.py", line 362, in gevent_prepare
        configure(self, ext)
      File "/tmp/pip-build-jxm9onav/gevent/_setuplibev.py", line 57, in configure_libev
        system(libev_configure_command)
      File "/tmp/pip-build-jxm9onav/gevent/_setuputils.py", line 212, in system
        if _system(cmd, cwd=cwd, env=env, **kwargs):
      File "/tmp/pip-build-jxm9onav/gevent/_setuputils.py", line 208, in _system
        return check_call(cmd, cwd=cwd, env=env, **kwargs)
      File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)

```

### What I've run:

pip3 install gevent

**Comment by jamadden** [comment]
[gevent 1.5 and newer](http://www.gevent.org/whatsnew_1_5.html#packaging-changes) distribute [manylinux2010](https://www.python.org/dev/peps/pep-0571/) binary wheels. These can only be installed on manylinux2010 compliant systems.

At a quick glance of the [FAQs for amazon linux 2](https://aws.amazon.com/amazon-linux-2/faqs/) and [the manylinux2010 policy](https://www.python.org/dev/peps/pep-0571/#the-manylinux2010-policy), it *looks* to me like amazon linux 2 should be compatible with that standard, so please check that you're using the [required version of pip 19+](http://www.gevent.org/install.html#id1) to do the installation. If you are, and you feel that your system is manylinux2010 compliant but that's not being recognized by pip, you'll need to open a pip bug.

Other than that, I can only direct you to the [information on compiling from source](http://www.gevent.org/development/installing_from_source.html). You'll need a full compiler toolchain and the ability to run the standard GNU autotools programs—this is a requirement of the libraries gevent uses, but gevent has no control over that.

**Comment by corby** [comment]
yep, that was it.

For documentation purposes:
The amazonlinux yum repo version of python3-pip is 9.x (so super old)
In you Dockerfile add the line
`RUN pip3 install -U pip`
before installing your requirements.txt to bring it up to date.

Adding keywords for web search:
amazonlinux
gevent
