### ISSUE TITLE
gevent from haiku os

### ISSUE THREAD

**Issue by skarmiglione** [gevent/gevent#1658]
* gevent version: Github version with pip install git+git://github.com/gevent/gevent.git#egg=gevent
 
* Python version: Please be as specific as possible: "cPython 2.7.9 downloaded from python.org"
python38-3.8.3-1 downloaded from haikudepot

* Operating System: Please be as specific as possible: "Raspbian (Debian Linux 8.0 Linux 4.9.35-v7+  armv7l)"

Haiku os hrev54415 x64 intel i5 2dn gen

### Description:

I am trying to install gevent on haiku os

### What I've run:

https://pastebin.com/uDm1bCfL here it is the log complete

Here i will past the last part of the log:
```
  configure: WARNING: Continuing even with errors mentioned immediately above this line.
  configure: error: couldn't find libraries for gethostbyname()
  configure: creating cache config.cache
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking whether make supports nested variables... yes
  checking whether to enable debug build options... no
  checking whether to enable compiler optimizer... not specified (assuming yes)
  checking whether to enable strict compiler warnings... no
  checking whether to enable compiler warnings as errors... no
  checking whether to enable curl debug memory tracking... no
  checking whether to enable hiding of library internal symbols... yes
  checking whether to expose internal static functions for testing... no
  checking for path separator... :
  checking for sed... /bin/sed
  checking for grep... /bin/grep
  checking for egrep... /bin/grep -E
  checking for ar... /bin/ar
  checking for a sed that does not truncate output... (cached) /bin/sed
  checking whether to build with code coverage support... no
  checking build system type... x86_64-unknown-haiku
  checking host system type... x86_64-unknown-haiku
  configure: using CFLAGS: -Wno-unused-result -Wsign-compare -DNDEBUG -D_BSD_SOURCE -D_BSD_SOURCE
  configure: CFLAGS error: CFLAGS may only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -DNDEBUG
  configure: CFLAGS error: CFLAGS may only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -D_BSD_SOURCE
  configure: CFLAGS error: CFLAGS may only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -D_BSD_SOURCE
  checking for a BSD-compatible install... /bin/install -c
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking how to run the C preprocessor... gcc -E
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking whether g++ supports C++11 features by default... yes
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether make supports the include directive... yes (GNU style)
  checking dependency style of gcc... none
  checking dependency style of g++... none
  checking for grep that handles long lines and -e... (cached) /bin/grep
  checking for egrep... /bin/grep -E
  checking if OS is AIX (to define _ALL_SOURCE)... no
  checking if _THREAD_SAFE is already defined... no
  checking if _THREAD_SAFE is actually needed... no
  checking if _THREAD_SAFE is onwards defined... no
  checking if _REENTRANT is already defined... no
  checking if _REENTRANT is actually needed... no
  checking if _REENTRANT is onwards defined... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking how to print strings... printf
  checking for a sed that does not truncate output... (cached) /bin/sed
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /boot/system/develop/tools/x86_64-unknown-haiku/bin/ld
  checking if the linker (/boot/system/develop/tools/x86_64-unknown-haiku/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
  checking the name lister (/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 24576
  checking how to convert x86_64-unknown-haiku file names to x86_64-unknown-haiku format... func_convert_file_noop
  checking how to convert x86_64-unknown-haiku file names to toolchain format... func_convert_file_noop
  checking for /boot/system/develop/tools/x86_64-unknown-haiku/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /bin/dd
  checking how to truncate binary pipes... /bin/dd bs=4096 count=1
  checking for mt... no
  checking if : is a manifest tool... no
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC...  -DPIC
  checking if gcc PIC flag  -DPIC works... yes
  checking if gcc static flag  works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/boot/system/develop/tools/x86_64-unknown-haiku/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... yes
  checking dynamic linker characteristics... haiku runtime_loader
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking how to run the C++ preprocessor... g++ -E
  checking for ld used by g++... /boot/system/develop/tools/x86_64-unknown-haiku/bin/ld
  checking if the linker (/boot/system/develop/tools/x86_64-unknown-haiku/bin/ld) is GNU ld... yes
  checking whether the g++ linker (/boot/system/develop/tools/x86_64-unknown-haiku/bin/ld) supports shared libraries... yes
  checking for g++ option to produce PIC...  -DPIC
  checking if g++ PIC flag  -DPIC works... yes
  checking if g++ static flag  works... yes
  checking if g++ supports -c -o file.o... yes
  checking if g++ supports -c -o file.o... (cached) yes
  checking whether the g++ linker (/boot/system/develop/tools/x86_64-unknown-haiku/bin/ld) supports shared libraries... yes
  checking dynamic linker characteristics... haiku runtime_loader
  checking how to hardcode library paths into programs... immediate
  checking whether to build shared libraries with -version-info... yes
  checking whether to build shared libraries with -no-undefined... no
  checking whether to build shared libraries with -mimpure-text... no
  checking whether to build shared libraries with PIC... yes
  checking whether to build static libraries with PIC... no
  checking whether to build shared libraries only... no
  checking whether to build static libraries only... no
  checking if compiler is DEC/Compaq/HP C... no
  checking if compiler is HP-UX C... no
  checking if compiler is IBM C... no
  checking if compiler is Intel C... no
  checking if compiler is clang... no
  checking if compiler is GNU C... yes
  checking if compiler is LCC... no
  checking if compiler is SGI MIPSpro C... no
  checking if compiler is SGI MIPS C... no
  checking if compiler is SunPro C... no
  checking if compiler is Tiny C... no
  checking if compiler is Watcom C... no
  checking if compiler accepts debug disabling options... yes
  configure: compiler options added: -g0
  checking if compiler optimizer assumed setting might be used... yes
  checking if compiler accepts optimizer enabling options... yes
  configure: compiler options added: -O2
  checking if compiler accepts strict warning options... yes
  configure: compiler options added: -Wno-system-headers
  checking if compiler halts on compilation errors... yes
  checking if compiler halts on negative sized arrays... yes
  checking if compiler halts on function prototype mismatch... yes
  checking if compiler supports hiding library internal symbols... yes
  checking for windows.h... no
  checking whether build target is a native Windows one... no
  checking if X/Open network library is required... no
  checking for gethostbyname... no
  checking for gethostbyname in -lnsl... no
  checking for gethostbyname in -lsocket... no
  checking for gethostbyname with both nsl and socket libs... no
  checking for gethostbyname for Minix 3... no
  checking for gethostbyname for eCos... no
  checking for gethostbyname in -lnet... no
  ```

```python traceback
  Traceback (most recent call last):
    File "/packages/python38-3.8.3-1/.self/non-packaged/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/packages/python38-3.8.3-1/.self/non-packaged/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/packages/python38-3.8.3-1/.self/non-packaged/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/setuptools/build_meta.py", line 211, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/setuptools/build_meta.py", line 197, in _build_with_temp_dir
      self.run_setup()
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/setuptools/build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 471, in <module>
      run_setup(EXT_MODULES)
    File "setup.py", line 338, in run_setup
      setup(
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 142, in run
      base_class.run(self)
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 142, in run
      base_class.run(self)
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/boot/system/cache/tmp/pip-build-env-sdizl9lv/overlay/non-packaged/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/boot/system/cache/tmp/pip-install-8t6yxp45/gevent/_setuputils.py", line 350, in build_extension
      self.gevent_prepare(ext)
    File "/boot/system/cache/tmp/pip-install-8t6yxp45/gevent/_setuputils.py", line 347, in gevent_prepare
      configure(self, ext)
    File "/boot/system/cache/tmp/pip-install-8t6yxp45/gevent/_setupares.py", line 80, in configure_ares
      system(ares_configure_command)
    File "/boot/system/cache/tmp/pip-install-8t6yxp45/gevent/_setuputils.py", line 194, in system
      if _system(cmd, cwd=cwd, env=env, **kwargs):
    File "/boot/system/cache/tmp/pip-install-8t6yxp45/gevent/_setuputils.py", line 190, in _system
      return check_call(cmd, cwd=cwd, env=env, **kwargs)
    File "/packages/python38-3.8.3-1/.self/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '(cd  "/boot/system/cache/tmp/pip-install-8t6yxp45/gevent/deps/c-ares"  && if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && sh ./configure --disable-dependency-tracking -C CFLAGS="-Wno-unused-result -Wsign-compare -DNDEBUG -D_BSD_SOURCE -D_BSD_SOURCE"  && cp ares_config.h ares_build.h "$OLDPWD"   && cat ares_build.h   && if [ -r ares_build.h.orig ]; then mv ares_build.h.orig ares_build.h; fi) > configure-output.txt' returned non-zero exit status 1.
```
```
  ----------------------------------------
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent which use PEP 517 and cannot be installed directly
```

**Comment by jamadden** [comment]
(I fixed the formatting of the original post.)

Haiku is not a tested configuration, so I don't know if gevent works there. If you can get it to build, you should [run the test suite](http://www.gevent.org/development/running_tests.html) before you try to depend on it.

The relevant error appears to be:
```
  checking for gethostbyname... no
  checking for gethostbyname in -lnsl... no
  checking for gethostbyname in -lsocket... no
  checking for gethostbyname with both nsl and socket libs... no
  checking for gethostbyname for Minix 3... no
  checking for gethostbyname for eCos... no
  checking for gethostbyname in -lnet... no
  configure: error: couldn't find libraries for gethostbyname()
```

This occurs when building the c-ares dependency. You'll need to alter your compiler configuration (e.g., the CFLAGS and LDFLAGS environment variables) to make it possible to link to the `gethostbyname` function. I don't know enough about your platform to be more specific than that.

Since you're working from a source checkout, you could also try altering `setup.py` to remove `ARES` from the `EXT_MODULES` list, around line 157.

Good luck!

**Comment by skarmiglione** [comment]
oh thanks, i did 
 export LDFLAGS=“-lnetwork”
 export CFFLAGS=“-lnetwork”



now it give this:
https://pastebin.com/y7TmNquS

is that what you say about setup.py? i am little noob, but with the will to learn, thanks for your help :) 
really want to use gevent, cause is a requirement for zeronet

**Comment by jamadden** [comment]
Apparently those aren't the flags you need. It broke the compiler:
```
  configure: error: in `/boot/system/cache/tmp/pip-install-pwow7qtr/gevent/deps/libev':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
```

(The `config.log` file will be in the directory the error mentions. It should contain the exact details of how the compiler broke. You may need to pass an argument to pip to make it keep that temporary directory around.)

What I said about setup.py was that you could edit it yourself and remove the variable `ARES` from the list `EXT_MODULES` at about line 157. The compiler flags don't have anything to do with that.

```console
$ cd where/gevent/is/checked/out
$ vi setup.py # Edit the setup.py , disable ARES by taking it out of that list
$ pip install . # Install from this checkout
```

**Comment by skarmiglione** [comment]
I dont know what happen here, this is new : 
  Building wheel for gevent (PEP 517) ... done
  Created wheel for gevent: filename=gevent-20.6.3.dev0-cp38-cp38-haiku_1_x86_64.whl size=1723089 sha256=0295311eeb47ea527d133cea1295acf3e1decdc4dd64c928f645f943e6e2c2e7
  Stored in directory: /boot/system/cache/tmp/pip-ephem-wheel-cache-xzk8s1y9/wheels/58/f2/97/19de2d4ad542513868698f89959ab3d2b04594baa1448d0047
Successfully built gevent
Installing collected packages: zope.interface, zope.event, greenlet, gevent
Successfully installed gevent-20.6.3.dev0 greenlet-0.4.16 zope.event-4.4 zope.interface-5.1.0
Traceback (most recent call last):
  File "/boot/system/non-packaged/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/packages/python38-3.8.3-1/.self/non-packaged/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)


i just remove ares, nothing else if i remember. is not clear for me if it is now installed or what with tha traceback in the end, here the pastebin :

https://pastebin.com/q00j9Hm3

interesting experience.

**Comment by skarmiglione** [comment]
Ey thanks it works, now Zeronet is working too.

**Comment by skarmiglione** [comment]
https://pastebin.com/q8ejqdW5 gevent tesst full

**Comment by jamadden** [comment]
I'm glad you got it built.

The tests show a number of errors: things are slower than expected, threads and subprocesses have some issues, and there are even some socket issues. But basic functionality seems to work. I wouldn't use it for anything mission critical, but for just toying around you could probably get pretty far.

**Comment by skarmiglione** [comment]
Yeah, Haiku is just a Beta yet, but, we are growing the support in software, things are changing,

**Comment by jamadden** [comment]
I ran and loved BeOS back in the day, and I follow and root for Haiku today. As I said, glad you got a build and that it mostly works! 

Please feel free to close this issue when you’re ready.
