### ISSUE TITLE
greenlet cleanup results in exception when timeout occurs

### ISSUE THREAD

**Issue by dobe** [gevent/gevent#1663]
* gevent version:
reproduced with 1.5.0  and 20.6.2
* Python version: 
3.8.5
* Operating System: 
osx, docker(alpine)

### Description:

the commit https://github.com/gevent/gevent/commit/0138e4186f529f8d56349b7eaa88795e8071687e#diff-95e0c3476a10ac45903801381ec5dc36R465-R471 introduced a bug which results in an exception because args[0] is a Timeout exception object not a class:

```
type(ex)
type <class 'gevent.timeout.Timeout'>
```

```
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/gevent/timeout.py", line 241, in _on_expiration
    prev_greenlet.throw(ex)
  File "src/gevent/greenlet.py", line 590, in gevent._gevent_cgreenlet.Greenlet.throw
  File "src/gevent/greenlet.py", line 465, in gevent._gevent_cgreenlet.Greenlet._Greenlet__handle_death_before_start
TypeError: issubclass() arg 1 must be a class
```

**Comment by jamadden** [comment]
Can you provide an example to reproduce this?
