### ISSUE TITLE
TypeError: memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by 0x78f1935** [gevent/gevent#1664]
* gevent version: 20.6.2
* Python version: python:3.8.3-slim
* Docker: Docker version 19.03.1, build 74b1e89
* Operating System: debian-9-stretch-v20190813
* Google cloud machine n1-standard-4 (4 vCPUs, 15 GB memory)

### Description:

The docker environment starts as follows:
```
CMD /usr/sbin/cron && gunicorn -b 0.0.0.0:5000 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 webserver:server
```
It runs a flask application. Every-time a socket connection seems to acquire the incoming response looks like a string while bytes are expected.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 970, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/site-packages/geventwebsocket/handler.py", line 82, in run_application
    self.process_result()
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 904, in process_result
    self.write(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 751, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 772, in _write_with_headers
    self._write(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 734, in _write
    self._sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 708, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 533, in sendall
    data_memory = _get_memory(data)
  File "src/gevent/_greenlet_primitives.py", line 98, in gevent._gevent_c_greenlet_primitives.get_memory
  File "src/gevent/_greenlet_primitives.py", line 121, in gevent._gevent_c_greenlet_primitives.get_memory
  File "src/gevent/_greenlet_primitives.py", line 109, in gevent._gevent_c_greenlet_primitives.get_memory
TypeError: memoryview: a bytes-like object is required, not 'str'
```

### What I've run:

The docker environment starts as follows:
```
CMD /usr/sbin/cron && gunicorn -b 0.0.0.0:5000 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 webserver:server
```

Request comes in as
```
2020-08-18T10:22:51Z {'REMOTE_ADDR': '192.168.1.3', 'REMOTE_PORT': '49710', 'HTTP_HOST': 'somewebsite.com', (hidden keys: 33)} failed with TypeError
```
Perhaps an exception handler? that tries to encode json string

**Comment by 0x78f1935** [comment]
I'm unable to test this since I'm a windows beach. lol

`src/gevent/_socket3.py`

```
import json

   # ...


    # ...

    def sendall(self, data, flags=0):
        # XXX Now that we run on PyPy3, see the notes in _socket2.py's sendall()
        # and implement that here if needed.
        # PyPy3 is not optimized for performance yet, and is known to be slower than
        # PyPy2, so it's possibly premature to do this. However, there is a 3.5 test case that
        # possibly exposes this in a severe way.

        # https://github.com/gevent/gevent/issues/1664
        if type(data) == "str":
            try: data = json.loads(data)
            except: pass

        data_memory = _get_memory(data)
        return _socketcommon._sendall(self, data_memory, flags)
```
Hope that works lol

**Comment by jamadden** [comment]
This looks like a bug in the application, not gevent; the WSGI specification is quite clear on which values the application supplies as native strings (the headers) and which values the application must supply as bytes (the response body or iterable). The application here seems to be supplying the response body as something that's not bytes.

The proposed fix (`type(data) == "str") is also incorrect. Sockets do not deal with strings, they deal with bytes, and that's not how type checking works in python.

**Comment by 0x78f1935** [comment]
After a couple of hours pulling my hair out i figured this was an NGINX miss configuration.
Could you please clarify how _get_memory is able to receive non bytes data? I'm still not sure.
My configuration runs in a docker environment and was online for a couple of weeks. Suddenly I have this issue where the client websocket resulted into a 502/504. I do use an NGINX reverse proxy and tried gunicorn / uwsgi with evenlet and/or gevent. all giving me different results. When I was certain I configured it correctly I mostly get the error posted above. Its difficult to debug.

**Comment by jamadden** [comment]
It’s not, and it doesn’t matter. It is just the socket API.
