### ISSUE TITLE
gevent using Cython 3.0a5 breaks compiling on 32-bit machines

### ISSUE THREAD

**Issue by ColeMurray** [gevent/gevent#1666]
* gevent version: 20.6.2
* Python version: Please be as specific as possible: "cPython 2.7.9 downloaded from python.org" Python 3.5.2 (default, May 23 2018, 00:00:00)
* Operating System: Please be as specific as possible: "Raspbian (Debian Linux 8.0 Linux 4.9.35-v7+  armv7l)"
https://hub.docker.com/r/i386/debian/ i386/debian:stretch
### Description:

What are you trying to get done, what has happened, what went wrong, and what did you expect?
When building gevent on a 32-bit device, Cython 3.0a5 causes an integer overflow. This has been patched in 3.0a6

See: https://github.com/cython/cython/issues/3793

**Expected Fix**
Upgrade to 3.0a6 or downgrade off alpha versions.

**Comment by jamadden** [comment]
Note that gevent [does test compiling in a 32-bit system](https://ci.appveyor.com/project/denik/gevent/builds/33554346/job/veop7h2bfmvlrj58), using the Cython version in the requirements, and does not exhibit any problems. Is it also operating-system specific? 

```
…
%PYEXE% --version
Python 3.5.4
%PYEXE% -c "import struct; print(struct.calcsize('P') * 8)"
32
…
%CMD_IN_ENV% %PYEXE% -m pip install --pre -U wheel cython setuptools cffi                    
Using default MSVC build environment for 32 bit architecture                                 
Executing: C:\Python35\python.exe -m pip install --pre -U wheel cython setuptools cffi       
Collecting wheel                                                                             
  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)                                     
Collecting cython                                                                            
  Using cached Cython-3.0a5-py2.py3-none-any.whl (1.0 MB)                                    
Collecting setuptools                                                                        
  Using cached setuptools-49.2.0-py3-none-any.whl (789 kB)                                   
Collecting cffi                                                                              
  Using cached cffi-1.14.0-cp35-cp35m-win32.whl (162 kB)                                     
Collecting pycparser                                                                         
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)                                  
Installing collected packages: wheel, cython, setuptools, pycparser, cffi                    
  Attempting uninstall: setuptools                                                           
    Found existing installation: setuptools 28.8.0                                           
    Uninstalling setuptools-28.8.0:                                                          
      Successfully uninstalled setuptools-28.8.0                                             
Successfully installed cffi-1.14.0 cython-3.0a5 pycparser-2.20 setuptools-49.2.0 wheel-0.34.2
...
Executing: C:\Python35\python.exe -m pip wheel …
Building wheels for collected packages: gevent
...
Successfully built gevent
```

That said, I don't see anything to do here. The version pin is already using an open upper bound (>=), and 3.0a6 has been released. 

https://github.com/gevent/gevent/blob/ca216c777b522db58681274b990ed41cfca472a0/pyproject.toml#L23

**Comment by ColeMurray** [comment]
From the most recent test run, it appears to still be using 3.0a5.
https://ci.appveyor.com/project/denik/gevent/build/job/7direo0m3x0vawf8

**Comment by jamadden** [comment]
That build predates a6, it was over a month ago.

**Comment by ColeMurray** [comment]
@jamadden Can you link to a build with a6 in it?
From the builds I've looked at on Travis and appveyor, both appear to still be using a5. It could be I'm looking at the wrong build branch

https://ci.appveyor.com/project/denik/gevent
https://travis-ci.org/github/gevent/gevent

**Comment by jamadden** [comment]
Most of the Travis builds don’t log explicitly, but they do *always* install the latest Cython.  One build it’s obvious that it used 3.0a6 on 32 bit is at https://ci.appveyor.com/project/denik/gevent/build/job/n6co5dm6prjyfh77

As I said before, I don’t know what you want me to do here. The version pin is already correct, and the CI platforms don’t reproduce the problem. So I’ll close this. If you have something actionable please feel free to reopen!

**Comment by y0va** [comment]
For me it continues to fail on a 32bit debian machine:

```
(env) modoboa@nantix:~$ pip install gevent==21.1.1
Collecting gevent==21.1.1
  Using cached gevent-21.1.1.tar.gz (5.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpa38jiyyx
       cwd: /tmp/pip-install-p1k24g6k/gevent_57594b374d0d483287f451a20b869143
  Complete output (62 lines):
  Compiling src/gevent/resolver/cares.pyx because it depends on /tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Includes/cpython/tuple.pxd.
  [1/1] Cythonizing src/gevent/resolver/cares.pyx
  Traceback (most recent call last):
    File "/srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 211, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 48, in <module>
      from _setupares import ARES
    File "/tmp/pip-install-p1k24g6k/gevent_57594b374d0d483287f451a20b869143/_setupares.py", line 129, in <module>
      ARES = cythonize1(ARES)
    File "/tmp/pip-install-p1k24g6k/gevent_57594b374d0d483287f451a20b869143/_setuputils.py", line 261, in cythonize1
      common_utility_include_dir=COMMON_UTILITY_INCLUDE_DIR,
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1110, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
      result = compile_single(pyx_file, options, full_module_name=full_module_name)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 575, in compile_single
      return run_pipeline(source, options, full_module_name)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
      pipeline = Pipeline.create_pyx_pipeline(context, options, result)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 252, in create_pyx_pipeline
      create_pipeline(context, mode, exclude_classes=exclude_classes),
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 144, in create_pipeline
      from .ParseTreeTransforms import WithTransform, NormalizeTree, PostParse, PxdPostParse
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1632, in <module>
      class AnalyseDeclarationsTransform(EnvTransform):
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1640, in AnalyseDeclarationsTransform
      """, level='c_class', pipeline=[NormalizeTree(None)])
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/TreeFragment.py", line 235, in __init__
      mod = t = parse_from_strings(name, fmt_code, fmt_pxds, level=level, initial_pos=initial_pos)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/TreeFragment.py", line 75, in parse_from_strings
      scope = scope, context = context, initial_pos = initial_pos)
    File "Cython/Compiler/Scanning.py", line 306, in Cython.Compiler.Scanning.PyrexScanner.__init__
    File "Cython/Compiler/Scanning.py", line 35, in Cython.Compiler.Scanning.get_lexicon
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Compiler/Lexicon.py", line 147, in make_lexicon
      (Eof, Method('eof_action'))
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Plex/Lexicons.py", line 129, in __init__
      nfa, default_initial_state, spec, token_number)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Plex/Lexicons.py", line 162, in add_token_to_machine
      match_bol=1, nocase=0)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Plex/Regexps.py", line 301, in build_machine
      re.build_machine(m, s1, s2, match_bol, nocase)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Plex/Regexps.py", line 340, in build_machine
      initial_state = self.build_opt(m, initial_state, BOL)
    File "/tmp/pip-build-env-9behjejv/overlay/lib/python3.7/site-packages/Cython/Plex/Regexps.py", line 136, in build_opt
      initial_state.link_to(s)
    File "Cython/Plex/Machines.py", line 86, in Cython.Plex.Machines.Node.link_to
    File "Cython/Plex/Machines.py", line 82, in Cython.Plex.Machines.Node.add_transition
    File "Cython/Plex/Transitions.py", line 60, in Cython.Plex.Transitions.TransitionMap.add
    File "Cython/Plex/Machines.py", line 124, in Cython.Plex.Machines.Node.__hash__
  OverflowError: Python int too large to convert to C ssize_t
  ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpa38jiyyx Check the logs for full command output.
(env) modoboa@nantix:~$ pip show Cython
Name: Cython
Version: 3.0a6
Summary: The Cython compiler for writing C extensions for the Python language.
Home-page: https://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache
Location: /srv/modoboa/env/lib/python3.7/site-packages
Requires: 
Required-by: 
(env) modoboa@nantix:~$ uname -a
Linux nantix 4.9.212-antix.1-486-smp #2 SMP Sat Feb 1 14:47:26 EET 2020 i686 GNU/Linux
(env) modoboa@nantix:~$ 
```

**Comment by jamadden** [comment]
Perhaps you don't realize that pip now "helpfully" executes in an isolated environment and it takes special steps to make it do otherwise.

**Comment by jamadden** [comment]
Regardless, there is nothing that gevent can do here.
