### ISSUE TITLE
Possibly more graceful ERRNO (11) EAGAIN handling?

### ISSUE THREAD

**Issue by compyman** [gevent/gevent#1668]
* gevent version: 20.6.2
* gunicorn version: 20.0.4
* Flask Version: 1.1.2
* Python version:  Heroku cPython 3.8.5 
* Operating System:  Heroku-18 Stack (Ubuntu 18.4) [Here is the DockerFile if that is helpful](https://github.com/heroku/stack-images/tree/main/heroku-18)

### Description:
We have a web application that runs a pretty standard flask web app served with gunicorn & gevent workers. 
Last night one of our heroku dynos became unresponsive - when I looked in the logs I found that each of the gevent workers threw an `EAGAIN` error when trying to write the response to the socket. After raising this error the worker would no longer be available to handle and as soon as all gevent workers threw this error the server stopped servicing requests entirely

After this error the worker greenthread stopped processing responses until it was restarted.

in _socket3.py it looks like gevent tries to handle `EWOULDBLOCK` by waiting until we can write to the socket and then attempting to send again. I think (although my understanding is shakey) that `EAGAIN` should be handled the same as a `EWOULDBLOCK` error? Should `EAGAIN` be added to `_socketcommon.GSENDAGAIN`

Alternatively should the responsibilty for handling these failures go on gunicorn - since I would hope that it would know to restart a worker if it has stopped being able to service requests?
```python traceback
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socket3.py", line 515, in send
    return self._sock.send(data, flags)
BlockingIOError: [Errno 11] Resource temporarily unavailable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 65, in handle
    util.reraise(*sys.exc_info())
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 625, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 128, in handle_request
    util.reraise(*sys.exc_info())
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 625, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request
    resp.write(item)
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 346, in write
    util.write(self.sock, arg, self.chunked)
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 286, in write
    sock.sendall(data)
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socket3.py", line 534, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socketcommon.py", line 392, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socketcommon.py", line 321, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socket3.py", line 521, in send
    return _socket.socket.send(self._sock, data, flags)
TimeoutError: [Errno 110] Connection timed out
```

Let me know if you need any more information of if I can clarify anything

**Comment by compyman** [comment]
just a ping on this if I can provide any more information? or assisstance?

**Comment by jamadden** [comment]
`EWOULDBLOCK` and `EAGAIN` are aliases on every platform gevent supports, so there's nothing additional to handle in that way. 

This looks like a straightforward timeout of your receiver, e.g., someone connected, made a request, and failed to read all of the data.

**Comment by compyman** [comment]
@jamadden I'm just confused since the code where this is happening appears to handle EWOULDBLOCK explicitly - 

```
        except error as ex:
            if ex.args[0] not in _socketcommon.GSENDAGAIN or timeout == 0.0:
                raise
            self._wait(self._write_event)
            try:
                return _socket.socket.send(self._sock, data, flags)
            except error as ex2:
                if ex2.args[0] == EWOULDBLOCK:
                    return 0
                raise
```
but we specifically got EAGAIN? sorry if I'm being dense but I'm not sure how to handle this better? guincorn stopped processing requests after this and we had to restart the server

**Comment by jamadden** [comment]
`EAGAIN == EWOULDBLOCK`. They're the same, there doesn't need to be an additional check.

```pycon
$ /opt/python/cp38-cp38/bin/python
Python 3.8.5 (default, Aug 20 2020, 16:08:12)
[GCC 8.3.1 20190311 (Red Hat 8.3.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import errno
>>> errno.EWOULDBLOCK
11
>>> errno.EAGAIN
11
>>> errno.EAGAIN == errno.EWOULDBLOCK
True
```

The first time we send, we get `EAGAIN` (or `EWOULDBLOCK`, same thing).

```python traceback
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socket3.py", line 515, in send
    return self._sock.send(data, flags)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

 We then wait until the socket is writable and attempt to send again. But at that point, the socket has timed out (`TimeoutError`).

```python traceback
  File "/app/.heroku/python/lib/python3.8/site-packages/gevent/_socket3.py", line 521, in send
    return _socket.socket.send(self._sock, data, flags)
TimeoutError: [Errno 110] Connection timed out
```

I don't see how this could cause gunicorn to stop processing requests, unless the application code has manually changed the timeouts on the sockets gunicorn is using to a very small value or something. Most likely this is some sort of application bug.

**Comment by sureshsankaran** [comment]
i am hitting this exact issue of EAGAIN and cpu of server reaches 100% with infinitely looping on write which consistently returns EAGAIN. Have to restart server to recover. Please suggest fix asap.

**Comment by sureshsankaran** [comment]
> `EWOULDBLOCK` and `EAGAIN` are aliases on every platform gevent supports, so there's nothing additional to handle in that way.
> 
> This looks like a straightforward timeout of your receiver, e.g., someone connected, made a request, and failed to read all of the data.

Looks like gevent is not handling this gracefully when there is multiple requests (parallel requests failed to read all the data - happens when refreshing our web UI) blocking all worker threads, hence causing the server unresponsive till restarting it.

Could you please suggest how to handle this case ?

**Comment by jamadden** [comment]
Someone is going to need to provide a [short example using only gevent](http://sscce.org) demonstrating the problem exists in gevent and not a framework or server.

**Comment by jamadden** [comment]
No activity for two months, closing.
