### ISSUE TITLE
TypeError: get() missing 1 required positional argument: 'cookie'

### ISSUE THREAD

**Issue by JabbaDesilijicTiure** [gevent/gevent#1677]
@jamadden here is the traceback:

Traceback (most recent call last):
File "/opt/z/environment/lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
thread_result.set(func(*args, **kwargs))
TypeError: get() missing 1 required positional argument: 'cookie'
2020-09-23T12:52:47Z (<ThreadPoolWorker at 0x7f868ae630f0 thread_ident=0x7f868a9e4700 threadpool-hub=<Hub at 0x7f868aea9a00 thread_ident=0x7f868d90b740>>, <bound method Queue.get of <gevent._threading.Queue object at 0x7f868a9f3480>>) failed with TypeError

Traceback (most recent call last):
File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
File "/opt/z/src/util/ThreadPool.py", line 148, in run
func, args, kwargs, event_done = self.pool.apply(self.queue_call.get)
File "/opt/z/environment/lib/python3.8/site-packages/gevent/pool.py", line 161, in apply
return self.spawn(func, *args, **kwds).get()
File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
File "/opt/z/environment/lib/python3.8/site-packages/gevent/_compat.py", line 65, in reraise
raise value.with_traceback(tb)
File "/opt/z/environment/lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
thread_result.set(func(*args, **kwargs))
TypeError: get() missing 1 required positional argument: 'cookie'
2020-09-23T12:52:47Z <Greenlet at 0x7f868aedf6a0: <bound method MainLoopCaller.run of <util.ThreadPool.MainLoopCaller object at 0x7f868aeca700>>> failed with TypeError

https://github.com/HelloZeroNet/ZeroNet/pull/2616#issuecomment-697351164

Version: 
gevent 20.9.0

**Comment by jamadden** [comment]
Thanks, this was a bug in ZeroNet. It was using undocumented internals of gevent that have changed.
