### ISSUE TITLE
Tracebacks on stderr with ssl

### ISSUE THREAD

**Issue by OzzieIsaacs** [gevent/gevent#1681]
* gevent version: 20.9.0
* Python version: Linux Mint Python 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0] on linux

* Operating System: Please be as specific as possible: Linux Mint 20 5.4.0-48 x86_64

### Description:

I'm running gevent as (optional) wsgi server in my project (https://github.com/janeczku/calibre-web), if using ssl the code throws ugly tracebacks upon several ssl errors on stderr. The errors can't easily be logged or suppressed. Would be great if you could consider to log the tracebacks to the error_log instead of just outputting them, so users could decide to ignore them (set higher log level), and at least they would not spam the console.

To reproduce it you can use the example given here: http://www.gevent.org/examples/wsgiserver_ssl.html

After starting the code, access the server under https://127.0.0.1:8443, you get the "SSLV3_ALERT_CERTIFICATE_UNKNOWN" and "SSLV3_ALERT_BAD_CERTIFICATE" error. If accessing it via http://127.0.0.1:8443 you get the "HTTP_REQUEST" error. 

I'm fully aware that the errors are vaild, just want to get them into the logbook.

I tried to also set `log=None` and `error_log=None` in the example on calling `pywsgi.WSGIServer`, with no success regarding the tracebacks.

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 797, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1108)
2020-09-27T04:51:20Z <Greenlet at 0x7f1dd0195590: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f1dd0c96ea)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 797, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1108)
2020-09-27T04:51:44Z <Greenlet at 0x7f1dd01956a0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f1dd010bb8)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 797, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1108)
2020-09-27T04:51:58Z <Greenlet at 0x7f1dd0e36bf0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f1dd0c9b1d)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 797, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/home/ozzie/Entwicklung/calibre-web-test/venv/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1108)
2020-09-27T04:52:01Z <Greenlet at 0x7f1dd0e36bf0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f1dd0c9b1d)> failed with SSLError
```

### What I've run:

```
#!/usr/bin/python
"""Secure WSGI server example based on gevent.pywsgi"""

from __future__ import print_function
from gevent import pywsgi


def hello_world(env, start_response):
    if env['PATH_INFO'] == '/':
        start_response('200 OK', [('Content-Type', 'text/html')])
        return [b"<b>hello world</b>"]

    start_response('404 Not Found', [('Content-Type', 'text/html')])
    return [b'<h1>Not Found</h1>']

print('Serving on https://:8443')
server = pywsgi.WSGIServer(('127.0.0.1', 8443), hello_world, keyfile='server.key', certfile='server.crt')
# to start the server asynchronously, call server.start()
# we use blocking serve_forever() here because we have no other jobs
server.serve_forever()
```

**Comment by jamadden** [comment]
You're welcome to do that, you just need to configure gevent to direct all, or some subset of, uncaught errors, to where you want them to go. You can do that directly on your server object (preferred) or globally. See [this very recent example](https://github.com/gevent/gevent/issues/1671) for a similar example.

Note that [it's not necessarily safe to use `logging` at arbitrary times](http://www.gevent.org/api/gevent.pywsgi.html#gevent.pywsgi.LoggingLogAdapter), which is one reason why gevent doesn't do that by default.
