### ISSUE TITLE
gevent.monkey.patch_socket() causes 'TypeError' exception when opening a HTTPS url

### ISSUE THREAD

**Issue by motoom** [gevent/gevent#1693]
* gevent version: 20.9.0
* Python version: cPython 3.8.5 included with Ubuntu 20 LTS
* Operating System: Ubuntu 20.04.1 LTS, Linux ubuntu-vps4 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Description:

Exception raised from calling `urlopen` when `gevent.monkey.patch_socket()` has been called before:

   `TypeError: _wrap_socket() argument 'sock' must be _socket.socket, not SSLSocket`

If I comment out the `patch_socket()` call, the example works OK, but then of course I don't get the advantages of using gevent.

```
Traceback (most recent call last):
  File "sockerror.py", line 9, in <module>
    resp = urlopen("https://my-json-server.typicode.com/typicode/demo/comments")
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1031, in _create
    self._sslobj = self._context._wrap_socket(
TypeError: _wrap_socket() argument 'sock' must be _socket.socket, not SSLSocket
```

### What I've run:

```python
#!/usr/bin/env python3

import gevent.monkey
gevent.monkey.patch_socket()

import gevent
from urllib.request import urlopen

resp = urlopen("https://my-json-server.typicode.com/typicode/demo/comments")
```

**Comment by jamadden** [comment]
If you're going to be using ssl, you also need to call [`patch_ssl()`](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_ssl).

I typically recommend just using `patch_all()`.

**Comment by motoom** [comment]
Thanks a lot Jason, now it works. You made my day a better day ;-)
