### ISSUE TITLE
Multi-threaded logging in monkey-patched environment not working properly

### ISSUE THREAD

**Issue by feisuzhu** [gevent/gevent#1698]
* gevent version: `20.9.0`
* Python version: Please be as specific as possible: `Python 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0] on linux, installed from apt`
* Operating System: Please be as specific as possible: `Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-42-generic x86_64)`

### Description:

**I WANT**: Use `logging` in thread spawned by `gevent.threadpool.ThreadPool.spawn`
**SITUATION**: Threads just crashes.
**EXPECTING**: Threads should log normally

### What I've run:

```python
import gevent.monkey
gevent.monkey.patch_all()
import logging
logging.basicConfig(filename="log", level=logging.DEBUG)

from gevent.threadpool import ThreadPool

print(gevent.__version__)

log = logging.getLogger('meh')


def run(v):
    while True:
        log.debug("Log from instance %s", v)

pool = ThreadPool(10)

for i in range(2):  # must >= 2, the first thread works
    pool.spawn(run, i)

import time
time.sleep(10000)
```

### Stack trace

```
20.9.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "a.py", line 15, in run
    log.debug("Log from instance %s", v)
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 863, in handle
    self.acquire()
  File "/usr/lib/python3.6/logging/__init__.py", line 814, in acquire
    self.lock.acquire()
  File "/usr/lib/python3.6/threading.py", line 147, in acquire
    rc = self._block.acquire(blocking, timeout)
  File "/usr/local/lib/python3.6/dist-packages/gevent/thread.py", line 118, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 143, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 178, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub 'ThreadPool Worker Hub' at 0x7fb97b2268d0 epoll pending=0 ref=0 fileno=6 thread_ident=0x7fb97afc9700>
	Handles:
[]
2020-11-06T10:25:37Z (<ThreadPoolWorker at 0x7fb97b1cf210 thread_ident=0x7fb97afc9700 threadpool-hub=<Hub at 0x7fb97b226198 thread_ident=0x7fb97f8af740>>, <function run at 0x7fb97c05f8c8>) failed with LoopExit
```

### Other concerns

I can see a similar issue https://github.com/gevent/gevent/issues/1350, which recommends not using gevent facility in threadpool. In this issue `logging` is implicit using it which is not something I can control, and this could be considered a major abstraction leak.

**Comment by jamadden** [comment]
Back in [20.5.1](http://www.gevent.org/changelog.html#id15) (#1437, #1617) I made locks (basically) work across threads, with the caveat that (a) it depended on the main thread acquiring the lock first for highest reliability and (b) sometimes it could still raise `LoopExit` (so thank you for raising an issue where it does that).

What makes this case interesting and different is that nothing in this background thread has actually used gevent or created gevent's hub for that thread. Nor does the main thread *ever* acquire the lock.

Simply adding `gevent.get_hub()` to the top of the `run` function causes this example to work, in that it no longer raises any exceptions. However, locks depend on the hub actually getting time to run, and this tight CPU-bound loop doesn't currently do that, so one of the threads never acquires the lock and never makes progress. Adding `gevent.sleep()` to the bottom of the loop may help with that (but I'm currently seeing another issue there, probably a race condition; it's possible that's only an issue with such a tight loop).

I'm continuing to investigate the issues and look for a more robust solution. But in the meantime, you might try those two things.
