### ISSUE TITLE
python error:'NoneType' object has no attribute 'close' & ERROR: Error processing & 'NoneType' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by GriffinChou** [gevent/gevent#1699]
* gevent version:
* Python version: 3.7
* Operating System: pycharm + windows 10**

### Description:
when i test scrapy i find a issue that i cannot solve,my project's pypelines.py as flows:

 Define your item pipelines here
```python
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: https://docs.scrapy.org/en/latest/topics/item-pipeline.html


# useful for handling different item types with a single interface
from itemadapter import ItemAdapter
import pymysql
#本地化存储

from time import sleep


class QiushibaikePipeline:
    fp = None
    #重写父类方法，旨在开始时调用
    def open_spider(self,spider):
        print('开始爬虫')
        self.fp = open('./qiushibaike.txt','w',encoding="utf-8")

    #每接收一个item即被调用一次
    def process_item(self, item, spider):
        #接受item
        author = item['author']
        age = item['age']
        content = item['content']

        self.fp.write(author+':'+content+'\n')

        return item#传递给下一个即将被执行的管道类

    #关闭管道
    def close(self,spider):
        print('结束爬虫')
        self.fp.close()

#数据库存储
class mysqlpipelines(object):
    #创建数据库链接对象
    cnn = None
    # cursor = None#游标对象

    cursor = None#游标对象

    def open_spider(self,spider):
        cnn = pymysql.connect(host='127.0.0.1',port=3308,user='root',password='mysql',db='spider',charset='utf8')
    def process_item(self,item,spider):
        #用游标对象执行sql语句
        # self.cursor = self.cnn.cursor()
        self.cursor = self.cnn.cursor()

        # print(self.cursor)
        #debug
        print('==================================================================')
        #要执行的sql语句
        try:
            # self.cursor.execute('insert into qiubai values("%s,"%s","%s")'%(item["author"],item["age"],item["content"]))
            sql = 'insert into qiushibaike values("%s,"%s","%s")'%(item["author"],item["age"],item["content"])
            print(sql)
            self.cursor.execute(sql)
            self.cnn.commit()

        except Exception as e:
            print(e)
            self.cnn.roolback()
        return item
    def close_spider(self,spider):
        self.cursor.close()
        self.cnn.close()

```

**this is errors or warings:**

```python traceback
Traceback (most recent call last):
  File "d:\python3.7\python-3.7.0\lib\site-packages\twisted\internet\defer.py", line 654, in _runCa
llbacks
    current.result = callback(current.result, *args, **kw)
  File "d:\python3.7\python-3.7.0\lib\site-packages\scrapy\utils\defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "D:\SoftData\Python\project\Timer\scrapy_test\qiushibaike\qiushibaike\pipelines.py", line 48
, in process_item
    self.cursor = self.cnn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-08 23:58:35 [scrapy.core.scraper] ERROR: Error processing {'age': '20',
 'author': '再见单身狗',
 'content': '\n'
            '\n'
            '\n'
            '每次闺女吃橘子我把橘子皮给她要过来，放进我的保温杯割一下今天逛商场有个帅哥拎着一袋子的
橘子，坐在椅子上慢慢的剥着吃，闺女就盯着人家看，帅哥被人看着吃挺不好意思的，就拿出来几个给闺女闺女
：哥哥，我不吃，把你剥的那个橘子皮全给我吧！帅哥：你要它干啥？闺女：我妈妈就喜欢吃别人扔的橘子皮！[
捂脸][捂脸][捂脸][捂脸]\n'
            '\n'
            '\n'
            '\n'}

```
so i ask for help from github,thanks for you  help!

**Comment by jamadden** [comment]
The error you're reporting:
```python traceback
  File "D:\SoftData\Python\project\Timer\scrapy_test\qiushibaike\qiushibaike\pipelines.py", line 48, in process_item
   self.cursor = self.cnn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
```

Means that `self.cnn` is `None`. I don't know what kind of object `self` is, or where it was supposed to initialize `self.cnn`, but this doesn't seem to have anything to do with gevent.

If the snippet of code you posted above is somehow related to this error, it's possible that you forgot to assign `self.cnn` in the `open_spider` method (again, I know nothing about this code or whatever framework you're trying to use, so that's just a guess).

```python
def open_spider(self,spider):
        self.cnn  = ...
```

Good luck!

**Comment by GriffinChou** [comment]
hi jamadden,
    thanks for your help,what if your means :assign  "self.cnn  = ..." in the function of open_sider()?
