### ISSUE TITLE
Install fails on M1 Mac mini running Big Sur

### ISSUE THREAD

**Issue by rpm886** [gevent/gevent#1707]
* gevent version: setuptools in ./venv/lib/python3.8/site-packages (from gevent) (50.3.2)
* Python version: Python 3.8.2 (pre installed on Mac)
* Operating System: System Version: macOS 11.0.1 (20B29)
      Kernel Version: Darwin 20.1.0

### Description:

trying to install using pip3 install gevent

```
 Traceback (most recent call last):
    File "/Users/robertmadonna/Documents/ZoomRooms/ZoomRoomsRestApi3/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/robertmadonna/Documents/ZoomRooms/ZoomRoomsRestApi3/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/robertmadonna/Documents/ZoomRooms/ZoomRoomsRestApi3/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 471, in <module>
      run_setup(EXT_MODULES)
    File "setup.py", line 338, in run_setup
      setup(
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/ym/s_l6sz_n56710cpcplppncp00000gn/T/pip-build-env-h3oqq7lv/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_10_14_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent which use PEP 517 and cannot be installed directly

```

### What I've run:

pip3 install eel

or pip3 install events

This was working on x86 versions

```python
"Put python code in python blocks"
```

**Comment by jamadden** [comment]
Thanks for the report, but that has nothing to do with gevent. You'll need an updated version of the `wheel` library. See https://github.com/pypa/wheel/issues/381

You should also be able to install gevent manually with the old-fashioned `python setup.py install` after unpacking the source and installing the dependencies. The information at https://www.gevent.org/development/getting_started.html and https://www.gevent.org/development/installing_from_source.html may be helpful.
