### ISSUE TITLE
An UnicodeDecodeError

### ISSUE THREAD

**Issue by abcvav** [gevent/gevent#1717]
* gevent version:20.9.0
* Python version:  "cPython 3.8.0 downloaded from python.org"
* Operating System: "win10"

```
Traceback (most recent call last):
  File "d:\myapps\python38\lib\site-packages\gevent\threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
2020-12-14T13:46:56Z (<ThreadPoolWorker at 0x1e16c94ab40 thread_ident=0x445c threadpool-hub=<Hub at 0x1e16c616700 thread_ident=0x3680>>, <built-in function gethostbyaddr>) failed with UnicodeDecodeError

Traceback (most recent call last):
  File "d:\myapps\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\myapps\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\MyApps\Python38\Scripts\auto-py-to-exe.exe\__main__.py", line 7, in <module>
  File "d:\myapps\python38\lib\site-packages\auto_py_to_exe\__main__.py", line 99, in run
    start_ui(logging_level)
  File "d:\myapps\python38\lib\site-packages\auto_py_to_exe\__main__.py", line 22, in start_ui
    ui.start(config.ui_open_mode)
  File "d:\myapps\python38\lib\site-packages\auto_py_to_exe\ui.py", line 142, in start
    eel.start('index.html', size=(650, 650), port=0, mode='user default')
  File "d:\myapps\python38\lib\site-packages\eel\__init__.py", line 164, in start
    run_lambda()
  File "d:\myapps\python38\lib\site-packages\eel\__init__.py", line 155, in run_lambda
    return btl.run(
  File "d:\myapps\python38\lib\site-packages\bottle.py", line 3137, in run
    server.run(app)
  File "d:\myapps\python38\lib\site-packages\bottle_websocket\server.py", line 17, in run
    server.serve_forever()
  File "d:\myapps\python38\lib\site-packages\gevent\baseserver.py", line 398, in serve_forever
    self.start()
  File "d:\myapps\python38\lib\site-packages\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "d:\myapps\python38\lib\site-packages\gevent\pywsgi.py", line 1501, in init_socket
    self.update_environ()
  File "d:\myapps\python38\lib\site-packages\gevent\pywsgi.py", line 1513, in update_environ
    name = socket.getfqdn(address[0])
  File "d:\myapps\python38\lib\site-packages\gevent\_socketcommon.py", line 287, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "d:\myapps\python38\lib\site-packages\gevent\_socketcommon.py", line 259, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "d:\myapps\python38\lib\site-packages\gevent\resolver\thread.py", line 66, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "d:\myapps\python38\lib\site-packages\gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "d:\myapps\python38\lib\site-packages\gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "d:\myapps\python38\lib\site-packages\gevent\threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
```

### What I've run:

**a package named auto_py_to_exe**: Paste short, self contained, correct example code (sscce.org), tracebacks, etc, here

**Comment by jamadden** [comment]
You don't follow the requested instructions and tell us what you were trying to run, so this will all be guesswork.

The traceback suggests that this is the result of calling `socket.getfqdn`, which uses `socket.gethostbyaddr`. By default, gevent just passes that through to the native real `socket.gethostbyaddr`. The native `socket.gethostbyaddr` function is raising a `UnicodeDecodeError`, and gevent is just passing that back.

in other words, if you simply open a Python console and type `import socket; socket.getfqdn(ADDR)`, where `ADDR` is the value that you used in this example (again, you don't say what you ran so I can't guess what that is, but it's probably whatever you bound the server to), it will probably raise the same thing. 

Running the program using gevent's [blocking resolver](http://www.gevent.org/dns.html) should also show the same thing.

In that case, this is likely to be a configuration issue on your system and not a problem in gevent.
