### ISSUE TITLE
gevent 20.12.1 will raise a error in pip install

### ISSUE THREAD

**Issue by OneMoreSecond** [gevent/gevent#1736]
* gevent version: 20.12.1 pip install from PyPI
* Python version: cPython 3.6 included in a docker image
* Operating System: Linux

### Description:

An automated pipeline of mine will install gevent to setup some environments.
In recent days (after `20.12.*` releases), it will raise following error from standard library which is quite weird:

```python-traceback
Collecting gevent (from -r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/98/d9/6811589dd5de85b3a911d547d43f43c5c8bdf4397ffdfbaefea7c373b7f6/gevent-20.12.1.tar.gz (5.9MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Complete output from command /opt/conda/bin/python /opt/conda/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8kfojhp0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17, < 2.0 ; platform_python_implementation == '"'"'CPython'"'"'':
  ERROR: Traceback (most recent call last):
    File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/conda/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/opt/conda/lib/python3.6/site-packages/pip/_internal/__init__.py", line 4, in <module>
      import locale
    File "/opt/conda/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/opt/conda/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'  
  ----------------------------------------
ERROR: Command "/opt/conda/bin/python /opt/conda/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8kfojhp0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17, < 2.0 ; platform_python_implementation == '"'"'CPython'"'"''" failed with error code 1 in None
```

**Comment by jamadden** [comment]
Thanks for the report, but as you can see from the command being executed, gevent is not involved at all; pip is just installing dependencies before executing any gevent code at all:
```
pip install ... 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3' 'greenlet >= 0.4.17, < 2.0'
…
  AttributeError: module 'enum' has no attribute 'IntFlag'  
```

This would seem to indicate a problem in your environment.

I vaguely remember seeing `AttributeError: module 'enum' has no attribute 'IntFlag' ` before; it may have had something to do with a third-party `enum` package being installed? I think I just created fresh virtual environments and that solved the problem.

Good luck!
