### ISSUE TITLE
"OverflowError: Python int too large to convert to C ssize_t" on legacy 32bit machine

### ISSUE THREAD

**Issue by y0va** [gevent/gevent#1753]
gevent 21.1.1 is not installable on a legacy 32bit machine:

Linux nantix 4.9.212-antix.1-486-smp #2 SMP Sat Feb 1 14:47:26 EET 2020 i686 GNU/Linux

```
(env) modoboa@nantix:~$ pip install gevent==21.1.1
Collecting gevent==21.1.1
  Using cached gevent-21.1.1.tar.gz (5.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5bvvqvz7
       cwd: /tmp/pip-install-lpbws6sg/gevent_54be877aab89466c8a2734ad79bea310
  Complete output (62 lines):
  Compiling src/gevent/resolver/cares.pyx because it depends on /tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Includes/cpython/tuple.pxd.
  [1/1] Cythonizing src/gevent/resolver/cares.pyx
  Traceback (most recent call last):
    File "/srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/modoboa/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 211, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 48, in <module>
      from _setupares import ARES
    File "/tmp/pip-install-lpbws6sg/gevent_54be877aab89466c8a2734ad79bea310/_setupares.py", line 129, in <module>
      ARES = cythonize1(ARES)
    File "/tmp/pip-install-lpbws6sg/gevent_54be877aab89466c8a2734ad79bea310/_setuputils.py", line 261, in cythonize1
      common_utility_include_dir=COMMON_UTILITY_INCLUDE_DIR,
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1110, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
      result = compile_single(pyx_file, options, full_module_name=full_module_name)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 575, in compile_single
      return run_pipeline(source, options, full_module_name)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
      pipeline = Pipeline.create_pyx_pipeline(context, options, result)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 252, in create_pyx_pipeline
      create_pipeline(context, mode, exclude_classes=exclude_classes),
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 144, in create_pipeline
      from .ParseTreeTransforms import WithTransform, NormalizeTree, PostParse, PxdPostParse
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1632, in <module>
      class AnalyseDeclarationsTransform(EnvTransform):
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1640, in AnalyseDeclarationsTransform
      """, level='c_class', pipeline=[NormalizeTree(None)])
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/TreeFragment.py", line 235, in __init__
      mod = t = parse_from_strings(name, fmt_code, fmt_pxds, level=level, initial_pos=initial_pos)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/TreeFragment.py", line 75, in parse_from_strings
      scope = scope, context = context, initial_pos = initial_pos)
    File "Cython/Compiler/Scanning.py", line 306, in Cython.Compiler.Scanning.PyrexScanner.__init__
    File "Cython/Compiler/Scanning.py", line 35, in Cython.Compiler.Scanning.get_lexicon
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Compiler/Lexicon.py", line 147, in make_lexicon
      (Eof, Method('eof_action'))
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Plex/Lexicons.py", line 129, in __init__
      nfa, default_initial_state, spec, token_number)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Plex/Lexicons.py", line 162, in add_token_to_machine
      match_bol=1, nocase=0)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Plex/Regexps.py", line 301, in build_machine
      re.build_machine(m, s1, s2, match_bol, nocase)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Plex/Regexps.py", line 340, in build_machine
      initial_state = self.build_opt(m, initial_state, BOL)
    File "/tmp/pip-build-env-zwhbittt/overlay/lib/python3.7/site-packages/Cython/Plex/Regexps.py", line 136, in build_opt
      initial_state.link_to(s)
    File "Cython/Plex/Machines.py", line 86, in Cython.Plex.Machines.Node.link_to
    File "Cython/Plex/Machines.py", line 82, in Cython.Plex.Machines.Node.add_transition
    File "Cython/Plex/Transitions.py", line 60, in Cython.Plex.Transitions.TransitionMap.add
    File "Cython/Plex/Machines.py", line 124, in Cython.Plex.Machines.Node.__hash__
  OverflowError: Python int too large to convert to C ssize_t
```

related: https://github.com/gevent/gevent/issues/1733

**Comment by jamadden** [comment]
This is not related to #1733, as that was a runtime issue. What you're seeing here is an issue in Cython, previously reported at https://github.com/gevent/gevent/issues/1666. The solution is to make sure you're using the newest Cython release (>= 3.0a6).
