### ISSUE TITLE
[Question] about: OSError: unexpected end of file while reading request at position

### ISSUE THREAD

**Issue by cgloeckner** [gevent/gevent#1762]
Hey there,
I'm using `bottle` in combination with `gevent` on a production-level application where I'm getting rare exceptions when a user uploads a file (most of the time it's working without problems, I cannot reproduce it, hence I'm sitting here and wait for it).
```python-traceback
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 1982464
```
I cannot just re-build a minimal version of that code, because the situation is happening inside a larger scale application with a couple of users intending to operate as usual.
Furthermore I'm not looking for a way to fix it but more to understand what and why it is happening. 

Here's my traceback (the calls are going through `bottle` into gevent's `pywsgi` implementation, since I'm using `gevent.pywsgi.WSGIServer`).
```python-traceback
Traceback (most recent call last):
  File "/root/pyvtt/utils.py", line 310, in wrapper
    return func(*args, **kwargs)
  File "./vtt.py", line 37, in wrapper
    return callback(*args, **kwargs)
  File "./vtt.py", line 251, in post_import_game
    files = request.files.getall('file')
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 172, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 1113, in files
    for name, item in self.POST.allitems():
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 172, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 1232, in POST
    args = dict(fp=self.body, environ=safe_env, keep_blank_values=True)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 1203, in body
    self._body.seek(0)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 172, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 1172, in _body
    for part in body_iter(read_func, self.MEMFILE_MAX):
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 1135, in _iter_body
    part = read(min(maxread, bufsize))
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 320, in read
    return self._do_read(length)
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 199, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 1982464
```
Here are some version numbers:
```bash
$ pip show gevent
Name: gevent
Version: 20.12.1
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Denis Bilenko
Author-email: denis.bilenko@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: setuptools, zope.interface, zope.event, greenlet
Required-by: gevent-websocket

$ python3
Python 3.8.7 (default, Dec 21 2020, 21:23:03) 
[GCC 5.4.0 20160609] on linux

$ uname -a
Linux usve272161 4.4.0-042stab145.3 #1 SMP Thu Jun 11 14:05:04 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```
Btw the server OS is pretty outdated - I hope that's not the reason here.

Greetings
glocke

**Comment by jamadden** [comment]
That looks like a problem from the client violating the HTTP spec. Why do you think it relates to gevent?

**Comment by cgloeckner** [comment]
> That looks like a problem from the client violating the HTTP spec. Why do you think it relates to gevent?

Thank you. To be honest, asking at `gevent` seemed natural to be, because the exception was thrown from gevent-code (and I wasn't able to find documentation on that). Hence asking you `gevent`-guys :-) 

Do you recommend catching the exception, maybe logging it and ignoring it after that?

**Comment by yakirs57** [comment]
How did you resolve this?

**Comment by cgloeckner** [comment]
@yakirs57 to be honest, I have neither an idea nor do I remember if or why I closed this.
