### ISSUE TITLE
Using native python threads alongside gevent event loop

### ISSUE THREAD

**Issue by guybortnikov** [gevent/gevent#1780]
* gevent version: 21.1.2 (latest from PyPi for Python2.7)
* Python version: Python 2.7.17 installed from "apt" (official Ubuntu repository), `sys.version` is `'2.7.17 (default, Feb 27 2021, 15:10:58) \n[GCC 7.5.0]'`
* Operating System: Ubuntu 18.04 (docker base image `ubuntu:18.04`)

### Description:
I'm trying to write an application that will use both native Python threads (that get translated to native pthreads) and gevent coroutines (using the patched synchronous API).
In order to accomplish that, I'm launching native threads (using the **unpatched** `threading` module), before the monkey-patching happens, and the code that runs within the threads is using only ["original"](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.get_original) (unpatched) functions.
I wrote a small code snippet (See #what-ive-run) that tries the following and got this locking error:

```python-traceback
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 892, in emit
  File "/usr/lib/python2.7/logging/__init__.py", line 892, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 854, in flush
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 854, in flush
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
Logged from file main.py, line 16
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
Logged from file main.py, line 16
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 16, in native_thread_entry
    logger.info("native thread")
  File "/usr/lib/python2.7/logging/__init__.py", line 1174, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 768, in handle
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 16, in native_thread_entry
    logger.info("native thread")
  File "/usr/lib/python2.7/logging/__init__.py", line 1174, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 768, in handle
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 16, in native_thread_entry
    logger.info("native thread")
  File "/usr/lib/python2.7/logging/__init__.py", line 1174, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 768, in handle
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
```

I dived a little deeper and saw that `gevent.monkey.patch_all()` will patch all existing locks (also the ones that the `logging` loggers are using),
I thought changing the `gevent.monkey.patch_all()` to
```python
gevent.monkey.patch_all(thread=False)
gevent.monkey.patch_thread(existing_locks=False)
```

I'm wondering if this usage is legitimate or my approach will not work at all. Moreover, if there are some major assumptions in gevent/greenlet that prevent normal (native) Python threads from running alongside the gevent event loop using only untouched (original) functions.

### What I've run:
main.py:
```python
import threading
import logging

def get_logger():
    logger = logging.getLogger(str(threading.current_thread().ident))
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    handler = logging.FileHandler("/tmp/log.txt")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.DEBUG)
    return logger

def native_thread_entry():
    logger = get_logger()
    while True:
        logger.info("native thread")

def main():
    threading.Thread(target=native_thread_entry).start()
    threading.Thread(target=native_thread_entry).start()
    threading.Thread(target=native_thread_entry).start()

    import time; time.sleep(1); del time

    import gevent.monkey
    gevent.monkey.patch_all()
    logger = get_logger()
    while True:
        logger.info("gevent loop")


if __name__ == "__main__":
    main()
```

**Comment by jamadden** [comment]
The gevent documentation is [pretty explicit](http://www.gevent.org/api/gevent.monkey.html) about needing to [monkey-patch *first*](http://www.gevent.org/intro.html#beyond-sockets) before doing (or importing) anything else. If you move that to the beginning of this module, rather than waiting until after you've started threads, you should see things behave more as expected.

To use native threads, rather than spawning them yourself, it is highly suggested to use ``gevent.get_hub().threadpool` to manage them, or the [`ThreadPoolExecutor`](http://www.gevent.org/api/gevent.threadpool.html#gevent.threadpool.ThreadPoolExecutor). 

In any case, you should watch the APIs you use in the native threads and ideally stick to CPU computations and avoid things that would have been monkey-patched by gevent.
