### ISSUE TITLE
name 'AF_INET' is not definname 'AF_INET' is not defineded

### ISSUE THREAD

**Issue by jeffin-ntx** [gevent/gevent#1786]
* gevent version: 21.1.2
* Python version: 3.9
* Operating System: `alpine-docker container`

### Description:

```python-traceback
NameError: name 'AF_INET' is not defined
Traceback (most recent call last):
  File "/opt/ags/gateway.py", line 254, in <module>
    AGSGateway().configure_and_start_app()
  File "/opt/ags/gateway.py", line 216, in configure_and_start_app
    monkey.patch_all()
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 1142, in patch_all
    patch_ssl(_warnings=_warnings, _first_time=first_time)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 183, in ignores
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 939, in patch_ssl
    gevent_mod, _ = _patch_module('ssl', _warnings=_warnings)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 400, in _patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/usr/lib/python3.9/site-packages/gevent/ssl.py", line 32, in <module>
    from gevent import _ssl3 as _source # pragma: no cover
  File "/usr/lib/python3.9/site-packages/gevent/_ssl3.py", line 171, in <module>
    class SSLSocket(socket):
  File "/usr/lib/python3.9/site-packages/gevent/_ssl3.py", line 184, in SSLSocket
    family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None,
NameError: name 'AF_INET' is not defined
Traceback (most recent call last):
  File "/opt/ags/gateway.py", line 254, in <module>
    AGSGateway().configure_and_start_app()
  File "/opt/ags/gateway.py", line 216, in configure_and_start_app
    monkey.patch_all()
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 1142, in patch_all
    patch_ssl(_warnings=_warnings, _first_time=first_time)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 183, in ignores
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 939, in patch_ssl
    gevent_mod, _ = _patch_module('ssl', _warnings=_warnings)
  File "/usr/lib/python3.9/site-packages/gevent/monkey.py", line 400, in _patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/usr/lib/python3.9/site-packages/gevent/ssl.py", line 32, in <module>
    from gevent import _ssl3 as _source # pragma: no cover
  File "/usr/lib/python3.9/site-packages/gevent/_ssl3.py", line 171, in <module>
    class SSLSocket(socket):
  File "/usr/lib/python3.9/site-packages/gevent/_ssl3.py", line 184, in SSLSocket
    family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None,
NameError: name 'AF_INET' is not defined

```

**Comment by jamadden** [comment]
I can't reproduce this:
```console
$ python --version && python -c 'from gevent.ssl import AF_INET; print(AF_INET)'
Python 3.9.4
AddressFamily.AF_INET
```

There is a simple static import for `AF_INET` that was added for Python 3.9 support: https://github.com/gevent/gevent/blob/f567d6bca7a4bba5e42c6cd463ae3cf8efb549a8/src/gevent/_ssl3.py#L33-L38

Are you certain you're using a version of gevent that supports Python 3.9?

**Comment by jamadden** [comment]
Based on the line numbers in your traceback, it looks like you're using gevent 20.5.2 or older. 

gevent 20.6 and newer is required for Python 3.9 support.

**Comment by jeffin-ntx** [comment]
sorry about that , Thanks @jamadden For the quick turn around , Appreciate the support 👍  Good day

**Comment by jeffin-ntx** [comment]
@jamadden I think -> The version is 21.1.2 



2021-04-19 10:37:14 6d0c80461f5d canaveral_build_tools.core.utils[14324] INFO Collecting gevent (from -r services/ags/requirements.txt (line 7))
2021-04-19 10:37:16 6d0c80461f5d canaveral_build_tools.core.utils[14324] INFO Downloading https://files.pythonhosted.org/packages/0b/50/1b1175ea3a269b5fa3f0f7fed11149888180695bef5fbf568adbb196efaf/gevent-21.1.2.tar.gz (5.9MB)
2021-04-19 10:37:18 6d0c80461f5d canaveral_build_tools.core.utils[14324] INFO I


![Uploading Screenshot 2021-04-19 at 4.55.17 PM.png…]()

**Comment by jamadden** [comment]
It can't be. The line numbers are wrong. I don't know what build tool you're using or your system, but perhaps you have one version installed in `site-packages` and another version installed somewhere else.

**Comment by jamadden** [comment]
Your traceback says:
```python traceback
  File "/usr/lib/python3.9/site-packages/gevent/_ssl3.py", line 184, in SSLSocket
    family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None,
```
This is line 184 in 21.1.2; it doesn't match:
https://github.com/gevent/gevent/blob/f567d6bca7a4bba5e42c6cd463ae3cf8efb549a8/src/gevent/_ssl3.py#L184

This is line 184 in 20.5.2; it *does* match:
https://github.com/gevent/gevent/blob/bd3673d44dbc42b6b25847237efe860e44a083fb/src/gevent/_ssl3.py#L184

In between those versions, support for Python 3.9 was added.

**Comment by jeffin-ntx** [comment]
Thanks for digging , let's see what is the issue now from machine side

**Comment by jeffin-ntx** [comment]
Ok @jamadden You were right The version was old 

<img width="719" alt="Screenshot 2021-04-19 at 10 27 11 PM" src="https://user-images.githubusercontent.com/59605042/115274556-6d703500-a15e-11eb-871d-f3cb27f38d86.png">

**Comment by jeffin-ntx** [comment]
But Trying to install gives this error 

```
Requirement already satisfied: greenlet>=0.4.14 in /usr/lib/python3.9/site-packages (from gevent) (1.0.0)
/ # pip install gevent
Requirement already satisfied: gevent in /usr/lib/python3.9/site-packages (1.5.0)
Requirement already satisfied: greenlet>=0.4.14 in /usr/lib/python3.9/site-packages (from gevent) (1.0.0)
/ # pip install gevent==20.6.0
Collecting gevent==20.6.0
  Downloading gevent-20.6.0.tar.gz (5.8 MB)
     |████████████████████████████████| 5.8 MB 14.3 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-fr37r5ts/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.16 ; platform_python_implementation == '"'"'CPython'"'"''
       cwd: None
  Complete output (202 lines):
  Collecting setuptools>=40.8.0
    Using cached setuptools-56.0.0-py3-none-any.whl (784 kB)
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting Cython>=3.0a5
    Using cached Cython-3.0a6-py2.py3-none-any.whl (1.0 MB)
  Collecting cffi>=1.12.3
    Using cached cffi-1.14.5-cp39-cp39-linux_x86_64.whl
  Collecting greenlet>=0.4.16
    Using cached greenlet-1.0.0.tar.gz (84 kB)
  Collecting pycparser
    Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Building wheels for collected packages: greenlet
    Building wheel for greenlet (setup.py): started
    Building wheel for greenlet (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-j20ac7tl
         cwd: /tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/
    Complete output (85 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/greenlet
    copying src/greenlet/__init__.py -> build/lib.linux-x86_64-3.9/greenlet
    creating build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/__init__.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_contextvars.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_cpp.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_extension_interface.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_gc.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_generator.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_generator_nested.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_greenlet.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_leaks.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_stack_saved.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_throw.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_tracing.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_version.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/test_weakref.py -> build/lib.linux-x86_64-3.9/greenlet/tests
    running egg_info
    writing src/greenlet.egg-info/PKG-INFO
    writing dependency_links to src/greenlet.egg-info/dependency_links.txt
    writing requirements to src/greenlet.egg-info/requires.txt
    writing top-level names to src/greenlet.egg-info/top_level.txt
    adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
    adding license file 'LICENSE.PSF' (matched pattern 'LICEN[CS]E*')
    adding license file 'AUTHORS' (matched pattern 'AUTHORS*')
    reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no files found matching '*.py' under directory 'appveyor'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found anywhere in distribution
    writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
    copying src/greenlet/greenlet.c -> build/lib.linux-x86_64-3.9/greenlet
    copying src/greenlet/greenlet.h -> build/lib.linux-x86_64-3.9/greenlet
    copying src/greenlet/slp_platformselect.h -> build/lib.linux-x86_64-3.9/greenlet
    creating build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_mips_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_s390_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x32_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x86_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
    copying src/greenlet/tests/_test_extension.c -> build/lib.linux-x86_64-3.9/greenlet/tests
    copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.linux-x86_64-3.9/greenlet/tests
    running build_ext
    building 'greenlet._greenlet' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/src
    creating build/temp.linux-x86_64-3.9/src/greenlet
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.linux-x86_64-3.9/src/greenlet/greenlet.o
    gcc -shared -Wl,--as-needed -fno-semantic-interposition -Wl,--as-needed -fno-semantic-interposition build/temp.linux-x86_64-3.9/src/greenlet/greenlet.o -L/usr/lib -o build/lib.linux-x86_64-3.9/greenlet/_greenlet.cpython-39-x86_64-linux-musl.so
    building 'greenlet.tests._test_extension' extension
    creating build/temp.linux-x86_64-3.9/src/greenlet/tests
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/greenlet/ -I/usr/include/python3.9 -c src/greenlet/tests/_test_extension.c -o build/temp.linux-x86_64-3.9/src/greenlet/tests/_test_extension.o
    gcc -shared -Wl,--as-needed -fno-semantic-interposition -Wl,--as-needed -fno-semantic-interposition build/temp.linux-x86_64-3.9/src/greenlet/tests/_test_extension.o -L/usr/lib -o build/lib.linux-x86_64-3.9/greenlet/tests/_test_extension.cpython-39-x86_64-linux-musl.so
    building 'greenlet.tests._test_extension_cpp' extension
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/greenlet/ -I/usr/include/python3.9 -c src/greenlet/tests/_test_extension_cpp.cpp -o build/temp.linux-x86_64-3.9/src/greenlet/tests/_test_extension_cpp.o
    gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
    ERROR: Failed building wheel for greenlet
    Running setup.py clean for greenlet
  Failed to build greenlet
  Installing collected packages: pycparser, wheel, setuptools, greenlet, Cython, cffi
      Running setup.py install for greenlet: started
      Running setup.py install for greenlet: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-utmmlvn3/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-fr37r5ts/overlay --compile --install-headers /tmp/pip-build-env-fr37r5ts/overlay/include/python3.9/greenlet
           cwd: /tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/
      Complete output (85 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/greenlet
      copying src/greenlet/__init__.py -> build/lib.linux-x86_64-3.9/greenlet
      creating build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/__init__.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_contextvars.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_cpp.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_extension_interface.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_gc.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_generator.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_generator_nested.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_greenlet.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_leaks.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_stack_saved.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_throw.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_tracing.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_version.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/test_weakref.py -> build/lib.linux-x86_64-3.9/greenlet/tests
      running egg_info
      writing src/greenlet.egg-info/PKG-INFO
      writing dependency_links to src/greenlet.egg-info/dependency_links.txt
      writing requirements to src/greenlet.egg-info/requires.txt
      writing top-level names to src/greenlet.egg-info/top_level.txt
      adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
      adding license file 'LICENSE.PSF' (matched pattern 'LICEN[CS]E*')
      adding license file 'AUTHORS' (matched pattern 'AUTHORS*')
      reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs/_build'
      warning: no files found matching '*.py' under directory 'appveyor'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '.coverage' found anywhere in distribution
      writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
      copying src/greenlet/greenlet.c -> build/lib.linux-x86_64-3.9/greenlet
      copying src/greenlet/greenlet.h -> build/lib.linux-x86_64-3.9/greenlet
      copying src/greenlet/slp_platformselect.h -> build/lib.linux-x86_64-3.9/greenlet
      creating build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_mips_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_s390_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_x32_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/platform/switch_x86_unix.h -> build/lib.linux-x86_64-3.9/greenlet/platform
      copying src/greenlet/tests/_test_extension.c -> build/lib.linux-x86_64-3.9/greenlet/tests
      copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.linux-x86_64-3.9/greenlet/tests
      running build_ext
      building 'greenlet._greenlet' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/src
      creating build/temp.linux-x86_64-3.9/src/greenlet
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.linux-x86_64-3.9/src/greenlet/greenlet.o
      gcc -shared -Wl,--as-needed -fno-semantic-interposition -Wl,--as-needed -fno-semantic-interposition build/temp.linux-x86_64-3.9/src/greenlet/greenlet.o -L/usr/lib -o build/lib.linux-x86_64-3.9/greenlet/_greenlet.cpython-39-x86_64-linux-musl.so
      building 'greenlet.tests._test_extension' extension
      creating build/temp.linux-x86_64-3.9/src/greenlet/tests
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/greenlet/ -I/usr/include/python3.9 -c src/greenlet/tests/_test_extension.c -o build/temp.linux-x86_64-3.9/src/greenlet/tests/_test_extension.o
      gcc -shared -Wl,--as-needed -fno-semantic-interposition -Wl,--as-needed -fno-semantic-interposition build/temp.linux-x86_64-3.9/src/greenlet/tests/_test_extension.o -L/usr/lib -o build/lib.linux-x86_64-3.9/greenlet/tests/_test_extension.cpython-39-x86_64-linux-musl.so
      building 'greenlet.tests._test_extension_cpp' extension
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -Isrc/greenlet/ -I/usr/include/python3.9 -c src/greenlet/tests/_test_extension_cpp.cpp -o build/temp.linux-x86_64-3.9/src/greenlet/tests/_test_extension_cpp.o
      gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rbl8ytcn/greenlet_6103dd2d2d7c43dbbf8ab9e95ac02810/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-utmmlvn3/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-fr37r5ts/overlay --compile --install-headers /tmp/pip-build-env-fr37r5ts/overlay/include/python3.9/greenlet Check the logs for full command output.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7a/e3/2aeb06b0fad51fd99a4ae401b704e7976b20d9b477d5ef88c53a00f24114/gevent-20.6.0.tar.gz#sha256=51cab8f792961a75da39452586bb3474eaa1607ab2c83398745ef1b9ba09cb92 (from https://pypi.org/simple/gevent/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-fr37r5ts/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.16 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement gevent==20.6.0
ERROR: No matching distribution found for gevent==20.6.0

```
