### ISSUE TITLE
Monkey patching gives random error when trying to get POST data

### ISSUE THREAD

**Issue by oriolcmp** [gevent/gevent#1791]
* gevent version: 21.1.2 From PyPI
* Python version: Python 3.8.5
* Operating System: CentOS Linux 7 (Core)

### Description:

I'm trying to use multithreading in our REST API service and sometimes(1 or 2 times per day) we get the error below in one of the requests to our service. It seems that the data from the POST request is not available

```python-traceback
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/local/lib/python3.8/site-packages/flask_basicauth.py", line 108, in wrapper
     return view_func(*args, **kwargs)
   File "/repo/api/app.py", line 252, in chatbot_answer
   File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 116, in get_json
     data = self._get_data_for_json(cache=cache)
   File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 85, in _get_data_for_json
     return self.get_data(cache=cache)
   File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/base_request.py", line 457, in get_data
     rv = self.stream.read()
   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 320, in read
     return self._do_read(length)
   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 199, in _do_read
     raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
 OSError: unexpected end of file while reading request at position 0
```

### What I've run:

```python
import gevent.monkey
gevent.monkey.patch_all()
from flask import Flask, jsonify, request, make_response, render_template
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

............

@app.route('/api/chatbot-answer', methods=['POST'], strict_slashes=False)
@basic_auth.required
def chatbot_answer():
  

    query_data = request.get_json()

........
```

**Comment by jamadden** [comment]
That would be the *sender* prematurely closing a chunked request. It shouldn't have anything to do with gevent on the server.
