### ISSUE TITLE
Unable to build gevent in aws codebuild agents. Help identify the poblem

### ISSUE THREAD

**Issue by KursLabIgor** [gevent/gevent#1799]
* gevent version: gevent==21.1.2 installed via pip
* Python version: python:3.7-alpine docker image
* Operating System: python:3.7-alpine

### Description:

Unable to build gevent when run build on aws codebuild agent. Builds fine locally. For me unclear how come. Also created ticket to AWS support.

### Stack trace

```python-traceback

running build_ext
--
generating cffi module 'build/temp.linux-x86_64-3.7/gevent.libuv._corecffi.c'
creating build/temp.linux-x86_64-3.7
Running '(cd  "/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136
config.status: error: in `/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/deps/libev':
config.status: error: Something went wrong bootstrapping makefile fragments
for automatic dependency tracking.  Try re-running configure with the
'--disable-dependency-tracking' option to at least be able to build
the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
main()
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 205, in build_wheel
metadata_directory)
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
wheel_directory, config_settings)
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
self.run_setup()
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
self).run_setup(setup_script=setup_script)
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
exec(compile(code, __file__, 'exec'), locals())
File "setup.py", line 479, in <module>
run_setup(EXT_MODULES)
File "setup.py", line 463, in run_setup
"signal_os_incompat = gevent.monkey:_subscribe_signal_os",
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
self.run_command('build')
File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 143, in run
ext.sources[0] = make_mod(self.build_temp, pre_run)
File "/tmp/pip-build-env-_7wi_zvn/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 128, in make_mod
pre_run(ext, ffi)
File "/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/_setuputils.py", line 364, in pre_run
action()
File "/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/_setuplibev.py", line 55, in configure_libev
system(libev_configure_command)
File "/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/_setuputils.py", line 195, in system
if _system(cmd, cwd=cwd, env=env, **kwargs):
File "/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/_setuputils.py", line 191, in _system
return check_call(cmd, cwd=cwd, env=env, **kwargs)
File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/tmp/pip-install-fw15y3vy/gevent_27411c98f48148e38e31acc7df88a136/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1.
----------------------------------------
[0m[91m  ERROR: Failed building wheel for gevent


```

### What I've run:

```docker
FROM python:3.7-alpine

RUN mkdir /cb_f
WORKDIR /cb_f

ENV PYTHONPATH "${PYTHONPATH}:/cb_f"
RUN \
 apk add --no-cache postgresql-libs bash supervisor && \
     apk add --no-cache --virtual .build-deps gcc libc-dev g++ postgresql-dev python3-dev libffi-dev musl-dev make build-base git alpine-sdk automake autoconf
RUN apk add libtool
ADD requirements.txt /cb_f/
RUN pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps
ADD configs/supervisord.conf /etc/
ADD configs/supervisord_2.conf /etc/
ADD configs/supervisord_3.conf /etc/
COPY . /cb_f/
EXPOSE 5000

```

**Comment by advance512** [comment]
We are facing the same issue. Started today. 

Might be related:
https://github.com/gevent/gevent/issues/1605
Their suggested fix:
> In you Dockerfile add the line
`RUN pip3 install -U pip`
> before installing your requirements.txt to bring it up to date.

**Comment by 99ACA** [comment]
try to get the previous version of alpine or apk add make

**Comment by advance512** [comment]
@jamadden 
any clue what this is?

**Comment by KursLabIgor** [comment]
> try to get the previous version of alpine or add `apk add make`

I already have this dependency. no luck. 10x

**Comment by KursLabIgor** [comment]
> RUN pip3 install -U pip

this also no luck.

**Comment by 99ACA** [comment]
> > try to get the previous version of alpine or add `apk add make`
> 
> I already have this dependency. no luck. 10x

The last commit change the python version https://github.com/docker-library/python/commit/0c29e9cf700253291c7f2327537cb1d65f14a428

**Comment by KursLabIgor** [comment]
moved to python:3.6.13-alpine also no luck

**Comment by 99ACA** [comment]
[See the current bug in pip](https://pip.pypa.io/en/stable/news/)
So probably the solution will be to install the previous version of pip

**Comment by KursLabIgor** [comment]
I've checked on both images Ubuntu and amazon linux, both gives same result. For me still no clear which part causes this issue. 
also back to python:3.7.10-alpine no luck...

i'll try to remove pip from base image and install some older version as suggest @99ACA

**Comment by 99ACA** [comment]
Can you check the version?

בתאריך יום ד׳, 30 ביוני 2021, 10:25, מאת Igor ***@***.***>:

**Comment by KursLabIgor** [comment]
Ok, problem solved after move to python:3.7.8-alpine. In this image pip 20.2.2 version works fine on AWS and build fixed.
@99ACA  thank you that point me in right directions.
thanks that help me here.

**Comment by ArnaudHeywear** [comment]
i had the same kind of issue in my builds on CircleCI, using python:3.8-alpine. Switching to python:3.8-alpine3.11 fixed it.

**Comment by andersoncontreira** [comment]
I solved my problem decreasing the version of the python from 3.8 to 3.7 like @ArnaudHeywear

**Comment by s-kovacevic** [comment]
Is there a solution for this that does not require downgrading alpine image? I need python 3.9. Tried many different combinations of gevent/pip/3.9-alpine versions, nothing worked...
