### ISSUE TITLE
Make gevent play nice with packagers like py2exe, cx_freeze and bb-freeze

### ISSUE THREAD

**Issue by martdi** [gevent/gevent#181]
gevent does not work well with packagers like cx_freeze, py2exe and bb-freeze. With the following sample script:

```
from gevent import monkey
monkey.patch_socket()

import urllib2
print urllib2.urlopen("http://www.google.com/").read()
```
# bb-freeze

running: 

```
bb-freeze test.py
dist\test.exe
```

outputs:

```
Failed to import set_exc_info: cannot import name get_hub
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__test__.py", line 6, in <module>
  File "urllib2.py", line 126, in urlopen
  File "urllib2.py", line 394, in open
  File "urllib2.py", line 412, in _open
  File "urllib2.py", line 372, in _call_chain
  File "urllib2.py", line 1199, in http_open
  File "urllib2.py", line 1168, in do_open
  File "httplib.py", line 955, in request
  File "httplib.py", line 989, in _send_request
  File "httplib.py", line 951, in endheaders
  File "httplib.py", line 811, in _send_output
  File "httplib.py", line 773, in send
  File "httplib.py", line 754, in connect
  File "gevent/socket.py", line 592, in create_connection
  File "gevent/socket.py", line 643, in getaddrinfo
  File "gevent/hub.py", line 206, in get_hub
  File "gevent/hub.py", line 312, in __init__
  File "gevent/hub.py", line 242, in _import
  File "gevent/hub.py", line 254, in _import
ImportError: No module named core
```
# cx_freeze

running:

```
cxfreeze test.py
dist\test.py
```

outputs:

```
Failed to import set_exc_info: cannot import name get_hub
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
    exec code in m.__dict__
  File "test.py", line 6, in <module>
    print urllib2.urlopen("http://www.google.com/").read()
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 394, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 412, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1168, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\lib\httplib.py", line 955, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 989, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 811, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 773, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\site-packages\gevent\socket.py", line 592, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python27\lib\site-packages\gevent\socket.py", line 643, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 206, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 312, in __init__
    loop_class = _import(self.loop_class)
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 242, in _import
    return _import(path[-1])
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 254, in _import
    x = __import__(module)
ImportError: No module named core
```

**Aditionnal infos**

when freezing, cx_freeze complains about missing modules:

```
Missing modules:
? _thread imported from gevent.hub
? py.magic imported from gevent.hub
? queue imported from gevent.queue
```
# py2exe

with the following setup.py script: 

```
from distutils.core import setup
import py2exe

setup(console=["test.py"])
```

running:

```
setup.py py2exe
dist\test.exe
```

outputs:

```
Failed to import set_exc_info: cannot import name get_hub
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print urllib2.urlopen("http://www.google.com/").read()
  File "urllib2.pyc", line 126, in urlopen
  File "urllib2.pyc", line 394, in open
  File "urllib2.pyc", line 412, in _open
  File "urllib2.pyc", line 372, in _call_chain
  File "urllib2.pyc", line 1199, in http_open
  File "urllib2.pyc", line 1168, in do_open
  File "httplib.pyc", line 955, in request
  File "httplib.pyc", line 989, in _send_request
  File "httplib.pyc", line 951, in endheaders
  File "httplib.pyc", line 811, in _send_output
  File "httplib.pyc", line 773, in send
  File "httplib.pyc", line 754, in connect
  File "gevent\socket.pyc", line 592, in create_connection
  File "gevent\socket.pyc", line 643, in getaddrinfo
  File "gevent\hub.pyc", line 206, in get_hub
  File "gevent\hub.pyc", line 312, in __init__
  File "gevent\hub.pyc", line 242, in _import
  File "gevent\hub.pyc", line 254, in _import
ImportError: No module named core
```

**Aditionnal infos**

when building the package, py2exe complains about the following missing modules:

```
The following modules appear to be missing
['_scproxy', '_thread', 'py.magic', 'queue']
```

**Comment by AndCycle** [comment]
well, this issue have to be redo again as current version of gevent add quite a lot of new module
