### ISSUE TITLE
Gevent monkey.patch_all() hangs my application

### ISSUE THREAD

**Issue by amks1** [gevent/gevent#1812]
* gevent version: v21.8.0 (Installed using `pip install gevent`
* Python version: v3.8.5 downloaded from python.org
* Operating System: Windows 10 Home. But issue also persists on production server which is _Ubuntu 20.04.2 LTS (Focal Fossa)_

### Description:

I am building a flask application which uses Flask-SocketIO and Flask-RQ2 which both rely on gevent for concurrency with my configuration. As per the documentation, I am supposed to monkey-patch my code at the very beginning, to ensure proper working. I've implemented this:

```python3
# run.py
from gevent import monkey
monkey.patch_all()

from fmconsole.factory_app import create_app
from fmconsole.factory_utils import socketio

if __name__ == "__main__":
    app = create_app()
    # app.run()
    socketio.run(app, port=5000, debug=False)
```

If I run this and browse to localhost:5000, the expected behavior is that my app launches. However, the page continuously shows as loading, and never completes loading. There is nothing in the browser console, there is no traceback. 

![image](https://user-images.githubusercontent.com/68153785/129256446-cabc869f-4c7b-4e49-a6c4-c6b7e7c66519.png)

### How I make it work:

Now, if I change the above code as follows (just added the `thread=False` argument):
```python3
# run.py
from gevent import monkey
monkey.patch_all(thread=False)

from fmconsole.factory_app import create_app
from fmconsole.factory_utils import socketio

if __name__ == "__main__":
    app = create_app()
    # app.run()
    socketio.run(app, port=5000, debug=False)
```
Then my app works normally and everything loads up really fast. 

However, I get the following runtime errors, especially on some of my workers that share the same code: 
```python-traceback
2021-08-10 10:40:05,575 DEBG 'rq2worker-0' stderr output:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 663, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
greenlet.error: cannot switch to a different thread
```
I am guessing that this is because gevent has not monkey patched threads. Please correct me if I'm wrong.

### Concern:
As of now, I don't find any functionality issues with the code other than the above runtime error. But the application is only under testing now, and I'm afraid that things will break further under load. 
I want monkey patch to patch everything, and it should work normally. How can I bugfix this and resolve it?

**Comment by jamadden** [comment]
Most likely, you have some dependency that gevent *can't* patch and which relies on true threads. These are typically implemented as C extensions. In such cases, the easiest option is usually to find a different implementation of the same functionality (as one example, use `PyMySQL` instead of `mysqlclient`; both implement the DB-ABI standard, but the former is implemented in Python and can be patched by gevent, while the latter is implemented in C and cannot).

To verify this, you'll want to grab a stack shot of where your application is hung. gevent has built-in ways to do this; see [the monitoring documentation](http://www.gevent.org/monitoring.html) for details.

**Comment by amks1** [comment]
@jamadden thanks for the quick response. After going through the link, I feel like I have to use `gevent.util.print_run_info()`, by hooking it to the signal handler. Here's what I did:

```python3
from gevent import monkey
monkey.patch_all()
from gevent import util

import signal
from fmconsole.factory_app import create_app
from fmconsole.factory_utils import socketio


if __name__ == "__main__":
    app = create_app()
    signal.signal(signal.SIGBREAK, util.print_run_info)
    socketio.run(app, port=5000, debug=False)
```

When it hangs, on keyboard interrupt here's the traceback:

```python-traceback
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "src\python\grpcio\grpc\_cython\_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
  File "C:\Users\amks1\Github\fmc\.venv-gevent\lib\site-packages\grpc\_channel.py", line 1258, in channel_spin  
    event = state.channel.next_call_event()
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 491, in grpc._cython.cygrpc.Channel.next_call_event      
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 169, in grpc._cython.cygrpc._next_call_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 163, in grpc._cython.cygrpc._next_call_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/completion_queue.pyx.pxi", line 63, in grpc._cython.cygrpc._latent_event        
  File "src\python\grpcio\grpc\_cython\_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\amks1\Github\fmc\.venv-gevent\lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument
KeyboardInterrupt
2021-08-12T20:44:28Z
Traceback (most recent call last):
  File "C:\Users\amks1\Github\fmc\run.py", line 17, in <module>
    socketio.run(app, port=5000, debug=False)
  File "C:\Users\amks1\Github\fmc\.venv-gevent\lib\site-packages\flask_socketio\__init__.py", line 665, in run  
    self.wsgi_server.serve_forever()
  File "C:\Users\amks1\Github\fmc\.venv-gevent\lib\site-packages\gevent\baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src\\gevent\\event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src\\gevent\\_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src\\gevent\\_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core       
  File "src\\gevent\\_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core       
  File "src\\gevent\\_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src\\gevent\\_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub   
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch     
  File "C:\Users\amks1\Github\fmc\.venv-gevent\lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument
KeyboardInterrupt
```

Am I doing this right?

**Comment by jamadden** [comment]
I just wanted you to enable the blocking monitoring thread; that's just setting an environment variable. But a signal handler will work as well.

grpc has been incompatible with gevent in the past. [In 2016, it was completely incompatible](https://github.com/gevent/gevent/issues/786), though some efforts were made, and eventually in [grpc 1.11 they added a way to work with gevent](https://github.com/grpc/grpc/issues/4629#issuecomment-376962677). I'm not sure what the current status is, so if that last example doesn't work for you,  I'd suggest you check in their repository.

**Comment by amks1** [comment]
@jamadden Thanks a lot! After going through the grpc repo and particularly [this PR](https://github.com/grpc/grpc/pull/14561), I was able to solve my issue by changing my code to the following:

```python3
#run.py
from gevent import monkey
monkey.patch_all()

import grpc._cython.cygrpc
grpc._cython.cygrpc.init_grpc_gevent()

from fmconsole.factory_app import create_app
from fmconsole.factory_utils import socketio

if __name__ == "__main__":
    app = create_app()
    socketio.run(app, port=5000, debug=False)
```

I haven't updated my workers to test for runtime errors, but I daresay they'd be resolved by this.
