### ISSUE TITLE
Gracefully shutdown server when on SIGTERM from docker or kubernetes

### ISSUE THREAD

**Issue by shubhamoli** [gevent/gevent#1817]
* gevent version: gevent==21.1.2 (from PyPI)
* Python version: v3.7.9
* Operating System: Ubuntu (in Docker)

### Description:

We're running a containerised flask app with `gevent` and trying to find a way to gracefully shutdown the `WSGIServer` whenever SIGTERM is sent by either `docker stop ...` or `Kubernetes`.

we couldn't find anything related to this in the docs (are we missing something here?) and so far we've implemented.

```
def term_handler(signum, info):
    server.stop()

server = gevent.wsgi.WSGIServer(('', 80), wsgi_app)
signal.signal(signal.SIGTERM, term_handler)
server.serve_forever()
```

Unfortunately this doesn't seem to work as expected and the app immediately dies (without answering the pending requests)  as soon as we pass the SIGTERM.

are there pointers to look for Graceful shutdown implementation? any help in this regard is highly appreciated.

**Comment by jamadden** [comment]
For full featured servers, I suggest you check out project like  gunicorn.

**Comment by shubhamoli** [comment]
Hi @jamadden,

Thanks for the quick reply.

`gevent` is already the part of most of our microservices and we're very satisfied with whatever it offers. 
Recently in our testing we found out that apps are not terminating gracefully whenever the SIGTERM is sent and that's why we started looking for the solution but couldn't find much in the docs.

Are you implying that `gevent` doesn't have graceful shutdown capabilities?

**Comment by mguijarr** [comment]
@shubhamoli did you try to use `gevent.signal_handler` instead of `signal.signal` ?

With `signal.signal` handler you cannot execute any blocking operation. From your example I guess `server.stop()` is called, but fails.
With `gevent.signal_handler`, the handler is executed in a new greenlet and you can do blocking operations it seems... It is different because it acts at the libev level (assuming you're using the default libev loop).

The following code works as expected:

```python
import gevent
import gevent.monkey
gevent.monkey.patch_all()
import signal
import sys

def term_handler():
    print("SIGTERM !")
    print("sleeping for 1 sec.")
    gevent.sleep(1)
    print("EXITING NOW")
    sys.exit()

gevent.signal_handler(signal.SIGTERM, term_handler)

while True:
        gevent.sleep(30)
```

See:

```
(bliss) [matias@brian dev]$ python test_sigterm.py &
[1] 94562
(bliss) [matias@brian dev]$ kill %1
(bliss) [matias@brian dev]$ SIGTERM !
sleeping for 1 sec.
EXITING NOW

[1]+  Done                    python test_sigterm.py
(bliss) [matias@brian dev]$ 
```

Whereas the `signal.signal` version fails:

```
(bliss) [matias@brian dev]$ python test_sigterm.py &
[1] 94573
(bliss) [matias@brian dev]$ kill %1
SIGTERM !
sleeping for 1 sec.
(bliss) [matias@brian dev]$ Traceback (most recent call last):
  File "test_sigterm.py", line 10, in term_handler
    gevent.sleep(1)
  File "/home/matias/dev/miniconda3/envs/bliss/lib/python3.7/site-packages/gevent/hub.py", line 166, in sleep
    hub.wait(t)
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 68, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

**Comment by shubhamoli** [comment]
Hi @mguijarr 

Thanks for suggesting `gevent.signal_handler()` and now our updated code looks like

```

def main():
    def term_handler():
        print("Received SIGTERM - Gracefully shutting down...")
        server.stop() 
    ...
    ...
    server = gevent.wsgi.WSGIServer(('', 8080), wsgi_app)
    gevent.signal_handler(signal.SIGTERM, term_handler)
    server.serve_forever()

```

but still the problem remains the same whenever the SIGTERM is sent the app immediately stops without answering pending requests

```
[2021-09-03 06:11:52,669] {manage.py:116} INFO - Serving on 8080...

...
...

Received SIGTERM - Gracefully shutting down...
(venv) shubham@build-02 $
```
also on the `curl` side of things
```
curl: (52) Empty reply from server
79f218098b49
[1]+  Exit 52                 curl localhost:8080/api/v1/test
```

Please guide us what are we doing wrong here.

**Comment by mguijarr** [comment]
Well, this is not stackoverflow - maybe you should ask your question over there. It does not seem to be a gevent issue. I admit sometimes github issues are a good way to get in touch with project maintainers and other knowledgeable helpful souls, though (I did a bit the same recently with #1815 ... 🙈 )

"Graceful shutdown" (= closing server socket, but letting living handlers to finish) seems to be already implemented in `stop()` on `WSGIServer` side... 🤔  See http://www.gevent.org/api/gevent.baseserver.html#gevent.baseserver.BaseServer.stop

So, maybe the request you make with curl happens after the server socket is closed ?

**Comment by shubhamoli** [comment]
Hi @mguijarr @jamadden 

Thank you for your responses. It's fine I'll ask this on the Stackoverflow.


>"Graceful shutdown" (= closing server socket, but letting living handlers to finish) seems to be already implemented in stop() on WSGIServer side See http://www.gevent.org/api/gevent.baseserver.html#gevent.baseserver.BaseServer.stop

This part of the code I already read before starting and I'm also expecting the same from my `term_handler`. Since this is not working as expected therefore I decided to create this issue here in Github.

> So, maybe the request you make with curl happens after the server socket is closed ?

We run cURL first (url only has sleep of 5s and then returns 200) and then send the SIGTERM to the app after 1 or 2s but     server immediately stops and doesn't wait for 5s to get response of the cURL.

**Comment by mguijarr** [comment]
> We run cURL first (url only has sleep of 5s and then returns 200) and then send the SIGTERM to the app after 1 or 2s but server immediately stops and doesn't wait for 5s to get response of the cURL.

In your test you should ensure the server received the request - are you 100% sure the request has been handled by the server ?

**Comment by shubhamoli** [comment]
I think server is handling the request properly.

and to verify it I've added a `print('Inside /test, Sleeping for 5s now ...', flush=True)` just before the `time.sleep(5)` inside my `/test` Controller.

```
[2021-09-03 06:11:52,669] {manage.py:116} INFO - Serving on 8080...
...
Inside /test, Sleeping for 5s now ...
Received SIGTERM - Gracefully shutting down...
(venv) shubham@build-02 
```

This `/test` route works fine if I cURL it normally.

**Comment by jgibo** [comment]
I had this issue as well with my kubernetes deployment. When kubernetes terminates the pod, it would always be a ungraceful shutdown no matter the different configurations we tried, and no matter if it appeared that uwsgi was gracefully shutting down. The logs would say it's graceful, but in-flight requests would be disconnected.

The workaround we use is to catch SIGTERM in uwsgi, and do nothing with it! When a pod termination event happens, kubernetes will stop sending traffic to the pod - so in effect by leaving uwsgi running when a SIGTERM is received, it has 30 seconds to finish serving it's current traffic (30 seconds is default kubernetes termination grace period).

You can catch sigterm and do nothing with these uwsgi.ini config options (or pass the equivalent cli options)
```
master = true
hook-master-start = unix_signal:15 stats
```

**Comment by olejorgenb** [comment]
I've concluded that the solution outlined by @jgibo is the simplest way of making this work as well. Strange that gunicorn/nginx or similar doesn't support this out-of-the-box without requiring such cooperation with the server process..
