### ISSUE TITLE
InvalidThreadUseError

### ISSUE THREAD

**Issue by CharlesFr** [gevent/gevent#1834]
I'm getting `InvalidThreadUseError` when making a `wait()` call on an `Event`.

[Here's](https://github.com/ftexchange/ftx/blob/85beb7d3cc452277d9c7b648633ee761f0152851/websocket/client.py#L112) the line where this error happens, can someone point me in the right direction?

```Traceback (most recent call last):
  File "D:\Users\Charles\Documents\dash_plotter.py", line 57, in update_graph_scatter
    perp_order_book = ws_perp.get_orderbook(market='KIN-PERP')
  File "D:\Users\Charles\Documents\ftx_client_ws\client.py", line 95, in get_orderbook
    self.wait_for_orderbook_update(market, 5)
  File "D:\Users\Charles\Documents\ftx_client_ws\client.py", line 112, in wait_for_orderbook_update
    self._orderbook_update_events[market].wait(timeout)
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
    
  File "src/gevent/_abstract_linkable.py", line 509, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
    
  File "src/gevent/_abstract_linkable.py", line 206, in gevent._gevent_c_abstract_linkable.AbstractLinkable._capture_hub
    
gevent.exceptions.InvalidThreadUseError: (<Hub '' at 0x1f35dd95f40 backend=default ptr=<cdata 'struct uv_loop_s *' 0x000001F35DE60030> pending=0 ref=0 callbacks=0 thread_ident=0x740c>, None, <greenlet.greenlet object at 0x000001F35D1E70F0 (otid=0x000001F35FEA1780) current active started main>)```

**Comment by jamadden** [comment]
That's coming from here: https://github.com/gevent/gevent/blob/69f361369400cdc77053a70f3b86c6fa7bf341b3/src/gevent/_abstract_linkable.py#L205-L210

It means that you're trying to use a `gevent.event.Event` from more than one real/native Thread. That's illegal; all gevent objects can only be used by one thread, except in a very few documented cases.

**Comment by CharlesFr** [comment]
Thanks @jamadden are you able to point me to a workaround that'd allow me to call it from my Dash application?

**Comment by CharlesFr** [comment]
Here's more [context ](https://community.plotly.com/t/adding-websocket-call-breaks-application-invalidthreaduseerror/58565)on how the call is initiated, your input is much appreciated!

**Comment by jamadden** [comment]
I don't know anything about dash or the other libraries you're using, but you since you cannot use an `Event` from two different threads, you basically have two options:

1) Don't use multiple threads in an arbitrary way. If libraries you depend on are built to use threads, then you can try [monkey-patching](http://www.gevent.org/api/gevent.monkey.html#module-gevent.monkey) to make them instead use greenlets. Depending on what you are doing, you may also be able to use gevent's thread pool. I would suggest monkey patching as the first choice.
2) OR, if you can't monkey-patch, then you need to use a different way to communicate between your threads. Depending on what you're doing, this can be arbitrarily complicated. At a high level, you might want to use [run_callback_threadsafe()](http://www.gevent.org/api/gevent.hub.html#gevent._interfaces.ILoop.run_callback_threadsafe). At a low level, you might replace your `Events` with [async_](http://www.gevent.org/api/gevent.hub.html#gevent._interfaces.ILoop.async_) watchers.
