### ISSUE TITLE
Using yield creates an error

### ISSUE THREAD

**Issue by JVT038** [gevent/gevent#1849]
* gevent version: Gevent version 21.8.0 from PyPi
* Python version: Python 3.9.8 from python.org
* Operating System: Windows 10

### Description:
I want to use the `yield('Ok')` function to return an acknowledgement from an incoming websocket request.
Instead of yielding the 'Ok' string, it gave me the following error:
```python-traceback
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "path\to\python\lib\site-packages\socketio\server.py", line 730, in _handle_event_internal
    server._send_packet(eio_sid, self.packet_class(
  File "path\to\python\lib\site-packages\socketio\server.py", line 641, in _send_packet      
    encoded_packet = pkt.encode()
  File "path\to\python\lib\site-packages\socketio\packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File "path\to\python\lib\site-packages\flask_socketio\__init__.py", line 227, in dumps     
    return flask_json.dumps(*args, **kwargs)
  File "path\to\python\lib\site-packages\flask\json\__init__.py", line 133, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\JVT038\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\JVT038\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\JVT038\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "path\to\python\lib\site-packages\flask\json\__init__.py", line 57, in default        
    return super().default(o)
  File "C:\Users\JVT038\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
```
My code:
```python
@socketio.on('event')
def download(data):
    yield('OK')
    // rest of the code
```
How do I use the `yield()` function without causing an error? `return` works fine, but I want to send the acknowledgement first, and after acknowledging it, continue the rest of the code. So that's why I'm using yield instead of return.

**Comment by jamadden** [comment]
It's utterly unclear to me why you think this has anything to do with gevent? It's certainly not in the stack trace, and the stack trace does seem to indicate that this is a programmer problem, not a framework problem.

**Comment by JVT038** [comment]
Sorry
