### ISSUE TITLE
Apple M1 Pro failed to install gevent-21.12.0

### ISSUE THREAD

**Issue by droxer** [gevent/gevent#1855]
* gevent version: 21.12.0
* Python version: CPython 3.8.12
* Operating System: Apple M1 Pro Monterey

```
(switchman-zh8LVWEe-py3.8) bash-3.2$ pip install gevent
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting gevent
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c8/18/631398e45c109987f2d8e57f3adda161cc5ff2bd8738ca830c3a2dd41a85/gevent-21.12.0.tar.gz (6.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/feihe/Library/Caches/pypoetry/virtualenvs/switchman-zh8LVWEe-py3.8/bin/python /Users/feihe/Library/Caches/pypoetry/virtualenvs/switchman-zh8LVWEe-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/tmpxcx7hcdj
       cwd: /private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-install-oc9sjecu/gevent_69f73eb273f340979d3352c2ca5b8f54
  Complete output (40 lines):
  Traceback (most recent call last):
    File "/Users/feihe/Library/Caches/pypoetry/virtualenvs/switchman-zh8LVWEe-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/feihe/Library/Caches/pypoetry/virtualenvs/switchman-zh8LVWEe-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/feihe/Library/Caches/pypoetry/virtualenvs/switchman-zh8LVWEe-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 481, in <module>
      run_setup(EXT_MODULES)
    File "setup.py", line 348, in run_setup
      setup(
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
      _setup_distribution = dist = klass(attrs)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 459, in __init__
      _Distribution.__init__(
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
      self.finalize_options()
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 837, in finalize_options
      ep(self)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
      exec(code, glob, glob)
    File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
      ffi = FFI()
    File "/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/cffi/api.py", line 48, in __init__
      import _cffi_backend as backend
  ImportError: dlopen(/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_prep_closure'
```

**Comment by jamadden** [comment]
Thanks for the report. 

```
 import _cffi_backend as backend
  ImportError: dlopen(/private/var/folders/xk/4tpt14zd2yz507x0qs1lh1n80000gn/T/pip-build-env-38vv8g2k/overlay/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_prep_closure'
```

There's a problem with CFFI on your machine. I don't know why it can't find symbols. The only thing I can suggest is that you ask [the CFFI maintainers](https://foss.heptapod.net/pypy/cffi/).
