### ISSUE TITLE
More precision in patching (stop patching x)?

### ISSUE THREAD

**Issue by Pithikos** [gevent/gevent#1862]
* gevent version: 21.12.0
* Python version: 3.9.9
* Operating System: Linux

### Description:

I want to patch only some of the sockets, not all. Is this possible?

Namely I'm working with a 3rd websocket client library in a bigger project and use a websocket server throughout the test-suite on separate threads. Hence I want to avoid patching the servers since I keep getting `cannot switch to a different thread`.

Below is a simplified example:
```
import threading
import logging
import time
from websocket_server import WebsocketServer
import gevent


# TEST SERVER ON SEPARATE THREAD - VANILLA SOCKET
def on_message(client, server, message):
    time.sleep(1)
    server.send_message(client, f"Received: {message} - Response: yes")

server = WebsocketServer(host='127.0.0.1', port=7000, loglevel=logging.INFO)
server.set_fn_message_received(on_message)
server_thread = threading.Thread(target=server.run_forever, daemon=True)
server_thread.start()


# CLIENT - PATCHED SOCKET
from gevent import monkey
monkey.patch_socket()
import websocket
ws = websocket.create_connection("ws://localhost:7000")

def run_task(task):
    print(f"Run task {task}")
    ws.send(str(task))
    result = ws.recv()
    print(f"Finished task {task} @ {time.time()}")


# Run tasks
tasks = []
for i in range(5):
    tasks.append(gevent.spawn(run_task, i))
gevent.joinall(tasks)
```

Output
```python-traceback
INFO:websocket_server.websocket_server:Listening on port 7000 for clients..
INFO:websocket_server.websocket_server:Starting WebsocketServer on main thread.
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 46356)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 284, in handle
    self.read_next_message()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 291, in read_next_message
    b1, b2 = self.read_bytes(2)
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket_server/websocket_server.py", line 287, in read_bytes
    return self.rfile.read(num)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/gevent/_socketcommon.py", line 693, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
greenlet.error: cannot switch to a different thread
----------------------------------------
Traceback (most recent call last):
  File "/home/o/workspace/myproject/myproject/test_gevent_ws_patch.py", line 24, in <module>
    result = ws.recv()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_core.py", line 362, in recv
    opcode, data = self.recv_data()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_abnf.py", line 337, in recv_frame
    self.recv_header()
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_abnf.py", line 293, in recv_header
    header = self.recv_strict(2)
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_abnf.py", line 372, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/home/o/workspace/myproject/myproject/.env/lib/python3.9/site-packages/websocket/_socket.py", line 125, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
```

So it seems that the server gets patched anyway for some reason. Is it possible to be more precise with the patching to avoid this?

Expected output:
```python
INFO:websocket_server.websocket_server:Listening on port 7000 for clients..
INFO:websocket_server.websocket_server:Starting WebsocketServer on main thread.
Run task 0
Run task 1
Run task 2
Run task 3
Run task 4
Finished task 0 @ 1643299572.0827596
Finished task 1 @ 1643299572.0828664
Finished task 2 @ 1643299572.0829055
Finished task 3 @ 1643299572.0829358
Finished task 4 @ 1643299572.082969
```

**Comment by jamadden** [comment]
Possibly the simple solution to "cannot switch to a different thread" is to just use `monkey.patch_all()` instead of just `monkey.patch_socket()`. That way the process uses greenlets instead of threads and this should go away.

The preferred solution to "but I only want some XXX to be cooperative" is to import the gevent apis directly. `from gevent import socket` instead of `import socket`. 

You can *try* monkey patching the modules that create the sockets you care about directly (`import x; x.socket = gevent.socket` or if `x` does `from socket import socket, create_connection` you'd do `import x; x.socket = gevent.socket.socket; x.create_connection = gevent.socket.create_connection`). That may or may not resolve your issue.

(There is internal-only experimental code in gevent that tries to import a single package with monkey-patches active, but if you know directly what is creating the sockets, patching as above is probably better.)
