### ISSUE TITLE
Popen stall in ThreadPoolEecutor under docker

### ISSUE THREAD

**Issue by horpto** [gevent/gevent#1865]
* gevent version:
21.12.0, wheels from pypi
* Python version: python 3.10.2
* Operating System: docker image [3.10.2-slim-bullseye](https://github.com/docker-library/python/blob/e0dacc4c580f4ad0aa68136789add4e37bdaab91/3.10/slim-bullseye/Dockerfile)

### Description:

Hi, the problem appears suddenly today. Build stage has stall on `manage.py compilemessages`. `strace` shows only a infinite futex waiting.
Usually it's always worked ok. I don't know why exactly a behaviour is changed. But I found why it is stall.

Simple reproducible example ((not) worked only under docker)

```python
from gevent import monkey
import gevent

if __name__ == '__main__':
    monkey.patch_thread();
    monkey.patch_subprocess();

    import subprocess
    from concurrent.futures import ThreadPoolExecutor

    def func():
        # gevent.sleep(0) # uncomment to fail
        return subprocess.run(["ls", "-l", "/dev/null"], capture_output=True)

    with ThreadPoolExecutor(max_workers=5) as executor:
        fut = executor.submit(func)
        print(fut.result())
```

This code will stall, but ctr+c give traceback:

```python-traceback
^CException ignored in: <built-in method acquire of _thread.lock object at 0x7f1af2ab8800>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gevent/os.py", line 431, in fork_and_watch
    pid = fork()
KeyboardInterrupt:
Traceback (most recent call last):
  File "/var/www/cabinet/test.py", line 16, in <module>
    fut = executor.submit(func)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 162, in submit
    with self._shutdown_lock, _global_shutdown_lock:
RuntimeError: release unlocked lock
```

If uncomment sleep in `func` all works fine. So problem occurs due to the code is not concurrent really. 
`ThreadPoolExecutor` acquires a several locks in [submit](https://github.com/python/cpython/blob/3.10/Lib/concurrent/futures/thread.py#L162). CPython calls a some handlers before `fork`  [here](https://github.com/python/cpython/blob/3.10/Modules/posixmodule.c#L574). Particularly `concurrent.futures.thread` sets [one](https://github.com/python/cpython/blob/3.10/Lib/concurrent/futures/thread.py#L41). As the code are not runned concurrently and `_global_shutdown_lock` is the simple Lock, not RLock, so it will be deadlocked.

**Comment by maciejp-ro** [comment]
@horpto which version of `setuptools` do you have in your system? If it's newer than 60.6.0, can you try downgrading to 60.6.0 and checking if it helps?

I'm debugging a mysterious freeze with uwsgi/django/gevent, which looked similar and started occuring on Feb 4 with setuptools 60.7.0 or 60.7.1 and pinning setuptools 60.6.0 has helped. I don't have any explanation or theory, but the description and timeline sounds similar enough to ask about it.

**Comment by horpto** [comment]
Thanks, I have exactly setuptools==60.7.1
I think something cythonized is not imported correctly and python version is not correct.

**Comment by maciejp-ro** [comment]
Update: this is not _only_ setuptools+gevent. In fresh `python:3.9` container with only `gevent` installed and `setuptools` upgraded, the snippet does not freeze. With our application's dependencies installed, it freezes. I'll post an update if I find anything interesting.

**Comment by arcivanov** [comment]
@maciejp-ro Setuptools have recently changed vendorization import loader so it might have affected what modules are being loaded and in what order.

**Comment by maciejp-ro** [comment]
> Update: this is not _only_ setuptools+gevent. In fresh `python:3.9` container with only `gevent` installed and `setuptools` upgraded, the snippet does not freeze. With our application's dependencies installed, it freezes. I'll post an update if I find anything interesting.

Please disregard, I was wrong – I just reproduced on empty `python:3.9` container:

```Dockerfile
FROM python:3.9-slim
RUN pip install -U setuptools gevent
ADD test.py . # <- reproduction script from this issue
```

**Comment by horpto** [comment]
Anyway setuptools has only one interesting commit: https://github.com/pypa/setuptools/pull/3070

**Comment by maciejp-ro** [comment]
https://gist.github.com/maciejp-ro/0b6c3bfca3c452d85c65b4dae319c821 <- diff of `python -v` output of the test script, the ordering has changed indeed.

**Comment by maciejp-ro** [comment]
I have also reproduced it without Docker, in a native MacOS virtualenv – `pip install -U setuptools` will make it freeze outside of container.

**Comment by horpto** [comment]
@maciejp-ro setuptools with version 60.7.0 has another interesting PR: https://github.com/pypa/setuptools/pull/3061.
it vendors some other libs.  Problem is here with module more_itertools.   [line](https://github.com/pypa/setuptools/blob/main/pkg_resources/_vendor/more_itertools/more.py#L5). More itertools too far import concurrent.futures.threading. My [diff](https://gist.github.com/horpto/073dd5882ea2e99c15ba9c3c02536d57) confirmed it. It's a first different imports from bad and good logs.

**Comment by maciejp-ro** [comment]
The following patch fixes the freeze, but it uses `importlib.metadata`, which was added in Python 3.8. [There is a backport](https://importlib-metadata.readthedocs.io/en/latest/using.html), but I'm not sure I'll be able to properly add and use a conditional dependency now.

```diff
diff --git i/src/gevent/events.py w/src/gevent/events.py
index 08b4e9a9..4b3e127d 100644
--- i/src/gevent/events.py
+++ w/src/gevent/events.py
@@ -63,6 +63,7 @@ __all__ = [

 # pylint:disable=no-self-argument,inherit-non-class
 import platform
+from importlib.metadata import entry_points

 from zope.interface import Interface
 from zope.interface import Attribute
@@ -71,8 +72,6 @@ from zope.interface import implementer
 from zope.event import subscribers
 from zope.event import notify

-from pkg_resources import iter_entry_points
-
 #: Applications may register for notification of events by appending a
 #: callable to the ``subscribers`` list.
 #:
@@ -100,7 +99,7 @@ finally:

 def notify_and_call_entry_points(event):
     notify(event)
-    for plugin in iter_entry_points(event.ENTRY_POINT_NAME):
+    for plugin in entry_points(group=event.ENTRY_POINT_NAME):
         subscriber = plugin.load()
         subscriber(event)

```

**Comment by arcivanov** [comment]
I think it's actually a bug in gevent itself. Patch threading is supposed to patch existing locks as well. That is, importing threading prior to patching should not have caused this.

**Comment by arcivanov** [comment]
> I think the best solution would be to change the way that new greenlet is scheduled. But a simpler solution could be to manually replace _global_shutdown_lock with a gevent-friendly lock.

And then also replace/reregister the `register_at_fork` function references.

**Comment by jamadden** [comment]
> And then also replace/reregister the register_at_fork function references.

I'm not sure that's necessary. 

The old registrations won't hurt, because the lock will never be acquired. 

The new gevent-friendly lock won't have the same issue that native locks do. The existing registrations are there because only one native thread survives a fork, and if it was some other thread that was holding the lock, then the process can hang (because the lock will never be released). But *all* greenlets survive a fork and keep running, so eventually the lock should be released. (That, BTW, is why one has to be careful forking subprocesses and using cooperative APIs in them.)

**Comment by horpto** [comment]
> I think the best solution would be to change the way that new greenlet is schedule

Thanks, I've thought about it. it should be the most reliable solution. But doesn't it have a performance loss?

**Comment by jamadden** [comment]
It may or may not be the most reliable solution — generally, things that rely on specific switching orders aren't that reliable. That was a very hand-wavy comment, and I haven't looked far enough into what was allowing triggering the switch to the other greenlet to even know for sure if it's possible. So "best" was a massive overstatement.

Detecting whether `concurent.futures.thread` has been imported at `patch_thread()` time, and if so (and it has the `_global_shutdon_lock`) replacing that lock directly is probably the better way to go.

**Comment by maciejp-ro** [comment]
Setuptools v60.8.2 that doesn't implicitly import threading has been released, this fixes the freeze.

However, `pkg_resources` is deprecated and newer versions of Python include a replacement in stdlib. Setuptools maintainer has suggested a portable solution in https://github.com/pypa/setuptools/issues/3090#issuecomment-1033167013 – I'll draft a PR with that.

**Comment by navytux** [comment]
For the reference: the problem might be reintroduced with CPython >= 3.11.10.

There `importlib.util` started to import `threading` to fix concurrency issue in `LazyLoader`:

https://github.com/python/cpython/commit/46f821d62b5a1599890419aa963d7353619942b6

While setuptools installs finders for editable wheels that do import `importlib.util` at python interpreter startup:

https://github.com/pypa/setuptools/blob/92b45e98/setuptools/command/editable_wheel.py#L786-L790

So when it comes to `gevent.monkey.patch_all()`, even if that is the first statement in the user program, `threading` might be already there pre-imported.

I've originally discovered this problem while testing pygolang because from py3.11.10  gpython started to refuse to start:

```console
(py311-venv) kirr@deca:~/src/tools/go/pygolang-master$ gpython
Traceback (most recent call last):
  File "/home/kirr/src/tools/go/py311-venv/bin/gpython", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kirr/src/tools/go/pygolang-master/gpython/__init__.py", line 368, in main
    raise RuntimeError('gpython: internal error: the following modules are pre-imported, but must be not:'
RuntimeError: gpython: internal error: the following modules are pre-imported, but must be not:

        ['threading']

sys.modules:

        ['__editable___pygolang_0_1_finder', '__future__', '__main__', '_abc', '_codecs', '_collections', '_collections_abc', '_distutils_hack', '_frozen_importlib', '_frozen_importlib_external', '_functools', '_imp', '_io', '_operator', '_signal', '_sitebuiltins', '_sre', '_stat', '_thread', '_warnings', '_weakref', '_weakrefset', 'abc', 'builtins', 'codecs', 'collections', 'contextlib', 'copyreg', 'encodings', 'encodings.aliases', 'encodings.utf_8', 'enum', 'errno', 'fnmatch', 'functools', 'genericpath', 'gpython', 'importlib', 'importlib._abc', 'importlib._bootstrap', 'importlib._bootstrap_external', 'importlib.machinery', 'importlib.util', 'io', 'ipaddress', 'itertools', 'keyword', 'marshal', 'ntpath', 'operator', 'os', 'os.path', 'pathlib', 'posix', 'posixpath', 're', 're._casefix', 're._compiler', 're._constants', 're._parser', 'reprlib', 'site', 'stat', 'sys', 'threading', 'time', 'types', 'urllib', 'urllib.parse', 'warnings', 'zipimport', 'zope']
```

as explained above that `import threading` comes from `__editable___pygolang_0_1_finder` installed by setuptools when doing `pip install -e` in pygolang or any other package:

```console
(py311-venv) kirr@deca:~/src/tools/go/pygolang-master$ python -v -c ''
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
...
import 'posixpath' # <class '_frozen_importlib.FrozenImporter'>
import 'os' # <class '_frozen_importlib.FrozenImporter'>
import '_sitebuiltins' # <class '_frozen_importlib.FrozenImporter'>
Processing global site-packages
Adding directory: '/home/kirr/src/tools/go/py311-venv/lib/python3.11/site-packages'
Processing .pth file: '/home/kirr/src/tools/go/py311-venv/lib/python3.11/site-packages/__editable__.pygolang-0.1.pth'
# /home/kirr/src/tools/go/py311-venv/lib/python3.11/site-packages/__pycache__/__editable___pygolang_0_1_finder.cpython-311.pyc matches /home/kirr/src/tools/go/py311-venv/lib/python3.11/site-packages/__editable___pygolang_0_1_finder.py
# code object from '/home/kirr/src/tools/go/py311-venv/lib/python3.11/site-packages/__pycache__/__editable___pygolang_0_1_finder.cpython-311.pyc'
...
```

---- 8< ---- (`.../site-packages/__editable__.pygolang-0.1.pth`)
```py
import __editable___pygolang_0_1_finder; __editable___pygolang_0_1_finder.install()
```

---- 8< ---- (`.../site-packages/__editable___pygolang_0_1_finder.py`)
```py
import sys
from importlib.machinery import ModuleSpec
from importlib.machinery import all_suffixes as module_suffixes
from importlib.util import spec_from_file_location                    <-- NOTE
from itertools import chain
from pathlib import Path

MAPPING = {'golang': '/home/kirr/src/tools/go/pygolang-master/golang', 'gpython': '/home/kirr/src/tools/go/pygolang-master/gpython'}
NAMESPACES = {}
PATH_PLACEHOLDER = '__editable__.pygolang-0.1.finder' + ".__path_hook__"

...
```

I'm not sure what to do and I do not think cpython will accept

```diff
--- a/Lib/importlib/util.py
+++ b/Lib/importlib/util.py
@@ -15,7 +15,6 @@
 import _imp
 import functools
 import sys
-import threading
 import types
 import warnings
 
@@ -316,7 +315,7 @@ def exec_module(self, module):
         loader_state = {}
         loader_state['__dict__'] = module.__dict__.copy()
         loader_state['__class__'] = module.__class__
-        loader_state['lock'] = threading.RLock()
+        loader_state['lock'] = __import__('threading').RLock()
         loader_state['is_loading'] = False
         module.__spec__.loader_state = loader_state
         module.__class__ = _LazyModule
```

just to please gevent.

/cc @maciejp-ro, @effigies, @jaraco, @brettcannon, @abravalheri

**Comment by navytux** [comment]
It turns out the problem is there not only with editable installs, but also with regular install of any eggs with namespaces. For example `.../site-packages/zope.event-5.0-py3.11-nspkg.pth` contains the following

```py
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('zope',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('zope', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('zope', [os.path.dirname(p)])));m = m or sys.modules.setdefault('zope', types.ModuleType('zope'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
```

which also imports `importlib.util` and is generated by the following setuptools namespacing-support code:

https://github.com/pypa/setuptools/blob/92b45e9817ae829a5ca5a5962313a56b943cad91/setuptools/namespaces.py#L46-L61

**Comment by effigies** [comment]
> I'm not sure what to do and I do not think cpython will accept
> 
> ```diff
> --- a/Lib/importlib/util.py
> +++ b/Lib/importlib/util.py
> @@ -15,7 +15,6 @@
>  import _imp
>  import functools
>  import sys
> -import threading
>  import types
>  import warnings
>  
> @@ -316,7 +315,7 @@ def exec_module(self, module):
>          loader_state = {}
>          loader_state['__dict__'] = module.__dict__.copy()
>          loader_state['__class__'] = module.__class__
> -        loader_state['lock'] = threading.RLock()
> +        loader_state['lock'] = __import__('threading').RLock()
>          loader_state['is_loading'] = False
>          module.__spec__.loader_state = loader_state
>          module.__class__ = _LazyModule
> ```

I had initially proposed importing `threading` locally to the `exec_module` function. IMO it would not be a bad change to avoid unnecessary obligatory imports, but that's not my call.

**Comment by effigies** [comment]
@navytux Is there a minimal example? Installing `zope.event` into a virtual environment with the latest Python alpha and running `python -c 'import zope.event'` did not raise an error.

**Comment by abravalheri** [comment]
Hi @navytux, customising the import machinery behaviour is highly dependant of `importlib.util`.

Some of the implementation options discussed in PEP 660 (which `setuptools` implements) require such level of customisation.

I don't think we can avoid importing that.

**Comment by effigies** [comment]
A hack for this scenario could be:

```Python
import sys
import importlib.util
import gevent

have_threading = 'threading' in sys.modules
if have_threading:
    del sys.modules['threading']

gevent.monkey.patch_all()

if have_threading:
    import threading
```

**Comment by brettcannon** [comment]
FYI the issue was fixed in CPython in `main`/3.14, 3.13, and 3.12 (3.11 is in security mode so it isn't eligible for the tweak and the release manager also reiterated this point for this specific change).

**Comment by navytux** [comment]
@brettcannon, thanks for merging the fix and writing about it back here. This is good to see. Leaving 3.11 in "broken" state, as the breakage was introduced in 3.11.10, is sad though.
