### ISSUE TITLE
Server doesn't close connections when the client doesn't sends explicit "connection: close"

### ISSUE THREAD

**Issue by GiladRi** [gevent/gevent#1866]
* gevent version: "pip install gevent" from pypi.org -->  gevent-21.12.0-cp310-cp310-win_amd64.whl
* Python version: Python 3.10 downloaded from python.org
* Operating System: Windows 10

### Description:

The Gevent doesn't close connections when the client doesn't sends explicit "connection: close". This cause the server to open too many sockets. In Linux server it can appear as "too many open files".

Traceback (most recent call last):
  File "PATH\PycharmProjects\gevent_server\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "PATH\gevent_server\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "PATH\gevent_server\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

### What I've run:

```python
# Server:
from flask import Flask
from gevent.pywsgi import WSGIServer

app = Flask(__name__)


@app.route("/test")
def test():
    print("hi")
    return "Hi!"


if __name__ == '__main__':
    server = WSGIServer(("127.0.0.1", 8080), application=app)
    server.serve_forever()
```

```python
# Client
import requests


for i in range(10_000):
    response = requests.get(url="http://127.0.0.1:8080/test")
    print(response)
```

**Comment by jamadden** [comment]
I suspect the bug is in your client: it's not letting the request be terminated. See [requests's documentation](https://docs.python-requests.org/en/latest/user/advanced/#keep-alive).

> Note that connections are only released back to the pool for reuse once all body data has been read; be sure to either set stream to False or read the content property of the Response object.

**Comment by GiladRi** [comment]
I have a more complex Linux server that serves a real customer, and it happens also there. The solution I found is to override the WSGIHandler like you can see in this source: https://carsonip.me/posts/gevent-pywsgi-http-keep-alive-fd-leak/

**Comment by jamadden** [comment]
Still, the "bug", or at least bad behaviour, would be in the client — depending on your point of view. As noted in the issue you linked to, gevent doesn't do extra timeouts beyond the socket timeout. If the remote client is keeping connections open, they'll stay open; gevent isn't going to shut them down. This can be very beneficial in certain deployment strategies (i.e., with trusted clients; think micro-service architectures). But obviously, you don't want to expose that to the raw internet — as with *most* asynchronous request handlers, you want a proxy in front of it. gunicorn documents this, at least at one time.
