### ISSUE TITLE
Closing a waiting selector from another greenlet results in a TypeError

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#1880]
```
  File "/home/<snip>/lib/python3.10/site-packages/gevent/selectors.py", line 208, in select
    for fd, event in iteritems(self._accumulated_events):
TypeError: descriptor 'items' for 'dict' objects doesn't apply to a 'NoneType' object
```

The issue is as follows:

`selector.close`:
https://github.com/gevent/gevent/blob/5858d226045f701deb8e4b49c03db4cab63053d6/src/gevent/selectors.py#L241

`selector.select`:
https://github.com/gevent/gevent/blob/5858d226045f701deb8e4b49c03db4cab63053d6/src/gevent/selectors.py#L201-L208

**Comment by arcivanov** [comment]
Additionally, closing a selector that has a file registered  and is in a wait never returns from `select()`.

**Comment by arcivanov** [comment]
So, as far as the latter, CPython's behavior is inconsistent in re select-after-close:

```
Python 3.10.4 (main, Mar 28 2022, 17:39:22) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import selectors
>>> s = selectors.SelectSelector()
>>> s.close()
>>> s.select()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arcivanov/.pyenv/versions/3.10.4/lib/python3.10/selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
KeyboardInterrupt
>>> s = selectors.PollSelector()
>>> s.close()
>>> s.select()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arcivanov/.pyenv/versions/3.10.4/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
>>> s = selectors.EpollSelector()
>>> s.close()
>>> s.select()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arcivanov/.pyenv/versions/3.10.4/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
ValueError: I/O operation on closed epoll object
```

The kernel-primitive-based selectors throw an error, while call-based selectors simply disregard the closed status.

**Comment by arcivanov** [comment]
Related: https://github.com/python/cpython/issues/91433
