### ISSUE TITLE
AttributeError: 'gevent.libev.corecext.io' object has no attribute 'active'

### ISSUE THREAD

**Issue by othiman** [gevent/gevent#1884]
* gevent version: 21.12.0, installed via pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
* Python version: 3.10.4, installed via Ubuntu 22.04
* Operating System: Ubuntu 22.04
 
### Description:

Hi,

I updated my system from Ubuntu 21.10 to 22.04 (and therefore from Python 3.9 to 3.10) and now our uwsgi application throws the following traceback very often:

```AttributeError: 'gevent.libev.corecext.io' object has no attribute 'active'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
SystemError: <built-in function uwsgi_gevent_request> returned a result with an exception set
2022-05-05T09:31:14Z <Greenlet at 0x7f8a5a4a8a60: uwsgi_gevent_request(140232338205640)> failed with SystemError

AttributeError: 'gevent.libev.corecext.io' object has no attribute 'active'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 831, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 857, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 846, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
SystemError: <built-in function uwsgi_gevent_request> returned a result with an exception set

```

I am not really sure if this is a gevent problem, but hopefully someone can give me hint where to look at.

If any information is missing to help, please let me know.

Best regards, Thomas

**Comment by othiman** [comment]
After an update to Ubuntu 22.10 the problem is gone.
