### ISSUE TITLE
Mocking for events not working.

### ISSUE THREAD

**Issue by likecs** [gevent/gevent#1888]
I am currently in the process of porting my application from ancient gevent 1.0.1 to gevent 1.5.0 (which is python 2 compatible) before I port my python 2 software to python 3 and upgrade gevent again.

There are unit tests in my software which used to mock threading.Event "wait" or other methods and those used to work with gevent 1.0.1 but break after porting to 1.5.0. I dug a bit into this and found the difference is how event class is implemented across these 2 versions.

In 1.0.1, event inherits from object class whereas in 1.5.0, it inherits from AbstractLinkable which has slots defined. This means when we do `dir` on the Event object, 1.0.1 shows __dict__ but 1.5.0 doesn't show __dict__.

I tried to write the unit test using both mox and mock and the failure in both the cases is bit different.

Code being tested (File name is test.py)
```python
from gevent import monkey
monkey.patch_all()

import threading

def func():
  x = threading.Event()
  x.wait()
  return True
```

Mox based unit test (Mox version is 0.5.3)

```python
from gevent import monkey
monkey.patch_all()

import mox
import threading
import test

def run():
  print "Start"
  m = mox.Mox()
  ev = threading.Event()
  m.StubOutWithMock(ev, "wait")
  m.StubOutWithMock(test.threading, "Event")

  test.threading.Event().AndReturn(ev)
  ev.wait()

  print "Mocked"
  m.ReplayAll()
  test.func()
  print "Called"
  m.VerifyAll()
  print "Verified"
  m.ResetAll()
  print "Done"

if __name__ == "__main__":
  run()
```

The traceback seen is:
```python-traceback
Start
Traceback (most recent call last):
  File "py_test.py", line 28, in <module>
    run()
  File "py_test.py", line 12, in run
    m.StubOutWithMock(ev, "wait")
  File "build/bdist.linux-x86_64/egg/mox.py", line 319, in StubOutWithMock
  File "build/bdist.linux-x86_64/egg/stubout.py", line 120, in Set
AttributeError: 'gevent._event.Event' object has no attribute '__dict__'
```

Mock based unit tests (Mock version 3.0.5)

```python
from gevent import monkey
monkey.patch_all()

import mock
import threading
import test

def run():
  print "Start"
  m = mox.Mox()
  ev = threading.Event()
  t_ev_patch = mock.patch.object(ev, "wait")
  m.StubOutWithMock(test.threading, "Event")

  test.threading.Event().AndReturn(ev)
  t_ev = t_ev_patch.start()
  t_ev.return_value = None

  print "Mocked"
  m.ReplayAll()
  test.func()
  print "Called"
  m.VerifyAll()
  t_ev.stop()
  t_ev.assert_called_once_with()
  print "Verified"
  m.ResetAll()
  print "Done"

if __name__ == "__main__":
  run()
```

Traceback
```python-traceback
Start
Traceback (most recent call last):
  File "py_test.py", line 36, in <module>
    run()
  File "py_test.py", line 21, in run
    t_ev = t_ev_patch.start()
  File "build/bdist.linux-x86_64/egg/mock.py", line 1525, in start
  File "build/bdist.linux-x86_64/egg/mock.py", line 1485, in __enter__
AttributeError: 'gevent._event.Event' object attribute 'wait' is read-only
```

So, I need help in how to apply fixes to gevent 1.5.0 distribution I have locally to build the egg again so that I can mock Event "wait" method again. Note that I don't want to get away from mocking "wait" method since in some cases, I takes a timeout parameter which can be large and I want to validate that correct timeout value was passed instead of adding time.time() based checks in unit  tests or setting the event in a different gevent in the thread. Even if that work, for large timeout and their validation, it significantly increases the test execution time to validate everything works.

**Comment by jamadden** [comment]
There doesn't seem to be a question here, just an observation that things have changed. Your tests will likely need to change too (e.g., replace the entire `Event` *class* instead of trying to override one attribute).

Note that the current release of gevent, 21.12.0, remains Python 2 compatible. I expect the next release I make (as soon as I get time) will also be gevent compatible (but I do expect to drop Python 2 support this year).
