### ISSUE TITLE
Broken multiline log

### ISSUE THREAD

**Issue by pimuzzo** [gevent/gevent#1894]
Hi,
when I use gevent execution pool on Celery, instead of the default one, when an exception occurs it is logged in this way:
```
[2022-06-15 11:14:40,877: WARNING/MainProcess] Traceback (most recent call last):
[2022-06-15 11:14:40,877: WARNING/MainProcess]   File "src/gevent/_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/celery/worker/pidbox.py", line 124, in loop
    raise e
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/celery/worker/pidbox.py", line 118, in loop
    connection.drain_events(timeout=1.0)
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/kombu/connection.py", line 316, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 169, in drain_events
    return connection.drain_events(**kwargs)
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/amqp/connection.py", line 525, in drain_events
    while not self.blocking_read(timeout):
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/amqp/connection.py", line 531, in blocking_read
    return self.on_inbound_frame(frame)
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/amqp/connection.py", line 537, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/amqp/abstract_channel.py", line 156, in dispatch_method
    listener(*args)
[2022-06-15 11:14:40,878: WARNING/MainProcess]   File "/home/pimo/.pyenv/versions/core-3.10.4/lib/python3.10/site-packages/amqp/connection.py", line 667, in _on_close
    raise error_for_code(reply_code, reply_text,
```

What I would like to have is to have only the first line starting with: `[2022-06-15 11:14:40,877: WARNING/MainProcess]`

I think that the line causing this issue is this one:
`traceback.print_exception(t, v, tb, file=errstream) 610 hub.py`

* gevent version: installed from Pypi -> `celery[gevent]==5.2.7`
* Python version: 3.10.4 installed from pyenv

Is there a workaround or is there anything I can do to avoid it?

**Comment by maratkomarov** [comment]
Hey @pimuzzo , it has nothing to do with gevent. Is it celery wraps stdout into a log. You can turn it off https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-redirect-stdouts

**Comment by pimuzzo** [comment]
Thank you @maratkomarov 

I tried setting
```
    worker_redirect_stdouts = False
```
in my Celery config but unluckily the exception is logged in the same way.
If I have any news I will let you know.
