### ISSUE TITLE
AssertionError: AbstractLinkable._notifier is None in _notify_links method

### ISSUE THREAD

**Issue by ronaldnwilliams** [gevent/gevent#1895]
* gevent version: "~21.12.0" pypi
* Python version: python:3.9 from slim-buster docker image
* Operating System: python:3.9-slim-buster docker image

### Description:

Running django 3.2 using gunicorn 20.1. I keep seeing this traceback in my logs from `gevent/_abstract_linkable.py` `assert self._notifier is notifier, (self._notifier, notifier)`. 

```python-traceback
Traceback (most recent call last):
File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
AssertionError: (None, <callback at 0x7f3af9646600 args=([],)>)
```

No other logs surrounding these in the given context.

Is this something to be concerned about or anything I can fix?

### What I've run:
`ddtrace-run gunicorn --workers 5 --worker-class gevent project_name.wsgi:application`

**Comment by dannygoldstein** [comment]
I am also running into this issue

**Comment by dannygoldstein** [comment]
Digging into this a bit more, I've found that when I start my application with

gevent version: "~21.12.0" pypi
Python version: python:3.9 from slim-buster docker image
Operating System: python:3.9-slim-buster docker image

**Comment by dannygoldstein** [comment]
Digging into this a bit more, I've found that when I start my application with

```
ddtrace-run gunicorn -k gevent main:app
```

gevent version: "~21.12.0" pypi
Python version: python:3.9 from slim-buster docker image
Operating System: python:3.9-slim-buster docker image

I see these errors emitted at the beginning

```
Traceback (most recent call last):
File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
AssertionError: (None, <callback at 0x7f3af9646600 args=([],)>)
```

but the server actually does startup and handles http requests in an asynchronous way. I tried load testing this by sending ~1000 requests to an endpoint that `time.sleep()`s for 5 seconds and another that makes an http request to a server that sleeps for five seconds and in both cases all 1000 requests returned in 5 seconds. So it seems like these errors are not actually affecting the performance of the server. This is by no means comprehensive and it may be that certain parts of the library are broken but the ones I tested work. But based on my limited experience it seems that things are still working. It would be great to understand what is causing this error and understand its broader scope

**Comment by jd** [comment]
I don't know why it does this, but I found a workaround for gunicorn which is:
```
diff --git gunicorn/arbiter.py gunicorn/arbiter.py
index 0e705075..aacf883d 100644
--- gunicorn/arbiter.py
+++ gunicorn/arbiter.py
@@ -612,6 +612,7 @@ class Arbiter(object):
         of the master process.
         """

+        time.sleep(0)
         for _ in range(self.num_workers - len(self.WORKERS)):
             self.spawn_worker()
             time.sleep(0.1 * random.random())
```

It does not make much sense to me, but it seems that yielding back the control to the hub prevents this issue from happening.

**Comment by SuperH-0630** [comment]
I am also running into this issue.

**Comment by balanikaran** [comment]
Hey there!

I'm also running into the same issue.
The setup is basically to use `gunicorn` with `gevent` as the worker class with `ddtrace`.
I'm using Python 3.10.6.

Any update on the issue?

**Comment by arfn1366** [comment]
Same problem when I had tried to to  use monkey patch in  `gunicorn` server hook `when_ready`.

**Comment by twall** [comment]
I'm seeing this from `multiprocessing.Process` spawned from a gunicorn process.  The subprocess sometimes dies almost immediately and other times after a little bit of processing (I/O w/redis and/or elasticsearch, mostly).

**Comment by arcivanov** [comment]
`multiprocessing` requires https://github.com/karellen/geventmp to function.

**Comment by Pajinek** [comment]
I have started to receive this error when I upgrade the package gevent from 23.9.1 to  24.2.1 (Python image 3.11.8)

**Comment by salomon-smekecohen** [comment]
Is this related to the `callback` attribute being disallowed in `Gevent` SpawnedLinks?

**Comment by saichander17** [comment]
I noticed that this is happening in alpine image but not happening when I run it natively on m1 mac!

**Comment by dimon222** [comment]
> I noticed that this is happening in alpine image but not happening when I run it natively on m1 mac!

Unfortunately I noticed it even on x86_64 on RHEL9, so likely not Alpine or Apple Silicon related.

**Comment by jamadden** [comment]
This is an interaction between forking, the standard library's (sorta half-hearted) attempts to clean up its locks after forking, and gevent's implementation details. 

Certain standard library modules, notably `logging` (`Handler`), `threading` (`Thread`) and `multiprocessing.queue` (`Queue`), register `at_fork` handlers. These handlers find locks (and similar objects) that they know about and under some circumstances call the private `_at_fork_reinit` method of those objects that was added in Python 3.9 The intent of this method is to try to avoid deadlocks in the child if a thread other than the thread that called `fork` was holding the lock by resetting its internal state. gevent implements this method.

To simplify somewhat, if code was blocked on a lock (or similar) from one of those standard library modules, then obtains that lock and immediately forks, you could run into this issue. This is due to the way gevent handles lock wakeups (and many other things) using callbacks and links; the code after the lock is obtained is actually running in a callback, and the fork may re-init the lock out from under it.

I don't think this scenario is actually possible with `Thread` objects because you would have to have `join`ed the active thread that does the fork.

It's potentially possible with `multiprocessing.queue.Queue`, but it's a very subtle race condition that I'm not sure you can actually produce using greenlets.

It's most easily demonstrated with `logging.Handler`, which takes locks to perform IO:

```python
from gevent import monkey
monkey.patch_all()

from gevent import spawn

import os
from logging import Handler
from threading import Event
handler = Handler()
handler.acquire()

event = Event()

def forker():
    event.set()
    handler.acquire()
    handler.release()
    os.fork()

g = spawn(forker)
event.wait()
handler.release()
g.join()
```

Now that I've finally tracked this down, the fix shouldn't be difficult.
