### ISSUE TITLE
Build error since Cython update

### ISSUE THREAD

**Issue by serl** [gevent/gevent#1899]
* gevent version: 20.9.0 from pip+build
* Python version: 2.9.13
* Operating System: Docker on ARM (Apple Silicon)

### Description:

Probably this is not really an issue we can "solve", but we're experiencing problems since some days and maybe we're not alone, so I'm writing some notes here just in case somebody else stumbles on the same thing.

We're using Odoo 14, which fixes the gevent version to 20.9.0. Everything worked fine until Cython got updated to 3.0.0a11 on July 31. Since then, our builds fail on Apple Silicon.

Here's the minimum to reproduce the issue:

```
$ docker run --rm -ti --platform linux/arm64/v8 python:3.9-bullseye bash

root@2cbc96ab945c:/# pip install gevent==20.9.0
Collecting gevent==20.9.0
  Downloading gevent-20.9.0.tar.gz (5.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 7.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      warning: src/gevent/resolver/cares.pyx:38:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/resolver/cares.pyx:40:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/resolver/cares.pyx:41:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      Compiling src/gevent/resolver/cares.pyx because it changed.
      [1/1] Cythonizing src/gevent/resolver/cares.pyx
      warning: src/gevent/libev/corecext.pyx:325:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:783:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:785:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:787:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:791:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      Compiling src/gevent/libev/corecext.pyx because it changed.
      [1/1] Cythonizing src/gevent/libev/corecext.pyx
      Compiling src/gevent/_greenlet_primitives.py because it changed.
      [1/1] Cythonizing src/gevent/_greenlet_primitives.py
      Compiling src/gevent/_hub_primitives.py because it changed.
      [1/1] Cythonizing src/gevent/_hub_primitives.py
      Compiling src/gevent/_hub_local.py because it changed.
      [1/1] Cythonizing src/gevent/_hub_local.py
      Compiling src/gevent/_waiter.py because it changed.
      [1/1] Cythonizing src/gevent/_waiter.py
      warning: src/gevent/_gevent_cgreenlet.pxd:112:33: Declarations should not be declared inline.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef load_traceback
      cdef Waiter
      cdef wait
      cdef iwait
      cdef reraise
      cpdef GEVENT_CONFIG
            ^
      ------------------------------------------------------------

      src/gevent/_gevent_cgreenlet.pxd:181:6: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      Compiling src/gevent/greenlet.py because it changed.
      [1/1] Cythonizing src/gevent/greenlet.py
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-viwogjfd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-viwogjfd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-viwogjfd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-viwogjfd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 287, in <module>
        File "/tmp/pip-install-ejqz1p_n/gevent_5ef2b56f5de546f9ac8514bf67eb1248/_setuputils.py", line 236, in cythonize1
          new_ext = cythonize(
        File "/tmp/pip-build-env-viwogjfd/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-viwogjfd/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1296, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/greenlet.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

The solution we found is to create a build environment with the right version of Cython:

```
pip install pip setuptools wheel Cython==3.0.0a10
pip install gevent==20.9.0 --no-build-isolation
```

In particular, we're running these lines in a throwaway virtual environment to have the wheel in cache for a latter `pip install` on the right place.

Of course, the latest version of gevent is not impacted, as the right pre-compiled wheel is available to pip.

**Comment by eddisco** [comment]
Also have this issue as of today.  It would be great if there were both x86 and arm wheel files.

**Comment by abristow3** [comment]
Still an issue as of today

**Comment by TTPBruce** [comment]
Still an issue

**Comment by Gromil** [comment]
> Still an issue

using gevent==21.12.0 fixed the problem for me

**Comment by jamadden** [comment]
The previous comment is correct, gevent 20.9 doesn't support re-cythonizing with that new of a version of Cython. You need to use a newer version of gevent or an older version of Cython.

**Comment by lewikabu** [comment]
> pip install gevent==20.9.0 --no-build-isolation

Did this also need you to change the version of greenlet to > 1.1.0 ?

**Comment by miquelmassot** [comment]
Still an issue

**Comment by deepak-ttpl2018** [comment]
Still an issue

**Comment by SalihKalender** [comment]
still an issue
python@3.9.11

**Comment by Lazlo105** [comment]
still an issue

**Comment by victor-chevillotte** [comment]
Still an issue 
python@3.12
