### ISSUE TITLE
Install fails on M1 running Monterey

### ISSUE THREAD

**Issue by Jtang-1** [gevent/gevent#1907]
* gevent version: Attempting to install 21.8.0 through `pip install gevent==21.8.0`
* Python version: Tried both Python 3.6.15 and 3.8.13 installed through pyenv install
* Operating System: macOS Monterey Version 12.5.1

### Description:

I am trying to install gevent in my virtual environment made through `virtualenv`
Using cffi 1.15.0
wheel 0.37.1
```
Collecting gevent==21.8.0
  Using cached gevent-21.8.0.tar.gz (6.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/Users/jonathantang/.virtualenvs/cchq3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/jonathantang/.virtualenvs/cchq3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/jonathantang/.virtualenvs/cchq3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 481, in <module>
        File "<string>", line 348, in run_setup
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
          ffi = FFI()
        File "/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/cffi/api.py", line 48, in __init__
          import _cffi_backend as backend
      ImportError: dlopen(/private/var/folders/10/13kpj2mx2t53fg4lsrn94v8m0000gn/T/pip-build-env-dljps803/overlay/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_ffi_prep_closure)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

### What I've run:

```
pip install gevent==21.8.0
```

**Comment by jamadden** [comment]
Thanks for the report, but I don't think that's a gevent issue. The version of the third-party `cffi` library that you have installed appears not to be compatible with the version of the system library `ffi` that you have installed. Or something similar:
```
 ImportError: dlopen(/.../site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_ffi_prep_closure)
```

Maybe the [CFFI maintainers](https://foss.heptapod.net/pypy/cffi) can offer more insight.
