### ISSUE TITLE
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject

### ISSUE THREAD

**Issue by jpsiyyadri** [gevent/gevent#1923]
* gevent version: 22.10.2
* Python version: "python 3.7.8"
* Operating System: "macOS Ventura 13.0 @ Apple mac M1"

### Description:
**I tried to use dramatiq with django. I got below error when I started the app. It was working with 22.10.1 version**

```python-traceback
myDir: python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/jaiprakash/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/My Drive/codebase/nvs_doccls/ics_innovation/urls.py", line 19, in <module>
    from ics_innovation import views
  File "/Volumes/My Drive/codebase/nvs_doccls/ics_innovation/views.py", line 23, in <module>
    from .worker import start_extraction
  File "/Volumes/My Drive/codebase/nvs_doccls/ics_innovation/worker.py", line 4, in <module>
    import dramatiq
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/dramatiq/__init__.py", line 18, in <module>
    from .actor import Actor, actor
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/dramatiq/actor.py", line 21, in <module>
    from .broker import get_broker
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/dramatiq/broker.py", line 22, in <module>
    from .middleware import MiddlewareError, default_middleware
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/dramatiq/middleware/__init__.py", line 26, in <module>
    from .shutdown import Shutdown, ShutdownNotifications
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/dramatiq/middleware/shutdown.py", line 108, in <module>
    if is_gevent_active():
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/dramatiq/middleware/threading.py", line 38, in is_gevent_active
    from gevent import monkey
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Volumes/My Drive/codebase/nvs_doccls/env/lib/python3.8/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Users/jaiprakash/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
```

### What I've run:

**python manage.py makemigrations** this code is running fine with 22.10.1

**Comment by jamadden** [comment]
You appear to have somehow installed gevent 22.10.2 without also upgrading greenlet. A normal 'pip install' should upgrade both, because gevent 22.10.2 has a dependency on 'greenlet >= 2.0'.

Installing the correct greenlet version should resolve this.

**Comment by jpsiyyadri** [comment]
I had the latest version of greenlet, but still I'm getting the above error.
Please let me know in case I'm missing something here

```py
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import greenlet
>>> greenlet.__version__
'2.0.0.post0'
>>>
```

**Comment by MatiCoarasa** [comment]
I'm having this same issue! Any updates?

**Comment by akihironitta** [comment]
Hi @jamadden, where can I find `gevent` versions that are compatible with certain `greenlet` versions?

I'm having the same issue with the following environment:
```console
$ pip list|egrep "greenlet|gevent"
gevent                  22.10.2
geventhttpclient        2.0.8
greenlet                2.0.1
$ python -c "import gevent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nitta/.miniconda3/envs/dev9/lib/python3.9/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Users/nitta/.miniconda3/envs/dev9/lib/python3.9/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Users/nitta/.miniconda3/envs/dev9/lib/python3.9/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Users/nitta/.miniconda3/envs/dev9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
```

**Comment by jamadden** [comment]
Those should be the correct versions. 

Neither gevent nor greenlet distribute wheels for apple arm machines, so this is a "downstream" problem.

That must mean gevent was built incorrectly. It was built against an older greenlet, but the correct greenlet version is installed. Possibly what happened is that an existing, old, installation of greenlet (such as one from the system) was used to build gevent, instead of using gevent's bundled copy of the greenlet.h header from greenlet 2.

I haven't tried it, but a potential solution is to uninstall both gevent and greenlet, and rebuild from source using the correct versions. You'd probably want to clear out your pip cache before doing so.

**Comment by akihironitta** [comment]
As I was looking at `setup.py` at `22.10.2` tag, the versions seem correct as you mention. For now, I'll create a new env and see if it works. Thanks for your swift reply!
