### ISSUE TITLE
importing gevent cause error "ValueError: greenlet.greenlet size changed..." in m1 mac

### ISSUE THREAD

**Issue by miettal** [gevent/gevent#1927]
gevent==22.10.2

pyenv python 3.10

m1 mac

### Description:

I tried importing gavent, it cause error.

it seems related interface of greenlet. but I could not deside which is better to posting issue gevent project or greenlet project.

```python-traceback
Python 3.10.3+ (heads/3.10:c353835, Mar 22 2022, 16:50:49) [Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 160 from C header, got 40 from PyObject
```

### What I've run:

```python
import gevent
```

**Comment by miettal** [comment]
workaround:

```
pip install greenlet==1.1.3 gevent==21.8.0
```

**Comment by jamadden** [comment]
This is not a bug, you just didn't install compatible versions of gevent and greenlet. Old versions of gevent did not have an upper bound pin on greenlet, thus  letting you install greenlet 2, which is exactly what happened above.

The best thing to do is to install the current version of gevent, which has the proper versions pins.

**Comment by miettal** [comment]
Sorry, could you tell me meaning of current version of gevent.
I'm using 22.10.2.

```
$ pip install gevent==22.10.2
Collecting gevent==22.10.2
  Using cached gevent-22.10.2-cp310-cp310-macosx_12_0_arm64.whl
Requirement already satisfied: zope.interface in ./.pyenv/versions/3.10-dev/lib/python3.10/site-packages (from gevent==22.10.2) (5.5.0)
Requirement already satisfied: setuptools in ./.pyenv/versions/3.10-dev/lib/python3.10/site-packages (from gevent==22.10.2) (58.1.0)
Collecting greenlet>=2.0.0
  Using cached greenlet-2.0.1.tar.gz (163 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: zope.event in ./.pyenv/versions/3.10-dev/lib/python3.10/site-packages (from gevent==22.10.2) (4.5.0)
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Installing collected packages: greenlet, gevent
  Running setup.py install for greenlet ... done
Successfully installed gevent-22.10.2 greenlet-2.0.1

$ python
Python 3.10.3+ (heads/3.10:c353835, Mar 22 2022, 16:50:49) [Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Users/taisyo/.pyenv/versions/3.10-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 160 from C header, got 40 from PyObject
```

**Comment by akihironitta** [comment]
@miettal FYI, #1923 could be related to this issue.

**Comment by miettal** [comment]
Thank you I resolved this problem. I used pip with "--no-binary gevent" option.
