### ISSUE TITLE
KeyError at startup when importing matplotlib

### ISSUE THREAD

**Issue by danstewart** [gevent/gevent#1938]
* gevent version: 22.10.2
* Python version: 3.11.2 via docker `python:3.11-slim-bullseye`
* Operating System: Debian slim via docker `python:3.11-slim-bullseye`

### Description:

Apologies in advance if this is not a gevent issue.

At startup we get the following error when running flask via gunicorn with `--preload` and importing `matplotlib.pyplot` during `create_app`:
```
[2023-03-17 10:58:20 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-17 10:58:20 +0000] [1] [DEBUG] Arbiter booted
[2023-03-17 10:58:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2023-03-17 10:58:20 +0000] [1] [INFO] Using worker: gevent
[2023-03-17 10:58:20 +0000] [24] [INFO] Booting worker with pid: 24
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.11/threading.py", line 1042, in _bootstrap_inner
    self._delete()
  File "/usr/local/lib/python3.11/threading.py", line 1074, in _delete
    del _active[get_ident()]
        ~~~~~~~^^^^^^^^^^^^^
KeyError: 140531362327872
2023-03-17T10:58:20Z <Greenlet at 0x7fd001ee6d40: <bound method Thread._bootstrap of <Timer(Thread-1, stopped 140531362327872)>>> failed with KeyError

[2023-03-17 10:58:20 +0000] [25] [INFO] Booting worker with pid: 25
[2023-03-17 10:58:20 +0000] [26] [INFO] Booting worker with pid: 26
[2023-03-17 10:58:20 +0000] [27] [INFO] Booting worker with pid: 27
[2023-03-17 10:58:20 +0000] [1] [DEBUG] 4 workers
```

### What I've run:

Our gunicorn start command is:
```shell
  exec gunicorn \
    --config gunicorn_config.py \
    --workers 4 \
    --threads 4 \
    --worker-class gevent \
    --bind 0.0.0.0:5000 \
    --worker-tmp-dir /dev/shm \
    --log-level debug \
    --timeout 300 \
    --capture-output \
    --enable-stdio-inheritance \
    --forwarded-allow-ips="*" \
    --preload \
    'app:create_app()'
```

and `gunicorn_config.py` has:
```python
import gevent.monkey

gevent.monkey.patch_all()
```

If I move our `from matplotlib import pyplot` line into the function so it's not ran at startup it works and is fine at runtime.

**Comment by jamadden** [comment]
IIRC, that error means that the process has spawned native threads and only then monkey-patched. That is, monkey patching is happening too late. Presumably something in `matplotlib` is spawning a thread at import time?

It is known that gunicorn with `--preload` [patches too late for some applications](https://github.com/benoitc/gunicorn/issues/1566). The solution I use is to [start gunicorn from a script that has already monkey-patched](https://github.com/benoitc/gunicorn/issues/1056#issuecomment-115428187).
