### ISSUE TITLE
testFDPassSeparate fails on OpenIndiana (sunos5)

### ISSUE THREAD

**Issue by mtelka** [gevent/gevent#1952]
* gevent version: 22.10.2, installed from sdist during packaging `gevent` for OpenIndiana
* Python version: 3.9.16, part of OpenIndiana
* Operating System: OpenIndiana Hipster (latest)

### Description:

I'm packaging `gevent` for OpenIndiana and I found that following four tests fails due to an OSError:
```
  ======================================================================
  ERROR: testFDPassSeparate (__main__.RecvmsgSCMRightsStreamTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/test_socketogqslxst.py", line 372, in _tearDown
      raise exc
    File "/tmp/test_socketogqslxst.py", line 390, in clientRun
      test_func()
    File "/tmp/test_socketogqslxst.py", line 3527, in _testFDPassSeparate
      self.sendmsgToServer([MSG], [(socket.SOL_SOCKET,
    File "/tmp/test_socketogqslxst.py", line 2664, in sendmsgToServer
      return self.cli_sock.sendmsg(
    File "/usr/lib/python3.9/vendor-packages/gevent/_socket3.py", line 399, in sendmsg
      return self._sock.sendmsg(buffers, ancdata, flags, address)
  OSError: [Errno 22] Invalid argument
  
  ======================================================================
  ERROR: testFDPassSeparateMinSpace (__main__.RecvmsgSCMRightsStreamTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/test_socketogqslxst.py", line 372, in _tearDown
      raise exc
    File "/tmp/test_socketogqslxst.py", line 390, in clientRun
      test_func()
    File "/tmp/test_socketogqslxst.py", line 3554, in _testFDPassSeparateMinSpace
      self.sendmsgToServer([MSG], [(socket.SOL_SOCKET,
    File "/tmp/test_socketogqslxst.py", line 2664, in sendmsgToServer
      return self.cli_sock.sendmsg(
    File "/usr/lib/python3.9/vendor-packages/gevent/_socket3.py", line 399, in sendmsg
      return self._sock.sendmsg(buffers, ancdata, flags, address)
  OSError: [Errno 22] Invalid argument
  
  ======================================================================
  ERROR: testFDPassSeparate (__main__.RecvmsgIntoSCMRightsStreamTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/test_socketogqslxst.py", line 372, in _tearDown
      raise exc
    File "/tmp/test_socketogqslxst.py", line 390, in clientRun
      test_func()
    File "/tmp/test_socketogqslxst.py", line 3527, in _testFDPassSeparate
      self.sendmsgToServer([MSG], [(socket.SOL_SOCKET,
    File "/tmp/test_socketogqslxst.py", line 2664, in sendmsgToServer
      return self.cli_sock.sendmsg(
    File "/usr/lib/python3.9/vendor-packages/gevent/_socket3.py", line 399, in sendmsg
      return self._sock.sendmsg(buffers, ancdata, flags, address)
  OSError: [Errno 22] Invalid argument
  
  ======================================================================
  ERROR: testFDPassSeparateMinSpace (__main__.RecvmsgIntoSCMRightsStreamTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/test_socketogqslxst.py", line 372, in _tearDown
      raise exc
    File "/tmp/test_socketogqslxst.py", line 390, in clientRun
      test_func()
    File "/tmp/test_socketogqslxst.py", line 3554, in _testFDPassSeparateMinSpace
      self.sendmsgToServer([MSG], [(socket.SOL_SOCKET,
    File "/tmp/test_socketogqslxst.py", line 2664, in sendmsgToServer
      return self.cli_sock.sendmsg(
    File "/usr/lib/python3.9/vendor-packages/gevent/_socket3.py", line 399, in sendmsg
      return self._sock.sendmsg(buffers, ancdata, flags, address)
  OSError: [Errno 22] Invalid argument
```

All other `test_socket.py` tests either pass or are skipped.

### What I've run:

Tests

**Comment by jamadden** [comment]
That's not a platform we test on, so I can't offer much to help you. But, have you tried running the test _without_ gevent's test harness? That's a standard library test, and gevent's test harness just runs it monkey-patched. (You might be able to run it with `python -m test.test_socket` if you have the test library installed, otherwise you'll need to extract the file from gevent's source or the CPython repository, along with any dependencies, and run it that way). There's a good chance those functions don't work in the standard library either. [Solaris/OpenIndianna aren't supported by CPython](https://pythondev.readthedocs.io/platforms.html#best-effort-and-unofficial-platforms).

On the assumption that the tests fail with the standard library, I'm closing this. If they don't fail in the stdlib, and it's a bug in gevent, PRs welcome!

**Comment by mtelka** [comment]
```
$ python -m test.test_socket
ssssssssssssssssssssss.......................sss...ssss........ssss.......................s..........................s......s..s..............sss.............sssss................sss..........sssssss...................sssss..................ssssssssssssssssss..............ss................................................ssssssssssssssssssssssssssss................................................ssssssssssssssssss..............ss.......................................ssssssssssssssssssssss.......................................................s............s...............ssssssssssssssssssssss...................s..................ss..sssssssssss......sss...............................................
----------------------------------------------------------------------
Ran 709 tests in 25.692s

OK (skipped=191)
$ python -V
Python 3.9.16
$
```
