### ISSUE TITLE
greenlets accidentally stuck on sleep(0) after GC removes objects with sleep(0) in __del__ on python3.9+

### ISSUE THREAD

**Issue by unipolar** [gevent/gevent#1959]
* gevent version: 22.10.2
* Python version: 3.9.X
* Operating System: CentOS based or docker python3.9 + pip install gevent

### Description:

This code fails with `LoopExit: This operation would block forever` on Python 3.9.

```python
import gevent.monkey
gevent.monkey.patch_all()

class X:
    def __init__(self):
        # need this for GC
        self.link = self

    def __del__(self):
        gevent.hub.sleep()

def loop():
  i = 0
  while True:
    print(f'iteration {i}')
    i += 1
    X()
    gevent.hub.sleep()

a = gevent.spawn(loop)
# uncomment this if you want loop() greenlet to stuck
# b = gevent.spawn(gevent.hub.sleep, 100000000000000000)
a.join()
```
Reproducible with python:39 docker container.
```
# docker run  -v ${PWD}:/test python:3.9 sh -c "pip install gevent==22.10.2 2>&1; python /test/test.py 2>&1"  | tail -n 20
iteration 130
iteration 131
iteration 132
iteration 133
iteration 134
iteration 135
Traceback (most recent call last):
  File "/test/test.py", line 23, in <module>
    a.join()
  File "src/gevent/greenlet.py", line 833, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 859, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 848, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x7fc21b5c32c0 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7fc21c897740>
	Handles:
[]
```

loop() hangs after GC jumps in while hub.sleep(0) is executed between hub.run_callback(waiter.switch, None) and hub.switch() from waiter.get(). GC is executed in same greenlet, so added loop's waiter.switch callback wakes up waiter created in __del__ method, after that waiter.switch callback  added by __del__ method doesn't not switch to greenlet back, because it's waiter already has no self.greenlet, so execution never switch back to loop.

While provided example is artificial, we found it in real application after we switch to python3.9 and latest gevent.

Here is our traceback with __del__executed in sleep()/waiter.get().
```python-traceback
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 456, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 358, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 298, in connection_from_url
    return self.connection_from_host(
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 245, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 260, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 281, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 213, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 906, in __init__
    HTTPConnectionPool.__init__(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 206, in __init__
    self.pool.put(None)
  File "/usr/lib64/python3.9/queue.py", line 152, in put
    self.not_empty.notify()
  File "/usr/lib64/python3.9/threading.py", line 361, in notify
    if not self._is_owned():
  File "/usr/lib64/python3.9/threading.py", line 274, in _is_owned
    if self._lock.acquire(False):
  File "/usr/lib64/python3.9/site-packages/gevent/thread.py", line 141, in acquire
    sleep()
  File "/usr/lib64/python3.9/site-packages/gevent/hub.py", line 160, in sleep
    waiter.get()
  File "/usr/lib/python3.9/site-packages/keystoneauth1/session.py", line 397, in __del__       # <<<<<  GC IS HERE
    self._session.close()
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 797, in close
    v.close()
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 368, in close
    self.poolmanager.clear()
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 222, in clear
    self.pools.clear()
  File "/usr/lib/python3.9/site-packages/urllib3/_collections.py", line 100, in clear
    self.dispose_func(value)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 173, in <lambda>
    self.pools = RecentlyUsedContainer(num_pools, dispose_func=lambda p: p.close())
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 490, in close
    conn = old_pool.get(block=False)
  File "/usr/lib64/python3.9/queue.py", line 182, in get
    self.not_full.notify()
  File "/usr/lib64/python3.9/threading.py", line 361, in notify
    if not self._is_owned():
  File "/usr/lib64/python3.9/threading.py", line 274, in _is_owned
    if self._lock.acquire(False):
  File "/usr/lib64/python3.9/site-packages/gevent/thread.py", line 141, in acquire
    sleep()
  File "/usr/lib64/python3.9/site-packages/gevent/hub.py", line 160, in sleep
    waiter.get()
```

**Comment by unipolar** [comment]
Since https://github.com/python/cpython/issues/81521 each cython method call has perform a memory allocation, and memory allocation has chances to trigger GC collect. That explains why it is hard to reproduce it on python 3.8, but still possible, just need to use all slots in free_list cache.
