### ISSUE TITLE
AttributeError: '_Threadlocal' object has no attribute 'hub'

### ISSUE THREAD

**Issue by r-bk** [gevent/gevent#1961]
* gevent version: pip3 install gevent==22.10.2
* Python version: Python 3.8 from dockerhub python:3.8-slim-bullseye
* Operating System: Debian docker container python:3.8-slim-bullseye running on Linux host

### Description:

`get_hub_if_exists` raises `AttributeError`

```python-traceback
Exception ignored in: <finalize object at 0x7fecaa1435c0; dead>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1128, in _close_pool_connections
    conn = pool.get(block=False)
  File "/usr/local/lib/python3.8/queue.py", line 164, in get
    with self.not_empty:
  File "/usr/local/lib/python3.8/threading.py", line 247, in __enter__
    return self._lock.__enter__()
  File "src/gevent/_semaphore.py", line 278, in gevent._gevent_c_semaphore.Semaphore.__enter__
  File "src/gevent/_semaphore.py", line 279, in gevent._gevent_c_semaphore.Semaphore.__enter__
  File "src/gevent/_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "/usr/local/lib/python3.8/site-packages/gevent/thread.py", line 121, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 216, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 198, in gevent._gevent_c_abstract_linkable.AbstractLinkable._capture_hub
  File "src/gevent/_hub_local.py", line 88, in gevent._gevent_c_hub_local.get_hub_if_exists
    AttributeError: '_Threadlocal' object has no attribute 'hub'
```

**Comment by jfly** [comment]
@jamadden I wish I had a SSCCE for you, but we haven't been able to put one together.

If it's helpful, we've been seeing this stacktrace correlated with greenlets getting wedged. We found that pinning to urllib3 <= 1.26.16 made the problem go away (see https://github.com/gevent/gevent/issues/1957 and https://github.com/urllib3/urllib3/issues/3061).

**Comment by jamadden** [comment]
`_ThreadLocal` is a `_thread._local` object with an `__init__` method that sets `self.hub`; there is one instance in a `_threadlocal` variable. The only ways I know of that  `self.hub` could go missing are:

- Somebody does `del _threadlocal.hub` . BUT: `_threadlocal` is defined in C and not accessible from Python, and gevent's C code doesn't ever do that, so we can probably rule that out.
- The `tp_clear` slot of the `_thread._local` class gets called. This C function decrefs the thread-local `__dict__` attached to the `_thread._local` instance; that would cause them to get deleted if that were the only reference to them, but it would leave them invalid. But in addition, the `tp_clear` slot of the `dict` object itself clears the dictionary. `tp_clear` slots are generally invoked only in cases of circular garbage (eww). So if we somehow had the `_threadlocal` instance, or one of its dictionaries, involved in a cyclic reference cycle, the garbage collector might start clearing stuff out. Since we're running a weakref finalizer (and the referenced urllib code is talking about deliberately creating reference cycles, IIUC), garbage collection seems likely. It's unclear how that would happen, but it seems possible.

I can make a tweak to avoid the `AttributeError` but running gevent APIs when apparently large parts of the system are getting destroyed is, umm, risky and may not fix the problem.

**Comment by r-bk** [comment]
> @jamadden I wish I had a SSCCE for you, but we haven't been able to put one together.
> 
> If it's helpful, we've been seeing this stacktrace correlated with greenlets getting wedged. We found that pinning to urllib3 <= 1.26.16 made the problem go away (see #1957 and [urllib3/urllib3#3061](https://github.com/urllib3/urllib3/issues/3061)).

We needed to pin to `urllib3 == 1.26.15` to make it disappear. `urllib3 == 1.26.16` was the buggy version.

**Comment by jfly** [comment]
Urg, sorry @r-bk, I wrote `<= 1.26.16` when I meant `< 1.26.16`, aka `1.26.15` works and `1.25.16` does not work.

**Comment by LefterisJP** [comment]
Huh interesting so this issue does indeed seem similar to the one we see in #1957. Will leave a comment there what the result of some testing with Jason's prompts was.

**Comment by embray** [comment]
I am seeing this too, currently on urllib3==1.26.20.  This also seems possibly related to my investigation into https://github.com/gevent/gevent/issues/1826 (where the hub is mysteriously disappearing)

Seems maybe also related to https://github.com/gevent/gevent/issues/1826 but I'm not sure.  Will follow up more there.

**Comment by embray** [comment]
@NetJagaimo Do you have some code that reproduces this?  Despite hours trying to trace what *could* cause this condition, I was never able to track it down as I didn't have a reliable repro.  If we did we could probably fix it...
