### ISSUE TITLE
multiple values for argument pool

### ISSUE THREAD

**Issue by carlacohen** [gevent/gevent#1965]
* gevent version: 22.10.2 (also tried 21.12.0, 21.8.0) installed via conda
* Python version: 3.8.15 installed via conda
* Operating System: Description:    Ubuntu 22.04.2 LTS Release:        22.04
Codename:       jammy

### Description:

I'm running a pipeline in a ruffus/cgatcore framework. 
Pipeline is here: https://github.com/cribbslab/scflow/blob/master/scpipelines/pipeline_quantnuclei.py
Jobs are submitted to the queue and run correctly but after each task has run I get the following error. This stops the pipeline from progressing to the next step. 

```
Exception #1 \
                                                  '<class 'TypeError'>handle_sigint() got multiple values for argument 'pool'' raised in ... \
                                                Traceback (most recent call last): \
                                                  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_quantnuclei_minimal/lib/python3.8/site-packages/ruffus/task.py", line 5250, in pipeline_run \
                                                    job_result = ii.next(**itr_kwargs) \
                                                  File "src/gevent/_imap.py", line 105, in gevent._gevent_c_imap.IMapUnordered.__next__ \
                                                  File "src/gevent/_imap.py", line 113, in gevent._gevent_c_imap.IMapUnordered._inext \
                                                  File "src/gevent/queue.py", line 350, in gevent._gevent_cqueue.Queue.get \
                                                  File "src/gevent/queue.py", line 327, in gevent._gevent_cqueue.Queue._Queue__get_or_peek \
                                                  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get \
                                                  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch \
                                                  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch \
                                                  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch \
                                                  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch \
                                                TypeError: handle_sigint() got multiple values for argument 'pool' \
                                                 \

```

### What I've run:

$ python pipeline_quantnuclei.py make -v5

The pipeline used to run without this error so I wonder if it is related to the version of gevent? Can you help? Thanks!

**Comment by jamadden** [comment]
I can't imagine it would be related to gevent. For one thing, `handle_sigint` isn't a gevent function, and for another, none of those functions in the stack trace take a `pool` argument. I would be suspicious of your other libraries. You might look into what value `itr_kwargs` has and where it comes from.

Good luck!
