### ISSUE TITLE
`TypeError: child watchers are only available on the default loop` on importing some libraries

### ISSUE THREAD

**Issue by SkyToGround** [gevent/gevent#1966]
* gevent version: 22.10.2 via pip
* Python version: Python 3.10.6 via apt-get
* Operating System: Ubuntu 22.04.2 LTS

### Description:

I get the following type error exception when trying to access a Django view using the web servers Daphne, Uvicorn and Hypercorn:
`TypeError: child watchers are only available on the default loop`

This exception occurs when one or more of the following import statements are present in my code:

- `from scipy.interpolate import interp1d`
- `from scipy.optimize import least_squares`
- `import weasyprint`

```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/deprecation.py", line 146, in __acall__
    response = await sync_to_async(
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/middleware/locale.py", line 24, in process_request
    ) = is_language_prefix_patterns_used(urlconf)
  File "/usr/local/lib/python3.10/dist-packages/django/conf/urls/i18n.py", line 31, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/skydiving_tools/skydiving_tools/./skydiving_tools/urls.py", line 26, in <module>
    path("mass_and_balance/", include("mass_and_balance.urls")),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/skydiving_tools/skydiving_tools/./mass_and_balance/urls.py", line 3, in <module>
    from . import views
  File "/var/www/skydiving_tools/skydiving_tools/./mass_and_balance/views.py", line 5, in <module>
    from mass_and_balance.mass_and_balance import (
  File "/var/www/skydiving_tools/skydiving_tools/./mass_and_balance/mass_and_balance.py", line 4, in <module>
    from scipy.interpolate import interp1d
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_fitpack_py.py", line 10, in <module>
    from ._bsplines import BSpline
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_bsplines.py", line 8, in <module>
    from scipy.optimize import minimize_scalar
  File "/usr/local/lib/python3.10/dist-packages/scipy/optimize/__init__.py", line 405, in <module>
    from ._minimize import *
  File "/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minimize.py", line 26, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/usr/local/lib/python3.10/dist-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/usr/local/lib/python3.10/dist-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 5, in <module>
    from .._constraints import (
  File "/usr/local/lib/python3.10/dist-packages/scipy/optimize/_constraints.py", line 8, in <module>
    from numpy.testing import suppress_warnings
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/__init__.py", line 11, in <module>
    from ._private.utils import *
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1257, in <module>
    _SUPPORTS_SVE = check_support_sve()
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1251, in check_support_sve
    output = subprocess.run(cmd, capture_output=True, text=True)
  File "/usr/local/lib/python3.10/dist-packages/gevent/subprocess.py", line 2029, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/dist-packages/gevent/subprocess.py", line 842, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/dist-packages/gevent/subprocess.py", line 1675, in _execute_child
    self.pid = fork_and_watch(self._on_child, self._loop, True, fork)
  File "/usr/local/lib/python3.10/dist-packages/gevent/os.py", line 434, in fork_and_watch
    _watch_child(pid, callback, loop, ref)
  File "/usr/local/lib/python3.10/dist-packages/gevent/os.py", line 402, in _watch_child
    watcher = loop.child(pid, ref=ref)
  File "src/gevent/libev/corecext.pyx", line 716, in gevent.libev.corecext.loop.child
  File "src/gevent/libev/corecext.pyx", line 1257, in gevent.libev.corecext.child.__cinit__
TypeError: child watchers are only available on the default loop
```

**Comment by jamadden** [comment]
You described what happens but you didn't ask any question, so I have to guess. If your question is "is this expected?" the answer is, yes, that's expected. You can't use a child watcher from a non-main native thread, as the exception states. Try monkey patching the threading package.

**Comment by SkyToGround** [comment]
I am admittedly fumbling in the dark. Still: I consider it unexpected that an import statement causes an exception.

With that said, I think I found the actual culprit now: The _grequests_  library is the one pulling in _gevent_ and it seems that it breaks the _gevent_ rules for monkey patching.
