### ISSUE TITLE
Gevent release 23.7.0 not compiled for python 3.10

### ISSUE THREAD

**Issue by piraka9011** [gevent/gevent#1970]
* gevent version: 23.7.0 installed via pip
* Python version: 3.10, Dockerfile `python:3.10-slim`
* Operating System: Ubuntu 20.04

### Description:

Installing gevent via pip fails when using `*-slim` tags of python 3.10 w/ Docker.
This is because gevent needs to be built from scratch since there is no wheel in PyPi for python 3.10 and the slim docker tags do not have a C compiler installed.

I've trimmed the stack trace to the relevant lines, specifically the part

```
configure: error: no acceptable C compiler found in $PATH
```

```python-traceback
      ....
      configure: error: in `/tmp/pip-install-m9lauyrz/gevent_bbfe42ca51484eeeb0cd38999c04eab5/deps/libev':
      configure: error: no acceptable C compiler found in $PATH
      See `config.log' for more details
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 468, in <module>
        File "<string>", line 337, in run_setup
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-_1qmdult/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 143, in run
          ext.sources[0] = make_mod(self.build_temp, pre_run)
        File "/tmp/pip-build-env-_1qmdult/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 128, in make_mod
          pre_run(ext, ffi)
        File "/tmp/pip-install-m9lauyrz/gevent_bbfe42ca51484eeeb0cd38999c04eab5/_setuputils.py", line 381, in pre_run
          action()
        File "/tmp/pip-install-m9lauyrz/gevent_bbfe42ca51484eeeb0cd38999c04eab5/_setuplibev.py", line 55, in configure_libev
          system(libev_configure_command)
        File "/tmp/pip-install-m9lauyrz/gevent_bbfe42ca51484eeeb0cd38999c04eab5/_setuputils.py", line 195, in system
          if _system(cmd, cwd=cwd, env=env, **kwargs):
        File "/tmp/pip-install-m9lauyrz/gevent_bbfe42ca51484eeeb0cd38999c04eab5/_setuputils.py", line 191, in _system
          return check_call(cmd, cwd=cwd, env=env, **kwargs)
        File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '(cd  "/tmp/pip-install-m9lauyrz/gevent_bbfe42ca51484eeeb0cd38999c04eab5/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent, which is required to install pyproject.toml-based projects

```

### What I've run:

```sh
docker run -it 'python:3.10-slim' bash
pip install gevent
```

As a workaround, you can use the `python:3.10` image, but the `gevent` wheel still needs to be compiled.

To solve this for all python Docker tags and avoid building a wheel on install, please release a PyPi wheel built for all supported python versions!

**Comment by piraka9011** [comment]
I can confirm installing gevent from pypi now works without requiring a build.

Thank you @jamadden for the very quick turn around! :100:

**Comment by jamadden** [comment]
I didn't do anything. You just jumped the gun. It takes awhile for wheels to finish uploading, and they don't all become available at the same time.
