### ISSUE TITLE
gevent 1.5.0 will no longer install

### ISSUE THREAD

**Issue by blakecannon-projectcanary** [gevent/gevent#1982]
* gevent version: 1.5.0 with pip (clean and cached) or within the install script from https://github.com/espressif/esp-idf/blob/master/install.sh
* Python version: python3.8, python3.9, python3.10, and python3.11
* Operating System: Windows, macOs, Linux (Ubuntu 20.04, 22.04)

### Description:

**gevent 1.5.0 will not install**:

gevent 1.5.0 has been working for over a year. A few weeks ago it stopped working. All machines at the office, all machines on AWS (EC2, Codebuild, etc), all operating systems. 

All machines give the same error no matter python version or operating system. We are at a complete standstill.

```
$ pip install gevent==1.5.0
Defaulting to user installation because normal site-packages is not writeable
Collecting gevent==1.5.0
  Using cached gevent-1.5.0.tar.gz (5.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [318 lines of output]
      warning: src/gevent/resolver/cares.pyx:32:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/resolver/cares.pyx:33:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      Compiling src/gevent/resolver/cares.pyx because it changed.
      [1/1] Cythonizing src/gevent/resolver/cares.pyx
      warning: src/gevent/libev/corecext.pyx:325:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:778:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:780:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:782:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:786:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if events & ~(libev.EV__IOFDSET | libev.EV_READ | libev.EV_WRITE):
                  raise ValueError('illegal event mask: %r' % events)
              # All the vfd_functions are no-ops on POSIX
              cdef int vfd = libev.vfd_open(fd)
              libev.ev_io_init(&self._watcher, <void *>gevent_callback_io, vfd, events)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1027:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  raise ValueError('illegal event mask: %r' % events)
              # All the vfd_functions are no-ops on POSIX
              cdef int vfd = libev.vfd_open(fd)
              libev.ev_io_init(&self._watcher, <void *>gevent_callback_io, vfd, events)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &io_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1028:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          def __cinit__(self, loop loop, double after=0.0, double repeat=0.0, ref=True, priority=None):
              if repeat < 0.0:
                  raise ValueError("repeat must be positive or zero: %r" % repeat)
              libev.ev_timer_init(&self._watcher, <void *>gevent_callback_timer, after, repeat)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1072:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def __cinit__(self, loop loop, double after=0.0, double repeat=0.0, ref=True, priority=None):
              if repeat < 0.0:
                  raise ValueError("repeat must be positive or zero: %r" % repeat)
              libev.ev_timer_init(&self._watcher, <void *>gevent_callback_timer, after, repeat)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &timer_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1073:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # 1) "libev: ev_signal_start called with illegal signal number"
              #    EV_NSIG might be different from signal.NSIG on some platforms
              # 2) "libev: a signal must not be attached to two different loops"
              #    we probably could check that in LIBEV_EMBED mode, but not in general
              libev.ev_signal_init(&self._watcher, <void *>gevent_callback_signal, signalnum)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1117:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              #    EV_NSIG might be different from signal.NSIG on some platforms
              # 2) "libev: a signal must not be attached to two different loops"
              #    we probably could check that in LIBEV_EMBED mode, but not in general
              libev.ev_signal_init(&self._watcher, <void *>gevent_callback_signal, signalnum)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &signal_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1118:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef libev.ev_idle _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_idle_init(&self._watcher, <void*>gevent_callback_idle)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1133:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef libev.ev_idle _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_idle_init(&self._watcher, <void*>gevent_callback_idle)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &idle_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1134:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef libev.ev_prepare _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_prepare_init(&self._watcher, <void*>gevent_callback_prepare)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1146:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef libev.ev_prepare _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_prepare_init(&self._watcher, <void*>gevent_callback_prepare)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &prepare_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1147:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef libev.ev_check _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_check_init(&self._watcher, <void*>gevent_callback_check)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1159:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef libev.ev_check _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_check_init(&self._watcher, <void*>gevent_callback_check)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &check_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1160:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef libev.ev_fork _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_fork_init(&self._watcher, <void*>gevent_callback_fork)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1172:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef libev.ev_fork _watcher
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_fork_init(&self._watcher, <void*>gevent_callback_fork)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &fork_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1173:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # Note the use of ev_async_pending instead of ev_is_pending
              return True if libev.ev_async_pending(&self._watcher) else False
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_async_init(&self._watcher, <void*>gevent_callback_async)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1189:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              return True if libev.ev_async_pending(&self._watcher) else False
      
          def __cinit__(self, loop loop, ref=True, priority=None):
              libev.ev_async_init(&self._watcher, <void*>gevent_callback_async)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &async_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1190:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  raise AttributeError("Child watchers are not supported on Windows")
              if not loop.default:
                  raise TypeError('child watchers are only available on the default loop')
              libev.gevent_install_sigchld_handler()
              libev.ev_child_init(&self._watcher, <void *>gevent_callback_child, pid, trace)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1212:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if not loop.default:
                  raise TypeError('child watchers are only available on the default loop')
              libev.gevent_install_sigchld_handler()
              libev.ev_child_init(&self._watcher, <void *>gevent_callback_child, pid, trace)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &child_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1213:20: Cannot convert 'start_and_stop *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self._paths = paths
              else:
                  paths = <bytes>path
                  self._paths = paths
              libev.ev_stat_init(&self._watcher, <void *>gevent_callback_stat, <char*>paths, interval)
              self.__watcher = <libev.ev_watcher*>&self._watcher
                               ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1263:25: Cannot convert 'ev_watcher *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              else:
                  paths = <bytes>path
                  self._paths = paths
              libev.ev_stat_init(&self._watcher, <void *>gevent_callback_stat, <char*>paths, interval)
              self.__watcher = <libev.ev_watcher*>&self._watcher
              self.__ss = &stat_ss
                          ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:1264:20: Cannot convert 'start_and_stop *' to Python object
      Compiling src/gevent/libev/corecext.pyx because it changed.
      [1/1] Cythonizing src/gevent/libev/corecext.pyx
      Traceback (most recent call last):
        File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-781hay66/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-781hay66/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-781hay66/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-781hay66/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 49, in <module>
        File "/tmp/pip-install-2fv0jvx4/gevent_a44315bc7da7468880d631d1c0dda477/_setuputils.py", line 254, in cythonize1
          new_ext = cythonize(
        File "/tmp/pip-build-env-781hay66/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-781hay66/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jamadden** [comment]
I strongly recommend you use a current gevent version. gevent 1.5 does not support Python 3.9 or newer. There are absolutely things that it gets wrong on those newer versions that it is unaware of. That's the reason you have to compile it: 3.9 and newer aren't supported and there were never any binary wheels for them.

That said, I think you're running into issues with a newer Cython version. You'll need to set a pip constraint to get an older version of Cython; the version that gevent 1.5 was tested with was 0.29.14, but note that that version doesn't support Python 3.10 --- Python 3.10 was tested with 3.0a9 but that version won't compile gevent 1.5.  There may be a 0.X.X release that can handle newer Python versions and also compile gevent 1.5 code, but I've never tested that and I have no idea what version that would be.

```console
$ echo 'cython<3' > /tmp/constraints.txt
$ PIP_CONSTRAINT=/tmp/constraints.txt pip install gevent==1.5
```

Good luck.

**Comment by b264** [comment]
Using python 3.10.4 got this older version ESP-IDF 4.4.2 working for me.  With no changes to the [installation as instructed by espressif](https://docs.espressif.com/projects/esp-idf/en/v4.4.2/esp32/get-started/index.html).
