### ISSUE TITLE
23.9.1: env name py311-cffi conflicting with base python python2.7

### ISSUE THREAD

**Issue by mtelka** [gevent/gevent#1995]
```
$ cd gevent-23.9.1
$ tox -l
Traceback (most recent call last):
  File "/usr/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3.9/vendor-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/usr/lib/python3.9/vendor-packages/tox/run.py", line 45, in main
    return handler(state)
  File "/usr/lib/python3.9/vendor-packages/tox/session/cmd/legacy.py", line 107, in legacy
    return list_env(state)
  File "/usr/lib/python3.9/vendor-packages/tox/session/cmd/list_env.py", line 28, in list_env
    active = dict.fromkeys(state.envs.iter())
  File "/usr/lib/python3.9/vendor-packages/tox/session/env_select.py", line 403, in iter
    for name, env_info in self._defined_envs.items():
  File "/usr/lib/python3.9/vendor-packages/tox/session/env_select.py", line 273, in _defined_envs
    raise failed[next(iter(failed_to_create))]
  File "/usr/lib/python3.9/vendor-packages/tox/session/env_select.py", line 250, in _defined_envs
    run_env.package_env = self._build_pkg_env(pkg_name_type, name, env_name_to_active)
  File "/usr/lib/python3.9/vendor-packages/tox/session/env_select.py", line 321, in _build_pkg_env
    name_type = next(child_package_envs)
  File "/usr/lib/python3.9/vendor-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 173, in register_run_env
    yield from super().register_run_env(run_env)
  File "/usr/lib/python3.9/vendor-packages/tox/tox_env/python/package.py", line 116, in register_run_env
    pkg_env = run_env.conf["wheel_build_env"]
  File "/usr/lib/python3.9/vendor-packages/tox/config/sets.py", line 118, in __getitem__
    return self.load(item)
  File "/usr/lib/python3.9/vendor-packages/tox/config/sets.py", line 129, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))
  File "/usr/lib/python3.9/vendor-packages/tox/config/of_type.py", line 105, in __call__
    value = self.default(conf, args.env_name) if callable(self.default) else self.default
  File "/usr/lib/python3.9/vendor-packages/tox/tox_env/python/package.py", line 92, in default_wheel_tag
    run_py = cast(Python, run_env).base_python
  File "/usr/lib/python3.9/vendor-packages/tox/tox_env/python/api.py", line 246, in base_python
    base_pythons: list[str] = self.conf["base_python"]
  File "/usr/lib/python3.9/vendor-packages/tox/config/sets.py", line 118, in __getitem__
    return self.load(item)
  File "/usr/lib/python3.9/vendor-packages/tox/config/sets.py", line 129, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))
  File "/usr/lib/python3.9/vendor-packages/tox/config/of_type.py", line 107, in __call__
    value = self.post_process(value)
  File "/usr/lib/python3.9/vendor-packages/tox/tox_env/python/api.py", line 70, in validate_base_python
    return self._validate_base_python(self.name, value, self.core["ignore_base_python_conflict"])
  File "/usr/lib/python3.9/vendor-packages/tox/tox_env/python/api.py", line 175, in _validate_base_python
    raise Fail(msg)
tox.tox_env.errors.Fail: env name py311-cffi conflicting with base python python2.7
$
```

**Comment by jamadden** [comment]
The project doesn't use `tox.ini` so it's not well maintained. I'd be happy to look at PRs but I'm not going to mess with it myself.
