### ISSUE TITLE
AbstractLinkable._notify_links under VS Code debugger

### ISSUE THREAD

**Issue by dsuch** [gevent/gevent#1999]
Hello,

this is more of a FYI ticket - I will not have time to work on it further but it may be of interest or importance to you, @jamadden.

I have [an application](https://zato.io) that is currently using gevent v. 23.9.1, the behaviour that I am about to describe was observable under 22.10.2 and it started less than a year ago.

The behaviour is this - whenever I start the application under debugger in VS Code, I am getting this exception:

```
Traceback (most recent call last):
  File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
  File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
AssertionError: (None, <callback at 0x7f80422c3dc0 args=([],)>)
2023-09-27T18:53:43Z <callback at 0x7f80422c3dc0 args=([],)> failed with AssertionError
```

This never happens in a standalone process and, under VS Code, this does not prevent the application from anything, which is why it is not any priority from my perspective.

Yet, perhaps this is a manifestation of something that you would like to know about, which is why I am opening this ticket.

Regards.

**Comment by digdeep44** [comment]
Observing the same after upgrading to 3.11, traced it back till 3.8 as per this post, it occurs till 3.9
Application does not break, and our greenlets also work fine, but getting this traceback on first yield/blocking operation.

@jamadden any update on this?

**Comment by Pajinek** [comment]
I found similar old issue https://github.com/gevent/gevent/issues/1895#issuecomment-1946675676

**Comment by Zhou-ZJ** [comment]
`[2024-12-20 20:17:49 +0800] [1192773] [INFO] Starting gunicorn 22.0.0
[2024-12-20 20:17:49 +0800] [1192773] [INFO] Listening at: http://0.0.0.0:8000 (1192773)
[2024-12-20 20:17:49 +0800] [1192773] [INFO] Using worker: gevent
[2024-12-20 20:17:49 +0800] [1192774] [INFO] Booting worker with pid: 1192774
Traceback (most recent call last):
  File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
  File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
AssertionError: (None, <callback at 0x7f556a7dbfc0 args=([],)>)
2024-12-20T12:17:49Z <callback at 0x7f556a7dbfc0 args=([],)> failed with AssertionError` I also got this, using python3.12
