### ISSUE TITLE
TypeError: memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by soft-top-notch** [gevent/gevent#2009]
* gevent version: 23.9.1
* gevent-websocket version: 0.10.1
* Python version: 3.10.13
* Operating System: Ubuntu

### Description:

I'm running the geventwebsocket using gunicorn using below command:
```
gunicorn -k "geventwebsocket.gunicorn.workers.GeventWebSocketWorker" -w 2 -b unix:webrtc.sock -m 007 wsgi:app
```
And then, I keep getting below error constantly when I check `journalctl -f`:
```
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]: Traceback (most recent call last):
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 1107, in handle_one_response
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self.run_application()
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/geventwebsocket/handler.py", line 82, in run_application
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self.process_result()
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 1040, in process_result
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self.write(data)
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 888, in write
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self._write_with_headers(data)
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 909, in _write_with_headers
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self._write(data)
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 871, in _write
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self._sendall(data)
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 845, in _sendall
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     self.socket.sendall(data)
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "/home/ubuntu/lingopal/lingopal-webrtc-with-websocket/venv/lib/python3.10/site-packages/gevent/_socketcommon.py", line 701, in sendall
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:     data_memory = _get_memory(data)
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "src/gevent/_greenlet_primitives.py", line 98, in gevent._gevent_c_greenlet_primitives.get_memory
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "src/gevent/_greenlet_primitives.py", line 121, in gevent._gevent_c_greenlet_primitives.get_memory
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]:   File "src/gevent/_greenlet_primitives.py", line 109, in gevent._gevent_c_greenlet_primitives.get_memory
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]: TypeError: memoryview: a bytes-like object is required, not 'str'
Jan 05 11:46:47 ip-172-31-94-14 bash[85045]: 2024-01-05T11:46:47Z {'HTTP_HOST': 'webrtc.lingopal.ai,webrtc.lingopal.ai', (hidden keys: 26)} failed with TypeError
```

### What I've run:

gunicorn -k "geventwebsocket.gunicorn.workers.GeventWebSocketWorker" -w 2 -b unix:webrtc.sock -m 007 wsgi:app
journalctl -f

**Comment by jamadden** [comment]
This is most likely a bug in your WSGI application, or possibly `geventwebsocket.gunicorn.workers.GeventWebSocketWorker`. One or the other of them is using a string when it should be using bytes. 

gevent doesn't magically create and send data over a socket, the application is the source of the data.
