### ISSUE TITLE
24.2.1 breaking on Github runner

### ISSUE THREAD

**Issue by hiya-andyp** [gevent/gevent#2022]
* gevent version: 24.2.1 installing through pip and requirements.txt, no version specified
* Python version: 3.10 using the alpine docker image - python:3.10-alpine
* Operating System: Ubuntu 22.04 - v: 20240212.1.0

### Description:

Our gevent in requirements.txt isn't versioned, we ran this through UAT where it picked up 23.9.1 and it worked fine (all our builds over the last few weeks have been fine). Ran it through STG just after this new release and it picked up 24.2.1 and wouldn't build. Fixing the version back to 23.9.1 in requirements.txt has resolved our build problem, but I'm guessing the issue is there for others.

```python-traceback
running build_ext
#13 22.41       generating cffi module 'build/temp.linux-x86_64-cpython-310/gevent.libuv._corecffi.c'
#13 22.41       creating build/temp.linux-x86_64-cpython-310
#13 22.41       Running '(cd  "/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf
#13 22.41       configure: error: in `/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/deps/libev':
#13 22.41       configure: error: C compiler cannot create executables
#13 22.41       See `config.log' for more details
#13 22.41       Traceback (most recent call last):
#13 22.41         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#13 22.41           main()
#13 22.41         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#13 22.41           json_out['return_val'] = hook(**hook_input['kwargs'])
#13 22.41         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
#13 22.41           return _build_backend().build_wheel(wheel_directory, config_settings,
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 404, in build_wheel
#13 22.41           return self._build_with_temp_dir(
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
#13 22.41           self.run_setup()
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
#13 22.41           exec(code, locals())
#13 22.41         File "<string>", line 465, in <module>
#13 22.41         File "<string>", line 337, in run_setup
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
#13 22.41           return distutils.core.setup(**attrs)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
#13 22.41           return run_commands(dist)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#13 22.41           dist.run_commands()
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#13 22.41           self.run_command(cmd)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
#13 22.41           super().run_command(command)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#13 22.41           cmd_obj.run()
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
#13 22.41           self.run_command("build")
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#13 22.41           self.distribution.run_command(command)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
#13 22.41           super().run_command(command)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#13 22.41           cmd_obj.run()
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
#13 22.41           self.run_command(cmd_name)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
#13 22.41           self.distribution.run_command(command)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
#13 22.41           super().run_command(command)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#13 22.41           cmd_obj.run()
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 141, in run
#13 22.41           ext.sources[0] = make_mod(self.build_temp, pre_run)
#13 22.41         File "/tmp/pip-build-env-f0ydfhe_/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 126, in make_mod
#13 22.41           pre_run(ext, ffi)
#13 22.41         File "/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/_setuputils.py", line 393, in pre_run
#13 22.41           action()
#13 22.41         File "/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/_setuplibev.py", line 55, in configure_libev
#13 22.41           system(libev_configure_command)
#13 22.41         File "/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/_setuputils.py", line 198, in system
#13 22.41           if _system(cmd, cwd=cwd, env=env, **kwargs):
#13 22.41         File "/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/_setuputils.py", line 194, in _system
#13 22.41           return check_call(cmd, cwd=cwd, env=env, **kwargs)
#13 22.41         File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
#13 22.41           raise CalledProcessError(retcode, cmd)
#13 22.41       subprocess.CalledProcessError: Command '(cd  "/tmp/pip-install-p_8vi_v7/gevent_50e2e051de3041f6bdfd81b6ce1f0caf/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 77.
#13 22.41       [end of output]
#13 22.41   
#13 22.41   note: This error originates from a subprocess, and is likely not a problem with pip.
#13 22.41   ERROR: Failed building wheel for gevent
```

### What I've run:

As above, setting the version to 23.9.1 has fixed it for us. Running docker build locally builds fine, I'm guessing this must be an issue with the Github Action environment compatibility.

**Comment by jamadden** [comment]
`configure: error: C compiler cannot create executables` says you don't have a valid tool chain installed to build extensions with.

Most likely, you ran this during the brief window where binary wheels were still being uploaded and there wasn't a binary wheel for your platform yet. Please try again; there have been no changes in binary wheels so all the same platforms should still have them available.

If this continues to be a problem, we'll need to see the output of `pip -vv` to see why it's ignoring the binary wheels.
