### ISSUE TITLE
Socket timeouts when using gevent

### ISSUE THREAD

**Issue by wayne-li2** [gevent/gevent#2036]
* gevent version: gevent==24.2.1 from PyPI (can reproduce on previous versions)
* greenlet version: greenlet==3.0.3
* Python version: Python 3.8.10
* Operating System: `uname -a` returns `aarch64 aarch64 aarch64 GNU/Linux`

### Description:

**REPLACE ME**: What are you trying to get done, what has happened, what went wrong, and what did you expect?

Hey there! We're running a Python + Django + gunicon + wsgi stack, pretty high traffic (thousands of QPS). Recently, we noticed this stack trace starting to occur. First off, reading https://www.gevent.org/api/gevent.greenlet.html, we think
> [gevent.Greenlet](https://www.gevent.org/api/gevent.greenlet.html#gevent.Greenlet) is a light-weight cooperatively-scheduled execution unit. It is a more powerful version of [greenlet.greenlet](https://www.gevent.org/api/gevent.greenlet.html#gevent.greenlet.greenlet). For general information, see [Lightweight pseudothreads](https://www.gevent.org/intro.html#greenlet-basics).
this means we should be filing with you and not greenlet.

Next, we're reading up on gevent internals to get a sense of what's going on here. I traced this code from [here](https://github.com/gevent/gevent/blob/master/src/gevent/_hub_primitives.py#L295) to [here](https://github.com/gevent/gevent/blob/master/src/gevent/_greenlet_primitives.py#L65) but I'm a bit confused here. Because it looks like we do
```python
from greenlet import greenlet
locals()['_greenlet_switch'] = greenlet.switch
```
so we are using the greenlet library here, which makes me wonder if I **should file this with greenlet instead?**

Anyways, from the trace itself, as I understand it, we're making a network request, so gevent tells this Greenlet thread to start waiting while we I/O, and switch to another greenlet thread. It looks like we finish waiting and try to get a thread to switch into [here](https://github.com/gevent/gevent/blob/master/src/gevent/_hub_primitives.py#L55). But it looks like when we try to perform the switch to the new thread [here](https://github.com/gevent/gevent/blob/master/src/gevent/_gevent_c_greenlet_primitives.pxd#L35) but we fail due to socket timeout. And unfortunately the stacktrace ends here. Does this directly link with this greenlet code [here](https://github.com/python-greenlet/greenlet/blob/937f150e07823ee03344aeeb5111c0bb371a831d/src/greenlet/greenlet.cpp#L889)? **Am I understanding the trace correctly?** Another potential understanding would be that the greenlet thread we try to wait on threw a socket.timeout. After reading the code I think this is not what happened, but could use a confirmation. 

Is this just a simple case of switching back to an existing waiting greenlet just to find that the network request has timed out and the socket closed? Or is there something deeper going on here? We're still investigating this internally but would love to get some expertise / starting guidance / previous experience.

While we are seeing this consistently, it may be hard to reproduce deterministically, since as far as we can tell, there's no consistent input factors that cause this besides potentially scale.

```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 696, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out
```

### What I've run:

in `guincorn.py`
```python
worker_class = "gevent"
...
# Enable Gevent coroutine optimization with our third-party libraries
def on_starting(server):
    import grpc.experimental.gevent as grpc_gevent # 1.45.0rc1
    import psycogreen.gevent # 1.0

    psycogreen.gevent.patch_psycopg()
    grpc_gevent.init_gevent()
```

note: some names are replaced
in <business_logic>.py
```python
@traced(name="run_a_bunch_of_functions_in_parallel", inject_span=True)
def run_a_bunch_of_functions_in_parallel(
    a_bunch_of_functions: list[Callable[[], None]], span: Span
) -> None:
    span.set_tag("num_functions.count", len(a_bunch_of_functions))

    workers = [gevent.spawn(_thread, fn, span) for fn in a_bunch_of_functions]
    gevent.joinall(workers, timeout=settings.SOME_GLOBAL_TIMEOUT) # 5 seconds
    _rethrow_exceptions_if_any(workers)

def _rethrow_exceptions_if_any(workers: list[Greenlet]) -> None:
    for worker in workers:
        if isinstance(worker.value, WorkerException):
            einfo = worker.value.args
            try:
                raise einfo[0](einfo[1]).with_traceback(einfo[2])
            except AttributeError:
                raise einfo[0](einfo[1])
```

**Comment by valkyraycho** [comment]
hey have you solved this problem?
facing the same timeout error

**Comment by wayne-li2** [comment]
Unfortunately not.

**Comment by awoimbee** [comment]
@jamadden thanks for the answer... But what does it mean at a higher level ?

As the OP, I use wsgi and gunicorn.
In the stack trace I only see src/gevent/...
So where/who should catch the error? gunicorn?

**Comment by jamadden** [comment]
What higher level? It means you have a socket timeout. There is no higher level. 

> In the stack trace I only see src/gevent/... 

Funny, I see `urllib` and `http`

> So where/who should catch the error? gunicorn?

Who created the greenlet? Who wrote the code the greenlet is running? In other words, who is normally responsible for catching exceptions?
