### ISSUE TITLE
  TypeError: 'NoneType' object is not callable, error when I finish my code

### ISSUE THREAD

**Issue by Magnarks** [gevent/gevent#2042]
* gevent version: 24.2.1
* Python version: 3.12.3 and 3.12.4
* Operating System: Windows 11 Pro

### Description:

Greetings, suddenly I get errors from gevent, when I use flask_socketio, when I terminate the local server with CTRL + C, I get errors, for example if I have "debug=True" in Flask, this error appears, Additionally, it seems that the same websocket connection does not work, but a few days ago I developed another application with websocket and did not get the problem, I reinstalled all Python, the libaries, tried downloading the version, but the error persists.

```python-traceback
Traceback (most recent call last):
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

KeyboardInterrupt
2024-06-25T15:39:01Z
Exception ignored in: <function _removeHandlerRef at 0x000001B7C66E45E0>
Traceback (most recent call last):
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 884, in _removeHandlerRef
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 241, in _acquireLock
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 198, in acquire
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\thread.py", line 67, in get_ident
TypeError: 'NoneType' object is not callable

With debug=False:

Traceback (most recent call last):
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

KeyboardInterrupt
2024-06-25T15:40:01Z
Traceback (most recent call last):
  File "c:\xampp\htdocs\ambulancetogo\python\reconocimientofacial\reconocimiento\capasalidareconocimiento.py", line 166, in <module>
    socketio.run(reconfacial, debug=False, port=port)
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_socketio\__init__.py", line 718, in run
    self.wsgi_server.serve_forever()
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src\\gevent\\event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src\\gevent\\_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src\\gevent\\_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src\\gevent\\_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

KeyboardInterrupt

```

### What I've run:

from flask_socketio import SocketIO, emit
socketio = SocketIO(reconfacial, cors_allowed_origins=["http://localhost"])
if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))  
    socketio.run(reconfacial, debug=True, port=port)

```python
from flask_socketio import SocketIO, emit
socketio = SocketIO(reconfacial, cors_allowed_origins=["http://localhost"])
if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))  
    socketio.run(reconfacial, debug=True, port=port)
```

**Comment by miguelgrinberg** [comment]
When using `debug=True` there could be an incompatiblity between Flask and gevent, really not much that can be done about that.

With `debug=False` I believe everything works well correct? You get the `KeyboardInterrupt` exception, which happens when you press Ctrl-C. Is there anything not working in this case?

**Comment by Magnarks** [comment]
> When using `debug=True` there could be an incompatiblity between Flask and gevent, really not much that can be done about that.
> 
> With `debug=False` I believe everything works well correct? You get the `KeyboardInterrupt` exception, which happens when you press Ctrl-C. Is there anything not working in this case?

When I use debug=False, I also get an exception, but it is different

```python-traceback
Traceback (most recent call last):
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument
    
KeyboardInterrupt
2024-06-25T19:01:43Z
Traceback (most recent call last):
  File "c:\xampp\htdocs\ambulancetogo\python\reconocimientofacial\reconocimiento\capasalidareconocimiento.py", line 165, in <module>
    socketio.run(reconfacial, debug=False, port=port)
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_socketio\__init__.py", line 718, in run
    self.wsgi_server.serve_forever()
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src\\gevent\\event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src\\gevent\\_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src\\gevent\\_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src\\gevent\\_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src\\gevent\\_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "C:\Users\diego\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

KeyboardInterrupt
```

Additionally, it seems that the connection is not working well, I have this on both my back and front, but the Python code of the socket is not detonating, even though the front does show me connection

```python
@socketio.on('connect')
def handle_connect():
    print("connection back")
    session_id = request.sid
    print('Client', session_id)
```

```javascript
let socket = new WebSocket("ws://localhost:5000");

socket.onopen = function(e) {
	alert("[open] Conect");
	alert("sending");
	socket.send("test conection");
};
```

**Comment by matjam** [comment]
I'm seeing this in production so it's not just when you interrupt. 

I think it's something to do with how logging is being configured but I've not nailed it down yet. We use loguru.

Would a new ticket be useful or shall I add to this one?
