### ISSUE TITLE
gevent/boto3 - s3 upload + gevent.Timeout results in "This operation would block forever"

### ISSUE THREAD

**Issue by gogglesguy** [gevent/gevent#2043]
* gevent version: `24.2.1 (pip)`
* Python version: `3.12.3 (package from Arch Linux)`
* boto3 / botocore version: `1.34.138 (pip)`
* Operating System: `Arch Linux (Linux version 6.8.9-arch1-2 (linux@archlinux) (gcc (GCC) 14.1.1 20240507, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000)`
### Description:

We're not sure whether this is a bug, or simply an unsupported feature. We have a download process that fetch data from a remote site and uploads to an S3 bucket. In case we are dealing with really slow connections, we try to protect this download/upload by setting an overall time limit. The actual code uses multiple download streams using an imap and a pipe to feed bytes to the s3.upload_fileobj. The below sample code simplifies it a bit, but the essence stays the same.

What would expect is to have the timeout triggered and reach the exception handler. Instead, we end up with `gevent.exceptions.LoopExit: This operation would block forever`. 

If this is not supported, do you have any recommendations on how you would accomplish this instead?

```python-traceback

2024-07-03 17:02:11,527 [botocore.hooks] DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2024-07-03 17:02:11,528 [botocore.hooks] DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2024-07-03 17:02:11,528 [botocore.hooks] DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2024-07-03 17:02:11,529 [botocore.hooks] DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2024-07-03 17:02:11,529 [botocore.hooks] DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2024-07-03 17:02:11,530 [botocore.hooks] DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2024-07-03 17:02:11,530 [botocore.hooks] DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2024-07-03 17:02:11,531 [botocore.hooks] DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2024-07-03 17:02:11,531 [botocore.hooks] DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2024-07-03 17:02:11,531 [botocore.hooks] DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2024-07-03 17:02:11,531 [botocore.hooks] DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2024-07-03 17:02:11,533 [botocore.utils] DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: env
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: assume-role
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: assume-role-with-web-identity
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: sso
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: shared-credentials-file
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: custom-process
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: config-file
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: ec2-credentials-file
2024-07-03 17:02:11,534 [botocore.credentials] DEBUG - Looking for credentials via: boto-config
2024-07-03 17:02:11,534 [botocore.credentials] INFO - Found credentials in boto config file: ~/.boto
2024-07-03 17:02:11,535 [botocore.loaders] DEBUG - Loading JSON file: /home/sxj/Work/api/venv/lib/python3.12/site-packages/botocore/data/endpoints.json
2024-07-03 17:02:11,545 [botocore.loaders] DEBUG - Loading JSON file: /home/sxj/Work/api/venv/lib/python3.12/site-packages/botocore/data/sdk-default-configuration.json
2024-07-03 17:02:11,545 [botocore.hooks] DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7604358c27a0>
2024-07-03 17:02:11,554 [botocore.loaders] DEBUG - Loading JSON file: /home/sxj/Work/api/venv/lib/python3.12/site-packages/botocore/data/s3/2006-03-01/service-2.json.gz
2024-07-03 17:02:11,565 [botocore.loaders] DEBUG - Loading JSON file: /home/sxj/Work/api/venv/lib/python3.12/site-packages/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json.gz
2024-07-03 17:02:11,571 [botocore.loaders] DEBUG - Loading JSON file: /home/sxj/Work/api/venv/lib/python3.12/site-packages/botocore/data/partitions.json
2024-07-03 17:02:11,572 [botocore.hooks] DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x760435a17740>
2024-07-03 17:02:11,572 [botocore.hooks] DEBUG - Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x760435697b00>
2024-07-03 17:02:11,572 [botocore.hooks] DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x760435a174c0>
2024-07-03 17:02:11,572 [botocore.configprovider] DEBUG - Looking for endpoint for s3 via: environment_service
2024-07-03 17:02:11,572 [botocore.configprovider] DEBUG - Looking for endpoint for s3 via: environment_global
2024-07-03 17:02:11,572 [botocore.configprovider] DEBUG - Looking for endpoint for s3 via: config_service
2024-07-03 17:02:11,572 [botocore.configprovider] DEBUG - Looking for endpoint for s3 via: config_global
2024-07-03 17:02:11,572 [botocore.configprovider] DEBUG - No configured endpoint found.
2024-07-03 17:02:11,573 [botocore.endpoint] DEBUG - Setting s3 timeout as (60, 60)
2024-07-03 17:02:11,574 [botocore.loaders] DEBUG - Loading JSON file: /home/sxj/Work/api/venv/lib/python3.12/site-packages/botocore/data/_retry.json
2024-07-03 17:02:11,574 [botocore.client] DEBUG - Registering retry handlers for service: s3
2024-07-03 17:02:11,575 [botocore.utils] DEBUG - Registering S3 region redirector handler
2024-07-03 17:02:11,575 [botocore.utils] DEBUG - Registering S3Express Identity Resolver
2024-07-03 17:02:11,575 [main] INFO - Starting test
2024-07-03 17:02:11,575 [boto3.s3.transfer] DEBUG - Opting out of CRT Transfer Manager. Preferred client: auto, CRT available: False, Instance Optimized: False.
2024-07-03 17:02:11,575 [boto3.s3.transfer] DEBUG - Using default client. pid: 1770091, thread: 129760466484800
2024-07-03 17:02:11,575 [s3transfer.utils] DEBUG - Acquiring 0
2024-07-03 17:02:11,575 [s3transfer.tasks] DEBUG - UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x760434dff770>}) about to wait for the following futures []
2024-07-03 17:02:11,576 [s3transfer.tasks] DEBUG - UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x760434dff770>}) done waiting for dependent futures
2024-07-03 17:02:11,576 [s3transfer.tasks] DEBUG - Executing task UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x760434dff770>}) with kwargs {'client': <botocore.client.S3 object at 0x7604366ab230>, 'config': <boto3.s3.transfer.TransferConfig object at 0x7604366a9df0>, 'osutil': <s3transfer.utils.OSUtils object at 0x7604358058b0>, 'request_executor': <s3transfer.futures.BoundedExecutor object at 0x760435a2d640>, 'transfer_future': <s3transfer.futures.TransferFuture object at 0x760434dff770>}
2024-07-03 17:02:16,579 [s3transfer.futures] DEBUG - TransferCoordinator(transfer_id=0) cancel(5 seconds) called
Traceback (most recent call last):
  File "/home/sxj/test.py", line 52, in <module>
    main()
  File "/home/sxj/test.py", line 33, in main
    s3_client.upload_fileobj(pipe, bucket_name, object_name)
  File "/home/sxj/Work/api/venv/lib/python3.12/site-packages/boto3/s3/inject.py", line 634, in upload_fileobj
    with create_transfer_manager(self, config) as manager:
  File "/home/sxj/Work/api/venv/lib/python3.12/site-packages/s3transfer/manager.py", line 609, in __exit__
    self._shutdown(cancel, cancel_msg, cancel_exc_type)
  File "/home/sxj/Work/api/venv/lib/python3.12/site-packages/s3transfer/manager.py", line 648, in _shutdown
    self._submission_executor.shutdown()
  File "/home/sxj/Work/api/venv/lib/python3.12/site-packages/s3transfer/futures.py", line 481, in shutdown
    self._executor.shutdown(wait)
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 238, in shutdown
    t.join()
  File "/usr/lib/python3.12/threading.py", line 1147, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.12/threading.py", line 1167, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sxj/Work/api/venv/lib/python3.12/site-packages/gevent/thread.py", line 112, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/gevent/_semaphore.py", line 184, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 263, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 253, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x7604366b3650 epoll default pending=0 ref=0 fileno=4 thread_ident=0x760438028740>
	Handles:
[]
```

### What I've run:

```python
from gevent import monkey

monkey.patch_all()

import boto3
import gevent.queue
import logging
import sys


logger = logging.getLogger('main')


def init_log(level='DEBUG'):
    stream_fmt = '%(asctime)s [%(name)s] %(levelname)s - %(message)s'
    logging.basicConfig(level=level, force=True, format=stream_fmt, stream=sys.stderr)


def main():
    init_log()
    s3_client = boto3.client('s3')
    pipe = DummyPipe()
    bucket_name = '<bucket-name>'
    object_name = '<object-name>'
    logger.info('Starting test')
    with gevent.Timeout(5) as timeout:
        try:
            s3_client.upload_fileobj(pipe, bucket_name, object_name)
            logger.info('Upload complete')
        except gevent.Timeout as ex:
            if ex is timeout:
                logger.info('Request timed out')
            else:
                raise
    logger.info('Test complete')


class DummyPipe:
    def __init__(self):
        self.queue = gevent.queue.Queue()

    def read(self, n):
        self.queue.get()


if __name__ == '__main__':
    main()
```

**Comment by arcivanov** [comment]
This is not boto3. This is `requests` and only on specific versions of Python: #2033

**Comment by gogglesguy** [comment]
@arcivanov doubtful. boto3/botocore does not depend on requests.

**Comment by arcivanov** [comment]
Yeah, sorry, nevermind.
