### ISSUE TITLE
"greenlet.error: cannot switch to a different thread" from monkey patched request.session() in a Singleton class

### ISSUE THREAD

**Issue by OjusWiZard** [gevent/gevent#2047]
* gevent version: 24.2.1 from PyPI
* Python version: Python 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
* Operating System: Pop!_OS 22.04 LTS x86_64

### Description:
Hi, I stumbled upon this old error "greenlet.error: cannot switch to a different thread", that happens rarely when making requests from multiple threads using one monkey patched `requests.session()` in a Singleton class.

```python-traceback
Traceback (most recent call last):
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/gevent/ssl.py", line 434, in read
    bytes_read += self._sslobj.read(nbytes, buffer)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2580)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/gevent/threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/.run/test.py", line 31, in thread_task
    Singleton.make_request()
  File "/home/ojuswi/Documents/repos/rotki/.run/test.py", line 25, in make_request
    Singleton.session.get('https://httpbin.org/get')
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/gevent/ssl.py", line 625, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ojuswi/Documents/repos/rotki/venv/lib/python3.11/site-packages/gevent/ssl.py", line 440, in read
    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
greenlet.error: cannot switch to a different thread
2024-07-26T11:21:40Z (<ThreadPoolWorker at 0x719602294100 thread_ident=0x719600e00640 threadpool-hub=<Hub at 0x719602cd1850 thread_ident=0x719604b36000>>, <function thread_task at 0x71960377a840>) failed with error
```

### What I've run:
Here's a script that reproduces this error after a few seconds of making many requests

```python
from gevent import monkey
monkey.patch_all()

from requests import session
import gevent

hub = gevent.hub.get_hub()
hub.threadpool.maxsize = 4
threadpool = gevent.get_hub().threadpool


class Singleton:
    __instance = None
    session = session()

    def __new__(cls):
        if Singleton.__instance is not None:
            return Singleton.__instance

        Singleton.__instance = object.__new__(cls)
        return Singleton.__instance

    @staticmethod
    def make_request():
        Singleton.session.get('https://httpbin.org/get')


def thread_task(name):
    for i in range(1000):
        print(f'Making request {i + 1} from {name}')
        Singleton.make_request()


for i in range(16):
    threadpool.spawn(thread_task, f'thread {i + 1}')

gevent.wait()
```

**Comment by jamadden** [comment]
You can't do that. Sockets in gevent are bound to the hub that created them, and the hub that created them is bound to a thread. (It's not clear to me that request sessions are considered thread safe anyway.) If you need to share a session object, I suggest making it thread local.
