### ISSUE TITLE
importing ctypes triggers os.register_at_fork() with assertError when a thread has already been started

### ISSUE THREAD

**Issue by ddorian** [gevent/gevent#2055]
Environment:

    Python 3.12.3
    Ubuntu 22.04

dependencies:
```
gevent==24.2.1
greenlet==3.0.3
python-magic==0.4.27
```

### Description:

The combination below ends up in the error below. The loading of the ctypes happens in https://github.com/ahupp/python-magic/blob/067399b1ae104975fe83b5162dd3b83788cdfdd0/magic/__init__.py#L234

```python
import gevent.monkey

gevent.monkey.patch_all()
# no error if we don't patch subprocess
# gevent.monkey.patch_all(subprocess=False)


import os
import threading


def hook():
    print("inside fork hook")


os.register_at_fork(after_in_child=hook)


def worker():
    while True:
        import time

        time.sleep(1)


class MyMyMy:
    def __init__(self):
        self.worker_thread = threading.Thread(target=worker, daemon=True)
        self.worker_thread.start()
        os.register_at_fork(after_in_child=self._at_fork_reinit)  # pylint: disable=protected-access

    def _at_fork_reinit(self):
        print("WHY???")
        self.worker_thread = threading.Thread(target=worker, daemon=True)
        # this line triggers the SSL assert error
        self.worker_thread.start()


m = MyMyMy()
# doing this import shows the error and executes `register_at_fork`
import magic


```
```python
/home/guru/Desktop/.venv/bin/python /home/guru/Desktop/fshije.py 
Traceback (most recent call last):
  File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
  File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
AssertionError: (None, <callback at 0x7f3609e33740 args=([],)>)
2024-09-11T13:58:38Z <callback at 0x7f3609e33740 args=([],)> failed with AssertionError

inside fork hook
WHY???
inside fork hook
WHY???
```

**Comment by alexjircan** [comment]
I think this is related to https://github.com/gevent/gevent/issues/1895

**Comment by samschlegel** [comment]
> # no error if we don't patch subprocess
> # gevent.monkey.patch_all(subprocess=False)

This is the clue, and if my experience is applicable here then the issue you're seeing is because of two things
1) The current patch implementation for subprocess is implemented in pure Python, so the Python interpreter is briefly reentered in the child process before execve is called. Because of this `os.register_at_fork` calls end up getting called since they are only not run when the interpreter is expected to not reenter.
2) [`sys.platform`](https://github.com/ahupp/python-magic/blob/067399b1ae104975fe83b5162dd3b83788cdfdd0/magic/loader.py#L55C11-L55C23) runs `uname` in a subprocess as part of it's platform detection, triggering the first issue.

I could have sworn I had opened an issue in regards to the first issue, but I can't seem to find it now. We've been whack-a-moling this issue for a few months now so it's kind of embarrassing I hadn't opened one sooner 😅 

It's EOD for me but will try and get an issue up with a minimal repro tomorrow.
