### ISSUE TITLE
test_resolution failing on Fedora rwhide

### ISSUE THREAD

**Issue by opoplawski** [gevent/gevent#2064]
* gevent version: 24.10.1 - github source
* Python version: python3-3.13.0-1.fc42.x86_64
* Operating System: Fedora rawhide x86_4

### Description:

```python-traceback
- /usr/bin/python3 -u -m unittest gevent.tests.test__fileobject gevent.tests.test__greenio gevent.tests.test__greenlet gevent.tests.test__greenletset gevent.tests.test__hub gevent.tests.test__hub_join [Ran 216 tests in 10.0s (skipped=12)]
| /usr/bin/python3 -u -m unittest gevent.tests.test__core_callback gevent.tests.test__core_stat gevent.tests.test__core_timer gevent.tests.test__core_watcher gevent.tests.test__destroy_default_loop gevent.tests.test__event
  .......F...................................................
  ======================================================================
  FAIL: test_resolution (gevent.tests.test__core_timer.TestTimerResolution.test_resolution)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/flaky.py", line 106, in m
      f(*args)
      ~^^^^^^^
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/tests/test__core_timer.py", line 153, in test_resolution
      self.assertTrue(ran_at_least_once)
      ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  AssertionError: False is not true

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/testcase.py", line 320, in _callTestMethod
      method()
      ~~~~~~^^
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/errorhandler.py", line 47, in restore_fatal_error_wrapper
      return method(self, *args, **kwargs)
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/errorhandler.py", line 34, in fatal_error_wrapper
      return method(self, *args, **kwargs)
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/testcase.py", line 182, in timeout_wrapper
      return method(self, *args, **kwargs)
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/flaky.py", line 108, in m
      _func()
      ~~~~~^^
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/flaky.py", line 59, in reraiseFlakyTestRaceCondition
      six.reraise(FlakyAssertionError,
      ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
                  FlakyAssertionError(sys.exc_info()[1]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  sys.exc_info()[2])
                  ^^^^^^^^^^^^^^^^^^
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/six.py", line 13, in reraise
      raise value.with_traceback(tb)
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/testing/flaky.py", line 106, in m
      f(*args)
      ~^^^^^^^
    File "/home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages/gevent/tests/test__core_timer.py", line 153, in test_resolution
      self.assertTrue(ran_at_least_once)
      ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  gevent.testing.flaky.FlakyAssertionError: False is not true

  ----------------------------------------------------------------------
  Ran 59 tests in 3.550s

  FAILED (failures=1)
```

### What I've run:

```
/usr/bin/python3 -m gevent.test
```
```
        GEVENTTEST_QUIET        =       True
GEVENTTEST_USE_RESOURCES        =       all
           PYTHONDEVMODE        =       1
      PYTHONFAULTHANDLER        =       true
              PYTHONPATH        =       /home/orion/fedora/python-gevent/python-gevent-24.10.1-build/BUILDROOT/usr/lib64/python3.13/site-packages
          PYTHONWARNINGS        =       default,default::DeprecationWarning,default::ResourceWarning,ignore:::site:,ignore:::pkgutil:,ignore:::importlib._bootstrap:,ignore:::importlib._bootstrap_external:,ignore:::pkg_resources._vendor.pyparsing:,ignore:::dns.namedict:,ignore:::dns.hash:,ignore:::dns.zone:
WARNING: Testing monkey-patched stdlib has been disabled
Running tests in parallel with concurrency 5 (concurrency available: 5).
```

**Comment by opoplawski** [comment]
Unfortunate to have flaky tests that fail the test run overall.
