### ISSUE TITLE
TypeError: _wrap_socket() argument 'sock' must be _socket.socket, not SSLSocket

### ISSUE THREAD

**Issue by xandaaah** [gevent/gevent#2072]
* gevent version: from PyPi, installed via UV, v24.10.3

* Python version: CPython 3.12 from Nix(OS)

* Operating System: NixOS (unstable, Linux 6.6.56, x86_64)

### Description:

I was just trying to compare the speed with Gevent versus without Gevent.

```python-traceback
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/xanderm/python/easylet/easylet/__init__.py", line 20, in <module>
    [long_op() for _ in range(0,4)]
     ^^^^^^^^^
  File "/home/xanderm/python/easylet/easylet/__init__.py", line 15, in long_op
    requests.get('https://google.com')
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xanderm/python/easylet/.venv/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/ssl.py", line 1032, in _create
    self._sslobj = self._context._wrap_socket(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _wrap_socket() argument 'sock' must be _socket.socket, not SSLSocket
```

### What I've run:

```python
import gevent as ge, typing, time
def go(func: typing.Callable) -> typing.Callable[[list[typing.Any], dict[str, typing.Any]], ge.Greenlet]:
    """Just an alias to gevent.spawn for convienence."""
    def _go(*args, **kwargs) -> ge.Greenlet:
        return ge.spawn(func, *args, **kwargs)
    return _go
           


if __name__ == '__main__':
    import gevent.monkey as gm
    gm.patch_socket()
    import requests
    def long_op():
        requests.get('https://google.com')
    t = time.time()
    ge.joinall([go(long_op)() for _ in range(0,4)])
    print(time.time() - t)
    t = time.time()
    [long_op() for _ in range(0,4)]
    print(time.time() - t)
```
### Dependency tree:
```
project_name v0.1.0
├── gevent v24.10.3
│   ├── greenlet v3.1.1
│   ├── zope-event v5.0
│   │   └── setuptools v75.2.0
│   └── zope-interface v7.1.1
│       └── setuptools v75.2.0
└── requests v2.32.3
    ├── certifi v2024.8.30
    ├── charset-normalizer v3.4.0
    ├── idna v3.10
    └── urllib3 v2.2.3
```

**Comment by jamadden** [comment]
Your bug is that you only call `gevent.monkey.patch_socket()`, but then you attempt to use SSL sockets. If you're going to do that, you also need to call `gevent.monkey.patch_ssl()`.

But using individual patching functions is an advanced technique. The recommended approach for most people is to just use `gevent.monkey.patch_all()`.
