### ISSUE TITLE
Broken pipe socket error in local dev environment

### ISSUE THREAD

**Issue by chrisdl** [gevent/gevent#215]
iMac OS X 10.8.2

Things work on and off for my local django dev environment (suddenly a request will take forever and eventually error out while at other times things will flow well. Infinite request happen about every 2 minutes and last for about 2 minutes,). This is the error thrown.
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 284, in run
    self.finish_response()
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 324, in finish_response
    self.write(data)
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 403, in write
    self.send_headers()
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 467, in send_headers
    self.send_preamble()
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 385, in send_preamble
    'Date: %s\r\n' % http_date()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 464, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags, timeout=timeleft)
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
```
```
Exception happened during processing of request from ('127.0.0.1', 61650)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 570, in __init__
    BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 641, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 464, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags, timeout=timeleft)
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
```
Any thoughts? Is this gevent?

Using gevent==1.0dev (can't seem to install older version like 1.04b or 1.03b) and greenlet==0.4.0 in a virtualenv.

**Comment by jamadden** [comment]
This seems to have been fixed in a merged commit. If you can still reproduce it in 1.1, please feel free to reopen this issue.
