### ISSUE TITLE
AttributeError: 'module' object has no attribute 'path' when try to package it as exe on windows

### ISSUE THREAD

**Issue by mamcx** [gevent/gevent#226]
I'm using https://github.com/cloudmatrix/esky for package my app on windows.  I try with both py2exe and bbfreeze, and get the same traceback:

``` python
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__teleport__.py", line 11, in <module>
  File "gevent/monkey.py", line 181, in patch_all
  File "gevent/monkey.py", line 106, in patch_thread
  File "gevent/monkey.py", line 62, in patch_module
  File "gevent/thread.py", line 28, in <module>
  File "gevent/lock.py", line 5, in <module>
  File "gevent/_semaphore.py", line 8, in <module>
AttributeError: 'module' object has no attribute 'path'
```

This is the setup:

``` python
import os
from esky import bdist_esky
from distutils.core import setup

setup(name="TeleportServer",
      version="1.2.3",
      scripts=[os.path.join('TeleportServer', 'teleport.py')],
      options={"bdist_esky":{
        "includes":['gevent._semaphore'],
        "freezer_module": "bbfreeze",
      }},
     )
```

I have  gevent 1.0rc2, win 7, python 2.7

BTW with pyinstaller this work fine

**Comment by aidynzhumakadyr** [comment]
AttributeError: module 'os' has no attribute 'path'

**Comment by aidynzhumakadyr** [comment]
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site.py", line 580, in <module>
    main()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site.py", line 557, in main
    known_paths = removeduppaths()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site.py", line 127, in removeduppaths
    dir, dircase = makepath(dir)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site.py", line 92, in makepath
    dir = os.path.join(*paths)
AttributeError: module 'os' has no attribute 'path'
