### ISSUE TITLE
Popen.communicate blocks forever when killing process trees

### ISSUE THREAD

**Issue by vladev** [gevent/gevent#293]
When using gevent.subprocess.Popen with processes that spawn other processes calling ps.kill() and then ps.communicate() will block forever.

Here is a simple test case:

	from gevent.subprocess import Popen, PIPE
	from gevent import Timeout

	ps = Popen(['bash', 'forever.sh'], close_fds=True, stdout=PIPE)
	timeout = Timeout(2)
	timeout.start()
	try:
	    print 'line', ps.stdout.readline()
	except Timeout, t:
	    print 'killing'
	    ps.kill()
	finally:
	    ps.communicate()  # will block forever

Where forever.sh looks like:

	#!/bin/bash
	while true; do
	    sleep 365d
	done;

Note that 'bash' will spawn a child 'sleep', that will block indefinitely. 

Removing the Timeouts "fixes it".

Tested with both 1.0rc2 and HEAD.

Here is the traceback when killing it with Ctrl+C:

	Traceback (most recent call last):
	  File "forever.py", line 13, in <module>
	    ps.communicate()  # will block forever
	  File "/home/work/virtual-2.7/src/gevent/gevent/subprocess.py", line 294, in communicate
	    joinall(greenlets)
	  File "/home/work/virtual-2.7/src/gevent/gevent/greenlet.py", line 400, in joinall
	    wait(greenlets, timeout=timeout)
	  File "/home/work/virtual-2.7/src/gevent/gevent/hub.py", line 616, in wait
	    return list(iwait(objects, timeout))
	  File "/home/work/virtual-2.7/src/gevent/gevent/hub.py", line 594, in iwait
	    item = waiter.get()
	  File "/home/work/virtual-2.7/src/gevent/gevent/hub.py", line 568, in get
	    return self.hub.switch()
	  File "/home/work/virtual-2.7/src/gevent/gevent/hub.py", line 331, in switch
	    return greenlet.switch(self)
	KeyboardInterrupt

**Comment by jamadden** [comment]
I think the previous comment is correct. This same behaviour can be reproduced using the standard library's `subprocess` without any gevent involvement at all.

Closing as part of gevent 1.1 triage. Please feel free to reopen or open a different issue if this still seems like a bug in gevent.
