### ISSUE TITLE
test_urllib2 is unstable

### ISSUE THREAD

**Issue by fantix** [gevent/gevent#345]
I didn't look deeply into this, just pasting for reference.

    ======================================================================
      ERROR: test_file (__main__.HandlerTests)
      ----------------------------------------------------------------------
      Traceback (most recent call last):
        File "test_urllib2.py", line 690, in test_file
          os.remove(TESTFN)
      OSError: [Errno 2] No such file or directory: '@test'
    
      ----------------------------------------------------------------------
      Ran 34 tests in 0.075s
    
      FAILED (errors=1)
      Traceback (most recent call last):
        File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
          "__main__", fname, loader, pkg_name)
        File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
          exec code in run_globals
        File "/home/travis/build/fantix/gevent/greentest/monkey_test.py", line 34, in <module>
          exec(module_code, globals())
        File "test_urllib2.py", line 1277, in <module>
          test_main(verbose=True)
        File "test_urllib2.py", line 1274, in test_main
          test_support.run_unittest(*tests)
        File "/home/travis/build/fantix/gevent/greentest/test_support.py", line 517, in run_unittest
          run_suite(suite, testclass)
        File "/home/travis/build/fantix/gevent/greentest/test_support.py", line 502, in run_suite
          raise TestFailed(err)
      test_support.TestFailed: Traceback (most recent call last):
        File "test_urllib2.py", line 690, in test_file
          os.remove(TESTFN)
      OSError: [Errno 2] No such file or directory: '@test'
    ! GEVENT_RESOLVER=thread /usr/bin/python2.6 -u -m monkey_test --Event test_urllib2.py [code 255] [took 0.4s]

Also for Python 2.7.

**Comment by jamadden** [comment]
I haven't seen this on Travis or locally at all. There are a few tests that Travis sometimes fails, but this doesn't seem to be one of them. I'm going to go ahead and close this since it's a year and a half old; please feel free to reopen if you see this again.

**Comment by fantix** [comment]
Okay no problem!
