### ISSUE TITLE
gunicorn worker-class 

### ISSUE THREAD

**Issue by aztrock** [gevent/gevent#428]
2014-04-20 22:45:32 [29867] [INFO] Starting gunicorn 18.0
2014-04-20 22:45:32 [29867] [INFO] Listening at: http://0.0.0.0:8000 (29867)
2014-04-20 22:45:32 [29867] [INFO] Using worker: gevent
2014-04-20 22:45:32 [29870] [INFO] Booting worker with pid: 29870
2014-04-20 22:45:32 [29871] [INFO] Booting worker with pid: 29871
2014-04-20 22:45:32 [29872] [INFO] Booting worker with pid: 29872

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/baseserver.py", line 140, in _do_read
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/baseserver.py", line 140, in _do_read
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/baseserver.py", line 140, in _do_read
    args = self.do_read()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/server.py", line 99, in do_read
    args = self.do_read()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/server.py", line 93, in do_read
    return socket(client_socket), address
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/_socket3.py", line 37, in __init__
    args = self.do_read()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/server.py", line 93, in do_read
    client_socket, address = self.socket.accept()
    _socket.socket.__init__(self, family, type, proto, fileno)
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/_socket3.py", line 124, in accept
TypeError: an integer is required (got type socket)
    client_socket, address = self.socket.accept()
    self._wait(self._read_event)
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/_socket3.py", line 95, in _wait
    self.hub.wait(watcher)
<StreamServer at 0xb6d3e4ec fileno=5 address=0.0.0.0:8000 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0xb6d3e44c>>, <gunicorn.sock.TCPSocket object at 0xb6d3e70c>)> failed with TypeError

  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/_socket3.py", line 124, in accept
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 354, in wait
    self._wait(self._read_event)
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/_socket3.py", line 95, in _wait
    self.hub.wait(watcher)
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 354, in wait
    result = waiter.get()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 581, in get
    return self.hub.switch()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 343, in switch
    switch_out()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 347, in switch_out
    raise AssertionError('Impossible to call blocking function in the event loop callback')
AssertionError: Impossible to call blocking function in the event loop callback
    result = waiter.get()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 581, in get
    return self.hub.switch()
  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 343, in switch
    switch_out()
<StreamServer at 0xb6c54eec fileno=5 address=0.0.0.0:8000 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0xb6d3e76c>>, <gunicorn.sock.TCPSocket object at 0xb6d3e70c>)> failed with AssertionError

  File "/opt/repositories/billing/local/lib/python3.3/site-packages/gevent/hub.py", line 347, in switch_out
    raise AssertionError('Impossible to call blocking function in the event loop callback')
AssertionError: Impossible to call blocking function in the event loop callback
<StreamServer at 0xb6d3e4ec fileno=5 address=0.0.0.0:8000 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0xb6d3e40c>>, <gunicorn.sock.TCPSocket object at 0xb6d3e70c>)> failed with AssertionError

**Comment by jamadden** [comment]
Fixed in #413.
