### ISSUE TITLE
gevent (master branch) require cython to be present to execute setup.py

### ISSUE THREAD

**Issue by mouadino** [gevent/gevent#490]
Hi,

```
$ pip install git+https://github.com/surfly/gevent.git#egg=gevent
Downloading/unpacking gevent from git+https://github.com/surfly/gevent.git
  Cloning https://github.com/surfly/gevent.git to ./build/gevent
  Running setup.py (path:/Users/mouadbenchchaoui/test/build/gevent/setup.py) egg_info for package gevent
    /Users/mouadbenchchaoui/test/bin/python util/cythonpp.py -o gevent.corecext.c gevent/core.ppyx
    Running cython -o gevent.corecext.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && !defined(_WIN32)
    sh: cython: command not found
    Traceback (most recent call last):
      File "util/cythonpp.py", line 772, in <module>
        process_filename(filename, options.output_file)
      File "util/cythonpp.py", line 87, in process_filename
        output = run_cython(pyx_filename, sourcehash, output_filename, banner, comment)
      File "util/cythonpp.py", line 535, in run_cython
        system(command, comment)
      File "util/cythonpp.py", line 545, in system
        raise AssertionError('%r failed with code %s' % (command, result))
    AssertionError: 'cython -o gevent.corecext.c gevent/core.pyx' failed with code 32512
    make: *** [gevent/gevent.corecext.c] Error 1
    Running 'make' in /Users/mouadbenchchaoui/test/build/gevent
    Complete output from command python setup.py egg_info:
    /Users/mouadbenchchaoui/test/bin/python util/cythonpp.py -o gevent.corecext.c gevent/core.ppyx

Running cython -o gevent.corecext.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && !defined(_WIN32)

sh: cython: command not found

Traceback (most recent call last):

  File "util/cythonpp.py", line 772, in <module>

    process_filename(filename, options.output_file)

  File "util/cythonpp.py", line 87, in process_filename

    output = run_cython(pyx_filename, sourcehash, output_filename, banner, comment)

  File "util/cythonpp.py", line 535, in run_cython

    system(command, comment)

  File "util/cythonpp.py", line 545, in system

    raise AssertionError('%r failed with code %s' % (command, result))

AssertionError: 'cython -o gevent.corecext.c gevent/core.pyx' failed with code 32512

make: *** [gevent/gevent.corecext.c] Error 1

Running 'make' in /Users/mouadbenchchaoui/test/build/gevent
```

Now this problem happen because gevent run make for also a call like `python setup.py egg_info`, the fun part is even with a call like `python setup.py --help` the same error will show up :).

This is a known problem in pip (please refer to: https://github.com/pypa/pip/issues/25), other has worked around it (for example check https://github.com/Unidata/netcdf4-python/pull/257/files), setuptools have something for this **setup_requires**, distutils not so much. All of this are just solution that come to my mind, sadly I am not sure of the reason for the make call there, so sorry but I can't help any further.

**Comment by gitaarik** [comment]
I'm trying to install the master branch with pip like:

    pip install git+https://github.com/gevent/gevent.git

But fails with the same error. Shouldn't this installation also work without cython as a dependency?

**Comment by jamadden** [comment]
Installing from a git checkout will require require cython. This is normal and expected. Release archives on PyPI have already had cython run on them, but a development version has to have cython.
