### ISSUE TITLE
Invalid switch into greenlet

### ISSUE THREAD

**Issue by Perlence** [gevent/gevent#499]
I'm using SQLAlchemy + MySQL Connector and Celery with gevent concurrency. Sometimes this happens:

```
[2014-10-19 04:45:43,156: ERROR/MainProcess] Exception during reset or similar
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 557, in _finalize_fairy
    fairy._reset(pool, echo)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 688, in _reset
    pool._dialect.do_rollback(self)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2196, in do_rollback
    dbapi_connection.rollback()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/mysql/connector/connection.py", line 1415, in rollback
    self._execute_query("ROLLBACK")
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/mysql/connector/connection.py", line 1429, in _execute_query
    self.cmd_query(query)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/mysql/connector/connection.py", line 683, in cmd_query
    statement))
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/mysql/connector/connection.py", line 475, in _send_cmd
    return self._socket.recv()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/mysql/connector/network.py", line 190, in recv_plain
    packet = self.sock.recv(1)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gevent/socket.py", line 392, in recv
    self._wait(self._read_event)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gevent/socket.py", line 298, in _wait
    self.hub.wait(watcher)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gevent/hub.py", line 342, in wait
    assert result is unique, 'Invalid switch into %s: %r (expected %r)' % (getcurrent(), result, unique)
AssertionError: Invalid switch into <TracingGreenlet at 0x6341d70: <bound method Crawler.process of ...>: <gevent.event.AsyncResult object at 0x4b3e510> (expected <object object at 0x5860970>)
```

When I shutdown Celery after this exception, I get:

```
[2014-10-19 19:53:40,440: ERROR/MainProcess] Error on stopping Pool: LoopExit('This operation would block forever',)
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 155, in send_all
    fun(parent, *args)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 378, in stop
    return self.obj.stop()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/celery/concurrency/base.py", line 123, in stop
    self.on_stop()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/celery/concurrency/gevent.py", line 115, in on_stop
    self._pool.join()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gevent/pool.py", line 100, in join
    self._empty_event.wait(timeout=timeout)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
```

TracingGreenlet is a subclass of Greenlet that persists `exc_info`:

```python
class TracingGreenlet(gevent.Greenlet):
    def pop_exc_info(self):
        if hasattr(self, '_exc_info'):
            exc_info = self._exc_info
            del self._exc_info
            return exc_info

    def _report_error(self, exc_info):
        super(TracingGreenlet, self)._report_error(exc_info)
        if hasattr(self, '_exception'):
            self._exc_info = exc_info
```

**Comment by jamadden** [comment]
Are you using the C extensions to MySQL connector? I believe those cannot be properly monkey patched to work well with gevent. I don't know what causes this specific error but it's conceivable that they might have something to do with it. You might try using the pure-Python version. Alternately, I've had good experiences under gevent with either [PyMySQL](https://pypi.python.org/pypi/PyMySQL) or the combination of [umysql](https://pypi.python.org/pypi/umysql) and [umysqldb](https://pypi.python.org/pypi/umysqldb).

**Comment by Perlence** [comment]
Thank you for response. I've replaced Celery with simple ZeroMQ worker and switched to PyMySQL, so these errors no longer occur to me. To use PyMySQL was my first thought back then, but as far as I remember, it didn't help. Sorry, I guess I can't provide more info on this matter :disappointed:

**Comment by jamadden** [comment]
Ok, closing as a "can't-reproduce".
