### ISSUE TITLE
Syntax error when Gunicorn with Python 3.4

### ISSUE THREAD

**Issue by Kmaschta** [gevent/gevent#515]
Hi there !

I have this traceback when I run gevent with gunicorn in Python 3.4.2 

`gunicorn ${DJANGO_WSGI_MODULE}:application --name $NAME --workers 4 --timeout 120 --user=root --group=root --log-level=debug --bind=unix:/var/run/gunicorn.sock --worker-class gevent`

    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management

    Error: class uri 'gevent' invalid or not found: 

    [Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 139, in load_class
        mod = import_module('.'.join(components))
      File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 20, in <module>
        import gevent
      File "/usr/local/lib/python3.4/site-packages/gevent/__init__.py", line 36, in <module>
        from gevent.hub import get_hub, iwait, wait
      File "/usr/local/lib/python3.4/site-packages/gevent/hub.py", line 282
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax
    ]
    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management

    Error: class uri 'gevent' invalid or not found: 

    [Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 139, in load_class
        mod = import_module('.'.join(components))
      File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 20, in <module>
        import gevent
      File "/usr/local/lib/python3.4/site-packages/gevent/__init__.py", line 36, in <module>
        from gevent.hub import get_hub, iwait, wait
      File "/usr/local/lib/python3.4/site-packages/gevent/hub.py", line 282
        except Exception, ex:
                    ^
    SyntaxError: invalid syntax
    ]

    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
    
    Error: class uri 'gevent' invalid or not found: 
    
    [Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 139, in load_class
        mod = import_module('.'.join(components))
      File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 20, in <module>
        import gevent
      File "/usr/local/lib/python3.4/site-packages/gevent/__init__.py", line 36, in <module>
        from gevent.hub import get_hub, iwait, wait
      File "/usr/local/lib/python3.4/site-packages/gevent/hub.py", line 282
        except Exception, ex:
                    ^
    SyntaxError: invalid syntax
    ]
    
    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
    
    Error: class uri 'gevent' invalid or not found: 
    
    [Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 139, in load_class
        mod = import_module('.'.join(components))
      File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 20, in <module>
        import gevent
      File "/usr/local/lib/python3.4/site-packages/gevent/__init__.py", line 36, in <module>
        from gevent.hub import get_hub, iwait, wait
      File "/usr/local/lib/python3.4/site-packages/gevent/hub.py", line 282
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax

**Comment by avalanchy** [comment]
https://github.com/gevent/gevent/commit/f6489daf471cc5e3f08eb6713f56b00338c06554 again removed to achieve python 2.5 support

**Comment by smurfix** [comment]
Quite frankly, I fail to understand why supporting 2.5 seems to be more important that supporting 3.x.

**Comment by jamadden** [comment]
Please note that the change in question was only in the 1.0.2 released branch, and the 1.0.x series supports Python 2.5-2.7. It has no impact on the Python 3 support added in master. You can see those builds all passing on Travis.

**Comment by jamadden** [comment]
Closing this issue because it was a case of trying to use gevent 1.0.1 under Python 3, which is not supported. At this time, only unreleased master can be used under Python 3.
