### ISSUE TITLE
pywsgi AttributeError: 'socket' object has no attribute '_sock'

### ISSUE THREAD

**Issue by Linn9** [gevent/gevent#530]
Traceback (most recent call last):
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/gevent/pywsgi.py", line 225, in handle
    self.socket.sendall(response_body)
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/gevent/_socket3.py", line 301, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/gevent/_socket3.py", line 25, in _get_memory
    return memoryview(string)[offset:]
TypeError: memoryview: str object does not have the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/gevent/pywsgi.py", line 235, in handle
    self.socket._sock.recv(16384)
AttributeError: 'socket' object has no attribute '_sock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/gevent/greenlet.py", line 340, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/home/linn/virtualenvs/test01/lib/python3.4/site-packages/gevent/pywsgi.py", line 237, in handle
    self.socket._sock.close()  # do not rely on garbage collection
AttributeError: 'socket' object has no attribute '_sock'
<Greenlet at 0x7f17e396c5a0: <bound method SocketIOServer.handle of <SocketIOServer at 0x7f17e8b262e8 fileno=6 address=0.0.0.0:8000>>(<gevent._socket3.socket object, fd=9, family=2, ty, ('127.0.0.1', 49780))> failed with AttributeError

**Comment by jamadden** [comment]
With the merging of #581 I believe this should be fixed. I'm going to close this for now but please reopen if it's still a problem.

**Comment by QGB** [comment]
```
python3 wsgi.py
Traceback (most recent call last):
  File "wsgi.py", line 18, in <module>
    http_server.listen(8080)
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 166, in add_sockets
    sock, self._handle_connection
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\netutil.py", line 246, in add_accept_handler
    io_loop = IOLoop.current()
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\ioloop.py", line 263, in current
    loop = asyncio.get_event_loop()
  File "C:\QGB\Anaconda3\lib\asyncio\events.py", line 640, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "C:\QGB\Anaconda3\lib\asyncio\events.py", line 660, in new_event_loop
    return self._loop_factory()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 55, in __init__
    self._make_self_pipe()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 102, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "C:\QGB\Anaconda3\lib\socket.py", line 516, in socketpair
    lsock.bind((host, 0))
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
Exception ignored in: <function BaseEventLoop.__del__ at 0x0000029316308288>
Traceback (most recent call last):
  File "C:\QGB\Anaconda3\lib\asyncio\base_events.py", line 620, in __del__
    self.close()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 86, in close
    self._close_self_pipe()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 93, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_WindowsSelectorEventLoop' object has no attribute '_ssock'
D:\test\lean-flask>python3 wsgi.py
('C:/test/m.51kxiaoshuo.com/', 'http://m.51kxiaoshuo.com/', 'm.51kxiaoshuo.com')
Traceback (most recent call last):
  File "wsgi.py", line 18, in <module>
    http_server.listen(8080)
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 166, in add_sockets
    sock, self._handle_connection
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\netutil.py", line 246, in add_accept_handler
    io_loop = IOLoop.current()
  File "C:\QGB\Anaconda3\lib\site-packages\tornado\ioloop.py", line 263, in current
    loop = asyncio.get_event_loop()
  File "C:\QGB\Anaconda3\lib\asyncio\events.py", line 640, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "C:\QGB\Anaconda3\lib\asyncio\events.py", line 660, in new_event_loop
    return self._loop_factory()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 55, in __init__
    self._make_self_pipe()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 102, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "C:\QGB\Anaconda3\lib\socket.py", line 516, in socketpair
    lsock.bind((host, 0))
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
Exception ignored in: <function BaseEventLoop.__del__ at 0x000001E17F857288>
Traceback (most recent call last):
  File "C:\QGB\Anaconda3\lib\asyncio\base_events.py", line 620, in __del__
    self.close()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 86, in close
    self._close_self_pipe()
  File "C:\QGB\Anaconda3\lib\asyncio\selector_events.py", line 93, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_WindowsSelectorEventLoop' object has no attribute '_ssock'
```
