### ISSUE TITLE
KeyError in threading._shutdown() ignored

### ISSUE THREAD

**Issue by bobgrigoryan** [gevent/gevent#534]
using latest gevent (trunk/1.1.0dev) on PyPy 2.4.0.

this error appear on application shutdown.

minimal code to reproduce problem:
```python
import gevent.monkey; gevent.monkey.patch_all()
```

output (i've added some debug prints):
```
MainThread created
patching gevent thread
importing gevent threading
Exception KeyError: KeyError(140362117422288L,) in threading._shutdown() ignored
```

and the system-wide threading is imported from:
```
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "gevent.keyerror.shutdown.py", line 1, in <module>
    import gevent.monkey; gevent.monkey.patch_all()
  File "/srv/python-envs/swarm.pypy240/site-packages/gevent/__init__.py", line 42, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "/srv/python-envs/swarm.pypy240/site-packages/gevent/hub.py", line 8, in <module>
    import greenlet  # http://pypi.python.org/pypi/greenlet/
  File "/usr/lib/pypy/lib_pypy/greenlet.py", line 128, in <module>
    from threading import local as _local
  File "/usr/lib/pypy/lib-python/2.7/threading.py", line 4
    traceback.
             ^
SyntaxError: invalid syntax
```
from similar issues i'm aware that this problem occurs when mainthread is created before monkey-patching thread module.

and of course in case if gevent.monkey.patch_all(thread=False) this error dissappears.

**Comment by jamadden** [comment]
Although this is a harmless message, I believe it was fixed in fecd8d52364dde3094c9ca6c3ee665d038eed9eb which was merged a little while ago.
