### ISSUE TITLE
LoopExit: This operation would block forever

### ISSUE THREAD

**Issue by pikeszfish** [gevent/gevent#585]
I use psycopg2_pool.py from https://github.com/gevent/gevent/blob/master/examples/psycopg2_pool.py 
in my django project.
https://gist.github.com/pikeszfish/83c24e34c3ccaec4c4a8

I use a connection pool imported from psycopg2_pool.py and execute some sql.
However sometimes I got this error:
```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "path/to/project/web/helper.py", line 151, in _decorator
    return func(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)

  File "path/to/project/web/api.py", line 611, in download_trackpoints
    former_result = get_trackpoints(workout.id)

  File "path/to/project/web/helper.py", line 1616, in get_trackpoints
    result = pool.fetchone(final_sql)

  File "path/to/project/web/singleton.py", line 138, in fetchone
    with self.cursor(**kwargs) as cursor:

  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()

  File "path/to/project/web/singleton.py", line 121, in cursor
    with self.connection(isolation_level) as conn:

  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()

  File "path/to/project/web/singleton.py", line 93, in connection
    conn = self.get_one()

  File "path/to/project/web/singleton.py", line 70, in get_one
    return pool.get()

  File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 200, in get
    result = waiter.get()

  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 575, in get
    return self.hub.switch()

  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)

LoopExit: This operation would block forever
```

**Comment by jamadden** [comment]
A `LoopExit` is raised when the there's nothing else for the Hub to switch to. That is, there's only one greenlet running in the hub and it wants to switch out---but there's nothing to switch to. All other greenlets have exited (or aren't running in the hub). Is your entire process monkey-patched at an early stage so that the listening socket (at least) is running in a greenlet?

**Comment by ml31415** [comment]
I'm facing the same problem. It seems to happen randomly on e.g. calls to the logging module, which uses some monkeypatched semaphores. Given the number of error reports (psycopg2, paramiko, me), this is imho not just a question but an ordinary bug waiting for a fix. I'll try to get a simple demonstrator together.

**Comment by wpdevs** [comment]
This is happening to me too

**Comment by twall** [comment]
I see this happen when using celery (but _not_ its gevent pool).  After a celery main worker child process is killed, the main worker tries to register the failure with its redis backend, and results in this error:
```[2016-01-11 21:47:29,430: ERROR/MainProcess] Pool callback raised exception: LoopExit('This operation would block forever',)
Traceback (most recent call last):
  File "/opt/venvs/current/lib/python2.7/site-packages/billiard/pool.py", line 1700, in safe_apply_callback
    fun(*args, **kwargs)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/job.py", line 433, in on_failure
    self.id, exc, request=self,
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/backends/base.py", line 121, in mark_as_failure
    traceback=traceback, request=request)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/backends/base.py", line 254, in store_result
    request=request, **kwargs)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/backends/base.py", line 487, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/opt/venvs/current/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/backends/redis.py", line 169, in _set
    pipe.execute()
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/client.py", line 1987, in execute
    return execute(conn, stack, raise_on_error)
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/client.py", line 1877, in _execute_transaction
    self.parse_response(connection, '_')
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/client.py", line 1950, in parse_response
    self, connection, command_name, **options)
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/client.py", line 404, in parse_response
    response = connection.read_response()
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/connection.py", line 311, in read_response
    response = self._parser.read_response()
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/connection.py", line 105, in read_response
    response = self.read()
  File "/opt/venvs/current/lib/python2.7/site-packages/redis/connection.py", line 90, in read
    return self._fp.readline()[:-2]
  File "/usr/local/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
  File "/opt/venvs/current/lib/python2.7/site-packages/gevent/socket.py", line 394, in recv
    self._wait(self._read_event)
  File "/opt/venvs/current/lib/python2.7/site-packages/gevent/socket.py", line 300, in _wait
    self.hub.wait(watcher)
  File "/opt/venvs/current/lib/python2.7/site-packages/gevent/hub.py", line 348, in wait
    result = waiter.get()
  File "/opt/venvs/current/lib/python2.7/site-packages/gevent/hub.py", line 575, in get
    return self.hub.switch()
  File "/opt/venvs/current/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever```

**Comment by davidkhess** [comment]
Seeing this also with boto3 in a frozen app:

```
Traceback (most recent call last):
  File "lib\site-packages\boto3\s3\transfer.py", line 375, in upload_file
  File "lib\site-packages\boto3\s3\transfer.py", line 400, in _upload_parts
  File "concurrent\futures\_base.py", line 549, in result_iterator
  File "concurrent\futures\_base.py", line 395, in result
  File "concurrent\futures\_base.py", line 354, in __get_result
  File "concurrent\futures\thread.py", line 54, in run
  File "lib\site-packages\boto3\s3\transfer.py", line 413, in _upload_one_part
  File "lib\site-packages\botocore\client.py", line 310, in _api_call
  File "lib\site-packages\botocore\client.py", line 396, in _make_api_call
  File "lib\site-packages\botocore\endpoint.py", line 111, in make_request
  File "lib\site-packages\botocore\endpoint.py", line 140, in _send_request
  File "lib\site-packages\botocore\endpoint.py", line 213, in _needs_retry
  File "lib\site-packages\botocore\hooks.py", line 226, in emit
  File "lib\site-packages\botocore\hooks.py", line 209, in _emit
  File "lib\site-packages\botocore\retryhandler.py", line 183, in __call__
  File "lib\site-packages\botocore\retryhandler.py", line 250, in __call__
  File "lib\site-packages\botocore\retryhandler.py", line 265, in _should_retry
  File "lib\site-packages\botocore\retryhandler.py", line 313, in __call__
  File "lib\site-packages\botocore\retryhandler.py", line 222, in __call__
  File "lib\site-packages\botocore\retryhandler.py", line 355, in _check_caught_exception
  File "lib\site-packages\botocore\endpoint.py", line 168, in _get_response
  File "lib\site-packages\botocore\vendored\requests\sessions.py", line 573, in send
  File "lib\site-packages\botocore\vendored\requests\adapters.py", line 370, in send
  File "lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
  File "lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
  File "http\client.py", line 1137, in request
  File "lib\site-packages\botocore\awsrequest.py", line 129, in _send_request
  File "http\client.py", line 1182, in _send_request
  File "http\client.py", line 1133, in endheaders
  File "lib\site-packages\botocore\awsrequest.py", line 164, in _send_output
  File "lib\site-packages\botocore\awsrequest.py", line 207, in _handle_expect_response
  File "lib\site-packages\botocore\awsrequest.py", line 234, in _send_message_body
  File "lib\site-packages\botocore\awsrequest.py", line 241, in send
  File "http\client.py", line 926, in send
  File "lib\site-packages\gevent\_ssl3.py", line 278, in sendall
  File "lib\site-packages\gevent\_socket3.py", line 350, in sendall
  File "lib\site-packages\gevent\_ssl3.py", line 249, in send
  File "lib\site-packages\gevent\_socket3.py", line 134, in _wait
  File "lib\site-packages\gevent\hub.py", line 606, in wait
  File "lib\site-packages\gevent\hub.py", line 854, in get
  File "lib\site-packages\gevent\hub.py", line 585, in switch
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x1b416c0 select pending=0 ref=0>)
```

**Comment by davidkhess** [comment]
Hhhmm, I was using `gevent.monkey.patch_all(thread=False)`.

Is this what it looks like if a different thread tries to access the main thread's hub?

**Comment by davidkhess** [comment]
Switching to `gevent.monkey.patch_all()` fixed it.

So, based on my limited evidence, it appears this case is indicative of an improper access of gevent from another real thread other than the main thread that owns the gevent hub.

**Comment by twall** [comment]
I’m using event.monkey.patch_all().

The error only happens in mainProcess (that I’ve seen) when handling a lost child process due to SIGKILL.  Normally mainProcess doesn’t use gevent at all (I’m not using any of celery’s gevent support), but when it gets the child killed signal it tries to send a result out to the backend (redis) and encounters this error from the hub.

It sort of makes sense that the hub should exit given that there are no other gevent tasks in mainProcess, but on the other hand I’m not sure how to avoid it.  How might I launch a fake greenlet or otherwise avoid the LoopExit error?  Or maybe it’s innocuous, it’s not clear to me whether the result actually gets saved and the error happens after successful storage of the killed task result.

**Comment by davidkhess** [comment]
Are you using `event.monkey.patch_all()` before almost all other imports? It could be that some module is using an unpatched one. Or it could be that a C module or external library is using native threads internally.

If something is creating a thread, it's possible a threading issue is caused by the signal module - according to the documentation, signals are always delivered to the main thread and that might be a different thread than the one Redis is using gevent on.

**Comment by jamadden** [comment]
Closing in triage for 1.2 because there have been no updates since February and this seems to be caused by delayed/incomplete monkey-patching. Feel free to reopen if there is new information.

**Comment by brandonmp** [comment]
Was hitting this error using `boto3` in aws lambda after using `grequests.map` elsewhere in the program.

the only thing that fixed it was reloading monkeypatched modules before calling `boto3`. eg, 
```
import sys
import os
import socket
import ssl
import boto3
import grequests

# do grequest stuff

reload(sys)
reload(os)
reload(socket)
reload(ssl)
# do boto stuff
# then i guess monkeypatch again if you need it, i didn't
```


Not a python guy but thought this might be helpful to anyone finding similar problems.

**Comment by giorgiosironi** [comment]
Notice it is `grequests` using the monkey patching, while this project seems not to make it mandatory:
https://github.com/kennethreitz/grequests/blob/master/grequests.py#L15
My solution is that I remove `grequests` from my application.

**Comment by rkeerdo93** [comment]
I'm also getting the issue - 

    Apr 07 12:44:06 motor-ecu-1002 python[462]: Traceback (most recent call last):
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/motor/main.py", line 151, in outbound_ws_handler
    Apr 07 12:44:06 motor-ecu-1002 python[462]: socket.send(msg_out_buf)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/geventwebsocket/websocket.py", line 344, in send
    Apr 07 12:44:06 motor-ecu-1002 python[462]: self.send_frame(message, opcode)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/geventwebsocket/websocket.py", line 329, in send_frame
    Apr 07 12:44:06 motor-ecu-1002 python[462]: self.raw_write(header + message)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/gevent/_socket3.py", line 395, in sendall
    Apr 07 12:44:06 motor-ecu-1002 python[462]: data_sent += self.send(data_memory[data_sent:], flags)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/gevent/_socket3.py", line 375, in send
    Apr 07 12:44:06 motor-ecu-1002 python[462]: self._wait(self._write_event)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/gevent/_socket3.py", line 144, in _wait
    Apr 07 12:44:06 motor-ecu-1002 python[462]: self.hub.wait(watcher)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/gevent/hub.py", line 630, in wait
    Apr 07 12:44:06 motor-ecu-1002 python[462]: result = waiter.get()
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/gevent/hub.py", line 878, in get
    Apr 07 12:44:06 motor-ecu-1002 python[462]: return self.hub.switch()
    Apr 07 12:44:06 motor-ecu-1002 python[462]: File "/root/motor/venv/lib/python3.4/site-packages/gevent/hub.py", line 609, in switch
    Apr 07 12:44:06 motor-ecu-1002 python[462]: return greenlet.switch(self)
    Apr 07 12:44:06 motor-ecu-1002 python[462]: gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0xb07d31c0 epoll pending=0 ref=0 fileno=22>)

My application uses multiprocessing to start the web server in another process, and monkeypatches using the thread=False flag (otherwise it would fuck up my motor controller threads, resulting in random movements and messages across the bus being corrupted to shit). Is there a way to catch the exception? My code, where it happens, is already encapsulated in try/except, but it doesn't do anything.

**Comment by i3wangyi** [comment]
Hi I'm running into the same issue as well. Using Python3.6.4, redis==2.10.6, gevent==1.2.2, the issue only occurs in multithreads executions:

The stacktrace:
```
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/CryptoAnt.py", line 187, in get_local_best_trade_option
    return TradeOption.generate_trade_option(exchange_option, buy_orderbooks['ask'], sell_orderbooks['bid'])
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/CryptoAnt.py", line 135, in generate_trade_option
    last_profit_json = cache.get_last_profit_model(exchange_option)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/Cache.py", line 67, in get_last_profit_model
    if self.client.hexists(name=self.profit_index, key=key):
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/client.py", line 1959, in hexists
    return self.execute_command('HEXISTS', name, key)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/gevent/_socket3.py", line 336, in recv
    self._wait(self._read_event)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/gevent/_socket3.py", line 156, in _wait
    self.hub.wait(watcher)
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/gevent/hub.py", line 651, in wait
    result = waiter.get()
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/gevent/hub.py", line 898, in get
    return self.hub.switch()
  File "/Users/ywang4/Dropbox/workspace/CryptoAnt/ENV/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x10b2a0c28 select pending=0 ref=0>)
```
