### ISSUE TITLE
Cannot import core from module gevent.__init__.py

### ISSUE THREAD

**Issue by FirefighterBlu3** [gevent/gevent#598]
```pytb
2015-07-01 19:08:46 C 0.8 Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/gevent/hub.py", line 187, in get_hub
    return _threadlocal.hub
    AttributeError: '_thread._local' object has no attribute 'hub'
    
During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "abuse.api.py", line 1856, in <module>
    main(opts, config)
      File "abuse.api.py", line 1539, in main
    cams.id     = socket.getfqdn().split('.',1)[0] +'/'+config.get('CAMS', 'id')
      File "/usr/lib/python3.4/site-packages/gevent/_socketcommon.py", line 219, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
      File "/usr/lib/python3.4/site-packages/gevent/_socketcommon.py", line 199, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
      File "/usr/lib/python3.4/site-packages/gevent/hub.py", line 190, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
      File "/usr/lib/python3.4/site-packages/gevent/hub.py", line 289, in __init__
    loop_class = _import(self.loop_class)
      File "/usr/lib/python3.4/site-packages/gevent/hub.py", line 219, in _import
    return _import(path[-1])
      File "/usr/lib/python3.4/site-packages/gevent/hub.py", line 236, in _import
    raise ImportError('Cannot import %r from %r' % (attr, oldx))
    ImportError: Cannot import 'core' from <module 'gevent' from '/usr/lib/python3.4/site-packages/gevent/__init__.py'>
```

**Comment by jamadden** [comment]
Based on the line numbers, you appear to be using a source checkout of gevent/master that's several days old. It's **great** to see people testing based on master! It might save time though if, when reporting an issue, that fact was mentioned; it would also help to update to the latest master and see if the issue still exists and report with the current line numbers.

On CPython, `gevent.core` is implemented as a compiled C extension. The most common cause of not being able to import it is a missing `core.so`; this would mean the installation/compilation step (e.g., `python setup.py develop` or `python setup.py build`) was skipped. Another possible reason (though this usually results in a slightly different error) is trying to use a binary gevent compiled for a different Python version or build; that doesn't always work.

**Comment by FirefighterBlu3** [comment]
unfortunately this bug report is misplaced effort :-/ i had an unsaved include that monkey patched threading. my apologies (and noted)
