### ISSUE TITLE
SSL Broken for Python 2.7.10 on Windows

### ISSUE THREAD

**Issue by jkndrkn** [gevent/gevent#605]
I installed Python 2.7.10 on Windows 8.1 using this installer: https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi

Here are my installed packages:

    $ pip list
    gevent (1.0.2)
    gevent-socketio (0.3.6)
    gevent-websocket (0.9.5)
    greenlet (0.4.7)
    pip (7.1.0)
    pywin32 (219)
    setuptools (16.0)

Here is the relevant portion of my script:

    import sys,os,os.path
    from ctypes import *
    import ctypes.util
    import struct
    from Tkinter import *
    import time,glob
    import win32file,win32api,win32process,win32con,win32gui

    import tkMessageBox
    import subprocess
    import threading,Queue
    import socket
    from ESCmessage import *

    from gevent import monkey
    monkey.patch_all()
    import gevent
    import greenlet

    from socketio import socketio_manage
    from socketio.server import SocketIOServer
    from socketio.namespace import BaseNamespace
    from socketio.mixins import RoomsMixin, BroadcastMixin

Here is the error message I get when executing this script:

    $ ./test.sh
    Traceback (most recent call last):
      File "test.py", line 58, in <module>
        monkey.patch_all()
      File "C:\Python27\lib\site-packages\gevent\monkey.py", line 200, in patch_all
        patch_ssl()
      File "C:\Python27\lib\site-packages\gevent\monkey.py", line 146, in patch_ssl
        patch_module('ssl')
      File "C:\Python27\lib\site-packages\gevent\monkey.py", line 62, in patch_module
        gevent_module = getattr(__import__('gevent.' + name), name)
      File "C:\Python27\lib\site-packages\gevent\ssl.py", line 5, in <module>
        from gevent import _sslgte279 as _source
      File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 11, in <module>
        import ssl as __ssl__
      File "C:\Python27\lib\ssl.py", line 100, in <module>
        from _ssl import _SSLContext
    ImportError: cannot import name _SSLContext
    Exception KeyError: KeyError(42638512,) in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

If I change `monkey.patch_all()` to `monkey.patch_socket()` I see this error instead:

    $ ./test.sh
    Traceback (most recent call last):
      File "test.py", line 63, in <module>
        from socketio.server import SocketIOServer
      File "C:\Python27\lib\site-packages\socketio\server.py", line 6, in <module>
        from gevent.pywsgi import WSGIServer
      File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 8, in <module>
        import mimetools
      File "C:\Python27\lib\mimetools.py", line 6, in <module>
        import tempfile
      File "C:\Python27\lib\tempfile.py", line 35, in <module>
        from random import Random as _Random
      File "C:\Python27\lib\random.py", line 49, in <module>
        import hashlib as _hashlib
      File "C:\Python27\lib\hashlib.py", line 138, in <module>
        _hashlib.openssl_md_meth_names)
     AttributeError: 'module' object has no attribute 'openssl_md_meth_names'

Any ideas? Have been scratching my head over this for a while. I tried moving the calls to `monkey.patch...` before importing any other modules as one site recommended and this did not help.

**Comment by jamadden** [comment]
`_ssl` is the C implementation library that wraps OpenSSL. I don't think gevent messes with it in any way. Are you able to import ssl directly? E.g.,

```
$ python2.7 -c 'import ssl; print ssl.SSLContext'
<class 'ssl.SSLContext'>
```

The fact that you also have an OpenSSL related symbol missing from hashlib suggests to me that you have a build or system that doesn't support SSL. If so, then you probably want to do `monkey.patch_all(ssl=False). (And yes, please do make the monkey patch line the first line in your script.)

**Comment by jkndrkn** [comment]
Hi, thank you for your reply. Yes, it appears that there is a problem with SSL on my system.

    $ python -c 'import ssl; print ssl.SSLContext'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Python27\lib\ssl.py", line 100, in <module>
        from _ssl import _SSLContext
    ImportError: cannot import name _SSLContext

Furthermore, using `monkey.patch_all(ssl = False)` and moving it to the top of the script doesn't fix the issue that arises when trying to import `SocketIOServer` from `socket`:

    Traceback (most recent call last):
      File "test.py", line 63, in <module>
        from socketio.server import SocketIOServer
      File "C:\Python27\lib\site-packages\socketio\server.py", line 6, in <module>
        from gevent.pywsgi import WSGIServer
      File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 8, in <module>
        import mimetools
      File "C:\Python27\lib\mimetools.py", line 6, in <module>
        import tempfile
      File "C:\Python27\lib\tempfile.py", line 35, in <module>
        from random import Random as _Random
      File "C:\Python27\lib\random.py", line 49, in <module>
        import hashlib as _hashlib
      File "C:\Python27\lib\hashlib.py", line 138, in <module>
        _hashlib.openssl_md_meth_names)

I will look into making sure my system is configured to support OpenSSL (I am on Windows 8.1 and new to Python so any suggestions would be appreciated).

**Comment by jamadden** [comment]
Unfortunately, I don't have any Windows machines around, and I haven't used Windows in a long time, so all I could offer for help would be what a Google search turned up. Sorry.

I'm going to close this as part of triage for gevent 1.1. If anyone has a quick tip please feel free to add it to the comments.

**Comment by Ivoz** [comment]
Python 2.7.11 might work for you now.
