### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u010d' in position 19: ordinal not in range(256)

### ISSUE THREAD

**Issue by muhahacz** [gevent/gevent#614]
Hi, i found a bug in gevent 1.1a2  (latest ajenti)...
```
user@htpc:~$ python -c 'import sys; print sys.getfilesystemencoding(), sys.getdefaultencoding();'
UTF-8 asci
user@htpc:~$ locale
LANG=cs_CZ.UTF-8
LANG=cs_CZ.UTF-8
LANGUAGE=
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER="cs_CZ.UTF-8"
LC_NAME="cs_CZ.UTF-8"
LC_ADDRESS="cs_CZ.UTF-8"
LC_TELEPHONE="cs_CZ.UTF-8"
LC_MEASUREMENT="cs_CZ.UTF-8"
LC_IDENTIFICATION="cs_CZ.UTF-8"
LC_ALL=
```

```
15.07.2015 14:35 compat.py:20                  DEBUG [root] Popen: ['uname', '-mp']
15.07.2015 14:35 main.py:244                   DEBUG [root] {'Starting NetworkPlugin': 0.0825951099395752, 'Starting PasswordChangeSection': 0.007061958312988281, 'HTTP /ajenti:static/resources.css': 0.17467308044433594, 'Starting
 Notepad': 0.04988288879394531, 'Starting Filesystems': 0.059676170349121094, 'Starting Configurator': 0.0579831600189209, 'HTTP /ajenti:static/main/fontawesome.woff': 0.0010440349578857422, 'HTTP /ajenti:static/main/OpenSans.woff
': 0.0006608963012695312, 'HTTP /ajenti:static/resources.js': 0.48740220069885254, 'Starting Packages': 0.027421951293945312, 'HTTP /ajenti:static/main/error.jpeg': 0.0015492439270019531, 'HTTP /ajenti:static/main/icon.png': 0.000
637054443359375, 'HTTP /ajenti:static/main/OpenSans-Bold.woff': 0.0008959770202636719, 'Starting Terminals': 0.007463216781616211, 'Starting Resolv': 0.009209156036376953, 'Starting Users': 0.05221390724182129, 'Starting PluginsPl
ugin': 0.02356696128845215, 'Starting TaskManager': 0.01229405403137207, 'Starting FileManager': 0.04167485237121582, 'Starting Logs': 0.01854395866394043, 'HTTP /': 0.03156304359436035, 'HTTP /ajenti:static/main/favicon.png': 0.0
008530616760253906, 'Starting IPv6Firewall': 0.019594907760620117, 'HTTP /ajenti:static/main/icon-connecting.png': 0.00039696693420410156, 'Starting Dash': 0.060381174087524414, 'HTTP /ajenti:static/main/PS-Bold.woff': 0.000180959
70153808594, 'Starting Firewall': 0.019825220108032227, 'Starting Hosts': 0.009922027587890625, 'Starting Tasks': 0.030061006546020508, 'Rendering': 0.00771021842956543, 'Total': 0.0048961639404296875, 'Starting Services': 0.01917
8152084350586, 'HTTP /ajenti:auth': 7.4102559089660645, 'Starting Cron': 0.01864004135131836}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 534, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 521, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 512, in process_result
    self.write(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 422, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 431, in _write_with_headers
    towrite.extend(('%s: %s\r\n' % header).encode('latin-1'))
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u010d' in position 19: ordinal not in range(256)
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'cs-CZ,cs;q=0.8,en;q=0.6',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'advanced_toggle_checked=0; session=8c00fbdd3b28fef046a959ecad19b36bef610093; mp_b5e6ddf58b2d02245a7a19005d1cec48_mixpanel=%7B%22distinct_id%22%3A%20%2214e91ac00a2386-02d1ac8e1-383c5b02-232800-14e91ac00a3c6e%22%2C%
22%24initial_referrer%22%3A%20%22https%3A%2F%2F10.0.0.47%3A8000%2F%22%2C%22%24initial_referring_domain%22%3A%20%2210.0.0.47%3A8000%22%7D',
 'HTTP_HOST': '10.0.0.47:8000',
 'HTTP_REFERER': 'https://10.0.0.47:8000/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36',
 'PATH_INFO': '/ajenti:static/main/favicon.png',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '10.0.0.34',
 'REMOTE_PORT': '63722',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'htpc.Home',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f69b248a1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f699fc26e50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)} failed with UnicodeEncodeError
15.07.2015 14:35 __init__.py:207               DEBUG Root context instantiated [AjentiSyncProvider] <ajenti.usersync.local.AjentiSyncProvider object at 0x7f699fb613d0>
15.07.2015 14:35 __init__.py:207               DEBUG [root] Context for root instantiated [SectionPermissions] <ajenti.plugins.main.main.SectionPermissions object at 0x7f699fe3be90>
```

**Comment by jamadden** [comment]
HTTP header fields are [limited to the ISO-8859-1/Latin-1 character set](https://tools.ietf.org/html/rfc2616#section-2.2). There is an escape mechanism described through the use of [RFC 2047 MIME encoding](https://en.wikipedia.org/wiki/MIME#Encoded-Word) but (1) I've never actually seen that used in the wild; and (2) more importantly, its use is more-or-less deprecated by [newer standards](https://tools.ietf.org/html/rfc7230#section-3.2.4):

> Historically, HTTP has allowed field content with text in the
> ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
> through use of [RFC2047] encoding.  In practice, most HTTP header
> field values use only a subset of the US-ASCII charset . 
> Newly defined header fields SHOULD limit their field values to
>   US-ASCII octets.  A recipient SHOULD treat other octets in field
>   content (obs-text) as opaque data.

Further, I believe there's a problem with the application in this example. It's running under Python 2.7 (as evidenced by the `u` prefix on the character and the paths). In WSGI, all HTTP header values are [specified to be of the native `str` type](https://www.python.org/dev/peps/pep-3333/#a-note-on-string-types)---which, under Python 2 means non-Unicode. The application is passing a Unicode header and thus violating the WSGI specification, so the results are undefined. 

Such an application *may* have worked with previous versions of gevent, depending on the system setup (because unicode headers were implicitly converted by the Python 2 black magic). However, previous versions of gevent failed to properly implement this part of the HTTP specification, and the bytes on the wire would very likely have been unintelligible to a recipient. We can see how this character would get mangled by a proper client:

```
>>>> s = u'\u010d'
>>>> print(s)
č
>>>> print s.encode('utf-8').decode('latin-1')
Ä
```

This encoding is visible in other WSGI implementations such as [waitress](https://github.com/Pylons/waitress/blob/master/waitress/compat.py#L49) and [gunicorn](https://github.com/benoitc/gunicorn/blob/master/gunicorn/six.py#L579).

If an application must send non-Latin-1 characters in a header, the application needs to take care of encoding them properly.

**Comment by jamadden** [comment]
See also https://github.com/benoitc/gunicorn/pull/1102. I don't believe this is a bug in gevent. Please feel free to reopen if there is information to the contrary.
