### ISSUE TITLE
PyPy 2.6.0: "ImportError: No module named gevent._semaphore" after installing master with setup.py

### ISSUE THREAD

**Issue by parasyte** [gevent/gevent#620]
May be related to #619

In a fresh virtualenv:

```bash
$ pip install --upgrade pip setuptools
$ pip install cython
$ git clone https://github.com/gevent/gevent.git
$ cd gevent
$ pypy setup.py install >~/gevent-git.log 2>&1
$ pypy -c 'import gevent.core ; print gevent.core.get_version()'
libev-4.20
$ pypy -c 'import gevent.monkey ; gevent.monkey.patch_all() ; print "ok!"'
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "<builtin>/app_main.py", line 601, in run_it
  File "<string>", line 1, in <module>
  File "gevent/monkey.py", line 363, in patch_all
    patch_thread(Event=Event)
  File "gevent/monkey.py", line 200, in patch_thread
    patch_module('thread')
  File "gevent/monkey.py", line 94, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "gevent/thread.py", line 35, in <module>
    from gevent.lock import BoundedSemaphore
  File "gevent/lock.py", line 5, in <module>
    from gevent._semaphore import Semaphore, BoundedSemaphore
ImportError: No module named gevent._semaphore
```

The files seem to be there:

```bash
$ ls -l env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.*
-rw-rw-r-- 1 vagrant vagrant   629 Jul 21 18:09 env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.pxd
-rw-rw-r-- 1 vagrant vagrant   294 Jul 21 18:09 env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.py
-rw-rw-r-- 1 vagrant vagrant   544 Jul 21 18:09 env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.pyc
-rwxr-xr-x 1 vagrant vagrant 82422 Jul 21 18:09 env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.pypy-26.so
-rw-rw-r-- 1 vagrant vagrant  6606 Jul 21 18:09 env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.pyx
$ cat ../env/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/_semaphore.py
def __bootstrap__():
   global __bootstrap__, __loader__, __file__
   import sys, pkg_resources, imp
   __file__ = pkg_resources.resource_filename(__name__,'_semaphore.pypy-26.so')
   __loader__ = None; del __bootstrap__, __loader__
   imp.load_dynamic(__name__,__file__)
__bootstrap__()
```

Meanwhile, installing master through pip works great:

```bash
$ pip install --upgrade pip setuptools
$ pip install cython
$ pip install --verbose git+https://github.com/gevent/gevent.git#egg=gevent >gevent-pip.log 2>&1
$ pypy -c 'import gevent.core ; print gevent.core.get_version()'
In file included from /home/vagrant/env/site-packages/gevent/libev.h:2:0,
                 from env/site-packages/gevent/__pycache__/_cffi__g6b389c96xbac708c5.c:54:
/home/vagrant/env/site-packages/gevent/libev/ev.c:1692:31: warning: ‘ev_default_loop_ptr’ initialized and declared ‘extern’ [enabled by default]
env/site-packages/gevent/__pycache__/_cffi__g6b389c96xbac708c5.c: In function ‘evpipe_write’:
/home/vagrant/env/site-packages/gevent/libev/ev.c:2321:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
/home/vagrant/env/site-packages/gevent/libev/ev.c:2333:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
env/site-packages/gevent/__pycache__/_cffi__g6b389c96xbac708c5.c: In function ‘pipecb’:
/home/vagrant/env/site-packages/gevent/libev/ev.c:2354:16: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
/home/vagrant/env/site-packages/gevent/libev/ev.c:2368:16: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
libev-4.20
$ pypy -c 'import gevent.monkey ; gevent.monkey.patch_all() ; print "ok!"'
ok!
```

You see CFFI actually compiled the extensions this time! :smile:

And the site-packages is a little bit different (seems to be expected; I told pip that the egg name is `gevent`)

```bash
$ ls -l env/site-packages/ | grep gevent
drwxrwxr-x  4 vagrant vagrant  4096 Jul 21 17:49 gevent
drwxrwxr-x  2 vagrant vagrant  4096 Jul 21 17:49 gevent-1.1b2.dev0-py2.7.egg-info
$ ls -l env/site-packages/gevent/_semaphore.*
-rw-rw-r-- 1 vagrant vagrant   629 Jul 21 17:48 env/site-packages/gevent/_semaphore.pxd
-rwxrwxr-x 1 vagrant vagrant 82422 Jul 21 17:49 env/site-packages/gevent/_semaphore.pypy-26.so
-rw-rw-r-- 1 vagrant vagrant  6606 Jul 21 17:48 env/site-packages/gevent/_semaphore.pyx
```

Here are the installation logs:

* setup.py: https://gist.github.com/parasyte/a0546d4535d43c031043#file-gevent-git-log
* pip: https://gist.github.com/parasyte/a0546d4535d43c031043#file-gevent-pip-log

**Comment by jamadden** [comment]
If you do `python setup.py install`, you must change directories before attempting to use gevent. With no path prefix on setup.py, you have the gevent clone as your working directory. The gevent clone contains a `gevent` directory which is used *in preference* to the installed egg when that's your working directory. But the clone directory wasn't setup properly, only the installed egg was.

```
[~/Projects/gevent master]$ pypy setup.py install
...
[~/Projects/gevent master]$ ls -ld gevent
drwxrwxr-x 4 user user 4096 Jul 21 20:22 gevent
[~/Projects/gevent master]$ pypy -c 'import gevent; print gevent; import gevent.lock'
<module 'gevent' from 'gevent/__init__.pyc'>
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "<builtin>/app_main.py", line 601, in run_it
  File "<string>", line 1, in <module>
  File "gevent/lock.py", line 5, in <module>
    from gevent._semaphore import Semaphore, BoundedSemaphore
ImportError: No module named gevent._semaphore
[~/Projects/GithubSources/gevent master]$ (cd .. && pypy -c 'import gevent; print gevent; import gevent.lock; print gevent.lock')
$ (cd .. && pypy -c 'import gevent; print gevent; import gevent.lock; print gevent.lock')
<module 'gevent' from '//Projects/VirtualEnvs/gevent-master/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/__init__.pyc'>
<module 'gevent.lock' from '//Projects/VirtualEnvs/gevent-master/site-packages/gevent-1.1b2.dev0-py2.7-linux-x86_64.egg/gevent/lock.pyc'>
```

When working with a source checkout in a virtualenv, I use `python setup.py develop` which *does* make the clone directory a working installation and avoids this problem.

**Comment by parasyte** [comment]
:facepalm: Of course it's referencing the gevent clone in the cwd! Very nice trick with `setup.py develop`.
