### ISSUE TITLE
gevent 1.1b1 get error on gunicorn 19.3.0

### ISSUE THREAD

**Issue by simpleapples** [gevent/gevent#621]
[2015-07-22 15:07:35 +0800] [19019] [INFO] Booting worker with pid: 19019
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 174, in run
    self.manage_workers()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2015-07-22 15:07:35 +0800] [19019] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 185, in init_process
    self.patch()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 74, in patch
    _sock=s))
TypeError: __init__() got an unexpected keyword argument '_sock'
Traceback (most recent call last):
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 185, in init_process
    self.patch()
  File "/var/www/pagani/venv/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 74, in patch
    _sock=s))
TypeError: __init__() got an unexpected keyword argument '_sock'
[2015-07-22 15:07:35 +0800] [19019] [INFO] Worker exiting (pid: 19019)

**Comment by jamadden** [comment]
There is no released version of gunicorn that supports Python 3 and gevent. If you want to run gunicorn on Python 3 with gevent at this time, you'll need to use a git checkout. Support was apparently added in https://github.com/benoitc/gunicorn/pull/1066 and https://github.com/benoitc/gunicorn/commit/66a0fdfd4f3aa94bc8e34661261fc9debda99a2d#diff-24baff6269faf10cb820888842174a8b. (I haven't personally tested it.)

The underlying reason is that the socket constructor changed between Python 2.x and Python 3.x (see below). gevent provides the same API that the standard library does. Previously because gevent only ran on Python 2.x, gunicorn simply assumed the 2.x API. With that commit it uses the constructor appropriate to the platform.

```
$ python3.4 -c "import socket; help(socket.socket.__init__)"
Help on function __init__ in module socket:

__init__(self, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=0, fileno=None)

$ python2.7 -c "import socket; help(socket.socket.__init__)"
Help on method __init__ in module socket:

__init__(self, family=2, type=1, proto=0, _sock=None) unbound socket._socketobject method
```

**Comment by simpleapples** [comment]
@jamadden thank you.
