### ISSUE TITLE
gevent 1.1a2 monkey.patch_socket() fails on Windows - no attribute 'socketpair'

### ISSUE THREAD

**Issue by jacekt** [gevent/gevent#627]
gevent 1.1a2, Python 3.4.3 on Windows

STEPS TO REPRODUCE:
```
> py -3 -c "import gevent.monkey; gevent.monkey.patch_socket()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 215, in patch_socket
    patch_module('socket', items=items)
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 102, in patch_module
    patch_item(module, attr, getattr(gevent_module, attr))
AttributeError: 'module' object has no attribute 'socketpair'
```

PATCH:
```
--- _socketcommon.py.org	2015-08-01 15:22:47.740125000 +0200
+++ _socketcommon.py	2015-08-01 16:21:29.363125000 +0200
@@ -89,6 +89,9 @@
 import socket as __socket__
 
 
+if not hasattr(__socket__, 'socketpair'):
+    _implements.remove('socketpair')
+
 for name in __imports__[:]:
     try:
         value = getattr(__socket__, name)
```

**Comment by jamadden** [comment]
I believe this is fixed in https://github.com/gevent/gevent/commit/2e313e9b586c34762ed4f3e6f6caa6102bdc532f. Can you retry with current master?

**Comment by jacekt** [comment]
Works correctly on master.  Looks that it was fixed before I even reported - that's really fast ;)  Thanks.
