### ISSUE TITLE
PyPy2.6 with Gunicorn19.3.0, Gevent1.1b2 and Django1.8.3

### ISSUE THREAD

**Issue by tebanep** [gevent/gevent#637]
When trying gevent with gunicorn the following error raises:

ImportError: Cannot import 'core' from module 'gevent' from '/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/__init__.py'

Full error message:

```
(env)root@sandbox:/opt/python_sandbox/django_rest/tutorial# gunicorn -b 0.0.0.0:8000 -k gevent tutorial.wsgi:application
[2015-08-13 02:39:49 +0000] [19237] [INFO] Starting gunicorn 19.3.0
[2015-08-13 02:39:49 +0000] [19237] [INFO] Listening at: http://0.0.0.0:8000 (19237)
[2015-08-13 02:39:49 +0000] [19237] [INFO] Using worker: gevent
[2015-08-13 02:39:49 +0000] [19244] [INFO] Booting worker with pid: 19244
[2015-08-13 02:39:49 +0000] [19244] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gunicorn/workers/ggevent.py", line 185, in init_process
    self.patch()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gunicorn/workers/ggevent.py", line 74, in patch
    _sock=s))
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/_socket2.py", line 93, in __init__
    self.hub = get_hub()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 308, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 423, in __init__
    loop_class = _import(self.loop_class)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 337, in _import
    return _import(path[-1])
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 349, in _import
    x = __import__(module)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/builtins.py", line 43, in __import__
    result = _import(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/core.py", line 4, in <module>
    from gevent import corecffi as _core
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/builtins.py", line 43, in __import__
    result = _import(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/corecffi.py", line 288, in <module>
    libev = C = ffi.verify(_source, include_dirs=include_dirs)
  File "/usr/lib/pypy/lib_pypy/cffi/api.py", line 373, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/pypy/lib_pypy/cffi/verifier.py", line 96, in load_library
    self._compile_module()
  File "/usr/lib/pypy/lib_pypy/cffi/verifier.py", line 192, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib/pypy/lib_pypy/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib/pypy/lib_pypy/cffi/ffiplatform.py", line 62, in _build
    dist.run_command('build_ext')
  File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/pypy/lib-python/2.7/distutils/command/build_ext.py", line 347, in run
    self.build_extensions()
  File "/usr/lib/pypy/lib-python/2.7/distutils/command/build_ext.py", line 456, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/pypy/lib-python/2.7/distutils/command/build_ext.py", line 506, in build_extension
    depends=ext.depends)
  File "/usr/lib/pypy/lib-python/2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/pypy/lib-python/2.7/distutils/unixccompiler.py", line 135, in _compile
    extra_postargs)
  File "/usr/lib/pypy/lib-python/2.7/distutils/ccompiler.py", line 875, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/pypy/lib-python/2.7/distutils/spawn.py", line 38, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/pypy/lib-python/2.7/distutils/spawn.py", line 143, in _spawn_posix
    pid = os.fork()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/os.py", line 314, in fork
    return fork_and_watch(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/os.py", line 293, in fork_and_watch
    loop = loop or get_hub().loop
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 308, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 423, in __init__
    loop_class = _import(self.loop_class)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 337, in _import
    return _import(path[-1])
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 354, in _import
    raise ImportError('Cannot import %r from %r' % (attr, oldx))
ImportError: Cannot import 'core' from <module 'gevent' from '/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/__init__.py'>
Traceback (most recent call last):
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gunicorn/workers/ggevent.py", line 185, in init_process
    self.patch()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gunicorn/workers/ggevent.py", line 74, in patch
    _sock=s))
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/_socket2.py", line 93, in __init__
    self.hub = get_hub()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 308, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 423, in __init__
    loop_class = _import(self.loop_class)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 337, in _import
    return _import(path[-1])
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 349, in _import
    x = __import__(module)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/builtins.py", line 43, in __import__
    result = _import(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/core.py", line 4, in <module>
    from gevent import corecffi as _core
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/builtins.py", line 43, in __import__
    result = _import(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/corecffi.py", line 288, in <module>
    libev = C = ffi.verify(_source, include_dirs=include_dirs)
  File "/usr/lib/pypy/lib_pypy/cffi/api.py", line 373, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/pypy/lib_pypy/cffi/verifier.py", line 96, in load_library
    self._compile_module()
  File "/usr/lib/pypy/lib_pypy/cffi/verifier.py", line 192, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib/pypy/lib_pypy/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib/pypy/lib_pypy/cffi/ffiplatform.py", line 62, in _build
    dist.run_command('build_ext')
  File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/pypy/lib-python/2.7/distutils/command/build_ext.py", line 347, in run
    self.build_extensions()
  File "/usr/lib/pypy/lib-python/2.7/distutils/command/build_ext.py", line 456, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/pypy/lib-python/2.7/distutils/command/build_ext.py", line 506, in build_extension
    depends=ext.depends)
  File "/usr/lib/pypy/lib-python/2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/pypy/lib-python/2.7/distutils/unixccompiler.py", line 135, in _compile
    extra_postargs)
  File "/usr/lib/pypy/lib-python/2.7/distutils/ccompiler.py", line 875, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/pypy/lib-python/2.7/distutils/spawn.py", line 38, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/pypy/lib-python/2.7/distutils/spawn.py", line 143, in _spawn_posix
    pid = os.fork()
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/os.py", line 314, in fork
    return fork_and_watch(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/os.py", line 293, in fork_and_watch
    loop = loop or get_hub().loop
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 308, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 423, in __init__
    loop_class = _import(self.loop_class)
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 337, in _import
    return _import(path[-1])
  File "/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/hub.py", line 354, in _import
    raise ImportError('Cannot import %r from %r' % (attr, oldx))
ImportError: Cannot import 'core' from <module 'gevent' from '/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/__init__.py'>
[2015-08-13 02:39:49 +0000] [19244] [INFO] Worker exiting (pid: 19244)
[2015-08-13 02:39:49 +0000] [19237] [INFO] Shutting down: Master
[2015-08-13 02:39:49 +0000] [19237] [INFO] Reason: Worker failed to boot.
(env)root@sandbox:/opt/python_sandbox/django_rest/tutorial# In file included from /mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev.h:2:0,
                 from env/site-packages/gevent/__pycache__/_cffi__gb8862c55x95d370a.c:54:
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c:1692:31: warning: ‘ev_default_loop_ptr’ initialized and declared ‘extern’ [enabled by default]
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c: In function ‘evpipe_write’:
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c:2321:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &counter, sizeof (uint64_t));
                 ^
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c:2333:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &(evpipe [1]), 1);
                 ^
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c: In function ‘pipecb’:
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c:2354:16: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [1], &counter, sizeof (uint64_t));
                ^
/mnt/python_sandbox/django_rest/tutorial/env/site-packages/gevent/libev/ev.c:2368:16: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [0], &dummy, sizeof (dummy));
```
I tried with Python2.7 instead of PyPy2.6 and django rest framework with gunicorn's gevent worker runs just fine.

Thank you!

**Comment by tebanep** [comment]
To reproduce just try the Django Rest Framework tutorial (http://www.django-rest-framework.org/tutorial/quickstart/) with the following PyPy2.6 virtual environment requirements:

cffi==1.1.0
Django==1.8.3
djangorestframework==3.2.1
gevent==1.1b2
greenlet==0.4.7
gunicorn==19.3.0
readline==6.2.4.1
wheel==0.24.0

**Comment by jamadden** [comment]
I suspect this is a dup of #631 and #619, which are already fixed in *master*. To confirm, can you try current *master*? Or, failing that, add the line `from gevent.core import loop` at the top of your `__main__` module?

**Comment by tebanep** [comment]
Thanks a lot @jamadden

Importing "loop" from gevent.core in one of my files didn't make it. However, after importing that module in a python REPL the gunicorn worker started normally:

(env)root@sandbox:/opt/python_sandbox/django_rest/tutorial# python
Python 2.7.9 (2.6.0+dfsg-1~ppa0+ubuntu14.04, Jun 08 2015, 14:48:00)
[PyPy 2.6.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from gevent.core import loop
>>>> loop
<class 'gevent.corecffi.loop'>
>>>>

KeyboardInterrupt
>>>>

And then:

(env)root@sandbox:/opt/python_sandbox/django_rest/tutorial# gunicorn -b 0.0.0.0:8000 -k gevent tutorial.wsgi
Warning: cannot find your CPU L2 cache size in /proc/cpuinfo
[2015-08-13 13:15:04 +0000] [1902] [INFO] Starting gunicorn 19.3.0
[2015-08-13 13:15:04 +0000] [1902] [INFO] Listening at: http://0.0.0.0:8000 (1902)
[2015-08-13 13:15:04 +0000] [1902] [INFO] Using worker: gevent
[2015-08-13 13:15:04 +0000] [1909] [INFO] Booting worker with pid: 1909

Later I wil try with master branch to check if the bug has been already fixed. Thanks again!

**Comment by jamadden** [comment]
It looks like the same issue, then (`__pycache__` not being populated correctly by pip). Possibly why importing didn't work for you was because it has to be done very early in the lifecycle. I'm going to tentatively close this as a duplicate; please feel free to reopen if it occurs for you on a newer version.

**Comment by tebanep** [comment]
I tried again in a new virtualenv with gevent's master branch (I had to install Cython first for gevent to compile):
<pre>
pip install git+https://github.com/gevent/gevent.git
</pre>

requirements.txt

<pre>
cffi==1.1.0
Cython==0.23
Django==1.8.3
djangorestframework==3.2.1
gevent==1.1b3.dev0
greenlet==0.4.7
gunicorn==19.3.0
readline==6.2.4.1
wheel==0.24.0
</pre>

The first time I ran gunicorn, it succeeded but with the following output:

<pre>
(env3)root@sandbox:/opt/python_sandbox/django_rest/tutorial# gunicorn -b 0.0.0.0:8000 -k gevent tutorial.wsgi
Warning: cannot find your CPU L2 cache size in /proc/cpuinfo
In file included from /mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev.h:2:0,
                 from env3/site-packages/gevent/__pycache__/_cffi__g41f626b7x5f4c9dc4.c:54:
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c:1692:31: warning: ‘ev_default_loop_ptr’ initialized and declared ‘extern’ [enabled by default]
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c: In function ‘evpipe_write’:
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c:2321:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &counter, sizeof (uint64_t));
                 ^
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c:2333:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &(evpipe [1]), 1);
                 ^
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c: In function ‘pipecb’:
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c:2354:16: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [1], &counter, sizeof (uint64_t));
                ^
/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/libev/ev.c:2368:16: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [0], &dummy, sizeof (dummy));
                ^
[2015-08-13 15:03:53 +0000] [9282] [INFO] Starting gunicorn 19.3.0
[2015-08-13 15:03:53 +0000] [9282] [INFO] Listening at: http://0.0.0.0:8000 (9282)
[2015-08-13 15:03:53 +0000] [9282] [INFO] Using worker: gevent
[2015-08-13 15:03:53 +0000] [9295] [INFO] Booting worker with pid: 9295
^CFrom cffi callback <bound method loop._check_callback of <loop at 0x49b07c8 epoll default pending=0 ref=3 fileno=7>>:
[2015-08-13 15:04:29 +0000] [9282] [INFO] Handling signal: int
Traceback (most recent call last):
  File "/mnt/python_sandbox/django_rest/tutorial/env3/site-packages/gevent/corecffi.py", line 596, in _check_callback
[2015-08-13 15:04:30 +0000] [9295] [INFO] Worker exiting (pid: 9295)
[2015-08-13 15:04:30 +0000] [9282] [INFO] Shutting down: Master
</pre>

Running gunicorn again after that doesn't raise any warning or error:

<pre>
(env3)root@sandbox:/opt/python_sandbox/django_rest/tutorial# gunicorn -b 0.0.0.0:8000 -k gevent tutorial.wsgi
Warning: cannot find your CPU L2 cache size in /proc/cpuinfo
[2015-08-13 15:04:35 +0000] [9299] [INFO] Starting gunicorn 19.3.0
[2015-08-13 15:04:35 +0000] [9299] [INFO] Listening at: http://0.0.0.0:8000 (9299)
[2015-08-13 15:04:35 +0000] [9299] [INFO] Using worker: gevent
[2015-08-13 15:04:35 +0000] [9306] [INFO] Booting worker with pid: 9306
</pre>

Think that's it! Thank you!
