### ISSUE TITLE
BUG PyPy 2.6.0 gevent.idle()

### ISSUE THREAD

**Issue by chilun2008** [gevent/gevent#639]
```
Python 2.7.9 (295ee98b6928, May 31 2015, 07:29:04)
[PyPy 2.6.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import gevent
>>>> gevent.sleep()
>>>> gevent.idle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gevent/hub.py", line 132, in idle
    watcher = hub.loop.idle()
  File "gevent/corecffi.py", line 769, in idle
    return idle(self, ref, priority)
  File "gevent/corecffi.py", line 894, in __init__
    self._gwatcher = ffi.new('struct gevent_' + self._watcher_type + '*')
  File "/opt/pypy-2.6.0-linux64/lib_pypy/cffi/api.py", line 237, in new
    return self._backend.newp(cdecl, init)
TypeError: cannot instantiate ctype 'struct gevent_ev_idle *' of unknown size
```

I found list _watcher_types hadn't  'ev_idle' in corecffi.py,Add  'ev_idle'  into _watcher_types then OK

**Comment by jamadden** [comment]
Thank you for the report.

**Comment by thedrow** [comment]
@jamadden Can we add some coverage to ensure this doesn't break again?

**Comment by jamadden** [comment]
Yes, I did that. https://github.com/gevent/gevent/blob/master/greentest/test__issue639.py

**Comment by thedrow** [comment]
Great. Thanks!
