### ISSUE TITLE
gevent.queue.Queue.peek ValueError

### ISSUE THREAD

**Issue by kchen** [gevent/gevent#647]
The following code works in gevent 1.1b2, but not in 1.1b4:

```python
import gevent.queue
q = gevent.queue.Queue()
g = gevent.spawn(q.peek)
g.start()
gevent.sleep(0)
q.put(1)
gevent.hub.get_hub().join()
```

In 1.1b4:
```
Traceback (most recent call last):
  File "/home/kechen/workspaces/foo/python-gevent/gevent-1.1b4/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/kechen/workspaces/foo/python-gevent/gevent-1.1b4/gevent/queue.py", line 309, in peek
    self.getters.remove(waiter)
ValueError: deque.remove(x): x not in deque
<Greenlet at 0xf73247fc: <bound method Queue.peek of <Queue at 0xf7409e2c queue=deque([1])>>> failed with ValueError
```

**Comment by jamadden** [comment]
Thanks for the report!
