### ISSUE TITLE
LoopExit due to syntax error at import time

### ISSUE THREAD

**Issue by mikekap** [gevent/gevent#651]
```python
# test.py
import gevent

def fn():
    return thisisalie

gevent.spawn(fn).get()
```

Running `python -c 'from gevent import monkey; monkey.patch_all(); import test'` gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 53, in __import__
    result = _import(*args, **kwargs)
  File "test.py", line 6, in <module>
    gevent.spawn(fn).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 451, in get
    result = self.parent.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 536, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x10200d230 select default pending=0 ref=1>)
```

This is python2.7 on osx.

**Comment by mikekap** [comment]
Just tested the latest master - the fix does not fix this issue - it's not related to the import in hub.py

**Comment by jamadden** [comment]
Can you clarify what you're seeing? I see the ``NameError`` I would expect to see using current master (with or without the extra print statement):

```
$ cat test.py
# test.py
import gevent
print(gevent.__version__)
def fn():
    return thisisalie

gevent.spawn(fn).get()

$ python -c 'from gevent import monkey; monkey.patch_all(); import test'
1.1b5.dev0
Traceback (most recent call last):
  File "//python3.4/site-packages/gevent-1.1b5.dev0-py3.4-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/private/tmp/test.py", line 5, in fn
    return thisisalie
NameError: name 'thisisalie' is not defined
<Greenlet at 0x10f45be88: fn> failed with NameError

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/test.py", line 7, in <module>
    gevent.spawn(fn).get()
  File "/python3.4/site-packages/gevent-1.1b5.dev0-py3.4-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 468, in get
    self._raise_exception()
  File "//python3.4/site-packages/gevent-1.1b5.dev0-py3.4-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 163, in _raise_exception
    reraise(*self.exc_info)
  File "//python3.4/site-packages/gevent-1.1b5.dev0-py3.4-macosx-10.10-x86_64.egg/gevent/hub.py", line 44, in reraise
    raise value.with_traceback(tb)
  File "//python3.4/site-packages/gevent-1.1b5.dev0-py3.4-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/private/tmp/test.py", line 5, in fn
    return thisisalie
NameError: name 'thisisalie' is not defined
```

**Comment by mikekap** [comment]
Looks like python==python3 for you :). With python2:

```shell
$ python -c 'from gevent import monkey; monkey.patch_all(); import test'
2.7.8 (default, Oct 23 2014, 00:29:11)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]
1.1b5.dev0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 53, in __import__
    result = _import(*args, **kwargs)
  File "test.py", line 10, in <module>
    gevent.spawn(fn).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 451, in get
    result = self.parent.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 538, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x109656230 select default pending=0 ref=1>)
```

A wild guess might be the traceback pickling code is lazily importing something (and hence hitting the same import lock issue). I might send a PR later to generally make LoopExit more useful by dumping all active greenlet stacks.

**Comment by jamadden** [comment]
D'oh. Indeed, I was testing the wrong python, thanks for pointing that out. Should be fixed now.
