### ISSUE TITLE
LoopExit due to gevent.wait at import time

### ISSUE THREAD

**Issue by mikekap** [gevent/gevent#652]
```python
import gevent

def fn2():
    return 2

def fn():
    return gevent.wait([gevent.spawn(fn2), gevent.spawn(fn2)])

gevent.spawn(fn).get()
```

Running `python -c 'from gevent import monkey; monkey.patch_all(); import test'`, gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 53, in __import__
    result = _import(*args, **kwargs)
  File "test.py", line 9, in <module>
    gevent.spawn(fn).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 451, in get
    result = self.parent.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 535, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x106801190 select default pending=0 ref=1>)
```

This is due to a line in https://github.com/gevent/gevent/blob/b25b4c009251a80fcc9e4013b3c5ba56de57de97/gevent/hub.py#L830 - which imports on the hub greenlet.

Generally this & #651 are regressions due to https://github.com/gevent/gevent/commit/0924a16f3d87d6af5a234ee806a94d9adff7cec5 which actually turned on import locking for python2.

**Comment by jamadden** [comment]
Thanks for the report and the diagnosis!
