### ISSUE TITLE
Regression: gunicorn with gevent_pywsgi worker raises LoggingLogAdapter exception

### ISSUE THREAD

**Issue by parasyte** [gevent/gevent#663]
Any WSGI application will do. This example is from the bottle documentation:

```python
# test.py

from bottle import Bottle, run

app = Bottle()

@app.route('/hello')
def hello():
    return "Hello World!"

if __name__ == '__main__':
    run(app, host='localhost', port=8000, server='gevent')
```

Run it with gunicorn, using the gevent_pywsgi worker:

```bash
$ gunicorn --worker-class=gevent_pywsgi test:app
```

Every request will raise an exception, as it attempts to call a custom method on the logger object:

```
Traceback (most recent call last):
  File "/opt/pubnub/pn-auth/env/site-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/pubnub/pn-auth/env/site-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/opt/pubnub/pn-auth/env/site-packages/gevent/pywsgi.py", line 1121, in handle
    handler.handle()
  File "/opt/pubnub/pn-auth/env/site-packages/gevent/pywsgi.py", line 376, in handle
    result = self.handle_one_request()
  File "/opt/pubnub/pn-auth/env/site-packages/gevent/pywsgi.py", line 580, in handle_one_request
    self.handle_one_response()
  File "/opt/pubnub/pn-auth/env/site-packages/gevent/pywsgi.py", line 829, in handle_one_response
    self.log_request()
  File "/opt/pubnub/pn-auth/env/site-packages/gunicorn/workers/ggevent.py", line 219, in log_request
    self.server.log.access(resp, req_headers, self.environ, response_time)
AttributeError: 'LoggingLogAdapter' object has no attribute 'access'
```

I'm able to workaround this issue by commenting the following lines: https://github.com/gevent/gevent/blob/0e0099a23bd5da5f911843f34c9c21238aa38a3d/gevent/pywsgi.py#L1094-L1095

The gunicorn `Logger` class is here: https://github.com/benoitc/gunicorn/blob/19.3/gunicorn/glogging.py#L149 It has a `log` method, but no `write` method.

**Comment by jamadden** [comment]
Hnh. We have an app using gunicorn+gevent1.1bx and we don't see this...but I do confirm it with a simple example. I wonder how we're avoiding it...

**Comment by jamadden** [comment]
Thanks for the report.
