### ISSUE TITLE
snakemq patch

### ISSUE THREAD

**Issue by danceasarxx** [gevent/gevent#670]
I am writing a simple snakemq server(*from the examples*):

```python
import snakemq
import snakemq.link
import snakemq.packeter
import snakemq.messaging
import snakemq.message
from gevent import monkey
monkey.patch_socket()

def on_recv(conn, ident, message):
    print("received from", conn, ident, vars(message))

s = snakemq.link.Link()
s.add_connector(("localhost", 4000))
pktr = snakemq.packeter.Packeter(s)
m = snakemq.messaging.Messaging("xconnector", "", pktr)
m.on_message_recv.add(on_recv)
s.loop()
```

When I run I get **this**:
```python
Traceback (most recent call last):
  File "server.py", line 29, in <module>
    s.loop()
  File "/home/arewa/Workspace/async/pyenv/lib/python3.4/site-packages/snakemq/link.py", line 417, in loop
    self.deal_connects()
  File "/home/arewa/Workspace/async/pyenv/lib/python3.4/site-packages/snakemq/link.py", line 741, in deal_connects
    self.connect(address)
  File "/home/arewa/Workspace/async/pyenv/lib/python3.4/site-packages/snakemq/link.py", line 489, in connect
    err = sock.connect()
  File "/home/arewa/Workspace/async/pyenv/lib/python3.4/site-packages/snakemq/link.py", line 118, in connect
    return self.sock.connect_ex(self.remote_peer)
  File "/home/arewa/Workspace/async/pyenv/lib/python3.4/site-packages/gevent/_socket3.py", line 269, in connect_ex
    return self.connect(address) or 0
  File "/home/arewa/Workspace/async/pyenv/lib/python3.4/site-packages/gevent/_socket3.py", line 243, in connect
    return _socket.socket.connect(self._sock, address)
BlockingIOError: [Errno 115] Operation now in progress
```

I though monkey patching was straight forward

**Comment by jamadden** [comment]
Generally it is recommended that if you monkey patch you do it *first*, before any other imports, most especially when importing non-stdlib modules. I suggest that as a matter of good form here.

The error suggests an incompatible use of sharing sockets across threads, *or* it suggests that the library you're using is trying to manually put the sockets into blocking mode. I'm not familiar with the library.

Have you tried using `patch_all` instead of `patch_socket`?

**Comment by danceasarxx** [comment]
yes I did...given up on snakemq anyways....got what I wanted with zeromq...thanks regardless

**Comment by jamadden** [comment]
I had a quick look at the snake sources. It does want to manually manage the blocking status of the sockets, which often means it follows an approach that is either not compatible with gevent, or at least not helpful.

**Comment by danceasarxx** [comment]
Well it's not your fault...
