### ISSUE TITLE
bdist_rpm failure

### ISSUE THREAD

**Issue by osier** [gevent/gevent#671]
Hi, 

I tried to make rpm with the git top of gevent, but failed with the following error:

====
```
root@builder:~/gevent# python setup.py bdist_rpm --python=/usr/bin/python2.7
Running 'make ' in /root/gevent
/usr/bin/python util/cythonpp.py -o gevent.corecext.c gevent/core.ppyx
Running cython -o gevent.corecext.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && !defined(_WIN32)
Running cython -o gevent.corecext.c gevent/core.pyx  # !EV_USE_SIGNALFD && !defined(LIBEV_EMBED) && defined(_WIN32)
Running cython -o gevent.corecext.c gevent/core.pyx  # !EV_USE_SIGNALFD && defined(LIBEV_EMBED) && !defined(_WIN32)
Running cython -o gevent.corecext.c gevent/core.pyx  # !EV_USE_SIGNALFD && defined(LIBEV_EMBED) && defined(_WIN32)
Running cython -o gevent.corecext.c gevent/core.pyx  # EV_USE_SIGNALFD && defined(LIBEV_EMBED) && !defined(_WIN32)
Running cython -o gevent.corecext.c gevent/core.pyx  # EV_USE_SIGNALFD && defined(LIBEV_EMBED) && defined(_WIN32)
Reusing cython -o gevent.corecext.c gevent/core.pyx  # EV_USE_SIGNALFD && defined(LIBEV_EMBED) && !defined(_WIN32)
Reusing cython -o gevent.corecext.c gevent/core.pyx  # EV_USE_SIGNALFD && defined(LIBEV_EMBED) && defined(_WIN32)
Generating gevent.corecext.c 2251014 bytes
Saving gevent/core.pyx
echo '#include "callbacks.c"' >> gevent.corecext.c
mv gevent.corecext.* gevent/
cython -o gevent.ares.c gevent/ares.pyx
mv gevent.ares.* gevent/
cp gevent/_semaphore.pyx gevent/_semaphore.py
cython -o gevent._semaphore.c gevent/_semaphore.py

Error compiling Cython file:
------------------------------------------------------------
...
cdef class Semaphore:
    cdef public int counter
    cdef readonly object _links
                        ^
------------------------------------------------------------

gevent/_semaphore.pxd:3:25: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(_semaphore.py:1:0)
StatListNode.stats[4] = StatListNode(_semaphore.py:9:0)
StatListNode.stats[0] = CClassDefNode(_semaphore.py:9:0,
    class_name = u'Semaphore',
    doc = u"\n    Semaphore(value=1) -> Semaphore\n\n    A semaphore manages a counter representing the number of release()\n    calls minus the number of acquire() calls, plus an initial value.\n    The acquire() method blocks if necessary until it can return\n    without making the counter negative.\n\n    If not given, ``value`` defaults to 1.\n\n    This Semaphore's ``__exit__`` method does not call the trace function.\n    ",
    visibility = 'private')

Compiler crash traceback from this point on:
  File "Visitor.py", line 168, in Cython.Compiler.Visitor.TreeVisitor._visit (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Visitor.c:4111)
  File "Visitor.py", line 284, in Cython.Compiler.Visitor.CythonTransform.visit_Node (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Visitor.c:6039)
  File "Visitor.py", line 236, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Visitor.c:5084)
  File "Visitor.py", line 210, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Visitor.c:4862)
AssertionError: Cannot insert list here: body in <Cython.Compiler.Nodes.PropertyNode object at 0x2ca1b90>
make: *** [gevent/gevent._semaphore.c] Error 1
Traceback (most recent call last):
  File "setup.py", line 425, in <module>
    run_setup(ext_modules, run_make=run_make)
  File "setup.py", line 378, in run_setup
    make()
  File "setup.py", line 232, in make
    system('make ' + targets)
  File "setup.py", line 142, in system
    if _system(cmd):
  File "setup.py", line 138, in _system
    return check_call(cmd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make ' returned non-zero exit status 2
```
I'm not farmilar with Cython yet, anyone knowns how to fix it?

**Comment by jamadden** [comment]
Your cython version looks to be quite old. I suspect that's the source of the issue. gevent requires cython >= 0.23.4. I bet if you update that will fix this. 

Others have had issues with a SyntaxError when building an RPM. Check the closed issues for a solution to that.

**Comment by osier** [comment]
Indeed, cython on my platform is 0.19, which is too much old.  I updated it to 0.23.4, and it works now.

Thanks. @jamadden
