### ISSUE TITLE
Syntax err in gevent for Py3k

### ISSUE THREAD

**Issue by 230v** [gevent/gevent#678]
Python 3.5.0 (default, Sep 20 2015, 11:56:03) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/lib/python3.5/site-packages/gevent/hub.py", line 289
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
>>>

**Comment by jamadden** [comment]
You seem to be installing/using gevent 1.0.x gevent 1.0.x does *not* support Python 3. Please install 1.1b6 instead. 1.1 *does* support Python 3.
