### ISSUE TITLE
Doctest: gevent.subprocess.check_output failes with 1.1b6

### ISSUE THREAD

**Issue by jlec** [gevent/gevent#681]
```python
======================================================================
  FAIL: check_output (gevent.subprocess)
  Doctest: gevent.subprocess.check_output
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib64/python3.5/doctest.py", line 2189, in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
  AssertionError: Failed doctest test for gevent.subprocess.check_output
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6-python3_5/lib/gevent/subprocess.py", line 199, in check_output
  
  ----------------------------------------------------------------------
  File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6-python3_5/lib/gevent/subprocess.py", line 216, in gevent.subprocess.check_output
  Failed example:
      check_output(["/bin/sh", "-c",
                    "ls -l non_existent_file ; exit 0"],
                   stderr=STDOUT)
  Expected:
      b'ls: non_existent_file: No such file or directory\n'
  Got:
      b'ls: cannot access non_existent_file: No such file or directory\n'
  
  
  ----------------------------------------------------------------------
  Ran 7 tests in 0.437s
  
  FAILED (failures=1)
```

**Comment by jamadden** [comment]
I'm afraid that it's specific to what version of `ls` you have; a recent change in `ls` (coreutils) changed the messages. But it's system specific, and I have to keep the tests passing on Travis. 

The docstrings are copies of the stdlib docstrings that get updated as the subprocess module gets update, so there's also not much motivation to make changes to the docstrings themselves. 

I would review a PR that added a doctest normalizer to deal with the change.

**Comment by jlec** [comment]
```
$ (0) ls --version
ls (GNU coreutils) 8.24
Packaged by Gentoo (8.24 (p1.1))
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
```

Perhaps test for "No such file or directory" in stderr would be more robust.
