### ISSUE TITLE
gevent v1.0.2 wheel for osx 10.11 is invalid

### ISSUE THREAD

**Issue by kols** [gevent/gevent#683]
```
$ pip --no-cache-dir install gevent==1.0.2
Collecting gevent==1.0.2
  Downloading gevent-1.0.2-cp27-none-macosx_10_11_intel.whl (559kB)
    100% |████████████████████████████████| 561kB 686kB/s 
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in ./lib/python2.7/site-packages (from gevent==1.0.2)
Installing collected packages: gevent
gevent is in an unsupported or invalid wheel
```

a file missing in the package causes the problem:

```
$ pip install gevent==1.0.2                                                                                                                                       [88/508]
Collecting gevent==1.0.2
  Using cached gevent-1.0.2-cp27-none-macosx_10_11_intel.whl
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages (from gevent==1.0.2)
Installing collected packages: gevent
Exception:
Traceback (most recent call last):
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/req/req_install.py", line 800, in install
    version = pip.wheel.wheel_version(self.source_dir)
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/wheel.py", line 551, in wheel_version
    wheel_data = dist.get_metadata('WHEEL')
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1611, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/Users/kane/.virtualenvs/tmp-17a4f6bf1f5ef5e2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1722, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/private/var/folders/wf/2rbmwk0d2yndql9ff1x7d7lr0000gp/T/pip-build-I6HC5s/gevent/gevent-1.0.2-py2.6.egg-info/WHEEL'
```

**Comment by mimiron8080** [comment]
I have the same issue 
```
$ pip install gevent
Collecting gevent
  Using cached gevent-1.0.2-cp27-none-macosx_10_11_intel.whl
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /Users/air/project/demoP/demoPEnv/lib/python2.7/site-packages (from gevent)
Installing collected packages: gevent
gevent is in an unsupported or invalid wheel
```

**Comment by mimiron8080** [comment]
I find a solution it works for me
```
$CFLAGS='-std=c99' pip install gevent --no-use-wheel
```

**Comment by jamadden** [comment]
Thank you for the report. It appears there was an issue with the 2.7 "universal" wheel. (The 64-bit only wheel worked fine in my testing.) I have removed the broken wheel, but it [is impossible to upload a fixed wheel](https://github.com/pypa/packaging-problems/issues/74). The workaround to compile from source does work on El Capitan, or you can use gevent==1.1b6 (which is quite stable).

**Comment by Ivoz** [comment]
@jamadden if it was a simple build configuration process that needed to be fixed, the recommended PyPA thing to do is a [post-release](https://www.python.org/dev/peps/pep-0440/#post-releases) version. E.g a `1.0.2.post1`
