### ISSUE TITLE
Cannot run gevent.subprocess from a native thread

### ISSUE THREAD

**Issue by nolar** [gevent/gevent#688]
Cannot run a subprocess in a thread unless threads are monkey-patched (which I do not want to have).

There are no statements in the manual that this will not work. Instead, there is a [gevent test](https://github.com/gevent/gevent/blob/master/greentest/test__monkey_hub_in_thread.py) that supposes that gevent loops should work in threads.

With money-patched threads it works.

Error is:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./f.py", line 11, in fn
    proc = gevent.subprocess.Popen('echo 123', shell=True)
  File "...venv/lib/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "...venv/lib/python2.7/site-packages/gevent/subprocess.py", line 725, in _execute_child
    self._watcher = self._loop.child(self.pid)
  File "gevent/core.pyx", line 499, in gevent.core.loop.child (gevent/gevent.core.c:9508)
  File "gevent/core.pyx", line 1864, in gevent.core.child.__init__ (gevent/gevent.core.c:31175)
TypeError: child watchers are only available on the default loop
```

Check with 1.0.2 & 1.1rc1 — error is the same.

Sample script:

```
#!/usr/bin/env python
import gevent.monkey
# gevent.monkey.patch_thread()
import gevent.subprocess
import subprocess
import threading


def main():
    def fn():
        proc = gevent.subprocess.Popen('echo 123', shell=True)
        proc.communicate()

    thread = threading.Thread(target=fn)
    thread.start()
    thread.join()


if __name__ == '__main__':
    main()
```

**Comment by jamadden** [comment]
The basic hub should work in threads (that was a feature of 1.0 and there are a few different tests for that; the test you reference is specifically about import locks if the hub is *only* used in threads), but the behaviour of signal handlers (which child watchers are built on) are effectively undefined when multiple threads are used. The signal may go to any thread in the process, and there's currently no way to get the signal from the thread/loop it's delivered on to the thread/loop that may have spawned the child. This is a [general feature](http://www.linuxprogrammingblog.com/all-about-linux-signals?page=11) of POSIX threads and signals.

I'll see if there's a good place to add gevent-specific documentation.
