### ISSUE TITLE
Unable to install via pip (python 3.5)

### ISSUE THREAD

**Issue by cbdelavenne** [gevent/gevent#695]
Hello!

I am unable to install gevent via pip using Python 3.5.0:
```
Collecting gevent
  Using cached gevent-1.0.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /Users/cbdelavenne/.virtualenv/python3.5/lib/python3.5/site-packages (from gevent)
Building wheels for collected packages: gevent
  Running setup.py bdist_wheel for gevent
  Complete output from command /Users/cbdelavenne/.virtualenv/python3.5/bin/python -c "import setuptools;__file__='/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/tmpsd5tu3vbpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-3.5
  creating build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/_ssl2.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/_sslgte279.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/_threading.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/backdoor.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/baseserver.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/coros.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/event.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/fileobject.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/greenlet.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/hub.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/local.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/lock.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/monkey.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/os.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/pool.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/pywsgi.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/queue.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/resolver_ares.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/resolver_thread.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/select.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/server.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/socket.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/ssl.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/subprocess.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/thread.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/threading.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/threadpool.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/timeout.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/util.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/win32util.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/wsgi.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  Running '/bin/sh /private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/libev/configure > configure-output.txt' in /private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/build/temp.macosx-10.11-x86_64-3.5/libev
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py", line 317, in <module>
      run_setup(ext_modules)
    File "/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py", line 312, in run_setup
      "Development Status :: 4 - Beta"])
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/cbdelavenne/.virtualenv/python3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 176, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py", line 234, in build_extension
      self.gevent_prepare(ext)
    File "/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py", line 231, in gevent_prepare
      configure(self, ext)
    File "/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py", line 139, in configure_libev
      make_universal_header('config.h', 'SIZEOF_LONG', 'SIZEOF_SIZE_T', 'SIZEOF_TIME_T')
    File "/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py", line 111, in make_universal_header
      print >>f, line
  TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
  
  ----------------------------------------
Failed to build gevent
Installing collected packages: gevent
  Running setup.py install for gevent
    Complete output from command /Users/cbdelavenne/.virtualenv/python3.5/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pip-u5g0mn5z-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cbdelavenne/.virtualenv/python3.5/bin/../include/site/python3.5/gevent:
    running install
    running build
    running build_py
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'gevent.core' extension
    creating build/temp.macosx-10.11-x86_64-3.5/gevent
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U__llvm__ -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.11-x86_64-3.5/libev -Ilibev -I/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c gevent/gevent.core.c -o build/temp.macosx-10.11-x86_64-3.5/gevent/gevent.core.o
    In file included from gevent/gevent.core.c:249:
    In file included from gevent/libev.h:2:
    libev/ev.c:483:48: warning: '/*' within block comment [-Wcomment]
    /*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                                   ^
    libev/ev.c:1029:42: error: '_Noreturn' keyword must precede function declarator
      ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                             ^~~~~~~~~~~~
      _Noreturn
    libev/ev.c:832:26: note: expanded from macro 'ecb_noreturn'
      #define ecb_noreturn   _Noreturn
                             ^
    libev/ev.c:1625:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
      EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                                  ^
    libev/ev.c:1796:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
          ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:1807:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:1934:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
          ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    In file included from gevent/gevent.core.c:249:
    In file included from gevent/libev.h:2:
    In file included from libev/ev.c:2484:
    libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    In file included from gevent/gevent.core.c:249:
    In file included from gevent/libev.h:2:
    In file included from libev/ev.c:2490:
    libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
          ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:3648:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
      fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                           ~~~~~~~~~~^~~~~~~~~~~~~ ~
    libev/ev.c:3648:34: note: place parentheses around the '&' expression to silence this warning
      fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                     ^
                           (                      )
    libev/ev.c:3687:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4367:5: warning: unused variable 'ocur_' [-Wunused-variable]
        array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
        ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4407:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4445:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_check *, checks, checkmax, checkcnt, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4592:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4675:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
      ^
    libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    14 warnings and 1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------

  Failed building wheel for gevent
Command "/Users/cbdelavenne/.virtualenv/python3.5/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pip-u5g0mn5z-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cbdelavenne/.virtualenv/python3.5/bin/../include/site/python3.5/gevent" failed with error code 1 in /private/var/folders/qg/105dxk893pjc2xgq7tnj7md40000gp/T/pycharm-packaging0.tmp/gevent
```

Any idea what the problem might be?
Thanks!

**Comment by jamadden** [comment]
gevent 1.0.x is not compatible with Python 3. Please install 1.1rc1 for Python 3 support.
