### ISSUE TITLE
'import event' in python 3.5 fails with syntax error

### ISSUE THREAD

**Issue by mikeyhew** [gevent/gevent#721]
gevent==1.0.2

```
Python 3.5.1 (default, Jan 14 2016, 23:04:25) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/workspace/venv/lib/python3.5/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/home/ubuntu/workspace/venv/lib/python3.5/site-packages/gevent/hub.py", line 289
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

**Comment by mikeyhew** [comment]
Note: gevent was installed with pip

**Comment by mikeyhew** [comment]
Whoops, didn't mean to close the issue

**Comment by jamadden** [comment]
You need to use gevent 1.1 on Python 3. Gevent 1.0 does not support Python 3

**Comment by mikeyhew** [comment]
OK I see. The version on pip3 should be changed then, if it hasn't already been updated.

**Comment by Ivoz** [comment]
@mikeyhew gevent 1.1 is currently not stable yet (rc3 at time of writing). When it gets a stable release everything will work normally.
