### ISSUE TITLE
Gevent 1.1rc3 gets blocked in gevent/_semaphore.py:168 

### ISSUE THREAD

**Issue by rishi-chalo** [gevent/gevent#743]
Hi
Our stack is django - python v2.7.10 - running under gunicorn with greenlets set up on Heroku. Our gunicorn is set up to kill greenlets if they consume more than 25sec (using Mozilla's MozSvcGeventWorker).

Recently we moved to gevent 1.1rc3 and saw a big increase in timeouts, all with the following callstack:

    Traceback (most recent call last): 
      File "/app/.heroku/python/lib/python2.7/site-packages/gevent/greenlet.py", line 522, in run 
        result = self._run(*self.args, **self.kwargs) 
      File "/app/.heroku/python/lib/python2.7/site-packages/gevent/baseserver.py", line 153, in _close_when_done 
        return handle(*args) 
      File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 47, in handle 
        self.handle_request(listener_name, req, client, addr) 
      File "/app/gunicorn_worker.py", line 134, in handle_request 
        return super(MozSvcGeventWorker, self).handle_request(*args) 
      File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request 
        super(GeventWorker, self).handle_request(*args) 
      File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 100, in handle_request 
        respiter = self.wsgi(environ, resp.start_response) 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 175, in __call__ 
        signals.request_started.send(sender=self.__class__) 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send 
        response = receiver(signal=self, sender=sender, **named) 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 96, in reset_queries 
        for conn in connections.all(): 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 257, in all 
        return [self[alias] for alias in self] 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 242, in __getitem__ 
        backend = load_backend(db['ENGINE']) 
      File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 108, in load_backend 
        return import_module('%s.base' % backend_name) 
      File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module 
        __import__(name) 
      File "/app/.heroku/python/lib/python2.7/site-packages/gevent/builtins.py", line 56, in __import__ 
        _g_import_lock.acquire() 
      File "/app/.heroku/python/lib/python2.7/site-packages/gevent/lock.py", line 206, in acquire 
        rc = self._block.acquire(blocking) 
      File "gevent/_semaphore.py", line 201, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:4111) 
        def acquire(self, blocking=True, timeout=None): 
      File "gevent/_semaphore.py", line 229, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3932) 
        timeout = self._do_wait(timeout) 
      File "gevent/_semaphore.py", line 172, in gevent._semaphore.Semaphore._do_wait (gevent/gevent._semaphore.c:3199) 
        raise 
      File "gevent/_semaphore.py", line 168, in gevent._semaphore.Semaphore._do_wait (gevent/gevent._semaphore.c:3101) 
        result = get_hub().switch() 
      File "/app/.heroku/python/lib/python2.7/site-packages/gevent/hub.py", line 585, in switch 
        return greenlet.switch(self) 
    Timeout: 25 seconds 
    <Greenlet at 0x7fb828ed9b90: _close_when_done(<socket at 0x7fb82a4471d0 fileno=[Errno 9] Bad fil, ('10.61.193.190', 16066))> failed with Timeout 
In case it matters -- the callstack does refer to a load_backend(db['ENGINE'])  -- we use a Postgres database via psycopg + psycogreen, and use pgBouncer for database connection pooling. 

Any ideas what might be happening? Will moving to 1.1rc4 help?
Thanks!

**Comment by jamadden** [comment]
The traceback suggests a form of deadlock due to importing from multiple greenlets. It seems likely that the same deadlock could be observed using plain Python and threads instead of greenlets.

1.1rc4 *may* fix this for you because it backports Python 3's more fine-grained import locking.

**Comment by rishi-chalo** [comment]
Thanks! I'll try 1.1rc4 and report back. BTW one datapoint is: before we moved to rc3 (on Python 2.7.10), our previous stack was gevent 1.0.1 on Python 2.7.5, and we did not experience this issue. Anyway, I'll update this thread after we see how 1.1rc4 behaves under load.

**Comment by jamadden** [comment]
Under 1.0, the import lock system was completely bypassed (because the default lock was only a thread lock, and greenlets all share one thread). This could result in very bizarre and hard to debug behaviour, so greenlet locks were taken starting in 1.1b5 (IIRC) making gevent perform closer to the standard python behaviour. (See #108)

But it turned out that there were cases of code *relying* on this no-lock behaviour---code that would deadlock on standard python, but "worked" under gevent 1.0 because the locks were bypassed. This too makes debugging difficult and hampers portability to Python 3 (which handles locks differently than Python 2). So 1.1rc4 introduced a compromise that solves the known deadlock cases by behaving more like Python 3. (Partly explained in #728)

**Comment by rishi-chalo** [comment]
Wow thanks so much for the pointers and explanation! I've pushed rc4 to our production. I'll monitor how it behaves under load for the next 24h and will let you know.

**Comment by rishi-chalo** [comment]
Reporting back with good news - 1.1rc4 has been behaving well under load for us. Pl feel free to close out this issue if there's no further action items.

Thanks for all the help Jason and the gevent contributors, for the excellent library you've created!
