### ISSUE TITLE
Exception in pywsgi ??

### ISSUE THREAD

**Issue by kennedyshead** [gevent/gevent#760]
```
Traceback (most recent call last):
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/home/magnus/backendv2/env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7f0da23ba550: _handle_and_close_when_done(<bound method SocketIOServer.handle of <SocketIOSe, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f0da2375250 fileno=[Errno 9] Bad fi)> failed with UnicodeError

**Comment by jamadden** [comment]
It appears that the value for the header, 3600, is an int. The second argument to the `start_response` callable only accepts a List of tuples of strings (even for values; both the `header_name` and `header_value` are of type `str`)

**Comment by jamadden** [comment]
Note that other WSGI servers like [waitress](https://pypi.python.org/pypi/waitress) also produce a similar error. If you're just upgrading from gevent 1.0 to 1.1, this is newly enforced for better compliance with PEP3333 and support of Python 3. It's [documented](http://www.gevent.org/whatsnew_1_1.html#compatibility) in the release notes.
