### ISSUE TITLE
Can not join thread in signal handler after monkey patching

### ISSUE THREAD

**Issue by liujingchen** [gevent/gevent#799]
Joining thread inside a signal handler after calling "patch_all()" will cause "BlockingSwitchOutError: Impossible to call blocking function in the event loop callback".
This code can reproduce it:
```
from gevent.monkey import patch_all
patch_all()
from threading import Thread, Event
import signal
from time import sleep

stop_event = Event()

def run():
    stop_event.wait()
    print "run exit"

t = Thread(target=run)
t.start()

def close(signum, frame):
    print "Get exit signal, start to exit."
    stop_event.set()
    t.join()
    print "Join succeed"
    exit(0)

signal.signal(signal.SIGINT, close)
signal.signal(signal.SIGTERM, close)

while True:
    sleep(3)
    print "waiting..."
```
Pressing Ctrl + C, will get this error message:
```
^CGet exit signal, start to exit.
Traceback (most recent call last):
  File "test-gevent.py", line 19, in close
    t.join()
  File "/Users/liu/.pyenv/versions/2.7.9/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/Users/liu/.pyenv/versions/2.7.9/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
  File "gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:4038)
    def acquire(self, blocking=True, timeout=None):
  File "gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3859)
    timeout = self._do_wait(timeout)
  File "gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (gevent/gevent._semaphore.c:3092)
    result = get_hub().switch()
  File "/Users/liu/.pyenv/versions/tmp-venv/lib/python2.7/site-packages/gevent/hub.py", line 605, in switch
    switch_out()
  File "/Users/liu/.pyenv/versions/tmp-venv/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch_out
    raise BlockingSwitchOutError('Impossible to call blocking function in the event loop callback')
BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
Traceback (most recent call last):
  File "test-gevent.py", line 27, in <module>
    sleep(3)
  File "/Users/liu/.pyenv/versions/tmp-venv/lib/python2.7/site-packages/gevent/hub.py", line 194, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/Users/liu/.pyenv/versions/tmp-venv/lib/python2.7/site-packages/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/Users/liu/.pyenv/versions/tmp-venv/lib/python2.7/site-packages/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/Users/liu/.pyenv/versions/tmp-venv/lib/python2.7/site-packages/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
gevent.hub.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
run exit
```
If comment out the "patch_all()" in the 2nd line, the program can exit successfully. And if change it to "patch_all(thread=False)", the program can exit successfully as well. The cause seems to be the monkey patching for threads.
My environment is python 2.7.9 under Mac OSX 10.10.5. Versions from "pip freeze":
```
gevent==1.1.1
greenlet==0.4.9
```
Also tried in python 3.5.1, got the same results.

**Comment by jamadden** [comment]
This is expected.

Signal handlers run in the main thread and the main greenlet in that thread (whether anything is patched or not). The main greenlet is running the hub, and things that run in the hub can't switch out. Trying to join a greenlet-based thread requires switching.

The solution in gevent is to spawn a new greenlet from the signal handler to do the real work. [gevent.signal](http://www.gevent.org/gevent.html#gevent.signal) is a function that does that for you.

(More generally, I'm not sure it's a good idea to be doing much arbitrary work with other threads in a signal handler. By definition signals are asynchronous, which means that it's very difficult to know the state of the system at that time; locks could be held, for example, that prevent threads from finishing. The traditional approach to things like this is to set a flag from the handler that the main program examines periodically when it is safe to do so.)

**Comment by jamadden** [comment]
If there's nothing else here can you close this issue @liujingchen ?

**Comment by liujingchen** [comment]
@jamadden thank you very much for the answer!
Yes, I will close it.
