### ISSUE TITLE
gevent exception at end of test run: AttributeError: 'NoneType' object has no attribute 'modules' 

### ISSUE THREAD

**Issue by qluo1** [gevent/gevent#802]
I have encountered this strange error from gevent 1.1.1 in RedHat 6. 

gevent 1.1.1 always throws an exception after py.test finished test run.i am using gevent/zerorpc/0mq within my tests.

tried with gevent 1.0.2 seems ok.

the exception indicate that "sys" module is None? which is fairly strange to me??
```
=========================================== 6 passed, 693 deselected in 73.87 seconds ============================================
Traceback (most recent call last):
  File "/local/data/home/eqtdata/sandbox/luosam/works/lib/python2.7/site-packages/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 61
4, in _kill
    greenlet.throw(exception)
  File "/local/data/home/eqtdata/sandbox/luosam/works/lib/python2.7/site-packages/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 34
6, in throw
    greenlet.throw(self, *args)
  File "/local/data/home/eqtdata/sandbox/luosam/works/lib/python2.7/site-packages/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 53
7, in run
    self._report_error(sys.exc_info())
  File "/local/data/home/eqtdata/sandbox/luosam/works/lib/python2.7/site-packages/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 51
8, in _report_error
    self._exc_info = exc_info[0], exc_info[1], dump_traceback(exc_info[2])
  File "/local/data/home/eqtdata/sandbox/luosam/works/lib/python2.7/site-packages/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/_tblib.py", line 239,
 in g
**    if 'gevent.builtins' in sys.modules:
AttributeError: 'NoneType' object has no attribute 'modules'**
Traceback (most recent call last):
  File "/local/data/home/eqtdata/sandbox/luosam/works/lib/python2.7/site-packages/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/hub.py", line 596, in
 print_exception
    context = self.format_context(context)
  File "/gns/mw/lang/python/python-2.7.2-gns.03/lib/python2.7/pprint.py", line 60, in pformat
    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
TypeError: 'NoneType' object is not callable
<Greenlet at 0x29a5c30> failed with AttributeError
```

**Comment by jamadden** [comment]
On Python 2, module globals are set to `None` as one of the last parts of interpreter shutdown. So this appears to be an exception that's being thrown during interpreter shutdown (an atexit hook?), which is trying to be reported and in turn triggers an AttributeError. (Under earlier versions of gevent, it's entirely possible that the original exception went unnoticed.)

Can you debug the original exception?

**Comment by qluo1** [comment]
thanks for the help. it turned out that is my zerorpc client session hasn't been closed properly on interpreter shutdown.

## remove rpc
symbol_manager = zerorpc.Client(settings.SYMBOL_MANAGER_ENDPOINT,timeout=60,heartbeat=60)
**atexit.register(symbol_manager.close)**

add code atexit, seems fixed my problem.
the zerorpc client's close method actually close stock and kill its internal gevent worker.

hasn't got time to track down exactly where and what exception occurred?? i would suspect it is zmq socket generated original exception??

**Comment by jamadden** [comment]
I would certainly have no idea, those are a lot of heavy third party dependencies. 

If there's nothing more to this can you close the issue?

**Comment by qluo1** [comment]
issue closed. thanks for the help.
