### ISSUE TITLE
"Cannot set attribute" when module reload(site) called

### ISSUE THREAD

**Issue by jakehilton** [gevent/gevent#805]
Using saltstack 2016.3 I recently ran across this traceback:
```
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_proxy'
[DEBUG   ] Refreshing modules...
......
Passed invalid arguments: Cannot set attribute.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 594, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3173, in call_highstate
    self.load_dynamic(matches)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2706, in load_dynamic
    self.state.module_refresh()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 857, in module_refresh
    reload(site)
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 541, in main
    abs__file__()
  File "/usr/lib/python2.7/site.py", line 100, in abs__file__
    m.__file__ = os.path.abspath(m.__file__)
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 87, in __setattr__
    raise TypeError("Cannot set attribute")
TypeError: Cannot set attribute
```

The bug is filed here: https://github.com/saltstack/salt/issues/33143

They believe this to be a bug in gevent 1.1 and not the specific implementation of how they are using it. It seems as though a simple `reload(site)` is causing the blowup which shouldn't be so.

Any help on flushing this out would be much appreciated.

**Comment by jakehilton** [comment]
Environment details:
Ubuntu 14.04
Python 2.7.6
Gevent: 1.1.1

**Comment by jamadden** [comment]
Thanks for the report!

**Comment by jakehilton** [comment]
No problem. Thank you for the quick fix!
