### ISSUE TITLE
WSGIServer fails on FreeBSD for non-local addresses: AttributeError: 'gaierror' object has no attribute 'with_traceback'

### ISSUE THREAD

**Issue by yurivict** [gevent/gevent#817]
* gevent version: py27-gevent-1.1.0
* Python version: 2.7_2
* Operating System: FreeBSD 10.3

This script https://github.com/gevent/gevent/blob/master/examples/wsgiserver.py fails on FreeBSD. It fails with ip='', ip='0.0.0.0' and ip=<some non-local address>, but succeeds with ip='127.0.0.1'

```
Serving on 8088...
Traceback (most recent call last):
  File "ui-all.py", line 18, in <module>
    WSGIServer(('0.0.0.0', 8088), application).serve_forever()
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
    self.start()
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 291, in start
    self.init_socket()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1223, in init_socket
    self.update_environ()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1235, in update_environ
    name = socket.getfqdn(address[0])
  File "/usr/local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 307, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
  File "/usr/local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 280, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "/usr/local/lib/python2.7/site-packages/gevent/resolver_thread.py", line 67, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 379, in get
    return self.get(block=False)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 369, in get
    return self._raise_exception()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 349, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python2.7/site-packages/gevent/_util_py2.py", line 8, in reraise
    raise type(value).with_traceback(tb)
AttributeError: 'gaierror' object has no attribute 'with_traceback'
```

**Comment by jamadden** [comment]
I'm very confused. How are you installing gevent? Are you perhaps installing a FreeBSD port or some other third-party (non-gevent) package? 

Because the traceback you mention is not possible in *any* 1.1.x version of gevent (including pre-releases) AFAICS. Here's line 8 in 1.1.0: https://github.com/gevent/gevent/blob/v1.1.0/gevent/_util_py2.py#L8

It almost looks like someone tried to "fix" (harmless) SyntaxErrors that are produced when byte-compiling under Python 3...but that code is only used under Python 2.

Can you try using the official gevent distributed on PyPI (1.1.1)?

**Comment by jamadden** [comment]
Yeah, FreeBSD is shipping *broken* code: http://svnweb.freebsd.org/ports/head/devel/py-gevent/files/patch-gevent-_util_py2.py?revision=410552&view=markup&pathrev=410552

**Comment by jamadden** [comment]
From inspection of the code, it seems clear that if you use the correct/official gevent code, this should work as intended. 

The version distributed by FreeBSD is going to be badly broken in many cases on Python 2.

It looks like the correct place to report a bug might be [here](https://bugs.freebsd.org/bugzilla/enter_bug.cgi) but I don't have, and don't want to create, an account there.

**Comment by yurivict** [comment]
Yes, I use The FreeBSD port. This is the official way to install packages on FreeBSD.

The *only* patch that this port applies to the version 1.1.1 is:
```
 def reraise(type, value, tb):
-    raise type, value, tb
+    raise type(value).with_traceback(tb)
```

How is the port damaged?

**Comment by yurivict** [comment]
I submitted the port bug report:  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210216
