### ISSUE TITLE
Cannot install gevent 1.1.1 on PyPy 5.3

### ISSUE THREAD

**Issue by thedrow** [gevent/gevent#820]
* gevent version: 1.1.1
* Python version: PyPy 5.3
* Operating System: OSX El Capitan

### Description:
I'm trying to install gevent on PyPy 5.3

### What I've run:
pip install gevent

See build output:
```
pip install gevent
Collecting gevent
  Downloading gevent-1.1.1.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 269kB/s
Building wheels for collected packages: gevent
  Running setup.py bdist_wheel for gevent ... error
  Complete output from command /Users/omer.katz/.virtualenvs/hiredis-py/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/tmpyff7V2pip-wheel- --python-tag pp253:
  Running '(cd  "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/libev"  && /bin/sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent
  Running 'rm config.h' in /private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-2.7
  creating build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_corecffi_build.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_fileobjectcommon.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_fileobjectposix.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_semaphore.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_socket2.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_socket3.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_socketcommon.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_ssl2.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_ssl3.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_sslgte279.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_tblib.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_threading.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/_util_py2.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/backdoor.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/baseserver.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/builtins.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/core.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/corecffi.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/coros.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/event.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/fileobject.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/greenlet.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/hub.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/local.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/lock.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/monkey.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/os.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/pool.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/pywsgi.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/queue.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/resolver_ares.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/resolver_thread.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/select.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/server.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/signal.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/socket.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/ssl.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/subprocess.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/thread.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/threading.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/threadpool.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/timeout.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/util.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/win32util.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/wsgi.py -> build/lib.macosx-10.11-x86_64-2.7/gevent
  running egg_info
  creating gevent.egg-info
  writing gevent.egg-info/PKG-INFO
  writing dependency_links to gevent.egg-info/dependency_links.txt
  writing top-level names to gevent.egg-info/top_level.txt
  writing manifest file 'gevent.egg-info/SOURCES.txt'
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'gevent.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching '*/__pycache__'
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '*.o' found anywhere in distribution
  no previously-included directories found matching 'doc/_build'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found under directory 'greentest'
  no previously-included directories found matching 'greentest/htmlcov'
  warning: no previously-included files matching 'stamp-h?' found under directory 'c-ares'
  warning: no previously-included files matching 'ares_build.h.orig' found under directory 'c-ares'
  warning: no previously-included files matching '_corecffi.c' found under directory 'gevent'
  warning: no previously-included files found matching 'Makefile'
  writing manifest file 'gevent.egg-info/SOURCES.txt'
  copying gevent/_semaphore.pxd -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/ares.pyx -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/callbacks.c -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/callbacks.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/cares.pxd -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/cares_ntop.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/cares_pton.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/corecext.ppyx -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/corecext.pyx -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/dnshelper.c -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/gevent._semaphore.c -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/gevent.ares.c -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/gevent.ares.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/gevent.corecext.c -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/gevent.corecext.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/libev.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/libev.pxd -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/libev_vfd.h -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/python.pxd -> build/lib.macosx-10.11-x86_64-2.7/gevent
  copying gevent/stathelper.c -> build/lib.macosx-10.11-x86_64-2.7/gevent
  running build_ext
  generating cffi module 'build/temp.macosx-10.11-x86_64-2.7/gevent._corecffi.c'
  creating build/temp.macosx-10.11-x86_64-2.7
  Running '(cd  "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/c-ares"  && if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && /bin/sh ./configure CONFIG_COMMANDS= CONFIG_FILES=   && cp ares_config.h ares_build.h "$OLDPWD"   && mv ares_build.h.orig ares_build.h) > configure-output.txt' in /private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/build/temp.macosx-10.11-x86_64-2.7/c-ares
  configure: error: Can not continue. Fix errors mentioned immediately above this line.
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
    File "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py", line 516, in <module>
      run_setup(ext_modules, run_make=run_make)
    File "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py", line 502, in run_setup
      **setup_kwds
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/omer.katz/.virtualenvs/hiredis-py/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/cmd.py", line 334, in run_command
      self.distribution.run_command(command)
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/cmd.py", line 334, in run_command
      self.distribution.run_command(command)
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib_pypy/cffi/setuptools_ext.py", line 109, in run
      base_class.run(self)
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/command/build_ext.py", line 347, in run
      self.build_extensions()
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/distutils/command/build_ext.py", line 456, in build_extensions
      self.build_extension(ext)
    File "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py", line 305, in build_extension
      self.gevent_prepare(ext)
    File "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py", line 302, in gevent_prepare
      configure(self, ext)
    File "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py", line 219, in configure_ares
      rc = _system(ares_configure_command)
    File "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/setup.py", line 172, in _system
      return check_call(cmd, shell=True)
    File "/Users/omer.katz/.pyenv/versions/pypy-5.3/lib-python/2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '(cd  "/private/var/folders/_1/_dz90xh13tjg1ddvrql64pn40009w1/T/pip-build-o3KH_I/gevent/c-ares"  && if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && /bin/sh ./configure CONFIG_COMMANDS= CONFIG_FILES=   && cp ares_config.h ares_build.h "$OLDPWD"   && mv ares_build.h.orig ares_build.h) > configure-output.txt' returned non-zero exit status 1
```

**Comment by jamadden** [comment]
The bundled c-ares library failed to configure (which should not be pypy-specific). If you check its output file (as included on the last line; you may have to run setup manually or tell pip not to clear temp directories) it should tell you why.

**Comment by thedrow** [comment]
I have set CFLAGS for something else. Man that's brittle.
Do you want to resolve this somehow (e.g. document this) or just close?

**Comment by jamadden** [comment]
It is documented in [at least one place](http://www.gevent.org/whatsnew_1_1.html#library-updates).

**Comment by thedrow** [comment]
Thanks!
