### ISSUE TITLE
exc_info on successfully completed greenlet raises TypeError

### ISSUE THREAD

**Issue by brentthew** [gevent/gevent#821]
* gevent version: 1.1.1
* Python version: 2.7.11
* Operating System: OSX

### Description:

Calling exc_info on a completed greenlet (that did not finish with an error) results in a TypeError.

### What I've run:

MVE:
```python
from gevent.greenlet import Greenlet

def foo():
    pass

bar = Greenlet(foo)
bar.start()
bar.join()

bar.exc_info
```

results in the following traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/greenlet.py", line 326, in exc_info
    return (e[0], e[1], load_traceback(e[2]))
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/_tblib.py", line 243, in g
    return f(a)
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/_tblib.py", line 304, in load_traceback
    return loads(s)
TypeError: must be string, not None
```

```
>>> bar._exc_info
(None, None, None)
```

So the issue is load_traceback is being called with None.

https://github.com/gevent/gevent/blob/master/src/gevent/greenlet.py#L311-L316

**Comment by brentthew** [comment]
The issue actually presented itself in code more like this snippet

```python
class Test(Greenlet):
    def __init__(self):
        super(Test, self).__init__()

        def _cb(g):
            print g.exc_info
        self.link(_cb)

    def _run(self):
        pass

test = Test()
test.start()
test.join()
```

With a similar traceback

```
Traceback (most recent call last):
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/greenlet.py", line 593, in _notify_links
    link(self)
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/greenlet.py", line 45, in __call__
    g.switch(source)
  File "<stdin>", line 5, in _cb
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/greenlet.py", line 326, in exc_info
    return (e[0], e[1], load_traceback(e[2]))
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/_tblib.py", line 243, in g
    return f(a)
  File "/Users/bthew/.virtualenvs/gevent_test/lib/python2.7/site-packages/gevent/_tblib.py", line 304, in load_traceback
    return loads(s)
TypeError: must be string, not None
(<function _cb at 0x101a649b0>, <Test at 0x1019834b0>) failed with TypeError
```

**Comment by jamadden** [comment]
Thank you for the report, I will make a change.

Please be aware that although `exc_info` has a docstring, it is not [a fully documented/supported property](http://www.gevent.org/gevent.html#gevent.Greenlet), didn't exist in 1.0, and might change in incompatible ways. The `exception` attribute is the supported mechanism for accessing this kind of information.
