### ISSUE TITLE
Constant exception under Python 3.5.1 OS X

### ISSUE THREAD

**Issue by ssteinerx** [gevent/gevent#823]
* gevent version: 1.1.1
* Python version: 3.5.1
* Operating System: OS X 10.11.5

Running example project from: [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO)

And, I've reported it there as well: [#272](https://github.com/miguelgrinberg/Flask-SocketIO/issues/272)

```
Traceback (most recent call last):
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 1253, in handle
    handler.handle()
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 916, in handle_one_response
    self.log_request()
  File "/.virtualenvs/lib/python3.5/site-packages/geventwebsocket/handler.py", line 236, in log_request
    if '101' not in self.status:
TypeError: a bytes-like object is required, not 'str'
<Greenlet at 0x103e139c8: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError
```

**Comment by jamadden** [comment]
gevent maintains `self.status` as a byte string on both python 2 and python 3. It does the same thing for the response headers.

**Comment by jamadden** [comment]
This is hardly surprising as geventwebsocket's latest PyPI release *predates* gevent 1.1a1, which was when Python 3 support debuted in gevent, so geventwebsocket probably doesn't support Python 3.

It appears [work began](https://bitbucket.org/noppo/gevent-websocket/commits/2141053485feae3431488b2f3a486c520e4be444#chg-geventwebsocket/handler.py) on Python 3 support in December 2015.
