### ISSUE TITLE
Raise exception with cannot watch more than 1024 sockets

### ISSUE THREAD

**Issue by yisake** [gevent/gevent#854]
* gevent version:1.1.1
* Python version:2.7.10.12
* Operating System:Windows7 64bit

### Description:

```
[2016-09-05 10:28:25,568] ThinkPad-PC/ERROR/stderr: Traceback (most recent call last):
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\locust\core
.py", line 267, in run
    self.execute_next_task()
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\locust\core
.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\locust\core
.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "D:\360云盘\Fangdd\python\locust_test.py", line 17, in index
    with self.client.get("/does_not_exist/", catch_response=True) as response:
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\se
ssions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\locust\clie
nts.py", line 113, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\locust\clie
nts.py", line 157, in _send_request_safe_mode
    return requests.Session.request(self, method, url, **kwargs)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\se
ssions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\se
ssions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\ad
apters.py", line 376, in send
    timeout=timeout
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\pa
ckages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\pa
ckages\urllib3\connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python27\Lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\Lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\Lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\Lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\Lib\httplib.py", line 855, in send
    self.connect()
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\pa
ckages\urllib3\connection.py", line 162, in connect
    conn = self._new_conn()
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\pa
ckages\urllib3\connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\requests\pa
ckages\urllib3\util\connection.py", line 71, in create_connection
    sock = socket.socket(af, socktype, proto)
  File "c:\users\administrator\documents\github\customer_side\packages\lib\site-packages\gevent\_soc
ket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:154
70)
IOError: cannot watch more than 1024 sockets
```

### What I've run:

```
I try to use locust to execute http load test, and locust use requests for generating the http request. But
I met the error with cannot watch more than 1024 sockets. If I need to set the number in my system?
```

**Comment by jamadden** [comment]
I'm sorry, I'm afraid that is one of many hard coded limitations of gevent and libev on windows. (http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#WIN32_PLATFORM_LIMITATIONS_AND_WORKA). I have no suggested workaround other than to use a different platform.

**Comment by yisake** [comment]
@jamadden What I can do for this exception, I raise by python requests lib. Need I close the session after sending request? Or where can I set the value for the maximum socket number?

**Comment by jamadden** [comment]
Please refer to the documentation for the particular tool you are using to see how to make it use fewer sockets (I suspect that would defeat the point of a load testing tool). You *cannot* change the number of sockets gevent supports.

**Comment by yisake** [comment]
May I just ask for a question @jamadden How can I record the server log into a file(I use > in linux but it doesn't have effect ). I want to check server errors.

#coding=utf-8
from gevent.pywsgi import WSGIServer

def application(environ, start_response):
    
    if environ['PATH_INFO'] =='/':
    
        status = '200 OK'

        headers = [
            ('Content-Type', 'text/html')
        ]

        start_response(status, headers)
        yield "<p>Hello"

WSGIServer(('', 8000), application).serve_forever()

**Comment by jamadden** [comment]
@yisake Please refer to the documentation for [WSGIServer](http://www.gevent.org/gevent.pywsgi.html#gevent.pywsgi.WSGIServer) and/or lookup [how to redirect stderr](https://www.google.com/search?client=safari&rls=en&q=redirect+stderr).

Please don't use this issue tracker to ask general questions (especially not on closed issues); try the mailing list, IRC, stackoverflow, etc.
