### ISSUE TITLE
Error when using BoundedSemaphore with initial value 0

### ISSUE THREAD

**Issue by hqythu** [gevent/gevent#862]
* gevent version: 1.1.2
* Python version: 3.5
* Operating System: Mac OS X

### Description:

I was trying to use semaphore with initial value of 0, which means a greenlet waited on this semaphore must wait until another greenlet to release to be continued. This is a common use case when a greenlet need to be informed of something to be continued.

### What I've run:

I write the following code as a simple illustration. 
```python
import gevent
from gevent.coros import Semaphore, BoundedSemaphore


sem = BoundedSemaphore(0)


def func1():
    print('greenlet 1 attempt to acquire semaphore')
    sem.acquire()
    print('greenlet 1 acquired semaphore')


def func2():
    print('greenlet 2 attempt to release semaphore')
    sem.release()
    print('greenlet 2 released semaphore')


def main():
    gevent.joinall([
        gevent.spawn(func1),
        gevent.spawn(func2),
    ])


if __name__ == '__main__':
    main()
```
full code can be get at [gist](https://gist.github.com/hqythu/12aba31be272c3f9cec49d14825d29e8)

and I get the following error:
```
greenlet 1 attempt to acquire semaphore
greenlet 2 attempt to release semaphore
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "semaphore_test.py", line 16, in func2
    sem.release()
  File "gevent/_semaphore.py", line 266, in gevent._semaphore.BoundedSemaphore.release (gevent/gevent._semaphore.c:4909)
  File "gevent/_semaphore.py", line 268, in gevent._semaphore.BoundedSemaphore.release (gevent/gevent._semaphore.c:4848)
ValueError: Semaphore released too many times
<Greenlet at 0x10beeaa60: func2> failed with ValueError

Traceback (most recent call last):
  File "semaphore_test.py", line 28, in <module>
    main()
  File "semaphore_test.py", line 23, in main
    gevent.spawn(func2),
  File "/usr/local/lib/python3.5/site-packages/gevent/greenlet.py", line 631, in joinall
    return wait(greenlets, timeout=timeout, count=count)
  File "/usr/local/lib/python3.5/site-packages/gevent/hub.py", line 1017, in wait
    return list(iwait(objects, timeout, count))
  File "/usr/local/lib/python3.5/site-packages/gevent/hub.py", line 964, in iwait
    item = waiter.get()
  File "/usr/local/lib/python3.5/site-packages/gevent/hub.py", line 918, in get
    Waiter.get(self)
  File "/usr/local/lib/python3.5/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/usr/local/lib/python3.5/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x10beea800 select default pending=0 ref=0>)
```

It turns out that value check in `BounedSemaphore ` cause that error. I reviewed that piece of code and run several test, and I found the bound check work well except for initial value 0.

Is that designed deliberately? Should I just use `Semaphore` instead? Or some modification should be made to solve that problem?

If needed, I can do something to resolve this issue.

**Comment by jamadden** [comment]
A BoundedSemaphore represents a limited resource, and the limit is given at construction time. To protect you from bugs, it enforces that limit. A limit of zero means there are no resources, so none can be returned. It's nonsensical. 

You could use a plain Semaphore, which doesn't enforce this constraint. However, it sounds like you may want an Event or Condition instead

gevent.coros has been deprecated for years. Please don't ignore the warning and please update to modern locations (and check the updated docs).

**Comment by hqythu** [comment]
Thanks for clarification. Since it is purposely designed, I will close this issue.

But I think it necessary to write the problem somewhere in the docs.
