### ISSUE TITLE
TypeError: child watchers are only available on the default loop

### ISSUE THREAD

**Issue by 984958198** [gevent/gevent#867]
tgscheduler + gevent + gnupg

Traceback (most recent call last):
  File "/home/risingstar-erp/source/risingstarerp/controllers/zhonghang.py", line 266, in sftp_download_orders
    retfile = gpg_decrypt_file(localPath)
  File "/home/risingstar-erp/source/risingstarerp/controllers/zhonghang.py", line 1132, in gpg_decrypt_file
    status = gpg.decrypt_file(f, passphrase=gpg_pw, output=output_name)
  File "/home/tg2env/local/lib/python2.7/site-packages/gnupg.py", line 1415, in decrypt_file
    self._handle_io(args, file, result, passphrase, binary=True)
  File "/home/tg2env/local/lib/python2.7/site-packages/gnupg.py", line 889, in _handle_io
    p = self._open_subprocess(args, passphrase is not None)
  File "/home/tg2env/local/lib/python2.7/site-packages/gnupg.py", line 808, in _open_subprocess
    startupinfo=si)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1153, in _execute_child
    self.pid = os.fork()
  File "/home/tg2env/local/lib/python2.7/site-packages/gevent/os.py", line 385, in fork
    return fork_and_watch(*args, **kwargs)
  File "/home/tg2env/local/lib/python2.7/site-packages/gevent/os.py", line 341, in fork_and_watch
    watcher = loop.child(pid, ref=ref)
  File "gevent/corecext.pyx", line 511, in gevent.corecext.loop.child (gevent/gevent.corecext.c:9881)
  File "gevent/corecext.pyx", line 1876, in gevent.corecext.child.__init__ (gevent/gevent.corecext.c:32615)
TypeError: child watchers are only available on the default loop

(tg2env)root@10-13-43-127:~# pip list
alembic (0.6.3)
Babel (1.3)
backlash (0.0.4)
Beaker (1.7.0)
chaussette (1.3.0)
cliff (1.5.2)
cmd2 (0.6.7)
crank (0.7.2)
decorator (3.4.2)
distribute (0.7.3)
ecdsa (0.13)
FormEncode (1.3.0)
gearbox (0.0.5)
gearbox-tools (0.0.1)
Genshi (0.7)
gevent (1.1.2)
greenlet (0.4.10)
Jinja2 (2.7.2)
lxml (3.3.1)
Mako (0.9.1)
MarkupSafe (0.23)
MySQL-python (1.2.5)
paramiko (1.15.2)
PasteDeploy (1.5.2)
pip (8.1.2)
prettytable (0.7.2)
pycrypto (2.6.1)
pyparsing (2.0.1)
python-dateutil (2.4.2)
python-gnupg (0.3.9)
pytz (2013.9)
repoze.lru (0.6)
repoze.who (2.2)
requests (2.7.0)
risingstarerp (0.1dev-r0, /home/risingstar-erp/source)
setuptools (18.0.1)
simplejson (3.3.3)
six (1.9.0)
speaklater (1.3)
sprox (0.9.7)
spyne (2.10.10)
SQLAlchemy (1.0.7)
stevedore (0.14.1)
suds (0.4)
Tempita (0.5.3.dev0)
tg.devtools (2.3.1)
tg2ext.express (0.3.3.dev0)
tgext.admin (0.6.5)
tgext.asyncjob (0.3.1)
tgext.crud (0.7.4)
TGScheduler (1.7.0)
transaction (1.4.4)
TurboGears2 (2.3.5)
tw2.core (2.2.2)
tw2.forms (2.2.2.1)
waitress (0.8.9)
WebOb (1.4.1)
WebTest (1.4.3)
xlrd (0.9.4)
xlwt (1.0.0)
zope.interface (4.1.2)
zope.sqlalchemy (0.7.6)

**Comment by jamadden** [comment]
What's your question? That is [a documented limitation](http://www.gevent.org/gevent.subprocess.html) of libev/gevent.

**Comment by 984958198** [comment]
我也说不清楚是什么问题，用tgscheduler开启一个定时任务gnupg模块会出错，脚本中使用了monkey.patch_all()，然而去掉它是正常的，但脚本中同时又使用了paramiko模块，需要用到monkey.patch_all()

**Comment by 984958198** [comment]
I don't know what the problem is, tgscheduler opened a timed task gnupg module will go wrong, using monkey.patch_all script (), but it is normal, but the script also uses the paramiko module, need to use monkey.patch_all ()

**Comment by jamadden** [comment]
I'm sorry, I do not know how to help you. All I can suggest is make sure you call `patch_all` as early as possible. 

You can try asking on the mailing list. I don't see how else to resolve this issue.

**Comment by 984958198** [comment]
Thank you
