### ISSUE TITLE
gevent grace period for greenlets to terminate

### ISSUE THREAD

**Issue by dansok** [gevent/gevent#869]
* gevent version: 1.0.2
* gevent-psycopg2version : 0.0.3
* gevent-websocket version: 0.3.6
* nose-gevent-monkey version: 0.0.1
* Python version: 2.7.10
* Operating System: OSX Yosemite 10.10.5

### Description:

I have n workers running on greenlets . On a SIGTERM signal, I'd like to first give the workers a grace period to run. If all the workers finished prior to the expiration of that grace period, terminate instantly; else, if that period expires, I'd like to forcefully kill all the workers anyway.

### What I've run:

```
greenlets = map(lambda t: gevent.spawn(t), get_workers())

def die(signal=None, stack_trace=None):
    print "I AM HERE !!!"
    gevent.wait(objects=greenlets, timeout=3)
    # gevent.killall(greenlets)

signal.signal(signal.SIGTERM, die)

gevent.joinall(greenlets)
```

### Output in console:

```
I AM HERE !!!
Traceback (most recent call last):
  File "mq/app/scheduler.py", line 41, in die
    gevent.wait(objects=greenlets, timeout=3)
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 1017, in wait
    return list(iwait(objects, timeout, count))
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 964, in iwait
    item = waiter.get()
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 918, in get
    Waiter.get(self)
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 608, in switch
    switch_out()
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 612, in switch_out
    raise BlockingSwitchOutError('Impossible to call blocking function in the event loop callback')
BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
Traceback (most recent call last):
  File "mq/app/scheduler.py", line 46, in <module>
    gevent.joinall(greenlets)
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/greenlet.py", line 631, in joinall
    return wait(greenlets, timeout=timeout, count=count)
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 1017, in wait
    return list(iwait(objects, timeout, count))
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 964, in iwait
    item = waiter.get()
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 918, in get
    Waiter.get(self)
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/Users/dansokolsky/api/env/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
gevent.hub.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback

```

**Comment by jamadden** [comment]
- gevent 1.0 is outdated. Please update to gevent 1.1
- The error is pretty clear; you can't call `wait` in the hub. You need to spawn a new greenlet to handle that. (This may be handled for you automatically in gevent 1.1, or if you use `gevent.signal` instead of relying on the (monkeypatched?) signal.signal).

**Comment by dansok** [comment]
Thanks for the comment. It seems like updating to gevent 1.1.2 solved the problem..
