### ISSUE TITLE
BlockingSwitchOutError when using spawn=None in pywsgi.WSGIServer and boto/dynamodb

### ISSUE THREAD

**Issue by mike-hart** [gevent/gevent#877]
* gevent version: 1.1.2
* Python version: pypy 5.4.1
* Operating System: Debian GNU/Linux 8

### Description:

Using spawn=None (as opposed to not specifying spawn at all) in pywsgi.WSGIServer causes a traceback when accessing an AWS DynamoDB table using boto3. If you don't specify spawn=None, it appears to work.

### What I've run:

(using boto3==1.4.1, falcon==1.1.0rc1)

```
import os
import time

import boto3
import falcon
import gevent.monkey
import gevent.pywsgi


class Resource(object):

    def on_get(self, req, resp):
        table.get_item(Key={'id': 0})


if __name__ == '__main__':
    gevent.monkey.patch_all()
    print 1
    dynamodb = boto3.resource('dynamodb', region_name=os.environ['AWS_REGION'])
    table = dynamodb.Table('test_table')
    # table = dynamodb.create_table(
    #     TableName='test_table',
    #     KeySchema=[{'AttributeName': 'id', 'KeyType': 'HASH'}],
    #     AttributeDefinitions=[{'AttributeName': 'id', 'AttributeType': 'N'}],
    #     ProvisionedThroughput={'ReadCapacityUnits': 100,
    #                            'WriteCapacityUnits': 100})
    # table.wait_until_exists()
    # while table.table_status != 'ACTIVE':
    #     time.sleep(0.5)
    app = falcon.API()
    app.add_route('/', Resource())
    server = gevent.pywsgi.WSGIServer(('', 8000), app, spawn=None)
    server.serve_forever()
```

with pypy wsgi.py

Results in the traceback:

```
Traceback (most recent call last):
  File "/usr/local/site-packages/gevent/pywsgi.py", line 884, in handle_one_response
    self.run_application()
  File "/usr/local/site-packages/gevent/pywsgi.py", line 870, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/site-packages/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "wsgi.py", line 13, in on_get
    table.get_item(Key={'id': 0})
  File "/usr/local/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/usr/local/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

**Comment by mike-hart** [comment]
Finally worked out what spawn=None means, ignore this, sorry.

**Comment by mike-hart** [comment]
http://www.gevent.org/gevent.baseserver.html#gevent.baseserver.BaseServer for future reference of those who may have seen spawn=None used in some example code.
