### ISSUE TITLE
This operation would block forever on HTTP requests

### ISSUE THREAD

**Issue by LadaBr** [gevent/gevent#933]
* gevent version: newest
* Python version: 3.5.2
* Operating System: Ubuntu 14

### Description:

I use Django, UWSGI and Nginx and I installed packages called "steam" and "dota2" that requires gevent. Whenever I call 
```
client = SteamClient()
client.connect()
```

I start to get errors on all HTTP requests:

```
 Exception happened during processing of request from ('213.235.140.8', 48658)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/socketserver.py", line 625, in process_request_thread
     self.finish_request(request, client_address)
   File "/usr/local/lib/python3.5/socketserver.py", line 354, in finish_request
     self.RequestHandlerClass(request, client_address, self)
   File "/usr/local/lib/python3.5/socketserver.py", line 681, in __init__
     self.handle()
   File "/var/www/dotaleague.cz/env/lib/python3.5/site-packages/django/core/servers/basehttp.py", ine 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
   File "/usr/local/lib/python3.5/socket.py", line 575, in readinto
     return self._sock.recv_into(b)
   File "/var/www/dotaleague.cz/env/lib/python3.5/site-packages/gevent/_socket3.py", line 385, in recv_into
     self._wait(self._read_event)
   File "/var/www/dotaleague.cz/env/lib/python3.5/site-packages/gevent/_socket3.py", line 157, in _wait
     self.hub.wait(watcher)
   File "/var/www/dotaleague.cz/env/lib/python3.5/site-packages/gevent/hub.py", line 651, in wait
     result = waiter.get()
   File "/var/www/dotaleague.cz/env/lib/python3.5/site-packages/gevent/hub.py", line 899, in get
     return self.hub.switch()
   File "/var/www/dotaleague.cz/env/lib/python3.5/site-packages/gevent/hub.py", line 630, in switch
     return RawGreenlet.switch(self)
 gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7fd4e436b048 epoll pending=0 ref=0 fileno=167>)

```
Results in empty header responses.

**Comment by jamadden** [comment]
This (almost always) isn't a problem in gevent, it's a problem in the way it's being used. This indicates that there is not any other greenlets running to switch to. 

You're describing a very complicated environment so I can't offer any more guidance than that. There are lots of previous issues and google hits for this though that should help you figure it out.
