### ISSUE TITLE
Socks5 proxy and gevent error AttributeError: type object '_BaseSocket' has no attribute 'getpeername'

### ISSUE THREAD

**Issue by masolit** [gevent/gevent#934]
* gevent version: 1.2.1
* Python version: 3.6
* Operating System: Linux Arch

### Description:
You need to install PySocks
```
pip install pysocks
```
I try to use socks5 with gevent and i recieve error
```
AttributeError: type object '_BaseSocket' has no attribute 'getpeername'
```

### What I've run:

it's happened with gevent only

I try to use socks5 with gevent and i recieve error
```
AttributeError: type object '_BaseSocket' has no attribute 'getpeername'
```

### What I've run:
# requests
```python
from gevent import monkey
monkey.patch_all()

import requests
proxy = {'http': 'socks5://127.0.0.1:9050'}

r = requests.get('http://myip.dnsomatic.com', proxies=proxy).content
print(r)
```

```
Traceback (most recent call last):
  File "/home/masolit/IdeaProjects/Python/scraping/tor_reqests2.py", line 12, in <module>
    r = requests.get('http://myip.dnsomatic.com', proxies=proxy).content
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    conn.sock.settimeout(read_timeout)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 288, in settimeout
    peer = self.get_proxy_peername()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 429, in get_proxy_peername
    return _BaseSocket.getpeername(self)
AttributeError: type object '_BaseSocket' has no attribute 'getpeername'
```

### or:
# urllib
```python
from gevent import monkey
monkey.patch_all()

import urllib.request
import socks
from sockshandler import SocksiPyHandler

request = urllib.request.Request('http://myip.dnsomatic.com')
opener = urllib.request.build_opener(SocksiPyHandler(socks.SOCKS5, '127.0.0.1', 9050))
urllib.request.install_opener(opener)

handle = urllib.request.urlopen(request, timeout=60)
print(handle.read())
```

```
Traceback (most recent call last):
  File "/home/masolit/IdeaProjects/Python/scraping/tor_reqests2.py", line 28, in <module>
    handle = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 62, in http_open
    return self.do_open(build, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 35, in connect
    self.sock.settimeout(self.timeout)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 288, in settimeout
    peer = self.get_proxy_peername()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 429, in get_proxy_peername
    return _BaseSocket.getpeername(self)
AttributeError: type object '_BaseSocket' has no attribute 'getpeername'
```

**Comment by jamadden** [comment]
Can you please provide the full traceback for the error?

**Comment by jamadden** [comment]
gevent does not contain any class called '_BaseSocket'. Nor does CPython, AFAICS.

It's also worth noting that `geetpeername` [is optional](https://docs.python.org/3/library/socket.html#socket.socket.getpeername)

**Comment by masolit** [comment]
```
Traceback (most recent call last):
  File "/home/masolit/IdeaProjects/Python/scraping/tor_reqests2.py", line 28, in <module>
    handle = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 62, in http_open
    return self.do_open(build, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 35, in connect
    self.sock.settimeout(self.timeout)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 288, in settimeout
    peer = self.get_proxy_peername()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 429, in get_proxy_peername
    return _BaseSocket.getpeername(self)
AttributeError: type object '_BaseSocket' has no attribute 'getpeername'
```

**Comment by jamadden** [comment]
The preferred solution would be for the library to use `super(socksocket, self).getpeername()` instead of assuming it lives statically on the type object. Things that gevent doesn't need to implement are dynamically dispatched to the underlying native socket with `__getattr__`.

This same problem could arise on alternate implementations of Python, such as PyPy or IronPython or Jython. The *way* in which the (optional) getpeername is implemented is not defined/required to be a method statically available on the type, I think.

I'd rather not add a bunch of methods to gevent's socket type that simply delegate to the underlying socket---that's what `__getattr__` is for---because it's a maintenance burden and potential source of bugs (a violation of DRY).

**Comment by jamadden** [comment]
Also, in this specific case, because `getpeername` is optional, implementing it statically in gevent.socket would cause the wrong thing to happen for `hasattr(sock, 'getpeername')`.

**Comment by jamadden** [comment]
The fix has been merged in https://github.com/Anorov/PySocks/pull/64

**Comment by masolit** [comment]
# same problem after update

# urllib
```python
from gevent import monkey
monkey.patch_all()

import urllib.request
import socks
from sockshandler import SocksiPyHandler

request = urllib.request.Request('http://myip.dnsomatic.com')
opener = urllib.request.build_opener(SocksiPyHandler(socks.SOCKS5, '127.0.0.1', 9050))
urllib.request.install_opener(opener)

handle = urllib.request.urlopen(request, timeout=60)
print(handle.read())
```
```
Traceback (most recent call last):
  File "/home/masolit/IdeaProjects/Python/scraping/tor_reqests2.py", line 28, in <module>
    handle = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 62, in http_open
    return self.do_open(build, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 35, in connect
    self.sock.settimeout(self.timeout)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 288, in settimeout
    peer = self.get_proxy_peername()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 429, in get_proxy_peername
    return super(socksocket, self).getpeername()
AttributeError: 'super' object has no attribute 'getpeername'
```
