### ISSUE TITLE
When Gevent meet ProcessPoolExecutor, something strange happens

### ISSUE THREAD

**Issue by fjctlzy** [gevent/gevent#936]
* gevent version: gevent-1.1.2
* Python version: 3.5.2
* Operating System: Centos6

### Description:

I use parallel-ssh(gevent + paramiko) to execute command or scp files in parallel, as I have a lot of servers, so just use a process with parallel-ssh can't exhaust the performance of the scp server. 

So I decide to use multiprocessing with parallel-ssh, but I found that it doesn't work well. 

I search Google and github, and found little information about using gevent with ProcessPoolExecutor, so I have to open an issue here. 

the code below works well with parallel_scp directly, but with ProcessPoolExecutor, it fails. 
If I replace ProcessPoolExecutor with ThreadPoolExecutor, then it will work perfectly. 

```python
# -*- coding: utf-8 -*-
from gevent import monkey

monkey.patch_all()
import concurrent
import math
import traceback
from concurrent.futures import ProcessPoolExecutor

import pssh

server_list = ['server1', 'server2']
max_workers = 5


# divide arr into m chunks
def chunks(arr, m):
    n = int(math.ceil(len(arr) / float(m)))
    return [arr[i:i + n] for i in range(0, len(arr), n)]


def parallel_scp(host_list):
    ssh = pssh.ParallelSSHClient(hosts=host_list, user='log', pool_size=20)
    cmd = "mkdir -p /tmp"
    output = ssh.run_command(cmd, shell='bash -c')
    ssh.join(output)
    print('finished')
    return True


parallel_scp(server_list)

with ProcessPoolExecutor(max_workers=max_workers) as executor:
    tasks = {executor.submit(parallel_scp, server_chunks): server_chunks for
             server_chunks in
             chunks(server_list, max_workers)}
    for task in concurrent.futures.as_completed(tasks):
        try:
            result = task.result()
        except:
            print(traceback.print_exc())
```

the code won't quit unless I CTRL+C to interrupt, and during the running of the process, the strace command should that it's waiting all the time. 
```
#strace -p 1563 -f
Process 1563 attached - interrupt to quit
wait4(1568,
```

```
python3 a.py
not to use multiprocessing
finished
start using processpoolexecutor
finished
finished
finished
finished
finished
^[^CProcess Process-1:
Process Process-4:
Process Process-2:
Process Process-3:
Process Process-5:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/python3/lib/python3.5/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/opt/python3/lib/python3.5/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/opt/python3/lib/python3.5/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/opt/python3/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/opt/python3/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/opt/python3/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/python3/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/opt/python3/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/python3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/python3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/python3/lib/python3.5/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/opt/python3/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/python3/lib/python3.5/site-packages/gevent/threading.py", line 137, in run
    super(Thread, self).run()
  File "/opt/python3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 327, in _queue_management_worker
    shutdown_worker()
  File "/opt/python3/lib/python3.5/concurrent/futures/process.py", line 259, in shutdown_worker
    p.join()
  File "/opt/python3/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/opt/python3/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/python3/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/opt/python3/lib/python3.5/site-packages/gevent/os.py", line 302, in waitpid
    return _waitpid(pid, options)
KeyboardInterrupt

```

if I delete the monkey.patch_all(), then it will be like this, and nothing stdout. 

```
#strace -p 1188 -f
Process 1188 attached with 2 threads - interrupt to quit
[pid  1231] wait4(1225,  <unfinished ...>
[pid  1188] futex(0x2ae688000c10, FUTEX_WAIT_PRIVATE, 0, NULL^C <unfinished ...>
```

**Comment by jamadden** [comment]
It is [documented](http://www.gevent.org/gevent.monkey.html#gevent.monkey.patch_thread) that you can't use `ProcessPoolExecutor` or `multiprocessing.Queue` when `thread` has been monkey-patched.

>  Monkey-patching thread and using multiprocessing.Queue or concurrent.futures.ProcessPoolExecutor (which uses a Queue) will hang the process.

**Comment by thejinx0r** [comment]
I found this thread from google.
The link from @jamadden has moved to:
http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_thread
