### ISSUE TITLE
Failed to run with gRPC-python

### ISSUE THREAD

**Issue by abc100m** [gevent/gevent#938]
* gevent version: 1.2.1
* Python version: 2.7.11
* Operating System: centos
* grpcio: 1.1.0

### Description:
gevent  failed to run with gRPC:
```
Exception gevent.hub.LoopExit: LoopExit('This operation would block forever'...
```

### What I've run:

helloworld.proto
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```

server.py
```python
import concurrent.futures
import gevent
from gevent import monkey, sleep

#monkey.patch_all(thread=True)
monkey.patch_all()
from gevent.threadpool import ThreadPoolExecutor
concurrent.futures.ThreadPoolExecutor = ThreadPoolExecutor

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

import grpc
#import time
#import concurrent
import helloworld_pb2
import signal

class Greeter(helloworld_pb2.GreeterServicer):

  def SayHello(self, request, context):
    #sleep(10)
    return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)


def serve():
  server = grpc.server(ThreadPoolExecutor(max_workers=100))
  helloworld_pb2.add_GreeterServicer_to_server(Greeter(), server)
  server.add_insecure_port('[::]:50051')
  server.start()

  try:
    while True:
      sleep(_ONE_DAY_IN_SECONDS)
  except KeyboardInterrupt:
    server.stop(0)

def run_forever():
  gevent.sleep(_ONE_DAY_IN_SECONDS)


if __name__ == '__main__':
  serve()
  #gevent.signal(signal.SIGQUIT, gevent.shutdown)
  #thread = gevent.spawn(run_forever)
  #thread.join()
  print 'done.'
```

client.py
```python
from __future__ import print_function

import grpc
import threading
import helloworld_pb2
import time

def run():
  channel = grpc.insecure_channel('localhost:50051')
  stub = helloworld_pb2.GreeterStub(channel)
  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  print("Greeter client received: " + response.message)

def multi_run(n):
  for _ in xrange(n):
    t1 = threading.Thread(target=run)
    t1.setDaemon(True)
    t1.start()

if __name__ == '__main__':
  multi_run(20)
  time.sleep(3600*24)
```

start server:
```
#python server.py
```

start client:
```
#python client.py
```

when client started,  server failed with:

```
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/gevent/threadpool.py", line 211, in _worker
    value = func(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/grpc/_server.py", line 467, in _unary_response_in_pool
    argument = argument_thunk()
  File "/root/anaconda2/lib/python2.7/site-packages/grpc/_server.py", line 355, in unary_request
    state.condition.wait()
  File "/root/anaconda2/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
  File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)
  File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)
  File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
  File "/root/anaconda2/lib/python2.7/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
LoopExit: ('This operation would block forever', <Hub at 0x7f56a58eef50 epoll pending=0 ref=1 fileno=18>)
Fri Feb 10 00:58:17 2017 (<ThreadPool at 0x7f56a574a8d0 0/3/100>, <function _unary_response_in_pool at 0x7f56a56986e0>) failed with LoopExit
```

**Comment by jamadden** [comment]
I believe you saw #786, so you know that the grpc project specifically will not support gevent compatibility with full monkey-patching. The option most likely to work is to avoid patching threading. 

Other than that, gevent can provide a ThreadPoolExecutor that did at least partly work with one specific version of grpc at one time, and its up to the application to use that (as your code is doing). 

But it's also up to the application to make sure that it meets the general requirements of running a gevent loop, making sure that there are running greenlets to switch between. In this case there apparently aren't, which is what the `LoopExit` is telling you. How to fix that is probably going to be application specific. You may possibly be able to subclass the TPE to make it work, but given the aforementioned design of grpc, that may lead back to the initial problem. There may be some other things you can patch around in grpc. I don't know; the use of native code in grpc puts it somewhat out-of-bounds as far as gevent is concerned. You'll just have to try. I don't think there's much more gevent can do.

**Comment by abc100m** [comment]
Thanks for your reply.
=====
Yes, I have saw #786.  I was thought that ThreadPoolExecutor of gevent  works now but as my test, it didn't works well.

Since gRPC is not compatible with gevent yet, I will close this issue.  If there is a Hack way to let gRPC work with gevent, please let me

**Comment by abc100m** [comment]
[gRPC python discussion](https://github.com/grpc/grpc/issues/6046)
