### ISSUE TITLE
tblib tb print crashes with recursion error when printing recursion errors

### ISSUE THREAD

**Issue by ml31415** [gevent/gevent#954]
* gevent version: 1.1.1
* Python version: 2.7.12
* Operating System: Linux

Consider the following code, creating a recursion error on purpose:
```python
from gevent import spawn, monkey, sleep
monkey.patch_all()
import sys
sys.setrecursionlimit(50)

def f(x):
    return f(x)

g = spawn(f, 3)
sleep()
g.join()
```
Instead of a proper print of the resulting traceback, this code shows:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    self._report_error(sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 518, in _report_error
    self._exc_info = exc_info[0], exc_info[1], dump_traceback(exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/gevent/_tblib.py", line 243, in g
    return f(a)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_tblib.py", line 298, in dump_traceback
    return dumps(tb)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_tblib.py", line 217, in pickle_traceback
    return unpickle_traceback, (Frame(tb.tb_frame), tb.tb_lineno, tb.tb_next and Traceback(tb.tb_next))
  File "/usr/local/lib/python2.7/dist-packages/gevent/_tblib.py", line 156, in __init__
    self.tb_next = Traceback(tb.tb_next)
.........
  File "/usr/local/lib/python2.7/dist-packages/gevent/_tblib.py", line 146, in __init__
    self.f_code = Code(frame.f_code)
RuntimeError: maximum recursion depth exceeded
<callback at 0x7f5f656149d0 stopped> failed with RuntimeError
```
This is rather unfortunate, as it completely hides the original error.

**Comment by jamadden** [comment]
tblib is a vendored (third-party) library that gevent just bundles, not maintains. If you can report this [upstream](https://github.com/ionelmc/python-tblib) gevent can update its copy after its fixed there.

**Comment by ml31415** [comment]
Big thanks for the quick fix! :)
