### ISSUE TITLE
gevent - 'module' object has no attribute 'epoll' with Python2-7 and Gevent -1.0.1; with Requests-2.13.0

### ISSUE THREAD

**Issue by abarik1981** [gevent/gevent#973]
* gevent version: 1.0.1
* Python version: 2.7
* Operating System: Linux (redhat 5.3)

### Description:
Getting `AttributeError: 'module' object has no attribute 'epoll'` if anything gets imported before `gevent.monkey.patch_all()`. Looks like its not requests  error (https://github.com/kennethreitz/requests/issues/4051)

```

    >>> import requests
    >>> import sys
    >>> requests.get('http://www.python.org')
    <Response [200]>
    >>>
    >>>
    >>>
    >>> exit()


    >>> import gevent.monkey
    >>> gevent.monkey.patch_all()
    >>> import requests
    >>> import sys
    >>> requests.get('http://www.python.org')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/api.py", line 70, in get
        return request('get', url, params=params, **kwargs)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/api.py", line 56, in request
        return session.request(method=method, url=url, **kwargs)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/sessions.py", line 630, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/sessions.py", line 190, in resolve_redirects
        **adapter_kwargs
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
        conn.connect()
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
        ssl_context=context)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 438, in wrap_socket
        rd = util.wait_for_read(sock, sock.gettimeout())
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/util/wait.py", line 33, in wait_for_read
        return _wait_for_io_events(socks, EVENT_READ, timeout)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
        with DefaultSelector() as selector:
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/util/selectors.py", line 364, in __init__
        self._epoll = select.epoll()
    AttributeError: 'module' object has no attribute 'epoll'
    >>>


    import sys
    import gevent.monkey
    gevent.monkey.patch_all()
    import requests
    requests.get('http://www.python.org')

        return _wait_for_io_events(socks, EVENT_READ, timeout)
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
        with DefaultSelector() as selector:
      File "/apollo/env/NSDATools/lib/python2.7/site-packages/requests/packages/urllib3/util/selectors.py", line 364, in __init__
        self._epoll = select.epoll()
    AttributeError: 'module' object has no attribute 'epoll'


```

**Comment by jamadden** [comment]
It is widely documented (e.g., [here](http://www.gevent.org/gevent.monkey.html#patching)) that monkey patching should be imported and executed as early as possible. Failing to do so can result in errors like this. 

In general, there's nothing gevent can do if unknown third-party modules have state that is invalidated after monkey-patching (hence the suggestion to do so before anything else). In specific cases like this you might be able to patch a specific library that you're using, but that's beyond gevent's scope.

**Comment by abarik1981** [comment]
Thanks @jamadden
