### ISSUE TITLE
queue iteration doesn't handle StopIteration instances

### ISSUE THREAD

**Issue by wojtossfm** [gevent/gevent#988]
* gevent version: 1.1.0 (but present in master)
* Python version: 3.5
* Operating System: Ubuntu 14.04

### Description:

When using `gevent.queue.Queue` I attempted to pass an instance of StopIteration into the queue after seeing the example with the StopIteration class on the docs. Below is hopefully self-explanatory output from an example script:
```
What I expected to see:
Expect to see me 1

What I saw:
Expect to see me 1
Dont expect to see exc value
Dont expect to see me 2
```

### What I've run:

```python
import gevent.queue

items = [
	"Expect to see me 1",
	StopIteration("Dont expect to see exc value"),
	"Dont expect to see me 2",
	StopIteration,
	"Dont expect to see me 3",
]

queue = gevent.queue.Queue()
for item in items:
	queue.put(item)


def gen():
	for item in items:
		if item is StopIteration or isinstance(item, StopIteration):
			raise item
		yield item

print('What I expected to see:')

for item in gen():
	print(item)

print('\nWhat I saw:')

for item in queue:
	print(item)
```

Is there any specific reason that instances of StopIteration are handled differently than the class? I'm guessing this is an intentional design decision, but (at least to me) it would be better if it followed the
logic of a regular generator.

Also I do realise that the example generator does break convention by raising StopIteration instead of returning and could be refactored to adhere to PEP appropriately, but wanted to fairly mimic what I expected to see in the Queue.next logic.

**Comment by jamadden** [comment]
> Is there any specific reason that instances of StopIteration are handled differently than the class?

There is, yes. 

Most importantly, under Python 3, exceptions are stateful with respect to their traceback, among other things. This can lead to very odd results when raising an exception instance.

Let's define a sequence of functions to raise an exception:
```pycon
>>> def a(e):
...   raise e
...
>>> def b(e):
...   a(e)
...
>>> def c(e):
...   b(e)
...
```

Now lets raise the class a few times. Note how the traceback is always the same (always correct):
```pycon
>>> c(StopIteration)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
>>> c(StopIteration)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
```

Now lets try it with an instance. Whoops, notice how the traceback grows each time:
```pycon
>>> s = StopIteration()
>>> c(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
StopIteration
>>> c(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
StopIteration
>>> c(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in c
  File "<stdin>", line 2, in b
  File "<stdin>", line 2, in a
StopIteration
```

Secondarily, it's substantially faster to check `is` than `instanceof`. And of course the documentation only says `is`, so checking for an instance would be a breaking change for anyone who actually wants to queue instances.

**Comment by wojtossfm** [comment]
In the example you provided since you are accepting an argument of an exception instance I would expect you would want this growth to occur. It is supplying you with the `history` of how the exception was being raised. The example also is somewhat contrived. The instance would usually be bubbled upwards or a value from it would be used rather than just raising it in a loop.

In regards to the performance benefits then I can understand them.
